  @[Link("Graphics.Gdi")]
  lib LibGraphicsGdi
    GDI_ERROR = -1
ERROR = 0
NULLREGION = 1
SIMPLEREGION = 2
COMPLEXREGION = 3
RGN_ERROR = 0
MAXSTRETCHBLTMODE = 4
POLYFILL_LAST = 2
LAYOUT_BTT = 2
LAYOUT_VBH = 4
ASPECT_FILTERING = 1
META_SETBKCOLOR = 513
META_SETBKMODE = 258
META_SETMAPMODE = 259
META_SETROP2 = 260
META_SETRELABS = 261
META_SETPOLYFILLMODE = 262
META_SETSTRETCHBLTMODE = 263
META_SETTEXTCHAREXTRA = 264
META_SETTEXTCOLOR = 521
META_SETTEXTJUSTIFICATION = 522
META_SETWINDOWORG = 523
META_SETWINDOWEXT = 524
META_SETVIEWPORTORG = 525
META_SETVIEWPORTEXT = 526
META_OFFSETWINDOWORG = 527
META_SCALEWINDOWEXT = 1040
META_OFFSETVIEWPORTORG = 529
META_SCALEVIEWPORTEXT = 1042
META_LINETO = 531
META_MOVETO = 532
META_EXCLUDECLIPRECT = 1045
META_INTERSECTCLIPRECT = 1046
META_ARC = 2071
META_ELLIPSE = 1048
META_FLOODFILL = 1049
META_PIE = 2074
META_RECTANGLE = 1051
META_ROUNDRECT = 1564
META_PATBLT = 1565
META_SAVEDC = 30
META_SETPIXEL = 1055
META_OFFSETCLIPRGN = 544
META_TEXTOUT = 1313
META_BITBLT = 2338
META_STRETCHBLT = 2851
META_POLYGON = 804
META_POLYLINE = 805
META_ESCAPE = 1574
META_RESTOREDC = 295
META_FILLREGION = 552
META_FRAMEREGION = 1065
META_INVERTREGION = 298
META_PAINTREGION = 299
META_SELECTCLIPREGION = 300
META_SELECTOBJECT = 301
META_SETTEXTALIGN = 302
META_CHORD = 2096
META_SETMAPPERFLAGS = 561
META_EXTTEXTOUT = 2610
META_SETDIBTODEV = 3379
META_SELECTPALETTE = 564
META_REALIZEPALETTE = 53
META_ANIMATEPALETTE = 1078
META_SETPALENTRIES = 55
META_POLYPOLYGON = 1336
META_RESIZEPALETTE = 313
META_DIBBITBLT = 2368
META_DIBSTRETCHBLT = 2881
META_DIBCREATEPATTERNBRUSH = 322
META_STRETCHDIB = 3907
META_EXTFLOODFILL = 1352
META_SETLAYOUT = 329
META_DELETEOBJECT = 496
META_CREATEPALETTE = 247
META_CREATEPATTERNBRUSH = 505
META_CREATEPENINDIRECT = 762
META_CREATEFONTINDIRECT = 763
META_CREATEBRUSHINDIRECT = 764
META_CREATEREGION = 1791
NEWFRAME = 1
ABORTDOC = 2
NEXTBAND = 3
SETCOLORTABLE = 4
GETCOLORTABLE = 5
FLUSHOUTPUT = 6
DRAFTMODE = 7
QUERYESCSUPPORT = 8
SETABORTPROC = 9
STARTDOC = 10
ENDDOC = 11
GETPHYSPAGESIZE = 12
GETPRINTINGOFFSET = 13
GETSCALINGFACTOR = 14
MFCOMMENT = 15
GETPENWIDTH = 16
SETCOPYCOUNT = 17
SELECTPAPERSOURCE = 18
DEVICEDATA = 19
PASSTHROUGH = 19
GETTECHNOLGY = 20
GETTECHNOLOGY = 20
SETLINECAP = 21
SETLINEJOIN = 22
SETMITERLIMIT = 23
BANDINFO = 24
DRAWPATTERNRECT = 25
GETVECTORPENSIZE = 26
GETVECTORBRUSHSIZE = 27
ENABLEDUPLEX = 28
GETSETPAPERBINS = 29
GETSETPRINTORIENT = 30
ENUMPAPERBINS = 31
SETDIBSCALING = 32
EPSPRINTING = 33
ENUMPAPERMETRICS = 34
GETSETPAPERMETRICS = 35
POSTSCRIPT_DATA = 37
POSTSCRIPT_IGNORE = 38
MOUSETRAILS = 39
GETDEVICEUNITS = 42
GETEXTENDEDTEXTMETRICS = 256
GETEXTENTTABLE = 257
GETPAIRKERNTABLE = 258
GETTRACKKERNTABLE = 259
EXTTEXTOUT = 512
GETFACENAME = 513
DOWNLOADFACE = 514
ENABLERELATIVEWIDTHS = 768
ENABLEPAIRKERNING = 769
SETKERNTRACK = 770
SETALLJUSTVALUES = 771
SETCHARSET = 772
STRETCHBLT = 2048
METAFILE_DRIVER = 2049
GETSETSCREENPARAMS = 3072
QUERYDIBSUPPORT = 3073
BEGIN_PATH = 4096
CLIP_TO_PATH = 4097
END_PATH = 4098
EXT_DEVICE_CAPS = 4099
RESTORE_CTM = 4100
SAVE_CTM = 4101
SET_ARC_DIRECTION = 4102
SET_BACKGROUND_COLOR = 4103
SET_POLY_MODE = 4104
SET_SCREEN_ANGLE = 4105
SET_SPREAD = 4106
TRANSFORM_CTM = 4107
SET_CLIP_BOX = 4108
SET_BOUNDS = 4109
SET_MIRROR_MODE = 4110
OPENCHANNEL = 4110
DOWNLOADHEADER = 4111
CLOSECHANNEL = 4112
POSTSCRIPT_PASSTHROUGH = 4115
ENCAPSULATED_POSTSCRIPT = 4116
POSTSCRIPT_IDENTIFY = 4117
POSTSCRIPT_INJECTION = 4118
CHECKJPEGFORMAT = 4119
CHECKPNGFORMAT = 4120
GET_PS_FEATURESETTING = 4121
GDIPLUS_TS_QUERYVER = 4122
GDIPLUS_TS_RECORD = 4123
MILCORE_TS_QUERYVER_RESULT_FALSE = 0
MILCORE_TS_QUERYVER_RESULT_TRUE = 2147483647
SPCLPASSTHROUGH2 = 4568
PSIDENT_GDICENTRIC = 0
PSIDENT_PSCENTRIC = 1
PSINJECT_DLFONT = 3722304989
FEATURESETTING_NUP = 0
FEATURESETTING_OUTPUT = 1
FEATURESETTING_PSLEVEL = 2
FEATURESETTING_CUSTPAPER = 3
FEATURESETTING_MIRROR = 4
FEATURESETTING_NEGATIVE = 5
FEATURESETTING_PROTOCOL = 6
FEATURESETTING_PRIVATE_BEGIN = 4096
FEATURESETTING_PRIVATE_END = 8191
PSPROTOCOL_ASCII = 0
PSPROTOCOL_BCP = 1
PSPROTOCOL_TBCP = 2
PSPROTOCOL_BINARY = 3
QDI_SETDIBITS = 1
QDI_GETDIBITS = 2
QDI_DIBTOSCREEN = 4
QDI_STRETCHDIB = 8
SP_NOTREPORTED = 16384
SP_ERROR = -1
SP_APPABORT = -2
SP_USERABORT = -3
SP_OUTOFDISK = -4
SP_OUTOFMEMORY = -5
PR_JOBSTATUS = 0
LCS_CALIBRATED_RGB = 0
LCS_GM_BUSINESS = 1
LCS_GM_GRAPHICS = 2
LCS_GM_IMAGES = 4
LCS_GM_ABS_COLORIMETRIC = 8
CM_OUT_OF_GAMUT = 255
CM_IN_GAMUT = 0
BI_RGB = 0
BI_RLE8 = 1
BI_RLE4 = 2
BI_BITFIELDS = 3
BI_JPEG = 4
BI_PNG = 5
TMPF_FIXED_PITCH = 1
TMPF_VECTOR = 2
TMPF_DEVICE = 8
TMPF_TRUETYPE = 4
NTM_REGULAR = 64
NTM_BOLD = 32
NTM_ITALIC = 1
NTM_NONNEGATIVE_AC = 65536
NTM_PS_OPENTYPE = 131072
NTM_TT_OPENTYPE = 262144
NTM_MULTIPLEMASTER = 524288
NTM_TYPE1 = 1048576
NTM_DSIG = 2097152
LF_FACESIZE = 32
LF_FULLFACESIZE = 64
OUT_SCREEN_OUTLINE_PRECIS = 9
CLEARTYPE_NATURAL_QUALITY = 6
DEFAULT_PITCH = 0
FIXED_PITCH = 1
VARIABLE_PITCH = 2
MONO_FONT = 8
ANSI_CHARSET = 0
DEFAULT_CHARSET = 1
SYMBOL_CHARSET = 2
SHIFTJIS_CHARSET = 128
HANGEUL_CHARSET = 129
HANGUL_CHARSET = 129
GB2312_CHARSET = 134
CHINESEBIG5_CHARSET = 136
OEM_CHARSET = 255
JOHAB_CHARSET = 130
HEBREW_CHARSET = 177
ARABIC_CHARSET = 178
GREEK_CHARSET = 161
TURKISH_CHARSET = 162
VIETNAMESE_CHARSET = 163
THAI_CHARSET = 222
EASTEUROPE_CHARSET = 238
RUSSIAN_CHARSET = 204
MAC_CHARSET = 77
BALTIC_CHARSET = 186
FS_LATIN1 = 1
FS_LATIN2 = 2
FS_CYRILLIC = 4
FS_GREEK = 8
FS_TURKISH = 16
FS_HEBREW = 32
FS_ARABIC = 64
FS_BALTIC = 128
FS_VIETNAMESE = 256
FS_THAI = 65536
FS_JISJAPAN = 131072
FS_CHINESESIMP = 262144
FS_WANSUNG = 524288
FS_CHINESETRAD = 1048576
FS_JOHAB = 2097152
FS_SYMBOL = -2147483648
FW_DONTCARE = 0
FW_THIN = 100
FW_EXTRALIGHT = 200
FW_LIGHT = 300
FW_NORMAL = 400
FW_MEDIUM = 500
FW_SEMIBOLD = 600
FW_BOLD = 700
FW_EXTRABOLD = 800
FW_HEAVY = 900
FW_ULTRALIGHT = 200
FW_REGULAR = 400
FW_DEMIBOLD = 600
FW_ULTRABOLD = 800
FW_BLACK = 900
PANOSE_COUNT = 10
PAN_FAMILYTYPE_INDEX = 0
PAN_SERIFSTYLE_INDEX = 1
PAN_WEIGHT_INDEX = 2
PAN_PROPORTION_INDEX = 3
PAN_CONTRAST_INDEX = 4
PAN_STROKEVARIATION_INDEX = 5
PAN_ARMSTYLE_INDEX = 6
PAN_LETTERFORM_INDEX = 7
PAN_MIDLINE_INDEX = 8
PAN_XHEIGHT_INDEX = 9
PAN_CULTURE_LATIN = 0
PAN_ANY = 0
PAN_NO_FIT = 1
PAN_FAMILY_TEXT_DISPLAY = 2
PAN_FAMILY_SCRIPT = 3
PAN_FAMILY_DECORATIVE = 4
PAN_FAMILY_PICTORIAL = 5
PAN_SERIF_COVE = 2
PAN_SERIF_OBTUSE_COVE = 3
PAN_SERIF_SQUARE_COVE = 4
PAN_SERIF_OBTUSE_SQUARE_COVE = 5
PAN_SERIF_SQUARE = 6
PAN_SERIF_THIN = 7
PAN_SERIF_BONE = 8
PAN_SERIF_EXAGGERATED = 9
PAN_SERIF_TRIANGLE = 10
PAN_SERIF_NORMAL_SANS = 11
PAN_SERIF_OBTUSE_SANS = 12
PAN_SERIF_PERP_SANS = 13
PAN_SERIF_FLARED = 14
PAN_SERIF_ROUNDED = 15
PAN_WEIGHT_VERY_LIGHT = 2
PAN_WEIGHT_LIGHT = 3
PAN_WEIGHT_THIN = 4
PAN_WEIGHT_BOOK = 5
PAN_WEIGHT_MEDIUM = 6
PAN_WEIGHT_DEMI = 7
PAN_WEIGHT_BOLD = 8
PAN_WEIGHT_HEAVY = 9
PAN_WEIGHT_BLACK = 10
PAN_WEIGHT_NORD = 11
PAN_PROP_OLD_STYLE = 2
PAN_PROP_MODERN = 3
PAN_PROP_EVEN_WIDTH = 4
PAN_PROP_EXPANDED = 5
PAN_PROP_CONDENSED = 6
PAN_PROP_VERY_EXPANDED = 7
PAN_PROP_VERY_CONDENSED = 8
PAN_PROP_MONOSPACED = 9
PAN_CONTRAST_NONE = 2
PAN_CONTRAST_VERY_LOW = 3
PAN_CONTRAST_LOW = 4
PAN_CONTRAST_MEDIUM_LOW = 5
PAN_CONTRAST_MEDIUM = 6
PAN_CONTRAST_MEDIUM_HIGH = 7
PAN_CONTRAST_HIGH = 8
PAN_CONTRAST_VERY_HIGH = 9
PAN_STROKE_GRADUAL_DIAG = 2
PAN_STROKE_GRADUAL_TRAN = 3
PAN_STROKE_GRADUAL_VERT = 4
PAN_STROKE_GRADUAL_HORZ = 5
PAN_STROKE_RAPID_VERT = 6
PAN_STROKE_RAPID_HORZ = 7
PAN_STROKE_INSTANT_VERT = 8
PAN_STRAIGHT_ARMS_HORZ = 2
PAN_STRAIGHT_ARMS_WEDGE = 3
PAN_STRAIGHT_ARMS_VERT = 4
PAN_STRAIGHT_ARMS_SINGLE_SERIF = 5
PAN_STRAIGHT_ARMS_DOUBLE_SERIF = 6
PAN_BENT_ARMS_HORZ = 7
PAN_BENT_ARMS_WEDGE = 8
PAN_BENT_ARMS_VERT = 9
PAN_BENT_ARMS_SINGLE_SERIF = 10
PAN_BENT_ARMS_DOUBLE_SERIF = 11
PAN_LETT_NORMAL_CONTACT = 2
PAN_LETT_NORMAL_WEIGHTED = 3
PAN_LETT_NORMAL_BOXED = 4
PAN_LETT_NORMAL_FLATTENED = 5
PAN_LETT_NORMAL_ROUNDED = 6
PAN_LETT_NORMAL_OFF_CENTER = 7
PAN_LETT_NORMAL_SQUARE = 8
PAN_LETT_OBLIQUE_CONTACT = 9
PAN_LETT_OBLIQUE_WEIGHTED = 10
PAN_LETT_OBLIQUE_BOXED = 11
PAN_LETT_OBLIQUE_FLATTENED = 12
PAN_LETT_OBLIQUE_ROUNDED = 13
PAN_LETT_OBLIQUE_OFF_CENTER = 14
PAN_LETT_OBLIQUE_SQUARE = 15
PAN_MIDLINE_STANDARD_TRIMMED = 2
PAN_MIDLINE_STANDARD_POINTED = 3
PAN_MIDLINE_STANDARD_SERIFED = 4
PAN_MIDLINE_HIGH_TRIMMED = 5
PAN_MIDLINE_HIGH_POINTED = 6
PAN_MIDLINE_HIGH_SERIFED = 7
PAN_MIDLINE_CONSTANT_TRIMMED = 8
PAN_MIDLINE_CONSTANT_POINTED = 9
PAN_MIDLINE_CONSTANT_SERIFED = 10
PAN_MIDLINE_LOW_TRIMMED = 11
PAN_MIDLINE_LOW_POINTED = 12
PAN_MIDLINE_LOW_SERIFED = 13
PAN_XHEIGHT_CONSTANT_SMALL = 2
PAN_XHEIGHT_CONSTANT_STD = 3
PAN_XHEIGHT_CONSTANT_LARGE = 4
PAN_XHEIGHT_DUCKING_SMALL = 5
PAN_XHEIGHT_DUCKING_STD = 6
PAN_XHEIGHT_DUCKING_LARGE = 7
ELF_VENDOR_SIZE = 4
ELF_VERSION = 0
ELF_CULTURE_LATIN = 0
RASTER_FONTTYPE = 1
DEVICE_FONTTYPE = 2
TRUETYPE_FONTTYPE = 4
PC_RESERVED = 1
PC_EXPLICIT = 2
PC_NOCOLLAPSE = 4
BKMODE_LAST = 2
GM_LAST = 2
PT_CLOSEFIGURE = 1
PT_LINETO = 2
PT_BEZIERTO = 4
PT_MOVETO = 6
ABSOLUTE = 1
RELATIVE = 2
STOCK_LAST = 19
CLR_INVALID = 4294967295
BS_SOLID = 0
BS_NULL = 1
BS_HOLLOW = 1
BS_HATCHED = 2
BS_PATTERN = 3
BS_INDEXED = 4
BS_DIBPATTERN = 5
BS_DIBPATTERNPT = 6
BS_PATTERN8X8 = 7
BS_DIBPATTERN8X8 = 8
BS_MONOPATTERN = 9
HS_API_MAX = 12
DT_PLOTTER = 0
DT_RASDISPLAY = 1
DT_RASPRINTER = 2
DT_RASCAMERA = 3
DT_CHARSTREAM = 4
DT_METAFILE = 5
DT_DISPFILE = 6
CC_NONE = 0
CC_CIRCLES = 1
CC_PIE = 2
CC_CHORD = 4
CC_ELLIPSES = 8
CC_WIDE = 16
CC_STYLED = 32
CC_WIDESTYLED = 64
CC_INTERIORS = 128
CC_ROUNDRECT = 256
LC_NONE = 0
LC_POLYLINE = 2
LC_MARKER = 4
LC_POLYMARKER = 8
LC_WIDE = 16
LC_STYLED = 32
LC_WIDESTYLED = 64
LC_INTERIORS = 128
PC_NONE = 0
PC_POLYGON = 1
PC_RECTANGLE = 2
PC_WINDPOLYGON = 4
PC_TRAPEZOID = 4
PC_SCANLINE = 8
PC_WIDE = 16
PC_STYLED = 32
PC_WIDESTYLED = 64
PC_INTERIORS = 128
PC_POLYPOLYGON = 256
PC_PATHS = 512
CP_NONE = 0
CP_RECTANGLE = 1
CP_REGION = 2
TC_OP_CHARACTER = 1
TC_OP_STROKE = 2
TC_CP_STROKE = 4
TC_CR_90 = 8
TC_CR_ANY = 16
TC_SF_X_YINDEP = 32
TC_SA_DOUBLE = 64
TC_SA_INTEGER = 128
TC_SA_CONTIN = 256
TC_EA_DOUBLE = 512
TC_IA_ABLE = 1024
TC_UA_ABLE = 2048
TC_SO_ABLE = 4096
TC_RA_ABLE = 8192
TC_VA_ABLE = 16384
TC_RESERVED = 32768
TC_SCROLLBLT = 65536
RC_BITBLT = 1
RC_BANDING = 2
RC_SCALING = 4
RC_BITMAP64 = 8
RC_GDI20_OUTPUT = 16
RC_GDI20_STATE = 32
RC_SAVEBITMAP = 64
RC_DI_BITMAP = 128
RC_PALETTE = 256
RC_DIBTODEV = 512
RC_BIGFONT = 1024
RC_STRETCHBLT = 2048
RC_FLOODFILL = 4096
RC_STRETCHDIB = 8192
RC_OP_DX_OUTPUT = 16384
RC_DEVBITS = 32768
SB_NONE = 0
SB_CONST_ALPHA = 1
SB_PIXEL_ALPHA = 2
SB_PREMULT_ALPHA = 4
SB_GRAD_RECT = 16
SB_GRAD_TRI = 32
CM_NONE = 0
CM_DEVICE_ICM = 1
CM_GAMMA_RAMP = 2
CM_CMYK_COLOR = 4
SYSPAL_ERROR = 0
CBM_INIT = 4
CCHFORMNAME = 32
DM_SPECVERSION = 1025
DM_ORIENTATION = 1
DM_PAPERSIZE = 2
DM_PAPERLENGTH = 4
DM_PAPERWIDTH = 8
DM_SCALE = 16
DM_POSITION = 32
DM_NUP = 64
DM_DISPLAYORIENTATION = 128
DM_COPIES = 256
DM_DEFAULTSOURCE = 512
DM_PRINTQUALITY = 1024
DM_COLOR = 2048
DM_DUPLEX = 4096
DM_YRESOLUTION = 8192
DM_TTOPTION = 16384
DM_COLLATE = 32768
DM_FORMNAME = 65536
DM_LOGPIXELS = 131072
DM_BITSPERPEL = 262144
DM_PELSWIDTH = 524288
DM_PELSHEIGHT = 1048576
DM_DISPLAYFLAGS = 2097152
DM_DISPLAYFREQUENCY = 4194304
DM_ICMMETHOD = 8388608
DM_ICMINTENT = 16777216
DM_MEDIATYPE = 33554432
DM_DITHERTYPE = 67108864
DM_PANNINGWIDTH = 134217728
DM_PANNINGHEIGHT = 268435456
DM_DISPLAYFIXEDOUTPUT = 536870912
DMORIENT_PORTRAIT = 1
DMORIENT_LANDSCAPE = 2
DMPAPER_LETTER = 1
DMPAPER_LETTERSMALL = 2
DMPAPER_TABLOID = 3
DMPAPER_LEDGER = 4
DMPAPER_LEGAL = 5
DMPAPER_STATEMENT = 6
DMPAPER_EXECUTIVE = 7
DMPAPER_A3 = 8
DMPAPER_A4 = 9
DMPAPER_A4SMALL = 10
DMPAPER_A5 = 11
DMPAPER_B4 = 12
DMPAPER_B5 = 13
DMPAPER_FOLIO = 14
DMPAPER_QUARTO = 15
DMPAPER_10X14 = 16
DMPAPER_11X17 = 17
DMPAPER_NOTE = 18
DMPAPER_ENV_9 = 19
DMPAPER_ENV_10 = 20
DMPAPER_ENV_11 = 21
DMPAPER_ENV_12 = 22
DMPAPER_ENV_14 = 23
DMPAPER_CSHEET = 24
DMPAPER_DSHEET = 25
DMPAPER_ESHEET = 26
DMPAPER_ENV_DL = 27
DMPAPER_ENV_C5 = 28
DMPAPER_ENV_C3 = 29
DMPAPER_ENV_C4 = 30
DMPAPER_ENV_C6 = 31
DMPAPER_ENV_C65 = 32
DMPAPER_ENV_B4 = 33
DMPAPER_ENV_B5 = 34
DMPAPER_ENV_B6 = 35
DMPAPER_ENV_ITALY = 36
DMPAPER_ENV_MONARCH = 37
DMPAPER_ENV_PERSONAL = 38
DMPAPER_FANFOLD_US = 39
DMPAPER_FANFOLD_STD_GERMAN = 40
DMPAPER_FANFOLD_LGL_GERMAN = 41
DMPAPER_ISO_B4 = 42
DMPAPER_JAPANESE_POSTCARD = 43
DMPAPER_9X11 = 44
DMPAPER_10X11 = 45
DMPAPER_15X11 = 46
DMPAPER_ENV_INVITE = 47
DMPAPER_RESERVED_48 = 48
DMPAPER_RESERVED_49 = 49
DMPAPER_LETTER_EXTRA = 50
DMPAPER_LEGAL_EXTRA = 51
DMPAPER_TABLOID_EXTRA = 52
DMPAPER_A4_EXTRA = 53
DMPAPER_LETTER_TRANSVERSE = 54
DMPAPER_A4_TRANSVERSE = 55
DMPAPER_LETTER_EXTRA_TRANSVERSE = 56
DMPAPER_A_PLUS = 57
DMPAPER_B_PLUS = 58
DMPAPER_LETTER_PLUS = 59
DMPAPER_A4_PLUS = 60
DMPAPER_A5_TRANSVERSE = 61
DMPAPER_B5_TRANSVERSE = 62
DMPAPER_A3_EXTRA = 63
DMPAPER_A5_EXTRA = 64
DMPAPER_B5_EXTRA = 65
DMPAPER_A2 = 66
DMPAPER_A3_TRANSVERSE = 67
DMPAPER_A3_EXTRA_TRANSVERSE = 68
DMPAPER_DBL_JAPANESE_POSTCARD = 69
DMPAPER_A6 = 70
DMPAPER_JENV_KAKU2 = 71
DMPAPER_JENV_KAKU3 = 72
DMPAPER_JENV_CHOU3 = 73
DMPAPER_JENV_CHOU4 = 74
DMPAPER_LETTER_ROTATED = 75
DMPAPER_A3_ROTATED = 76
DMPAPER_A4_ROTATED = 77
DMPAPER_A5_ROTATED = 78
DMPAPER_B4_JIS_ROTATED = 79
DMPAPER_B5_JIS_ROTATED = 80
DMPAPER_JAPANESE_POSTCARD_ROTATED = 81
DMPAPER_DBL_JAPANESE_POSTCARD_ROTATED = 82
DMPAPER_A6_ROTATED = 83
DMPAPER_JENV_KAKU2_ROTATED = 84
DMPAPER_JENV_KAKU3_ROTATED = 85
DMPAPER_JENV_CHOU3_ROTATED = 86
DMPAPER_JENV_CHOU4_ROTATED = 87
DMPAPER_B6_JIS = 88
DMPAPER_B6_JIS_ROTATED = 89
DMPAPER_12X11 = 90
DMPAPER_JENV_YOU4 = 91
DMPAPER_JENV_YOU4_ROTATED = 92
DMPAPER_P16K = 93
DMPAPER_P32K = 94
DMPAPER_P32KBIG = 95
DMPAPER_PENV_1 = 96
DMPAPER_PENV_2 = 97
DMPAPER_PENV_3 = 98
DMPAPER_PENV_4 = 99
DMPAPER_PENV_5 = 100
DMPAPER_PENV_6 = 101
DMPAPER_PENV_7 = 102
DMPAPER_PENV_8 = 103
DMPAPER_PENV_9 = 104
DMPAPER_PENV_10 = 105
DMPAPER_P16K_ROTATED = 106
DMPAPER_P32K_ROTATED = 107
DMPAPER_P32KBIG_ROTATED = 108
DMPAPER_PENV_1_ROTATED = 109
DMPAPER_PENV_2_ROTATED = 110
DMPAPER_PENV_3_ROTATED = 111
DMPAPER_PENV_4_ROTATED = 112
DMPAPER_PENV_5_ROTATED = 113
DMPAPER_PENV_6_ROTATED = 114
DMPAPER_PENV_7_ROTATED = 115
DMPAPER_PENV_8_ROTATED = 116
DMPAPER_PENV_9_ROTATED = 117
DMPAPER_PENV_10_ROTATED = 118
DMPAPER_LAST = 118
DMPAPER_USER = 256
DMBIN_UPPER = 1
DMBIN_ONLYONE = 1
DMBIN_LOWER = 2
DMBIN_MIDDLE = 3
DMBIN_MANUAL = 4
DMBIN_ENVELOPE = 5
DMBIN_ENVMANUAL = 6
DMBIN_AUTO = 7
DMBIN_TRACTOR = 8
DMBIN_SMALLFMT = 9
DMBIN_LARGEFMT = 10
DMBIN_LARGECAPACITY = 11
DMBIN_CASSETTE = 14
DMBIN_FORMSOURCE = 15
DMBIN_LAST = 15
DMBIN_USER = 256
DMRES_DRAFT = -1
DMRES_LOW = -2
DMRES_MEDIUM = -3
DMRES_HIGH = -4
DMCOLOR_MONOCHROME = 1
DMCOLOR_COLOR = 2
DMDUP_SIMPLEX = 1
DMDUP_VERTICAL = 2
DMDUP_HORIZONTAL = 3
DMTT_BITMAP = 1
DMTT_DOWNLOAD = 2
DMTT_SUBDEV = 3
DMTT_DOWNLOAD_OUTLINE = 4
DMCOLLATE_FALSE = 0
DMCOLLATE_TRUE = 1
DMDO_DEFAULT = 0
DMDO_90 = 1
DMDO_180 = 2
DMDO_270 = 3
DMDFO_DEFAULT = 0
DMDFO_STRETCH = 1
DMDFO_CENTER = 2
DM_INTERLACED = 2
DMDISPLAYFLAGS_TEXTMODE = 4
DMNUP_SYSTEM = 1
DMNUP_ONEUP = 2
DMICMMETHOD_NONE = 1
DMICMMETHOD_SYSTEM = 2
DMICMMETHOD_DRIVER = 3
DMICMMETHOD_DEVICE = 4
DMICMMETHOD_USER = 256
DMICM_SATURATE = 1
DMICM_CONTRAST = 2
DMICM_COLORIMETRIC = 3
DMICM_ABS_COLORIMETRIC = 4
DMICM_USER = 256
DMMEDIA_STANDARD = 1
DMMEDIA_TRANSPARENCY = 2
DMMEDIA_GLOSSY = 3
DMMEDIA_USER = 256
DMDITHER_NONE = 1
DMDITHER_COARSE = 2
DMDITHER_FINE = 3
DMDITHER_LINEART = 4
DMDITHER_ERRORDIFFUSION = 5
DMDITHER_RESERVED6 = 6
DMDITHER_RESERVED7 = 7
DMDITHER_RESERVED8 = 8
DMDITHER_RESERVED9 = 9
DMDITHER_GRAYSCALE = 10
DMDITHER_USER = 256
DISPLAY_DEVICE_ATTACHED_TO_DESKTOP = 1
DISPLAY_DEVICE_MULTI_DRIVER = 2
DISPLAY_DEVICE_PRIMARY_DEVICE = 4
DISPLAY_DEVICE_MIRRORING_DRIVER = 8
DISPLAY_DEVICE_VGA_COMPATIBLE = 16
DISPLAY_DEVICE_REMOVABLE = 32
DISPLAY_DEVICE_ACC_DRIVER = 64
DISPLAY_DEVICE_MODESPRUNED = 134217728
DISPLAY_DEVICE_RDPUDD = 16777216
DISPLAY_DEVICE_REMOTE = 67108864
DISPLAY_DEVICE_DISCONNECT = 33554432
DISPLAY_DEVICE_TS_COMPATIBLE = 2097152
DISPLAY_DEVICE_UNSAFE_MODES_ON = 524288
DISPLAY_DEVICE_ACTIVE = 1
DISPLAY_DEVICE_ATTACHED = 2
DISPLAYCONFIG_MAXPATH = 1024
DISPLAYCONFIG_PATH_MODE_IDX_INVALID = 4294967295
DISPLAYCONFIG_PATH_TARGET_MODE_IDX_INVALID = 65535
DISPLAYCONFIG_PATH_DESKTOP_IMAGE_IDX_INVALID = 65535
DISPLAYCONFIG_PATH_SOURCE_MODE_IDX_INVALID = 65535
DISPLAYCONFIG_PATH_CLONE_GROUP_INVALID = 65535
DISPLAYCONFIG_SOURCE_IN_USE = 1
DISPLAYCONFIG_TARGET_IN_USE = 1
DISPLAYCONFIG_TARGET_FORCIBLE = 2
DISPLAYCONFIG_TARGET_FORCED_AVAILABILITY_BOOT = 4
DISPLAYCONFIG_TARGET_FORCED_AVAILABILITY_PATH = 8
DISPLAYCONFIG_TARGET_FORCED_AVAILABILITY_SYSTEM = 16
DISPLAYCONFIG_TARGET_IS_HMD = 32
DISPLAYCONFIG_PATH_ACTIVE = 1
DISPLAYCONFIG_PATH_PREFERRED_UNSCALED = 4
DISPLAYCONFIG_PATH_SUPPORT_VIRTUAL_MODE = 8
DISPLAYCONFIG_PATH_VALID_FLAGS = 29
QDC_ALL_PATHS = 1
QDC_ONLY_ACTIVE_PATHS = 2
QDC_DATABASE_CURRENT = 4
QDC_VIRTUAL_MODE_AWARE = 16
QDC_INCLUDE_HMD = 32
QDC_VIRTUAL_REFRESH_RATE_AWARE = 64
SDC_TOPOLOGY_INTERNAL = 1
SDC_TOPOLOGY_CLONE = 2
SDC_TOPOLOGY_EXTEND = 4
SDC_TOPOLOGY_EXTERNAL = 8
SDC_TOPOLOGY_SUPPLIED = 16
SDC_USE_SUPPLIED_DISPLAY_CONFIG = 32
SDC_VALIDATE = 64
SDC_APPLY = 128
SDC_NO_OPTIMIZATION = 256
SDC_SAVE_TO_DATABASE = 512
SDC_ALLOW_CHANGES = 1024
SDC_PATH_PERSIST_IF_REQUIRED = 2048
SDC_FORCE_MODE_ENUMERATION = 4096
SDC_ALLOW_PATH_ORDER_CHANGES = 8192
SDC_VIRTUAL_MODE_AWARE = 32768
SDC_VIRTUAL_REFRESH_RATE_AWARE = 131072
RDH_RECTANGLES = 1
SYSRGN = 4
TT_POLYGON_TYPE = 24
TT_PRIM_LINE = 1
TT_PRIM_QSPLINE = 2
TT_PRIM_CSPLINE = 3
GCP_DBCS = 1
GCP_ERROR = 32768
FLI_MASK = 4155
FLI_GLYPHS = 262144
GCP_JUSTIFYIN = 2097152
GCPCLASS_LATIN = 1
GCPCLASS_HEBREW = 2
GCPCLASS_ARABIC = 2
GCPCLASS_NEUTRAL = 3
GCPCLASS_LOCALNUMBER = 4
GCPCLASS_LATINNUMBER = 5
GCPCLASS_LATINNUMERICTERMINATOR = 6
GCPCLASS_LATINNUMERICSEPARATOR = 7
GCPCLASS_NUMERICSEPARATOR = 8
GCPCLASS_PREBOUNDLTR = 128
GCPCLASS_PREBOUNDRTL = 64
GCPCLASS_POSTBOUNDLTR = 32
GCPCLASS_POSTBOUNDRTL = 16
GCPGLYPH_LINKBEFORE = 32768
GCPGLYPH_LINKAFTER = 16384
TT_AVAILABLE = 1
TT_ENABLED = 2
PFD_TYPE_RGBA = 0
PFD_TYPE_COLORINDEX = 1
PFD_MAIN_PLANE = 0
PFD_OVERLAY_PLANE = 1
PFD_UNDERLAY_PLANE = -1
PFD_DOUBLEBUFFER = 1
PFD_STEREO = 2
PFD_DRAW_TO_WINDOW = 4
PFD_DRAW_TO_BITMAP = 8
PFD_SUPPORT_GDI = 16
PFD_SUPPORT_OPENGL = 32
PFD_GENERIC_FORMAT = 64
PFD_NEED_PALETTE = 128
PFD_NEED_SYSTEM_PALETTE = 256
PFD_SWAP_EXCHANGE = 512
PFD_SWAP_COPY = 1024
PFD_SWAP_LAYER_BUFFERS = 2048
PFD_GENERIC_ACCELERATED = 4096
PFD_SUPPORT_DIRECTDRAW = 8192
PFD_DIRECT3D_ACCELERATED = 16384
PFD_SUPPORT_COMPOSITION = 32768
PFD_DEPTH_DONTCARE = 536870912
PFD_DOUBLEBUFFER_DONTCARE = 1073741824
PFD_STEREO_DONTCARE = 2147483648
DC_BINADJUST = 19
DC_EMF_COMPLIANT = 20
DC_DATATYPE_PRODUCED = 21
DC_MANUFACTURER = 23
DC_MODEL = 24
PRINTRATEUNIT_PPM = 1
PRINTRATEUNIT_CPS = 2
PRINTRATEUNIT_LPM = 3
PRINTRATEUNIT_IPM = 4
DCTT_BITMAP = 1
DCTT_DOWNLOAD = 2
DCTT_SUBDEV = 4
DCTT_DOWNLOAD_OUTLINE = 8
DCBA_FACEUPNONE = 0
DCBA_FACEUPCENTER = 1
DCBA_FACEUPLEFT = 2
DCBA_FACEUPRIGHT = 3
DCBA_FACEDOWNNONE = 256
DCBA_FACEDOWNCENTER = 257
DCBA_FACEDOWNLEFT = 258
DCBA_FACEDOWNRIGHT = 259
GS_8BIT_INDICES = 1
GGI_MARK_NONEXISTING_GLYPHS = 1
MM_MAX_NUMAXES = 16
MM_MAX_AXES_NAMELEN = 16
GDIREGISTERDDRAWPACKETVERSION = 1
AC_SRC_OVER = 0
AC_SRC_ALPHA = 1
GRADIENT_FILL_OP_FLAG = 255
CA_NEGATIVE = 1
CA_LOG_FILTER = 2
ILLUMINANT_DEVICE_DEFAULT = 0
ILLUMINANT_A = 1
ILLUMINANT_B = 2
ILLUMINANT_C = 3
ILLUMINANT_D50 = 4
ILLUMINANT_D55 = 5
ILLUMINANT_D65 = 6
ILLUMINANT_D75 = 7
ILLUMINANT_F2 = 8
ILLUMINANT_MAX_INDEX = 8
ILLUMINANT_TUNGSTEN = 1
ILLUMINANT_DAYLIGHT = 3
ILLUMINANT_FLUORESCENT = 8
ILLUMINANT_NTSC = 3
DI_APPBANDING = 1
DI_ROPS_READ_DESTINATION = 2
FONTMAPPER_MAX = 10
ICM_OFF = 1
ICM_ON = 2
ICM_QUERY = 3
ICM_DONE_OUTSIDEDC = 4
ENHMETA_SIGNATURE = 1179469088
ENHMETA_STOCK_OBJECT = 2147483648
EMR_HEADER = 1
EMR_POLYBEZIER = 2
EMR_POLYGON = 3
EMR_POLYLINE = 4
EMR_POLYBEZIERTO = 5
EMR_POLYLINETO = 6
EMR_POLYPOLYLINE = 7
EMR_POLYPOLYGON = 8
EMR_SETWINDOWEXTEX = 9
EMR_SETWINDOWORGEX = 10
EMR_SETVIEWPORTEXTEX = 11
EMR_SETVIEWPORTORGEX = 12
EMR_SETBRUSHORGEX = 13
EMR_EOF = 14
EMR_SETPIXELV = 15
EMR_SETMAPPERFLAGS = 16
EMR_SETMAPMODE = 17
EMR_SETBKMODE = 18
EMR_SETPOLYFILLMODE = 19
EMR_SETROP2 = 20
EMR_SETSTRETCHBLTMODE = 21
EMR_SETTEXTALIGN = 22
EMR_SETCOLORADJUSTMENT = 23
EMR_SETTEXTCOLOR = 24
EMR_SETBKCOLOR = 25
EMR_OFFSETCLIPRGN = 26
EMR_MOVETOEX = 27
EMR_SETMETARGN = 28
EMR_EXCLUDECLIPRECT = 29
EMR_INTERSECTCLIPRECT = 30
EMR_SCALEVIEWPORTEXTEX = 31
EMR_SCALEWINDOWEXTEX = 32
EMR_SAVEDC = 33
EMR_RESTOREDC = 34
EMR_SETWORLDTRANSFORM = 35
EMR_MODIFYWORLDTRANSFORM = 36
EMR_SELECTOBJECT = 37
EMR_CREATEPEN = 38
EMR_CREATEBRUSHINDIRECT = 39
EMR_DELETEOBJECT = 40
EMR_ANGLEARC = 41
EMR_ELLIPSE = 42
EMR_RECTANGLE = 43
EMR_ROUNDRECT = 44
EMR_ARC = 45
EMR_CHORD = 46
EMR_PIE = 47
EMR_SELECTPALETTE = 48
EMR_CREATEPALETTE = 49
EMR_SETPALETTEENTRIES = 50
EMR_RESIZEPALETTE = 51
EMR_REALIZEPALETTE = 52
EMR_EXTFLOODFILL = 53
EMR_LINETO = 54
EMR_ARCTO = 55
EMR_POLYDRAW = 56
EMR_SETARCDIRECTION = 57
EMR_SETMITERLIMIT = 58
EMR_BEGINPATH = 59
EMR_ENDPATH = 60
EMR_CLOSEFIGURE = 61
EMR_FILLPATH = 62
EMR_STROKEANDFILLPATH = 63
EMR_STROKEPATH = 64
EMR_FLATTENPATH = 65
EMR_WIDENPATH = 66
EMR_SELECTCLIPPATH = 67
EMR_ABORTPATH = 68
EMR_GDICOMMENT = 70
EMR_FILLRGN = 71
EMR_FRAMERGN = 72
EMR_INVERTRGN = 73
EMR_PAINTRGN = 74
EMR_EXTSELECTCLIPRGN = 75
EMR_BITBLT = 76
EMR_STRETCHBLT = 77
EMR_MASKBLT = 78
EMR_PLGBLT = 79
EMR_SETDIBITSTODEVICE = 80
EMR_STRETCHDIBITS = 81
EMR_EXTCREATEFONTINDIRECTW = 82
EMR_EXTTEXTOUTA = 83
EMR_EXTTEXTOUTW = 84
EMR_POLYBEZIER16 = 85
EMR_POLYGON16 = 86
EMR_POLYLINE16 = 87
EMR_POLYBEZIERTO16 = 88
EMR_POLYLINETO16 = 89
EMR_POLYPOLYLINE16 = 90
EMR_POLYPOLYGON16 = 91
EMR_POLYDRAW16 = 92
EMR_CREATEMONOBRUSH = 93
EMR_CREATEDIBPATTERNBRUSHPT = 94
EMR_EXTCREATEPEN = 95
EMR_POLYTEXTOUTA = 96
EMR_POLYTEXTOUTW = 97
EMR_SETICMMODE = 98
EMR_CREATECOLORSPACE = 99
EMR_SETCOLORSPACE = 100
EMR_DELETECOLORSPACE = 101
EMR_GLSRECORD = 102
EMR_GLSBOUNDEDRECORD = 103
EMR_PIXELFORMAT = 104
EMR_RESERVED_105 = 105
EMR_RESERVED_106 = 106
EMR_RESERVED_107 = 107
EMR_RESERVED_108 = 108
EMR_RESERVED_109 = 109
EMR_RESERVED_110 = 110
EMR_COLORCORRECTPALETTE = 111
EMR_SETICMPROFILEA = 112
EMR_SETICMPROFILEW = 113
EMR_ALPHABLEND = 114
EMR_SETLAYOUT = 115
EMR_TRANSPARENTBLT = 116
EMR_RESERVED_117 = 117
EMR_GRADIENTFILL = 118
EMR_RESERVED_119 = 119
EMR_RESERVED_120 = 120
EMR_COLORMATCHTOTARGETW = 121
EMR_CREATECOLORSPACEW = 122
EMR_MIN = 1
EMR_MAX = 122
SETICMPROFILE_EMBEDED = 1
CREATECOLORSPACE_EMBEDED = 1
COLORMATCHTOTARGET_EMBEDED = 1
GDICOMMENT_IDENTIFIER = 1128875079
GDICOMMENT_WINDOWS_METAFILE = 2147483649
GDICOMMENT_BEGINGROUP = 2
GDICOMMENT_ENDGROUP = 3
GDICOMMENT_MULTIFORMATS = 1073741828
EPS_SIGNATURE = 1179865157
GDICOMMENT_UNICODE_STRING = 64
GDICOMMENT_UNICODE_END = 128
WGL_FONT_LINES = 0
WGL_FONT_POLYGONS = 1
LPD_DOUBLEBUFFER = 1
LPD_STEREO = 2
LPD_SUPPORT_GDI = 16
LPD_SUPPORT_OPENGL = 32
LPD_SHARE_DEPTH = 64
LPD_SHARE_STENCIL = 128
LPD_SHARE_ACCUM = 256
LPD_SWAP_EXCHANGE = 512
LPD_SWAP_COPY = 1024
LPD_TRANSPARENT = 4096
LPD_TYPE_RGBA = 0
LPD_TYPE_COLORINDEX = 1
WGL_SWAP_MAIN_PLANE = 1
WGL_SWAP_OVERLAY1 = 2
WGL_SWAP_OVERLAY2 = 4
WGL_SWAP_OVERLAY3 = 8
WGL_SWAP_OVERLAY4 = 16
WGL_SWAP_OVERLAY5 = 32
WGL_SWAP_OVERLAY6 = 64
WGL_SWAP_OVERLAY7 = 128
WGL_SWAP_OVERLAY8 = 256
WGL_SWAP_OVERLAY9 = 512
WGL_SWAP_OVERLAY10 = 1024
WGL_SWAP_OVERLAY11 = 2048
WGL_SWAP_OVERLAY12 = 4096
WGL_SWAP_OVERLAY13 = 8192
WGL_SWAP_OVERLAY14 = 16384
WGL_SWAP_OVERLAY15 = 32768
WGL_SWAP_UNDERLAY1 = 65536
WGL_SWAP_UNDERLAY2 = 131072
WGL_SWAP_UNDERLAY3 = 262144
WGL_SWAP_UNDERLAY4 = 524288
WGL_SWAP_UNDERLAY5 = 1048576
WGL_SWAP_UNDERLAY6 = 2097152
WGL_SWAP_UNDERLAY7 = 4194304
WGL_SWAP_UNDERLAY8 = 8388608
WGL_SWAP_UNDERLAY9 = 16777216
WGL_SWAP_UNDERLAY10 = 33554432
WGL_SWAP_UNDERLAY11 = 67108864
WGL_SWAP_UNDERLAY12 = 134217728
WGL_SWAP_UNDERLAY13 = 268435456
WGL_SWAP_UNDERLAY14 = 536870912
WGL_SWAP_UNDERLAY15 = 1073741824
WGL_SWAPMULTIPLE_MAX = 16
NEWTRANSPARENT = 3
QUERYROPSUPPORT = 40
SELECTDIB = 41
SC_SCREENSAVE = 61760
TTFCFP_SUBSET = 0
TTFCFP_SUBSET1 = 1
TTFCFP_DELTA = 2
TTFCFP_APPLE_PLATFORMID = 1
TTFCFP_MS_PLATFORMID = 3
TTFCFP_DONT_CARE = 65535
TTFCFP_LANG_KEEP_ALL = 0
TTFCFP_FLAGS_SUBSET = 1
TTFCFP_FLAGS_COMPRESS = 2
TTFCFP_FLAGS_TTC = 4
TTFCFP_FLAGS_GLYPHLIST = 8
TTFMFP_SUBSET = 0
TTFMFP_SUBSET1 = 1
TTFMFP_DELTA = 2
ERR_GENERIC = 1000
ERR_READOUTOFBOUNDS = 1001
ERR_WRITEOUTOFBOUNDS = 1002
ERR_READCONTROL = 1003
ERR_WRITECONTROL = 1004
ERR_MEM = 1005
ERR_FORMAT = 1006
ERR_WOULD_GROW = 1007
ERR_VERSION = 1008
ERR_NO_GLYPHS = 1009
ERR_INVALID_MERGE_FORMATS = 1010
ERR_INVALID_MERGE_CHECKSUMS = 1011
ERR_INVALID_MERGE_NUMGLYPHS = 1012
ERR_INVALID_DELTA_FORMAT = 1013
ERR_NOT_TTC = 1014
ERR_INVALID_TTC_INDEX = 1015
ERR_MISSING_CMAP = 1030
ERR_MISSING_GLYF = 1031
ERR_MISSING_HEAD = 1032
ERR_MISSING_HHEA = 1033
ERR_MISSING_HMTX = 1034
ERR_MISSING_LOCA = 1035
ERR_MISSING_MAXP = 1036
ERR_MISSING_NAME = 1037
ERR_MISSING_POST = 1038
ERR_MISSING_OS2 = 1039
ERR_MISSING_VHEA = 1040
ERR_MISSING_VMTX = 1041
ERR_MISSING_HHEA_OR_VHEA = 1042
ERR_MISSING_HMTX_OR_VMTX = 1043
ERR_MISSING_EBDT = 1044
ERR_INVALID_CMAP = 1060
ERR_INVALID_GLYF = 1061
ERR_INVALID_HEAD = 1062
ERR_INVALID_HHEA = 1063
ERR_INVALID_HMTX = 1064
ERR_INVALID_LOCA = 1065
ERR_INVALID_MAXP = 1066
ERR_INVALID_NAME = 1067
ERR_INVALID_POST = 1068
ERR_INVALID_OS2 = 1069
ERR_INVALID_VHEA = 1070
ERR_INVALID_VMTX = 1071
ERR_INVALID_HHEA_OR_VHEA = 1072
ERR_INVALID_HMTX_OR_VMTX = 1073
ERR_INVALID_TTO = 1080
ERR_INVALID_GSUB = 1081
ERR_INVALID_GPOS = 1082
ERR_INVALID_GDEF = 1083
ERR_INVALID_JSTF = 1084
ERR_INVALID_BASE = 1085
ERR_INVALID_EBLC = 1086
ERR_INVALID_LTSH = 1087
ERR_INVALID_VDMX = 1088
ERR_INVALID_HDMX = 1089
ERR_PARAMETER0 = 1100
ERR_PARAMETER1 = 1101
ERR_PARAMETER2 = 1102
ERR_PARAMETER3 = 1103
ERR_PARAMETER4 = 1104
ERR_PARAMETER5 = 1105
ERR_PARAMETER6 = 1106
ERR_PARAMETER7 = 1107
ERR_PARAMETER8 = 1108
ERR_PARAMETER9 = 1109
ERR_PARAMETER10 = 1110
ERR_PARAMETER11 = 1111
ERR_PARAMETER12 = 1112
ERR_PARAMETER13 = 1113
ERR_PARAMETER14 = 1114
ERR_PARAMETER15 = 1115
ERR_PARAMETER16 = 1116
CHARSET_DEFAULT = 1
CHARSET_GLYPHIDX = 3
TTEMBED_FAILIFVARIATIONSIMULATED = 16
TTEMBED_WEBOBJECT = 128
TTEMBED_XORENCRYPTDATA = 268435456
TTEMBED_VARIATIONSIMULATED = 1
TTEMBED_EUDCEMBEDDED = 2
TTEMBED_SUBSETCANCEL = 4
TTLOAD_PRIVATE = 1
TTLOAD_EUDC_OVERWRITE = 2
TTLOAD_EUDC_SET = 4
TTDELETE_DONTREMOVEFONT = 1
E_NONE = 0
E_API_NOTIMPL = 1
E_CHARCODECOUNTINVALID = 2
E_CHARCODESETINVALID = 3
E_DEVICETRUETYPEFONT = 4
E_HDCINVALID = 6
E_NOFREEMEMORY = 7
E_FONTREFERENCEINVALID = 8
E_NOTATRUETYPEFONT = 10
E_ERRORACCESSINGFONTDATA = 12
E_ERRORACCESSINGFACENAME = 13
E_ERRORUNICODECONVERSION = 17
E_ERRORCONVERTINGCHARS = 18
E_EXCEPTION = 19
E_RESERVEDPARAMNOTNULL = 20
E_CHARSETINVALID = 21
E_FILE_NOT_FOUND = 23
E_TTC_INDEX_OUT_OF_RANGE = 24
E_INPUTPARAMINVALID = 25
E_ERRORCOMPRESSINGFONTDATA = 256
E_FONTDATAINVALID = 258
E_NAMECHANGEFAILED = 259
E_FONTNOTEMBEDDABLE = 260
E_PRIVSINVALID = 261
E_SUBSETTINGFAILED = 262
E_READFROMSTREAMFAILED = 263
E_SAVETOSTREAMFAILED = 264
E_NOOS2 = 265
E_T2NOFREEMEMORY = 266
E_ERRORREADINGFONTDATA = 267
E_FLAGSINVALID = 268
E_ERRORCREATINGFONTFILE = 269
E_FONTALREADYEXISTS = 270
E_FONTNAMEALREADYEXISTS = 271
E_FONTINSTALLFAILED = 272
E_ERRORDECOMPRESSINGFONTDATA = 273
E_ERRORACCESSINGEXCLUDELIST = 274
E_FACENAMEINVALID = 275
E_STREAMINVALID = 276
E_STATUSINVALID = 277
E_PRIVSTATUSINVALID = 278
E_PERMISSIONSINVALID = 279
E_PBENABLEDINVALID = 280
E_SUBSETTINGEXCEPTION = 281
E_SUBSTRING_TEST_FAIL = 282
E_FONTVARIATIONSIMULATED = 283
E_FONTFAMILYNAMENOTINFULL = 285
E_ADDFONTFAILED = 512
E_COULDNTCREATETEMPFILE = 513
E_FONTFILECREATEFAILED = 515
E_WINDOWSAPI = 516
E_FONTFILENOTFOUND = 517
E_RESOURCEFILECREATEFAILED = 518
E_ERROREXPANDINGFONTDATA = 519
E_ERRORGETTINGDC = 520
E_EXCEPTIONINDECOMPRESSION = 521
E_EXCEPTIONINCOMPRESSION = 522
enum R2_MODE : Int32
R2_BLACK = 1

R2_NOTMERGEPEN = 2

R2_MASKNOTPEN = 3

R2_NOTCOPYPEN = 4

R2_MASKPENNOT = 5

R2_NOT = 6

R2_XORPEN = 7

R2_NOTMASKPEN = 8

R2_MASKPEN = 9

R2_NOTXORPEN = 10

R2_NOP = 11

R2_MERGENOTPEN = 12

R2_COPYPEN = 13

R2_MERGEPENNOT = 14

R2_MERGEPEN = 15

R2_WHITE = 16

R2_LAST = 16

end
enum RGN_COMBINE_MODE : Int32
RGN_AND = 1

RGN_OR = 2

RGN_XOR = 3

RGN_DIFF = 4

RGN_COPY = 5

RGN_MIN = 1

RGN_MAX = 5

end
enum ETO_OPTIONS : UInt32
ETO_OPAQUE = 2

ETO_CLIPPED = 4

ETO_GLYPH_INDEX = 16

ETO_RTLREADING = 128

ETO_NUMERICSLOCAL = 1024

ETO_NUMERICSLATIN = 2048

ETO_IGNORELANGUAGE = 4096

ETO_PDY = 8192

ETO_REVERSE_INDEX_MAP = 65536

end
enum OBJ_TYPE : Int32
OBJ_PEN = 1

OBJ_BRUSH = 2

OBJ_DC = 3

OBJ_METADC = 4

OBJ_PAL = 5

OBJ_FONT = 6

OBJ_BITMAP = 7

OBJ_REGION = 8

OBJ_METAFILE = 9

OBJ_MEMDC = 10

OBJ_EXTPEN = 11

OBJ_ENHMETADC = 12

OBJ_ENHMETAFILE = 13

OBJ_COLORSPACE = 14

end
enum ROP_CODE : UInt32
SRCCOPY = 13369376

SRCPAINT = 15597702

SRCAND = 8913094

SRCINVERT = 6684742

SRCERASE = 4457256

NOTSRCCOPY = 3342344

NOTSRCERASE = 1114278

MERGECOPY = 12583114

MERGEPAINT = 12255782

PATCOPY = 15728673

PATPAINT = 16452105

PATINVERT = 5898313

DSTINVERT = 5570569

BLACKNESS = 66

WHITENESS = 16711778

NOMIRRORBITMAP = 2147483648

CAPTUREBLT = 1073741824

end
enum DIB_USAGE : UInt32
DIB_RGB_COLORS = 0

DIB_PAL_COLORS = 1

end
enum DRAWEDGE_FLAGS : UInt32
BDR_RAISEDOUTER = 1

BDR_SUNKENOUTER = 2

BDR_RAISEDINNER = 4

BDR_SUNKENINNER = 8

BDR_OUTER = 3

BDR_INNER = 12

BDR_RAISED = 5

BDR_SUNKEN = 10

EDGE_RAISED = 5

EDGE_SUNKEN = 10

EDGE_ETCHED = 6

EDGE_BUMP = 9

end
enum DFC_TYPE : UInt32
DFC_CAPTION = 1

DFC_MENU = 2

DFC_SCROLL = 3

DFC_BUTTON = 4

DFC_POPUPMENU = 5

end
enum DFCS_STATE : UInt32
DFCS_CAPTIONCLOSE = 0

DFCS_CAPTIONMIN = 1

DFCS_CAPTIONMAX = 2

DFCS_CAPTIONRESTORE = 3

DFCS_CAPTIONHELP = 4

DFCS_MENUARROW = 0

DFCS_MENUCHECK = 1

DFCS_MENUBULLET = 2

DFCS_MENUARROWRIGHT = 4

DFCS_SCROLLUP = 0

DFCS_SCROLLDOWN = 1

DFCS_SCROLLLEFT = 2

DFCS_SCROLLRIGHT = 3

DFCS_SCROLLCOMBOBOX = 5

DFCS_SCROLLSIZEGRIP = 8

DFCS_SCROLLSIZEGRIPRIGHT = 16

DFCS_BUTTONCHECK = 0

DFCS_BUTTONRADIOIMAGE = 1

DFCS_BUTTONRADIOMASK = 2

DFCS_BUTTONRADIO = 4

DFCS_BUTTON3STATE = 8

DFCS_BUTTONPUSH = 16

DFCS_INACTIVE = 256

DFCS_PUSHED = 512

DFCS_CHECKED = 1024

DFCS_TRANSPARENT = 2048

DFCS_HOT = 4096

DFCS_ADJUSTRECT = 8192

DFCS_FLAT = 16384

DFCS_MONO = 32768

end
enum CDS_TYPE : UInt32
CDS_FULLSCREEN = 4

CDS_GLOBAL = 8

CDS_NORESET = 268435456

CDS_RESET = 1073741824

CDS_SET_PRIMARY = 16

CDS_TEST = 2

CDS_UPDATEREGISTRY = 1

CDS_VIDEOPARAMETERS = 32

CDS_ENABLE_UNSAFE_MODES = 256

CDS_DISABLE_UNSAFE_MODES = 512

CDS_RESET_EX = 536870912

end
enum DISP_CHANGE : Int32
DISP_CHANGE_SUCCESSFUL = 0

DISP_CHANGE_RESTART = 1

DISP_CHANGE_FAILED = -1

DISP_CHANGE_BADMODE = -2

DISP_CHANGE_NOTUPDATED = -3

DISP_CHANGE_BADFLAGS = -4

DISP_CHANGE_BADPARAM = -5

DISP_CHANGE_BADDUALVIEW = -6

end
enum DRAWSTATE_FLAGS : UInt32
DST_COMPLEX = 0

DST_TEXT = 1

DST_PREFIXTEXT = 2

DST_ICON = 3

DST_BITMAP = 4

DSS_NORMAL = 0

DSS_UNION = 16

DSS_DISABLED = 32

DSS_MONO = 128

DSS_HIDEPREFIX = 512

DSS_PREFIXONLY = 1024

DSS_RIGHT = 32768

end
enum REDRAW_WINDOW_FLAGS : UInt32
RDW_INVALIDATE = 1

RDW_INTERNALPAINT = 2

RDW_ERASE = 4

RDW_VALIDATE = 8

RDW_NOINTERNALPAINT = 16

RDW_NOERASE = 32

RDW_NOCHILDREN = 64

RDW_ALLCHILDREN = 128

RDW_UPDATENOW = 256

RDW_ERASENOW = 512

RDW_FRAME = 1024

RDW_NOFRAME = 2048

end
enum ENUM_DISPLAY_SETTINGS_MODE : UInt32
ENUM_CURRENT_SETTINGS = 4294967295

ENUM_REGISTRY_SETTINGS = 4294967294

end
enum TEXT_ALIGN_OPTIONS : UInt32
TA_NOUPDATECP = 0

TA_UPDATECP = 1

TA_LEFT = 0

TA_RIGHT = 2

TA_CENTER = 6

TA_TOP = 0

TA_BOTTOM = 8

TA_BASELINE = 24

TA_RTLREADING = 256

TA_MASK = 287

VTA_BASELINE = 24

VTA_LEFT = 8

VTA_RIGHT = 0

VTA_CENTER = 6

VTA_BOTTOM = 2

VTA_TOP = 0

end
enum PEN_STYLE : UInt32
PS_GEOMETRIC = 65536

PS_COSMETIC = 0

PS_SOLID = 0

PS_DASH = 1

PS_DOT = 2

PS_DASHDOT = 3

PS_DASHDOTDOT = 4

PS_NULL = 5

PS_INSIDEFRAME = 6

PS_USERSTYLE = 7

PS_ALTERNATE = 8

PS_STYLE_MASK = 15

PS_ENDCAP_ROUND = 0

PS_ENDCAP_SQUARE = 256

PS_ENDCAP_FLAT = 512

PS_ENDCAP_MASK = 3840

PS_JOIN_ROUND = 0

PS_JOIN_BEVEL = 4096

PS_JOIN_MITER = 8192

PS_JOIN_MASK = 61440

PS_TYPE_MASK = 983040

end
enum TTEMBED_FLAGS : UInt32
TTEMBED_EMBEDEUDC = 32

TTEMBED_RAW = 0

TTEMBED_SUBSET = 1

TTEMBED_TTCOMPRESSED = 4

end
enum DRAW_TEXT_FORMAT : UInt32
DT_BOTTOM = 8

DT_CALCRECT = 1024

DT_CENTER = 1

DT_EDITCONTROL = 8192

DT_END_ELLIPSIS = 32768

DT_EXPANDTABS = 64

DT_EXTERNALLEADING = 512

DT_HIDEPREFIX = 1048576

DT_INTERNAL = 4096

DT_LEFT = 0

DT_MODIFYSTRING = 65536

DT_NOCLIP = 256

DT_NOFULLWIDTHCHARBREAK = 524288

DT_NOPREFIX = 2048

DT_PATH_ELLIPSIS = 16384

DT_PREFIXONLY = 2097152

DT_RIGHT = 2

DT_RTLREADING = 131072

DT_SINGLELINE = 32

DT_TABSTOP = 128

DT_TOP = 0

DT_VCENTER = 4

DT_WORDBREAK = 16

DT_WORD_ELLIPSIS = 262144

end
enum EMBED_FONT_CHARSET : UInt32
CHARSET_UNICODE = 1

CHARSET_SYMBOL = 2

end
enum GET_DCX_FLAGS : UInt32
DCX_WINDOW = 1

DCX_CACHE = 2

DCX_PARENTCLIP = 32

DCX_CLIPSIBLINGS = 16

DCX_CLIPCHILDREN = 8

DCX_NORESETATTRS = 4

DCX_LOCKWINDOWUPDATE = 1024

DCX_EXCLUDERGN = 64

DCX_INTERSECTRGN = 128

DCX_INTERSECTUPDATE = 512

DCX_VALIDATE = 2097152

end
enum GET_GLYPH_OUTLINE_FORMAT : UInt32
GGO_BEZIER = 3

GGO_BITMAP = 1

GGO_GLYPH_INDEX = 128

GGO_GRAY2_BITMAP = 4

GGO_GRAY4_BITMAP = 5

GGO_GRAY8_BITMAP = 6

GGO_METRICS = 0

GGO_NATIVE = 2

GGO_UNHINTED = 256

end
enum SET_BOUNDS_RECT_FLAGS : UInt32
DCB_ACCUMULATE = 2

DCB_DISABLE = 8

DCB_ENABLE = 4

DCB_RESET = 1

end
enum GET_STOCK_OBJECT_FLAGS : UInt32
BLACK_BRUSH = 4

DKGRAY_BRUSH = 3

DC_BRUSH = 18

GRAY_BRUSH = 2

HOLLOW_BRUSH = 5

LTGRAY_BRUSH = 1

NULL_BRUSH = 5

WHITE_BRUSH = 0

BLACK_PEN = 7

DC_PEN = 19

NULL_PEN = 8

WHITE_PEN = 6

ANSI_FIXED_FONT = 11

ANSI_VAR_FONT = 12

DEVICE_DEFAULT_FONT = 14

DEFAULT_GUI_FONT = 17

OEM_FIXED_FONT = 10

SYSTEM_FONT = 13

SYSTEM_FIXED_FONT = 16

DEFAULT_PALETTE = 15

end
enum MODIFY_WORLD_TRANSFORM_MODE : UInt32
MWT_IDENTITY = 1

MWT_LEFTMULTIPLY = 2

MWT_RIGHTMULTIPLY = 3

end
enum FONT_CLIP_PRECISION : UInt32
CLIP_CHARACTER_PRECIS = 1

CLIP_DEFAULT_PRECIS = 0

CLIP_DFA_DISABLE = 64

CLIP_EMBEDDED = 128

CLIP_LH_ANGLES = 16

CLIP_MASK = 15

CLIP_STROKE_PRECIS = 2

CLIP_TT_ALWAYS = 32

end
enum CREATE_POLYGON_RGN_MODE : UInt32
ALTERNATE = 1

WINDING = 2

end
enum EMBEDDED_FONT_PRIV_STATUS : UInt32
EMBED_PREVIEWPRINT = 1

EMBED_EDITABLE = 2

EMBED_INSTALLABLE = 3

EMBED_NOEMBEDDING = 4

end
enum MONITOR_FROM_FLAGS : UInt32
MONITOR_DEFAULTTONEAREST = 2

MONITOR_DEFAULTTONULL = 0

MONITOR_DEFAULTTOPRIMARY = 1

end
enum FONT_RESOURCE_CHARACTERISTICS : UInt32
FR_PRIVATE = 16

FR_NOT_ENUM = 32

end
enum DC_LAYOUT : UInt32
LAYOUT_BITMAPORIENTATIONPRESERVED = 8

LAYOUT_RTL = 1

end
enum GET_DEVICE_CAPS_INDEX : UInt32
DRIVERVERSION = 0

TECHNOLOGY = 2

HORZSIZE = 4

VERTSIZE = 6

HORZRES = 8

VERTRES = 10

BITSPIXEL = 12

PLANES = 14

NUMBRUSHES = 16

NUMPENS = 18

NUMMARKERS = 20

NUMFONTS = 22

NUMCOLORS = 24

PDEVICESIZE = 26

CURVECAPS = 28

LINECAPS = 30

POLYGONALCAPS = 32

TEXTCAPS = 34

CLIPCAPS = 36

RASTERCAPS = 38

ASPECTX = 40

ASPECTY = 42

ASPECTXY = 44

LOGPIXELSX = 88

LOGPIXELSY = 90

SIZEPALETTE = 104

NUMRESERVED = 106

COLORRES = 108

PHYSICALWIDTH = 110

PHYSICALHEIGHT = 111

PHYSICALOFFSETX = 112

PHYSICALOFFSETY = 113

SCALINGFACTORX = 114

SCALINGFACTORY = 115

VREFRESH = 116

DESKTOPVERTRES = 117

DESKTOPHORZRES = 118

BLTALIGNMENT = 119

SHADEBLENDCAPS = 120

COLORMGMTCAPS = 121

end
enum FONT_OUTPUT_PRECISION : UInt32
OUT_CHARACTER_PRECIS = 2

OUT_DEFAULT_PRECIS = 0

OUT_DEVICE_PRECIS = 5

OUT_OUTLINE_PRECIS = 8

OUT_PS_ONLY_PRECIS = 10

OUT_RASTER_PRECIS = 6

OUT_STRING_PRECIS = 1

OUT_STROKE_PRECIS = 3

OUT_TT_ONLY_PRECIS = 7

OUT_TT_PRECIS = 4

end
enum ARC_DIRECTION : UInt32
AD_COUNTERCLOCKWISE = 1

AD_CLOCKWISE = 2

end
enum TTLOAD_EMBEDDED_FONT_STATUS : UInt32
TTLOAD_FONT_SUBSETTED = 1

TTLOAD_FONT_IN_SYSSTARTUP = 2

end
enum STRETCH_BLT_MODE : UInt32
BLACKONWHITE = 1

COLORONCOLOR = 3

HALFTONE = 4

STRETCH_ANDSCANS = 1

STRETCH_DELETESCANS = 3

STRETCH_HALFTONE = 4

STRETCH_ORSCANS = 2

WHITEONBLACK = 2

end
enum FONT_QUALITY : UInt32
ANTIALIASED_QUALITY = 4

CLEARTYPE_QUALITY = 5

DEFAULT_QUALITY = 0

DRAFT_QUALITY = 1

NONANTIALIASED_QUALITY = 3

PROOF_QUALITY = 2

end
enum BACKGROUND_MODE : UInt32
OPAQUE = 2

TRANSPARENT = 1

end
enum GET_CHARACTER_PLACEMENT_FLAGS : UInt32
GCP_CLASSIN = 524288

GCP_DIACRITIC = 256

GCP_DISPLAYZWG = 4194304

GCP_GLYPHSHAPE = 16

GCP_JUSTIFY = 65536

GCP_KASHIDA = 1024

GCP_LIGATE = 32

GCP_MAXEXTENT = 1048576

GCP_NEUTRALOVERRIDE = 33554432

GCP_NUMERICOVERRIDE = 16777216

GCP_NUMERICSLATIN = 67108864

GCP_NUMERICSLOCAL = 134217728

GCP_REORDER = 2

GCP_SYMSWAPOFF = 8388608

GCP_USEKERNING = 8

end
enum DRAW_EDGE_FLAGS : UInt32
BF_ADJUST = 8192

BF_BOTTOM = 8

BF_BOTTOMLEFT = 9

BF_BOTTOMRIGHT = 12

BF_DIAGONAL = 16

BF_DIAGONAL_ENDBOTTOMLEFT = 25

BF_DIAGONAL_ENDBOTTOMRIGHT = 28

BF_DIAGONAL_ENDTOPLEFT = 19

BF_DIAGONAL_ENDTOPRIGHT = 22

BF_FLAT = 16384

BF_LEFT = 1

BF_MIDDLE = 2048

BF_MONO = 32768

BF_RECT = 15

BF_RIGHT = 4

BF_SOFT = 4096

BF_TOP = 2

BF_TOPLEFT = 3

BF_TOPRIGHT = 6

end
enum FONT_LICENSE_PRIVS : UInt32
LICENSE_PREVIEWPRINT = 4

LICENSE_EDITABLE = 8

LICENSE_INSTALLABLE = 0

LICENSE_NOEMBEDDING = 2

LICENSE_DEFAULT = 0

end
enum GRADIENT_FILL : UInt32
GRADIENT_FILL_RECT_H = 0

GRADIENT_FILL_RECT_V = 1

GRADIENT_FILL_TRIANGLE = 2

end
enum CREATE_FONT_PACKAGE_SUBSET_ENCODING : UInt32
TTFCFP_STD_MAC_CHAR_SET = 0

TTFCFP_SYMBOL_CHAR_SET = 0

TTFCFP_UNICODE_CHAR_SET = 1

end
enum EXT_FLOOD_FILL_TYPE : UInt32
FLOODFILLBORDER = 0

FLOODFILLSURFACE = 1

end
enum HATCH_BRUSH_STYLE : UInt32
HS_BDIAGONAL = 3

HS_CROSS = 4

HS_DIAGCROSS = 5

HS_FDIAGONAL = 2

HS_HORIZONTAL = 0

HS_VERTICAL = 1

end
enum DRAW_CAPTION_FLAGS : UInt32
DC_ACTIVE = 1

DC_BUTTONS = 4096

DC_GRADIENT = 32

DC_ICON = 4

DC_INBUTTON = 16

DC_SMALLCAP = 2

DC_TEXT = 8

end
enum SYSTEM_PALETTE_USE : UInt32
SYSPAL_NOSTATIC = 2

SYSPAL_NOSTATIC256 = 3

SYSPAL_STATIC = 1

end
enum GRAPHICS_MODE : UInt32
GM_COMPATIBLE = 1

GM_ADVANCED = 2

end
enum FONT_PITCH_AND_FAMILY : UInt32
FF_DECORATIVE = 80

FF_DONTCARE = 0

FF_MODERN = 48

FF_ROMAN = 16

FF_SCRIPT = 64

FF_SWISS = 32

end
enum CREATE_FONT_PACKAGE_SUBSET_PLATFORM : UInt32
TTFCFP_UNICODE_PLATFORMID = 0

TTFCFP_ISO_PLATFORMID = 2

end
enum HDC_MAP_MODE : UInt32
MM_ANISOTROPIC = 8

MM_HIENGLISH = 5

MM_HIMETRIC = 3

MM_ISOTROPIC = 7

MM_LOENGLISH = 4

MM_LOMETRIC = 2

MM_TEXT = 1

MM_TWIPS = 6

end
type HDC = LibC::Int*
type CreatedHDC = LibC::Int*
type HBITMAP = LibC::Int*
type HRGN = LibC::Int*
type HPEN = LibC::Int*
type HBRUSH = LibC::Int*
type HFONT = LibC::Int*
type HMETAFILE = LibC::Int*
type HENHMETAFILE = LibC::Int*
type HPALETTE = LibC::Int*
type HdcMetdataFileHandle = LibC::Int*
type HdcMetdataEnhFileHandle = LibC::Int*
type HGDIOBJ = LibC::Int*
type HMONITOR = LibC::Int*
struct XFORM
  eM11 : LibC::Single
  eM12 : LibC::Single
  eM21 : LibC::Single
  eM22 : LibC::Single
  eDx : LibC::Single
  eDy : LibC::Single
end
struct BITMAP
  bmType : LibC::Int32
  bmWidth : LibC::Int32
  bmHeight : LibC::Int32
  bmWidthBytes : LibC::Int32
  bmPlanes : LibC::UInt16
  bmBitsPixel : LibC::UInt16
  bmBits : LibC::Void*
end
struct RGBTRIPLE
  rgbtBlue : LibC::Byte
  rgbtGreen : LibC::Byte
  rgbtRed : LibC::Byte
end
struct RGBQUAD
  rgbBlue : LibC::Byte
  rgbGreen : LibC::Byte
  rgbRed : LibC::Byte
  rgbReserved : LibC::Byte
end
struct CIEXYZ
  ciexyzX : LibC::Int32
  ciexyzY : LibC::Int32
  ciexyzZ : LibC::Int32
end
struct CIEXYZTRIPLE
  ciexyzRed : CIEXYZ
  ciexyzGreen : CIEXYZ
  ciexyzBlue : CIEXYZ
end
struct BITMAPCOREHEADER
  bcSize : LibC::UInt32
  bcWidth : LibC::UInt16
  bcHeight : LibC::UInt16
  bcPlanes : LibC::UInt16
  bcBitCount : LibC::UInt16
end
struct BITMAPINFOHEADER
  biSize : LibC::UInt32
  biWidth : LibC::Int32
  biHeight : LibC::Int32
  biPlanes : LibC::UInt16
  biBitCount : LibC::UInt16
  biCompression : LibC::UInt32
  biSizeImage : LibC::UInt32
  biXPelsPerMeter : LibC::Int32
  biYPelsPerMeter : LibC::Int32
  biClrUsed : LibC::UInt32
  biClrImportant : LibC::UInt32
end
struct BITMAPV4HEADER
  bV4Size : LibC::UInt32
  bV4Width : LibC::Int32
  bV4Height : LibC::Int32
  bV4Planes : LibC::UInt16
  bV4BitCount : LibC::UInt16
  bV4V4Compression : LibC::UInt32
  bV4SizeImage : LibC::UInt32
  bV4XPelsPerMeter : LibC::Int32
  bV4YPelsPerMeter : LibC::Int32
  bV4ClrUsed : LibC::UInt32
  bV4ClrImportant : LibC::UInt32
  bV4RedMask : LibC::UInt32
  bV4GreenMask : LibC::UInt32
  bV4BlueMask : LibC::UInt32
  bV4AlphaMask : LibC::UInt32
  bV4CSType : LibC::UInt32
  bV4Endpoints : CIEXYZTRIPLE
  bV4GammaRed : LibC::UInt32
  bV4GammaGreen : LibC::UInt32
  bV4GammaBlue : LibC::UInt32
end
struct BITMAPV5HEADER
  bV5Size : LibC::UInt32
  bV5Width : LibC::Int32
  bV5Height : LibC::Int32
  bV5Planes : LibC::UInt16
  bV5BitCount : LibC::UInt16
  bV5Compression : LibC::UInt32
  bV5SizeImage : LibC::UInt32
  bV5XPelsPerMeter : LibC::Int32
  bV5YPelsPerMeter : LibC::Int32
  bV5ClrUsed : LibC::UInt32
  bV5ClrImportant : LibC::UInt32
  bV5RedMask : LibC::UInt32
  bV5GreenMask : LibC::UInt32
  bV5BlueMask : LibC::UInt32
  bV5AlphaMask : LibC::UInt32
  bV5CSType : LibC::UInt32
  bV5Endpoints : CIEXYZTRIPLE
  bV5GammaRed : LibC::UInt32
  bV5GammaGreen : LibC::UInt32
  bV5GammaBlue : LibC::UInt32
  bV5Intent : LibC::UInt32
  bV5ProfileData : LibC::UInt32
  bV5ProfileSize : LibC::UInt32
  bV5Reserved : LibC::UInt32
end
struct BITMAPINFO
  bmiHeader : BITMAPINFOHEADER
  bmiColors : Array(RGBQUAD)
end
struct BITMAPCOREINFO
  bmciHeader : BITMAPCOREHEADER
  bmciColors : Array(RGBTRIPLE)
end
struct BITMAPFILEHEADER
  bfType : LibC::UInt16
  bfSize : LibC::UInt32
  bfReserved1 : LibC::UInt16
  bfReserved2 : LibC::UInt16
  bfOffBits : LibC::UInt32
end
struct HANDLETABLE
  objectHandle : Array(HGDIOBJ)
end
struct METARECORD
  rdSize : LibC::UInt32
  rdFunction : LibC::UInt16
  rdParm : Array(LibC::UInt16)
end
struct METAHEADER
  mtType : LibC::UInt16
  mtHeaderSize : LibC::UInt16
  mtVersion : LibC::UInt16
  mtSize : LibC::UInt32
  mtNoObjects : LibC::UInt16
  mtMaxRecord : LibC::UInt32
  mtNoParameters : LibC::UInt16
end
struct ENHMETARECORD
  iType : LibC::UInt32
  nSize : LibC::UInt32
  dParm : Array(LibC::UInt32)
end
struct ENHMETAHEADER
  iType : LibC::UInt32
  nSize : LibC::UInt32
  rclBounds : RECTL
  rclFrame : RECTL
  dSignature : LibC::UInt32
  nVersion : LibC::UInt32
  nBytes : LibC::UInt32
  nRecords : LibC::UInt32
  nHandles : LibC::UInt16
  sReserved : LibC::UInt16
  nDescription : LibC::UInt32
  offDescription : LibC::UInt32
  nPalEntries : LibC::UInt32
  szlDevice : SIZE
  szlMillimeters : SIZE
  cbPixelFormat : LibC::UInt32
  offPixelFormat : LibC::UInt32
  bOpenGL : LibC::UInt32
  szlMicrometers : SIZE
end
struct TEXTMETRICA
  tmHeight : LibC::Int32
  tmAscent : LibC::Int32
  tmDescent : LibC::Int32
  tmInternalLeading : LibC::Int32
  tmExternalLeading : LibC::Int32
  tmAveCharWidth : LibC::Int32
  tmMaxCharWidth : LibC::Int32
  tmWeight : LibC::Int32
  tmOverhang : LibC::Int32
  tmDigitizedAspectX : LibC::Int32
  tmDigitizedAspectY : LibC::Int32
  tmFirstChar : LibC::Byte
  tmLastChar : LibC::Byte
  tmDefaultChar : LibC::Byte
  tmBreakChar : LibC::Byte
  tmItalic : LibC::Byte
  tmUnderlined : LibC::Byte
  tmStruckOut : LibC::Byte
  tmPitchAndFamily : LibC::Byte
  tmCharSet : LibC::Byte
end
struct TEXTMETRICW
  tmHeight : LibC::Int32
  tmAscent : LibC::Int32
  tmDescent : LibC::Int32
  tmInternalLeading : LibC::Int32
  tmExternalLeading : LibC::Int32
  tmAveCharWidth : LibC::Int32
  tmMaxCharWidth : LibC::Int32
  tmWeight : LibC::Int32
  tmOverhang : LibC::Int32
  tmDigitizedAspectX : LibC::Int32
  tmDigitizedAspectY : LibC::Int32
  tmFirstChar : LibC::Char
  tmLastChar : LibC::Char
  tmDefaultChar : LibC::Char
  tmBreakChar : LibC::Char
  tmItalic : LibC::Byte
  tmUnderlined : LibC::Byte
  tmStruckOut : LibC::Byte
  tmPitchAndFamily : LibC::Byte
  tmCharSet : LibC::Byte
end
struct NEWTEXTMETRICA
  tmHeight : LibC::Int32
  tmAscent : LibC::Int32
  tmDescent : LibC::Int32
  tmInternalLeading : LibC::Int32
  tmExternalLeading : LibC::Int32
  tmAveCharWidth : LibC::Int32
  tmMaxCharWidth : LibC::Int32
  tmWeight : LibC::Int32
  tmOverhang : LibC::Int32
  tmDigitizedAspectX : LibC::Int32
  tmDigitizedAspectY : LibC::Int32
  tmFirstChar : LibC::Byte
  tmLastChar : LibC::Byte
  tmDefaultChar : LibC::Byte
  tmBreakChar : LibC::Byte
  tmItalic : LibC::Byte
  tmUnderlined : LibC::Byte
  tmStruckOut : LibC::Byte
  tmPitchAndFamily : LibC::Byte
  tmCharSet : LibC::Byte
  ntmFlags : LibC::UInt32
  ntmSizeEM : LibC::UInt32
  ntmCellHeight : LibC::UInt32
  ntmAvgWidth : LibC::UInt32
end
struct NEWTEXTMETRICW
  tmHeight : LibC::Int32
  tmAscent : LibC::Int32
  tmDescent : LibC::Int32
  tmInternalLeading : LibC::Int32
  tmExternalLeading : LibC::Int32
  tmAveCharWidth : LibC::Int32
  tmMaxCharWidth : LibC::Int32
  tmWeight : LibC::Int32
  tmOverhang : LibC::Int32
  tmDigitizedAspectX : LibC::Int32
  tmDigitizedAspectY : LibC::Int32
  tmFirstChar : LibC::Char
  tmLastChar : LibC::Char
  tmDefaultChar : LibC::Char
  tmBreakChar : LibC::Char
  tmItalic : LibC::Byte
  tmUnderlined : LibC::Byte
  tmStruckOut : LibC::Byte
  tmPitchAndFamily : LibC::Byte
  tmCharSet : LibC::Byte
  ntmFlags : LibC::UInt32
  ntmSizeEM : LibC::UInt32
  ntmCellHeight : LibC::UInt32
  ntmAvgWidth : LibC::UInt32
end
struct PELARRAY
  paXCount : LibC::Int32
  paYCount : LibC::Int32
  paXExt : LibC::Int32
  paYExt : LibC::Int32
  paRGBs : LibC::Byte
end
struct LOGBRUSH
  lbStyle : LibC::UInt32
  lbColor : LibC::UInt32
  lbHatch : LibC::UIint*
end
struct LOGBRUSH32
  lbStyle : LibC::UInt32
  lbColor : LibC::UInt32
  lbHatch : LibC::UInt32
end
struct LOGPEN
  lopnStyle : LibC::UInt32
  lopnWidth : POINT
  lopnColor : LibC::UInt32
end
struct EXTLOGPEN
  elpPenStyle : LibC::UInt32
  elpWidth : LibC::UInt32
  elpBrushStyle : LibC::UInt32
  elpColor : LibC::UInt32
  elpHatch : LibC::UIint*
  elpNumEntries : LibC::UInt32
  elpStyleEntry : Array(LibC::UInt32)
end
struct EXTLOGPEN32
  elpPenStyle : LibC::UInt32
  elpWidth : LibC::UInt32
  elpBrushStyle : LibC::UInt32
  elpColor : LibC::UInt32
  elpHatch : LibC::UInt32
  elpNumEntries : LibC::UInt32
  elpStyleEntry : Array(LibC::UInt32)
end
struct PALETTEENTRY
  peRed : LibC::Byte
  peGreen : LibC::Byte
  peBlue : LibC::Byte
  peFlags : LibC::Byte
end
struct LOGPALETTE
  palVersion : LibC::UInt16
  palNumEntries : LibC::UInt16
  palPalEntry : Array(PALETTEENTRY)
end
struct LOGFONTA
  lfHeight : LibC::Int32
  lfWidth : LibC::Int32
  lfEscapement : LibC::Int32
  lfOrientation : LibC::Int32
  lfWeight : LibC::Int32
  lfItalic : LibC::Byte
  lfUnderline : LibC::Byte
  lfStrikeOut : LibC::Byte
  lfCharSet : LibC::Byte
  lfOutPrecision : LibC::Byte
  lfClipPrecision : LibC::Byte
  lfQuality : LibC::Byte
  lfPitchAndFamily : LibC::Byte
  lfFaceName : Array(CHAR)
end
struct LOGFONTW
  lfHeight : LibC::Int32
  lfWidth : LibC::Int32
  lfEscapement : LibC::Int32
  lfOrientation : LibC::Int32
  lfWeight : LibC::Int32
  lfItalic : LibC::Byte
  lfUnderline : LibC::Byte
  lfStrikeOut : LibC::Byte
  lfCharSet : LibC::Byte
  lfOutPrecision : LibC::Byte
  lfClipPrecision : LibC::Byte
  lfQuality : LibC::Byte
  lfPitchAndFamily : LibC::Byte
  lfFaceName : Array(LibC::Char)
end
struct ENUMLOGFONTA
  elfLogFont : LOGFONTA
  elfFullName : Array(LibC::Byte)
  elfStyle : Array(LibC::Byte)
end
struct ENUMLOGFONTW
  elfLogFont : LOGFONTW
  elfFullName : Array(LibC::Char)
  elfStyle : Array(LibC::Char)
end
struct ENUMLOGFONTEXA
  elfLogFont : LOGFONTA
  elfFullName : Array(LibC::Byte)
  elfStyle : Array(LibC::Byte)
  elfScript : Array(LibC::Byte)
end
struct ENUMLOGFONTEXW
  elfLogFont : LOGFONTW
  elfFullName : Array(LibC::Char)
  elfStyle : Array(LibC::Char)
  elfScript : Array(LibC::Char)
end
struct PANOSE
  bFamilyType : LibC::Byte
  bSerifStyle : LibC::Byte
  bWeight : LibC::Byte
  bProportion : LibC::Byte
  bContrast : LibC::Byte
  bStrokeVariation : LibC::Byte
  bArmStyle : LibC::Byte
  bLetterform : LibC::Byte
  bMidline : LibC::Byte
  bXHeight : LibC::Byte
end
struct EXTLOGFONTA
  elfLogFont : LOGFONTA
  elfFullName : Array(LibC::Byte)
  elfStyle : Array(LibC::Byte)
  elfVersion : LibC::UInt32
  elfStyleSize : LibC::UInt32
  elfMatch : LibC::UInt32
  elfReserved : LibC::UInt32
  elfVendorId : Array(LibC::Byte)
  elfCulture : LibC::UInt32
  elfPanose : PANOSE
end
struct EXTLOGFONTW
  elfLogFont : LOGFONTW
  elfFullName : Array(LibC::Char)
  elfStyle : Array(LibC::Char)
  elfVersion : LibC::UInt32
  elfStyleSize : LibC::UInt32
  elfMatch : LibC::UInt32
  elfReserved : LibC::UInt32
  elfVendorId : Array(LibC::Byte)
  elfCulture : LibC::UInt32
  elfPanose : PANOSE
end
struct Rabbitc03a7e584ed7
  dmPosition : POINTL
  dmDisplayOrientation : LibC::UInt32
  dmDisplayFixedOutput : LibC::UInt32
end
struct Bird2bf33734f82f
  dmOrientation : LibC::Int16
  dmPaperSize : LibC::Int16
  dmPaperLength : LibC::Int16
  dmPaperWidth : LibC::Int16
  dmScale : LibC::Int16
  dmCopies : LibC::Int16
  dmDefaultSource : LibC::Int16
  dmPrintQuality : LibC::Int16
end
type Othercefceaa53a05 = Bird2bf33734f82f | Rabbitc03a7e584ed7
type Othere5d41a7a2bc3 = LibC::UInt32 | LibC::UInt32
struct DEVMODEA
  dmDeviceName : Array(LibC::Byte)
  dmSpecVersion : LibC::UInt16
  dmDriverVersion : LibC::UInt16
  dmSize : LibC::UInt16
  dmDriverExtra : LibC::UInt16
  dmFields : LibC::UInt32
  anonymous1 : Othercefceaa53a05
  dmColor : LibC::Int16
  dmDuplex : LibC::Int16
  dmYResolution : LibC::Int16
  dmTTOption : LibC::Int16
  dmCollate : LibC::Int16
  dmFormName : Array(LibC::Byte)
  dmLogPixels : LibC::UInt16
  dmBitsPerPel : LibC::UInt32
  dmPelsWidth : LibC::UInt32
  dmPelsHeight : LibC::UInt32
  anonymous2 : Othere5d41a7a2bc3
  dmDisplayFrequency : LibC::UInt32
  dmICMMethod : LibC::UInt32
  dmICMIntent : LibC::UInt32
  dmMediaType : LibC::UInt32
  dmDitherType : LibC::UInt32
  dmReserved1 : LibC::UInt32
  dmReserved2 : LibC::UInt32
  dmPanningWidth : LibC::UInt32
  dmPanningHeight : LibC::UInt32
end
struct Rabbitddeee8525604
  dmOrientation : LibC::Int16
  dmPaperSize : LibC::Int16
  dmPaperLength : LibC::Int16
  dmPaperWidth : LibC::Int16
  dmScale : LibC::Int16
  dmCopies : LibC::Int16
  dmDefaultSource : LibC::Int16
  dmPrintQuality : LibC::Int16
end
struct Owldefb04fd521f
  dmPosition : POINTL
  dmDisplayOrientation : LibC::UInt32
  dmDisplayFixedOutput : LibC::UInt32
end
type Owlfad464cc313e = Rabbitddeee8525604 | Owldefb04fd521f
type Duckdc458d908e88 = LibC::UInt32 | LibC::UInt32
struct DEVMODEW
  dmDeviceName : Array(LibC::Char)
  dmSpecVersion : LibC::UInt16
  dmDriverVersion : LibC::UInt16
  dmSize : LibC::UInt16
  dmDriverExtra : LibC::UInt16
  dmFields : LibC::UInt32
  anonymous1 : Owlfad464cc313e
  dmColor : LibC::Int16
  dmDuplex : LibC::Int16
  dmYResolution : LibC::Int16
  dmTTOption : LibC::Int16
  dmCollate : LibC::Int16
  dmFormName : Array(LibC::Char)
  dmLogPixels : LibC::UInt16
  dmBitsPerPel : LibC::UInt32
  dmPelsWidth : LibC::UInt32
  dmPelsHeight : LibC::UInt32
  anonymous2 : Duckdc458d908e88
  dmDisplayFrequency : LibC::UInt32
  dmICMMethod : LibC::UInt32
  dmICMIntent : LibC::UInt32
  dmMediaType : LibC::UInt32
  dmDitherType : LibC::UInt32
  dmReserved1 : LibC::UInt32
  dmReserved2 : LibC::UInt32
  dmPanningWidth : LibC::UInt32
  dmPanningHeight : LibC::UInt32
end
struct DISPLAY_DEVICEA
  cb : LibC::UInt32
  deviceName : Array(CHAR)
  deviceString : Array(CHAR)
  stateFlags : LibC::UInt32
  deviceID : Array(CHAR)
  deviceKey : Array(CHAR)
end
struct DISPLAY_DEVICEW
  cb : LibC::UInt32
  deviceName : Array(LibC::Char)
  deviceString : Array(LibC::Char)
  stateFlags : LibC::UInt32
  deviceID : Array(LibC::Char)
  deviceKey : Array(LibC::Char)
end
enum DISPLAYCONFIG_COLOR_ENCODING : Int32
DISPLAYCONFIG_COLOR_ENCODING_RGB = 0

DISPLAYCONFIG_COLOR_ENCODING_YCBCR444 = 1

DISPLAYCONFIG_COLOR_ENCODING_YCBCR422 = 2

DISPLAYCONFIG_COLOR_ENCODING_YCBCR420 = 3

DISPLAYCONFIG_COLOR_ENCODING_INTENSITY = 4

DISPLAYCONFIG_COLOR_ENCODING_FORCE_UINT32 = -1

end
struct RGNDATAHEADER
  dwSize : LibC::UInt32
  iType : LibC::UInt32
  nCount : LibC::UInt32
  nRgnSize : LibC::UInt32
  rcBound : RECT
end
struct RGNDATA
  rdh : RGNDATAHEADER
  buffer : Array(CHAR)
end
struct ABC
  abcA : LibC::Int32
  abcB : LibC::UInt32
  abcC : LibC::Int32
end
struct ABCFLOAT
  abcfA : LibC::Single
  abcfB : LibC::Single
  abcfC : LibC::Single
end
struct OUTLINETEXTMETRICA
  otmSize : LibC::UInt32
  otmTextMetrics : TEXTMETRICA
  otmFiller : LibC::Byte
  otmPanoseNumber : PANOSE
  otmfsSelection : LibC::UInt32
  otmfsType : LibC::UInt32
  otmsCharSlopeRise : LibC::Int32
  otmsCharSlopeRun : LibC::Int32
  otmItalicAngle : LibC::Int32
  otmEMSquare : LibC::UInt32
  otmAscent : LibC::Int32
  otmDescent : LibC::Int32
  otmLineGap : LibC::UInt32
  otmsCapEmHeight : LibC::UInt32
  otmsXHeight : LibC::UInt32
  otmrcFontBox : RECT
  otmMacAscent : LibC::Int32
  otmMacDescent : LibC::Int32
  otmMacLineGap : LibC::UInt32
  otmusMinimumPPEM : LibC::UInt32
  otmptSubscriptSize : POINT
  otmptSubscriptOffset : POINT
  otmptSuperscriptSize : POINT
  otmptSuperscriptOffset : POINT
  otmsStrikeoutSize : LibC::UInt32
  otmsStrikeoutPosition : LibC::Int32
  otmsUnderscoreSize : LibC::Int32
  otmsUnderscorePosition : LibC::Int32
  otmpFamilyName : PSTR
  otmpFaceName : PSTR
  otmpStyleName : PSTR
  otmpFullName : PSTR
end
struct OUTLINETEXTMETRICW
  otmSize : LibC::UInt32
  otmTextMetrics : TEXTMETRICW
  otmFiller : LibC::Byte
  otmPanoseNumber : PANOSE
  otmfsSelection : LibC::UInt32
  otmfsType : LibC::UInt32
  otmsCharSlopeRise : LibC::Int32
  otmsCharSlopeRun : LibC::Int32
  otmItalicAngle : LibC::Int32
  otmEMSquare : LibC::UInt32
  otmAscent : LibC::Int32
  otmDescent : LibC::Int32
  otmLineGap : LibC::UInt32
  otmsCapEmHeight : LibC::UInt32
  otmsXHeight : LibC::UInt32
  otmrcFontBox : RECT
  otmMacAscent : LibC::Int32
  otmMacDescent : LibC::Int32
  otmMacLineGap : LibC::UInt32
  otmusMinimumPPEM : LibC::UInt32
  otmptSubscriptSize : POINT
  otmptSubscriptOffset : POINT
  otmptSuperscriptSize : POINT
  otmptSuperscriptOffset : POINT
  otmsStrikeoutSize : LibC::UInt32
  otmsStrikeoutPosition : LibC::Int32
  otmsUnderscoreSize : LibC::Int32
  otmsUnderscorePosition : LibC::Int32
  otmpFamilyName : PSTR
  otmpFaceName : PSTR
  otmpStyleName : PSTR
  otmpFullName : PSTR
end
struct POLYTEXTA
  x : LibC::Int32
  y : LibC::Int32
  n : LibC::UInt32
  lpstr : PSTR
  uiFlags : LibC::UInt32
  rcl : RECT
  pdx : LibC::Int32*
end
struct POLYTEXTW
  x : LibC::Int32
  y : LibC::Int32
  n : LibC::UInt32
  lpstr : PWSTR
  uiFlags : LibC::UInt32
  rcl : RECT
  pdx : LibC::Int32*
end
struct FIXED
  fract : LibC::UInt16
  value : LibC::Int16
end
struct MAT2
  eM11 : FIXED
  eM12 : FIXED
  eM21 : FIXED
  eM22 : FIXED
end
struct GLYPHMETRICS
  gmBlackBoxX : LibC::UInt32
  gmBlackBoxY : LibC::UInt32
  gmptGlyphOrigin : POINT
  gmCellIncX : LibC::Int16
  gmCellIncY : LibC::Int16
end
struct POINTFX
  x : FIXED
  y : FIXED
end
struct TTPOLYCURVE
  wType : LibC::UInt16
  cpfx : LibC::UInt16
  apfx : Array(POINTFX)
end
struct TTPOLYGONHEADER
  cb : LibC::UInt32
  dwType : LibC::UInt32
  pfxStart : POINTFX
end
struct GCP_RESULTSA
  lStructSize : LibC::UInt32
  lpOutString : PSTR
  lpOrder : LibC::UInt32*
  lpDx : LibC::Int32*
  lpCaretPos : LibC::Int32*
  lpClass : PSTR
  lpGlyphs : PWSTR
  nGlyphs : LibC::UInt32
  nMaxFit : LibC::Int32
end
struct GCP_RESULTSW
  lStructSize : LibC::UInt32
  lpOutString : PWSTR
  lpOrder : LibC::UInt32*
  lpDx : LibC::Int32*
  lpCaretPos : LibC::Int32*
  lpClass : PSTR
  lpGlyphs : PWSTR
  nGlyphs : LibC::UInt32
  nMaxFit : LibC::Int32
end
struct RASTERIZER_STATUS
  nSize : LibC::Int16
  wFlags : LibC::Int16
  nLanguageID : LibC::Int16
end
alias FONTENUMPROCA = (LOGFONTA*, TEXTMETRICA*, LibC::UInt32, LPARAM -> LibC::Int32)
alias FONTENUMPROCW = (LOGFONTW*, TEXTMETRICW*, LibC::UInt32, LPARAM -> LibC::Int32)
alias GOBJENUMPROC = (LibC::Void*, LPARAM -> LibC::Int32)
alias LINEDDAPROC = (LibC::Int32, LibC::Int32, LPARAM -> LibC::Void)
alias LPFNDEVMODE = (HWND, HINSTANCE, DEVMODEA*, PSTR, PSTR, DEVMODEA*, PSTR, LibC::UInt32 -> LibC::UInt32)
alias LPFNDEVCAPS = (PSTR, PSTR, LibC::UInt32, PSTR, DEVMODEA* -> LibC::UInt32)
struct WCRANGE
  wcLow : LibC::Char
  cGlyphs : LibC::UInt16
end
struct GLYPHSET
  cbThis : LibC::UInt32
  flAccel : LibC::UInt32
  cGlyphsSupported : LibC::UInt32
  cRanges : LibC::UInt32
  ranges : Array(WCRANGE)
end
struct DESIGNVECTOR
  dvReserved : LibC::UInt32
  dvNumAxes : LibC::UInt32
  dvValues : Array(LibC::Int32)
end
struct AXISINFOA
  axMinValue : LibC::Int32
  axMaxValue : LibC::Int32
  axAxisName : Array(LibC::Byte)
end
struct AXISINFOW
  axMinValue : LibC::Int32
  axMaxValue : LibC::Int32
  axAxisName : Array(LibC::Char)
end
struct AXESLISTA
  axlReserved : LibC::UInt32
  axlNumAxes : LibC::UInt32
  axlAxisInfo : Array(AXISINFOA)
end
struct AXESLISTW
  axlReserved : LibC::UInt32
  axlNumAxes : LibC::UInt32
  axlAxisInfo : Array(AXISINFOW)
end
struct ENUMLOGFONTEXDVA
  elfEnumLogfontEx : ENUMLOGFONTEXA
  elfDesignVector : DESIGNVECTOR
end
struct ENUMLOGFONTEXDVW
  elfEnumLogfontEx : ENUMLOGFONTEXW
  elfDesignVector : DESIGNVECTOR
end
struct TRIVERTEX
  x : LibC::Int32
  y : LibC::Int32
  red : LibC::UInt16
  green : LibC::UInt16
  blue : LibC::UInt16
  alpha : LibC::UInt16
end
struct GRADIENT_TRIANGLE
  vertex1 : LibC::UInt32
  vertex2 : LibC::UInt32
  vertex3 : LibC::UInt32
end
struct GRADIENT_RECT
  upperLeft : LibC::UInt32
  lowerRight : LibC::UInt32
end
struct BLENDFUNCTION
  blendOp : LibC::Byte
  blendFlags : LibC::Byte
  sourceConstantAlpha : LibC::Byte
  alphaFormat : LibC::Byte
end
struct DIBSECTION
  dsBm : BITMAP
  dsBmih : BITMAPINFOHEADER
  dsBitfields : Array(LibC::UInt32)
  dshSection : HANDLE
  dsOffset : LibC::UInt32
end
struct COLORADJUSTMENT
  caSize : LibC::UInt16
  caFlags : LibC::UInt16
  caIlluminantIndex : LibC::UInt16
  caRedGamma : LibC::UInt16
  caGreenGamma : LibC::UInt16
  caBlueGamma : LibC::UInt16
  caReferenceBlack : LibC::UInt16
  caReferenceWhite : LibC::UInt16
  caContrast : LibC::Int16
  caBrightness : LibC::Int16
  caColorfulness : LibC::Int16
  caRedGreenTint : LibC::Int16
end
struct KERNINGPAIR
  wFirst : LibC::UInt16
  wSecond : LibC::UInt16
  iKernAmount : LibC::Int32
end
struct EMR
  iType : LibC::UInt32
  nSize : LibC::UInt32
end
struct EMRTEXT
  ptlReference : POINTL
  nChars : LibC::UInt32
  offString : LibC::UInt32
  fOptions : LibC::UInt32
  rcl : RECTL
  offDx : LibC::UInt32
end
struct ABORTPATH
  emr : EMR
end
struct EMRSELECTCLIPPATH
  emr : EMR
  iMode : LibC::UInt32
end
struct EMRSETMITERLIMIT
  emr : EMR
  eMiterLimit : LibC::Single
end
struct EMRRESTOREDC
  emr : EMR
  iRelative : LibC::Int32
end
struct EMRSETARCDIRECTION
  emr : EMR
  iArcDirection : LibC::UInt32
end
struct EMRSETMAPPERFLAGS
  emr : EMR
  dwFlags : LibC::UInt32
end
struct EMRSETTEXTCOLOR
  emr : EMR
  crColor : LibC::UInt32
end
struct EMRSELECTOBJECT
  emr : EMR
  ihObject : LibC::UInt32
end
struct EMRSELECTPALETTE
  emr : EMR
  ihPal : LibC::UInt32
end
struct EMRRESIZEPALETTE
  emr : EMR
  ihPal : LibC::UInt32
  cEntries : LibC::UInt32
end
struct EMRSETPALETTEENTRIES
  emr : EMR
  ihPal : LibC::UInt32
  iStart : LibC::UInt32
  cEntries : LibC::UInt32
  aPalEntries : Array(PALETTEENTRY)
end
struct EMRSETCOLORADJUSTMENT
  emr : EMR
  colorAdjustment : COLORADJUSTMENT
end
struct EMRGDICOMMENT
  emr : EMR
  cbData : LibC::UInt32
  data : Array(LibC::Byte)
end
struct EMREOF
  emr : EMR
  nPalEntries : LibC::UInt32
  offPalEntries : LibC::UInt32
  nSizeLast : LibC::UInt32
end
struct EMRLINETO
  emr : EMR
  ptl : POINTL
end
struct EMROFFSETCLIPRGN
  emr : EMR
  ptlOffset : POINTL
end
struct EMRFILLPATH
  emr : EMR
  rclBounds : RECTL
end
struct EMREXCLUDECLIPRECT
  emr : EMR
  rclClip : RECTL
end
struct EMRSETVIEWPORTORGEX
  emr : EMR
  ptlOrigin : POINTL
end
struct EMRSETVIEWPORTEXTEX
  emr : EMR
  szlExtent : SIZE
end
struct EMRSCALEVIEWPORTEXTEX
  emr : EMR
  xNum : LibC::Int32
  xDenom : LibC::Int32
  yNum : LibC::Int32
  yDenom : LibC::Int32
end
struct EMRSETWORLDTRANSFORM
  emr : EMR
  xform : XFORM
end
struct EMRMODIFYWORLDTRANSFORM
  emr : EMR
  xform : XFORM
  iMode : LibC::UInt32
end
struct EMRSETPIXELV
  emr : EMR
  ptlPixel : POINTL
  crColor : LibC::UInt32
end
struct EMREXTFLOODFILL
  emr : EMR
  ptlStart : POINTL
  crColor : LibC::UInt32
  iMode : LibC::UInt32
end
struct EMRELLIPSE
  emr : EMR
  rclBox : RECTL
end
struct EMRROUNDRECT
  emr : EMR
  rclBox : RECTL
  szlCorner : SIZE
end
struct EMRARC
  emr : EMR
  rclBox : RECTL
  ptlStart : POINTL
  ptlEnd : POINTL
end
struct EMRANGLEARC
  emr : EMR
  ptlCenter : POINTL
  nRadius : LibC::UInt32
  eStartAngle : LibC::Single
  eSweepAngle : LibC::Single
end
struct EMRPOLYLINE
  emr : EMR
  rclBounds : RECTL
  cptl : LibC::UInt32
  aptl : Array(POINTL)
end
struct EMRPOLYLINE16
  emr : EMR
  rclBounds : RECTL
  cpts : LibC::UInt32
  apts : Array(POINTS)
end
struct EMRPOLYDRAW
  emr : EMR
  rclBounds : RECTL
  cptl : LibC::UInt32
  aptl : Array(POINTL)
  abTypes : Array(LibC::Byte)
end
struct EMRPOLYDRAW16
  emr : EMR
  rclBounds : RECTL
  cpts : LibC::UInt32
  apts : Array(POINTS)
  abTypes : Array(LibC::Byte)
end
struct EMRPOLYPOLYLINE
  emr : EMR
  rclBounds : RECTL
  nPolys : LibC::UInt32
  cptl : LibC::UInt32
  aPolyCounts : Array(LibC::UInt32)
  aptl : Array(POINTL)
end
struct EMRPOLYPOLYLINE16
  emr : EMR
  rclBounds : RECTL
  nPolys : LibC::UInt32
  cpts : LibC::UInt32
  aPolyCounts : Array(LibC::UInt32)
  apts : Array(POINTS)
end
struct EMRINVERTRGN
  emr : EMR
  rclBounds : RECTL
  cbRgnData : LibC::UInt32
  rgnData : Array(LibC::Byte)
end
struct EMRFILLRGN
  emr : EMR
  rclBounds : RECTL
  cbRgnData : LibC::UInt32
  ihBrush : LibC::UInt32
  rgnData : Array(LibC::Byte)
end
struct EMRFRAMERGN
  emr : EMR
  rclBounds : RECTL
  cbRgnData : LibC::UInt32
  ihBrush : LibC::UInt32
  szlStroke : SIZE
  rgnData : Array(LibC::Byte)
end
struct EMREXTSELECTCLIPRGN
  emr : EMR
  cbRgnData : LibC::UInt32
  iMode : LibC::UInt32
  rgnData : Array(LibC::Byte)
end
struct EMREXTTEXTOUTA
  emr : EMR
  rclBounds : RECTL
  iGraphicsMode : LibC::UInt32
  exScale : LibC::Single
  eyScale : LibC::Single
  emrtext : EMRTEXT
end
struct EMRPOLYTEXTOUTA
  emr : EMR
  rclBounds : RECTL
  iGraphicsMode : LibC::UInt32
  exScale : LibC::Single
  eyScale : LibC::Single
  cStrings : LibC::Int32
  aemrtext : Array(EMRTEXT)
end
struct EMRBITBLT
  emr : EMR
  rclBounds : RECTL
  xDest : LibC::Int32
  yDest : LibC::Int32
  cxDest : LibC::Int32
  cyDest : LibC::Int32
  dwRop : LibC::UInt32
  xSrc : LibC::Int32
  ySrc : LibC::Int32
  xformSrc : XFORM
  crBkColorSrc : LibC::UInt32
  iUsageSrc : LibC::UInt32
  offBmiSrc : LibC::UInt32
  cbBmiSrc : LibC::UInt32
  offBitsSrc : LibC::UInt32
  cbBitsSrc : LibC::UInt32
end
struct EMRSTRETCHBLT
  emr : EMR
  rclBounds : RECTL
  xDest : LibC::Int32
  yDest : LibC::Int32
  cxDest : LibC::Int32
  cyDest : LibC::Int32
  dwRop : LibC::UInt32
  xSrc : LibC::Int32
  ySrc : LibC::Int32
  xformSrc : XFORM
  crBkColorSrc : LibC::UInt32
  iUsageSrc : LibC::UInt32
  offBmiSrc : LibC::UInt32
  cbBmiSrc : LibC::UInt32
  offBitsSrc : LibC::UInt32
  cbBitsSrc : LibC::UInt32
  cxSrc : LibC::Int32
  cySrc : LibC::Int32
end
struct EMRMASKBLT
  emr : EMR
  rclBounds : RECTL
  xDest : LibC::Int32
  yDest : LibC::Int32
  cxDest : LibC::Int32
  cyDest : LibC::Int32
  dwRop : LibC::UInt32
  xSrc : LibC::Int32
  ySrc : LibC::Int32
  xformSrc : XFORM
  crBkColorSrc : LibC::UInt32
  iUsageSrc : LibC::UInt32
  offBmiSrc : LibC::UInt32
  cbBmiSrc : LibC::UInt32
  offBitsSrc : LibC::UInt32
  cbBitsSrc : LibC::UInt32
  xMask : LibC::Int32
  yMask : LibC::Int32
  iUsageMask : LibC::UInt32
  offBmiMask : LibC::UInt32
  cbBmiMask : LibC::UInt32
  offBitsMask : LibC::UInt32
  cbBitsMask : LibC::UInt32
end
struct EMRPLGBLT
  emr : EMR
  rclBounds : RECTL
  aptlDest : Array(POINTL)
  xSrc : LibC::Int32
  ySrc : LibC::Int32
  cxSrc : LibC::Int32
  cySrc : LibC::Int32
  xformSrc : XFORM
  crBkColorSrc : LibC::UInt32
  iUsageSrc : LibC::UInt32
  offBmiSrc : LibC::UInt32
  cbBmiSrc : LibC::UInt32
  offBitsSrc : LibC::UInt32
  cbBitsSrc : LibC::UInt32
  xMask : LibC::Int32
  yMask : LibC::Int32
  iUsageMask : LibC::UInt32
  offBmiMask : LibC::UInt32
  cbBmiMask : LibC::UInt32
  offBitsMask : LibC::UInt32
  cbBitsMask : LibC::UInt32
end
struct EMRSETDIBITSTODEVICE
  emr : EMR
  rclBounds : RECTL
  xDest : LibC::Int32
  yDest : LibC::Int32
  xSrc : LibC::Int32
  ySrc : LibC::Int32
  cxSrc : LibC::Int32
  cySrc : LibC::Int32
  offBmiSrc : LibC::UInt32
  cbBmiSrc : LibC::UInt32
  offBitsSrc : LibC::UInt32
  cbBitsSrc : LibC::UInt32
  iUsageSrc : LibC::UInt32
  iStartScan : LibC::UInt32
  cScans : LibC::UInt32
end
struct EMRSTRETCHDIBITS
  emr : EMR
  rclBounds : RECTL
  xDest : LibC::Int32
  yDest : LibC::Int32
  xSrc : LibC::Int32
  ySrc : LibC::Int32
  cxSrc : LibC::Int32
  cySrc : LibC::Int32
  offBmiSrc : LibC::UInt32
  cbBmiSrc : LibC::UInt32
  offBitsSrc : LibC::UInt32
  cbBitsSrc : LibC::UInt32
  iUsageSrc : LibC::UInt32
  dwRop : LibC::UInt32
  cxDest : LibC::Int32
  cyDest : LibC::Int32
end
struct EMREXTCREATEFONTINDIRECTW
  emr : EMR
  ihFont : LibC::UInt32
  elfw : EXTLOGFONTW
end
struct EMRCREATEPALETTE
  emr : EMR
  ihPal : LibC::UInt32
  lgpl : LOGPALETTE
end
struct EMRCREATEPEN
  emr : EMR
  ihPen : LibC::UInt32
  lopn : LOGPEN
end
struct EMREXTCREATEPEN
  emr : EMR
  ihPen : LibC::UInt32
  offBmi : LibC::UInt32
  cbBmi : LibC::UInt32
  offBits : LibC::UInt32
  cbBits : LibC::UInt32
  elp : EXTLOGPEN32
end
struct EMRCREATEBRUSHINDIRECT
  emr : EMR
  ihBrush : LibC::UInt32
  lb : LOGBRUSH32
end
struct EMRCREATEMONOBRUSH
  emr : EMR
  ihBrush : LibC::UInt32
  iUsage : LibC::UInt32
  offBmi : LibC::UInt32
  cbBmi : LibC::UInt32
  offBits : LibC::UInt32
  cbBits : LibC::UInt32
end
struct EMRCREATEDIBPATTERNBRUSHPT
  emr : EMR
  ihBrush : LibC::UInt32
  iUsage : LibC::UInt32
  offBmi : LibC::UInt32
  cbBmi : LibC::UInt32
  offBits : LibC::UInt32
  cbBits : LibC::UInt32
end
struct EMRFORMAT
  dSignature : LibC::UInt32
  nVersion : LibC::UInt32
  cbData : LibC::UInt32
  offData : LibC::UInt32
end
struct EMRGLSRECORD
  emr : EMR
  cbData : LibC::UInt32
  data : Array(LibC::Byte)
end
struct EMRGLSBOUNDEDRECORD
  emr : EMR
  rclBounds : RECTL
  cbData : LibC::UInt32
  data : Array(LibC::Byte)
end
struct EMRSETCOLORSPACE
  emr : EMR
  ihCS : LibC::UInt32
end
struct EMREXTESCAPE
  emr : EMR
  iEscape : LibC::Int32
  cbEscData : LibC::Int32
  escData : Array(LibC::Byte)
end
struct EMRNAMEDESCAPE
  emr : EMR
  iEscape : LibC::Int32
  cbDriver : LibC::Int32
  cbEscData : LibC::Int32
  escData : Array(LibC::Byte)
end
struct EMRSETICMPROFILE
  emr : EMR
  dwFlags : LibC::UInt32
  cbName : LibC::UInt32
  cbData : LibC::UInt32
  data : Array(LibC::Byte)
end
struct COLORMATCHTOTARGET
  emr : EMR
  dwAction : LibC::UInt32
  dwFlags : LibC::UInt32
  cbName : LibC::UInt32
  cbData : LibC::UInt32
  data : Array(LibC::Byte)
end
struct COLORCORRECTPALETTE
  emr : EMR
  ihPalette : LibC::UInt32
  nFirstEntry : LibC::UInt32
  nPalEntries : LibC::UInt32
  nReserved : LibC::UInt32
end
struct EMRALPHABLEND
  emr : EMR
  rclBounds : RECTL
  xDest : LibC::Int32
  yDest : LibC::Int32
  cxDest : LibC::Int32
  cyDest : LibC::Int32
  dwRop : LibC::UInt32
  xSrc : LibC::Int32
  ySrc : LibC::Int32
  xformSrc : XFORM
  crBkColorSrc : LibC::UInt32
  iUsageSrc : LibC::UInt32
  offBmiSrc : LibC::UInt32
  cbBmiSrc : LibC::UInt32
  offBitsSrc : LibC::UInt32
  cbBitsSrc : LibC::UInt32
  cxSrc : LibC::Int32
  cySrc : LibC::Int32
end
struct EMRGRADIENTFILL
  emr : EMR
  rclBounds : RECTL
  nVer : LibC::UInt32
  nTri : LibC::UInt32
  ulMode : GRADIENT_FILL
  ver : Array(TRIVERTEX)
end
struct EMRTRANSPARENTBLT
  emr : EMR
  rclBounds : RECTL
  xDest : LibC::Int32
  yDest : LibC::Int32
  cxDest : LibC::Int32
  cyDest : LibC::Int32
  dwRop : LibC::UInt32
  xSrc : LibC::Int32
  ySrc : LibC::Int32
  xformSrc : XFORM
  crBkColorSrc : LibC::UInt32
  iUsageSrc : LibC::UInt32
  offBmiSrc : LibC::UInt32
  cbBmiSrc : LibC::UInt32
  offBitsSrc : LibC::UInt32
  cbBitsSrc : LibC::UInt32
  cxSrc : LibC::Int32
  cySrc : LibC::Int32
end
struct WGLSWAP
  hdc : HDC
  uiFlags : LibC::UInt32
end
alias CFP_ALLOCPROC = (LibC::UIint* -> LibC::Void*)
alias CFP_REALLOCPROC = (LibC::Void*, LibC::UIint* -> LibC::Void*)
alias CFP_FREEPROC = (LibC::Void* -> LibC::Void)
alias READEMBEDPROC = (LibC::Void*, LibC::Void*, LibC::UInt32 -> LibC::UInt32)
alias WRITEEMBEDPROC = (LibC::Void*, LibC::Void*, LibC::UInt32 -> LibC::UInt32)
struct TTLOADINFO
  usStructSize : LibC::UInt16
  usRefStrSize : LibC::UInt16
  pusRefStr : LibC::UInt16*
end
struct TTEMBEDINFO
  usStructSize : LibC::UInt16
  usRootStrSize : LibC::UInt16
  pusRootStr : LibC::UInt16*
end
struct TTVALIDATIONTESTSPARAMS
  ulStructSize : LibC::UInt32
  lTestFromSize : LibC::Int32
  lTestToSize : LibC::Int32
  ulCharSet : LibC::UInt32
  usReserved1 : LibC::UInt16
  usCharCodeCount : LibC::UInt16
  pusCharCodeSet : LibC::UInt16*
end
struct TTVALIDATIONTESTSPARAMSEX
  ulStructSize : LibC::UInt32
  lTestFromSize : LibC::Int32
  lTestToSize : LibC::Int32
  ulCharSet : LibC::UInt32
  usReserved1 : LibC::UInt16
  usCharCodeCount : LibC::UInt16
  pulCharCodeSet : LibC::UInt32*
end
alias GRAYSTRINGPROC = (HDC, LPARAM, LibC::Int32 -> BOOL)
alias DRAWSTATEPROC = (HDC, LPARAM, WPARAM, LibC::Int32, LibC::Int32 -> BOOL)
struct PAINTSTRUCT
  hdc : HDC
  fErase : BOOL
  rcPaint : RECT
  fRestore : BOOL
  fIncUpdate : BOOL
  rgbReserved : Array(LibC::Byte)
end
struct DRAWTEXTPARAMS
  cbSize : LibC::UInt32
  iTabLength : LibC::Int32
  iLeftMargin : LibC::Int32
  iRightMargin : LibC::Int32
  uiLengthDrawn : LibC::UInt32
end
struct MONITORINFO
  cbSize : LibC::UInt32
  rcMonitor : RECT
  rcWork : RECT
  dwFlags : LibC::UInt32
end
struct MONITORINFOEXA
  _AnonymousBase_winuser_L13567_C43 : MONITORINFO
  szDevice : Array(CHAR)
end
struct MONITORINFOEXW
  _AnonymousBase_winuser_L13571_C43 : MONITORINFO
  szDevice : Array(LibC::Char)
end
alias MONITORENUMPROC = (HMONITOR, HDC, RECT*, LPARAM -> BOOL)
fun getObjectA(h : HGDIOBJ, c : LibC::Int32, pv : LibC::Void*) : LibC::Int32
fun addFontResourceA(param0 : PSTR) : LibC::Int32
fun addFontResourceW(param0 : PWSTR) : LibC::Int32
fun arc(hdc : HDC, x1 : LibC::Int32, y1 : LibC::Int32, x2 : LibC::Int32, y2 : LibC::Int32, x3 : LibC::Int32, y3 : LibC::Int32, x4 : LibC::Int32, y4 : LibC::Int32) : BOOL
fun bitBlt(hdc : HDC, x : LibC::Int32, y : LibC::Int32, cx : LibC::Int32, cy : LibC::Int32, hdcSrc : HDC, x1 : LibC::Int32, y1 : LibC::Int32, rop : ROP_CODE) : BOOL
fun cancelDC(hdc : HDC) : BOOL
fun chord(hdc : HDC, x1 : LibC::Int32, y1 : LibC::Int32, x2 : LibC::Int32, y2 : LibC::Int32, x3 : LibC::Int32, y3 : LibC::Int32, x4 : LibC::Int32, y4 : LibC::Int32) : BOOL
fun closeMetaFile(hdc : HDC) : HMETAFILE
fun combineRgn(hrgnDst : HRGN, hrgnSrc1 : HRGN, hrgnSrc2 : HRGN, iMode : RGN_COMBINE_MODE) : LibC::Int32
fun copyMetaFileA(param0 : HMETAFILE, param1 : PSTR) : HMETAFILE
fun copyMetaFileW(param0 : HMETAFILE, param1 : PWSTR) : HMETAFILE
fun createBitmap(nWidth : LibC::Int32, nHeight : LibC::Int32, nPlanes : LibC::UInt32, nBitCount : LibC::UInt32, lpBits : LibC::Void*) : HBITMAP
fun createBitmapIndirect(pbm : BITMAP*) : HBITMAP
fun createBrushIndirect(plbrush : LOGBRUSH*) : HBRUSH
fun createCompatibleBitmap(hdc : HDC, cx : LibC::Int32, cy : LibC::Int32) : HBITMAP
fun createDiscardableBitmap(hdc : HDC, cx : LibC::Int32, cy : LibC::Int32) : HBITMAP
fun createCompatibleDC(hdc : HDC) : CreatedHDC
fun createDCA(pwszDriver : PSTR, pwszDevice : PSTR, pszPort : PSTR, pdm : DEVMODEA*) : CreatedHDC
fun createDCW(pwszDriver : PWSTR, pwszDevice : PWSTR, pszPort : PWSTR, pdm : DEVMODEW*) : CreatedHDC
fun createDIBitmap(hdc : HDC, pbmih : BITMAPINFOHEADER*, flInit : LibC::UInt32, pjBits : LibC::Void*, pbmi : BITMAPINFO*, iUsage : DIB_USAGE) : HBITMAP
fun createDIBPatternBrush(h : LibC::Int*, iUsage : DIB_USAGE) : HBRUSH
fun createDIBPatternBrushPt(lpPackedDIB : LibC::Void*, iUsage : DIB_USAGE) : HBRUSH
fun createEllipticRgn(x1 : LibC::Int32, y1 : LibC::Int32, x2 : LibC::Int32, y2 : LibC::Int32) : HRGN
fun createEllipticRgnIndirect(lprect : RECT*) : HRGN
fun createFontIndirectA(lplf : LOGFONTA*) : HFONT
fun createFontIndirectW(lplf : LOGFONTW*) : HFONT
fun createFontA(cHeight : LibC::Int32, cWidth : LibC::Int32, cEscapement : LibC::Int32, cOrientation : LibC::Int32, cWeight : LibC::Int32, bItalic : LibC::UInt32, bUnderline : LibC::UInt32, bStrikeOut : LibC::UInt32, iCharSet : LibC::UInt32, iOutPrecision : FONT_OUTPUT_PRECISION, iClipPrecision : FONT_CLIP_PRECISION, iQuality : FONT_QUALITY, iPitchAndFamily : FONT_PITCH_AND_FAMILY, pszFaceName : PSTR) : HFONT
fun createFontW(cHeight : LibC::Int32, cWidth : LibC::Int32, cEscapement : LibC::Int32, cOrientation : LibC::Int32, cWeight : LibC::Int32, bItalic : LibC::UInt32, bUnderline : LibC::UInt32, bStrikeOut : LibC::UInt32, iCharSet : LibC::UInt32, iOutPrecision : FONT_OUTPUT_PRECISION, iClipPrecision : FONT_CLIP_PRECISION, iQuality : FONT_QUALITY, iPitchAndFamily : FONT_PITCH_AND_FAMILY, pszFaceName : PWSTR) : HFONT
fun createHatchBrush(iHatch : HATCH_BRUSH_STYLE, color : LibC::UInt32) : HBRUSH
fun createICA(pszDriver : PSTR, pszDevice : PSTR, pszPort : PSTR, pdm : DEVMODEA*) : CreatedHDC
fun createICW(pszDriver : PWSTR, pszDevice : PWSTR, pszPort : PWSTR, pdm : DEVMODEW*) : CreatedHDC
fun createMetaFileA(pszFile : PSTR) : HdcMetdataFileHandle
fun createMetaFileW(pszFile : PWSTR) : HdcMetdataFileHandle
fun createPalette(plpal : LOGPALETTE*) : HPALETTE
fun createPen(iStyle : PEN_STYLE, cWidth : LibC::Int32, color : LibC::UInt32) : HPEN
fun createPenIndirect(plpen : LOGPEN*) : HPEN
fun createPatternBrush(hbm : HBITMAP) : HBRUSH
fun createRectRgn(x1 : LibC::Int32, y1 : LibC::Int32, x2 : LibC::Int32, y2 : LibC::Int32) : HRGN
fun createRectRgnIndirect(lprect : RECT*) : HRGN
fun createRoundRectRgn(x1 : LibC::Int32, y1 : LibC::Int32, x2 : LibC::Int32, y2 : LibC::Int32, w : LibC::Int32, h : LibC::Int32) : HRGN
fun createScalableFontResourceA(fdwHidden : LibC::UInt32, lpszFont : PSTR, lpszFile : PSTR, lpszPath : PSTR) : BOOL
fun createScalableFontResourceW(fdwHidden : LibC::UInt32, lpszFont : PWSTR, lpszFile : PWSTR, lpszPath : PWSTR) : BOOL
fun createSolidBrush(color : LibC::UInt32) : HBRUSH
fun deleteDC(hdc : CreatedHDC) : BOOL
fun deleteMetaFile(hmf : HMETAFILE) : BOOL
fun deleteObject(ho : HGDIOBJ) : BOOL
fun drawEscape(hdc : HDC, iEscape : LibC::Int32, cjIn : LibC::Int32, lpIn : PSTR) : LibC::Int32
fun ellipse(hdc : HDC, left : LibC::Int32, top : LibC::Int32, right : LibC::Int32, bottom : LibC::Int32) : BOOL
fun enumFontFamiliesExA(hdc : HDC, lpLogfont : LOGFONTA*, lpProc : FONTENUMPROCA, lParam : LPARAM, dwFlags : LibC::UInt32) : LibC::Int32
fun enumFontFamiliesExW(hdc : HDC, lpLogfont : LOGFONTW*, lpProc : FONTENUMPROCW, lParam : LPARAM, dwFlags : LibC::UInt32) : LibC::Int32
fun enumFontFamiliesA(hdc : HDC, lpLogfont : PSTR, lpProc : FONTENUMPROCA, lParam : LPARAM) : LibC::Int32
fun enumFontFamiliesW(hdc : HDC, lpLogfont : PWSTR, lpProc : FONTENUMPROCW, lParam : LPARAM) : LibC::Int32
fun enumFontsA(hdc : HDC, lpLogfont : PSTR, lpProc : FONTENUMPROCA, lParam : LPARAM) : LibC::Int32
fun enumFontsW(hdc : HDC, lpLogfont : PWSTR, lpProc : FONTENUMPROCW, lParam : LPARAM) : LibC::Int32
fun enumObjects(hdc : HDC, nType : OBJ_TYPE, lpFunc : GOBJENUMPROC, lParam : LPARAM) : LibC::Int32
fun equalRgn(hrgn1 : HRGN, hrgn2 : HRGN) : BOOL
fun excludeClipRect(hdc : HDC, left : LibC::Int32, top : LibC::Int32, right : LibC::Int32, bottom : LibC::Int32) : LibC::Int32
fun extCreateRegion(lpx : XFORM*, nCount : LibC::UInt32, lpData : RGNDATA*) : HRGN
fun extFloodFill(hdc : HDC, x : LibC::Int32, y : LibC::Int32, color : LibC::UInt32, type : EXT_FLOOD_FILL_TYPE) : BOOL
fun fillRgn(hdc : HDC, hrgn : HRGN, hbr : HBRUSH) : BOOL
fun floodFill(hdc : HDC, x : LibC::Int32, y : LibC::Int32, color : LibC::UInt32) : BOOL
fun frameRgn(hdc : HDC, hrgn : HRGN, hbr : HBRUSH, w : LibC::Int32, h : LibC::Int32) : BOOL
fun getROP2(hdc : HDC) : LibC::Int32
fun getAspectRatioFilterEx(hdc : HDC, lpsize : SIZE*) : BOOL
fun getBkColor(hdc : HDC) : LibC::UInt32
fun getDCBrushColor(hdc : HDC) : LibC::UInt32
fun getDCPenColor(hdc : HDC) : LibC::UInt32
fun getBkMode(hdc : HDC) : LibC::Int32
fun getBitmapBits(hbit : HBITMAP, cb : LibC::Int32, lpvBits : LibC::Void*) : LibC::Int32
fun getBitmapDimensionEx(hbit : HBITMAP, lpsize : SIZE*) : BOOL
fun getBoundsRect(hdc : HDC, lprect : RECT*, flags : LibC::UInt32) : LibC::UInt32
fun getBrushOrgEx(hdc : HDC, lppt : POINT*) : BOOL
fun getCharWidthA(hdc : HDC, iFirst : LibC::UInt32, iLast : LibC::UInt32, lpBuffer : LibC::Int32*) : BOOL
fun getCharWidthW(hdc : HDC, iFirst : LibC::UInt32, iLast : LibC::UInt32, lpBuffer : LibC::Int32*) : BOOL
fun getCharWidth32A(hdc : HDC, iFirst : LibC::UInt32, iLast : LibC::UInt32, lpBuffer : LibC::Int32*) : BOOL
fun getCharWidth32W(hdc : HDC, iFirst : LibC::UInt32, iLast : LibC::UInt32, lpBuffer : LibC::Int32*) : BOOL
fun getCharWidthFloatA(hdc : HDC, iFirst : LibC::UInt32, iLast : LibC::UInt32, lpBuffer : LibC::Single*) : BOOL
fun getCharWidthFloatW(hdc : HDC, iFirst : LibC::UInt32, iLast : LibC::UInt32, lpBuffer : LibC::Single*) : BOOL
fun getCharABCWidthsA(hdc : HDC, wFirst : LibC::UInt32, wLast : LibC::UInt32, lpABC : ABC*) : BOOL
fun getCharABCWidthsW(hdc : HDC, wFirst : LibC::UInt32, wLast : LibC::UInt32, lpABC : ABC*) : BOOL
fun getCharABCWidthsFloatA(hdc : HDC, iFirst : LibC::UInt32, iLast : LibC::UInt32, lpABC : ABCFLOAT*) : BOOL
fun getCharABCWidthsFloatW(hdc : HDC, iFirst : LibC::UInt32, iLast : LibC::UInt32, lpABC : ABCFLOAT*) : BOOL
fun getClipBox(hdc : HDC, lprect : RECT*) : LibC::Int32
fun getClipRgn(hdc : HDC, hrgn : HRGN) : LibC::Int32
fun getMetaRgn(hdc : HDC, hrgn : HRGN) : LibC::Int32
fun getCurrentObject(hdc : HDC, type : OBJ_TYPE) : HGDIOBJ
fun getCurrentPositionEx(hdc : HDC, lppt : POINT*) : BOOL
fun getDeviceCaps(hdc : HDC, index : GET_DEVICE_CAPS_INDEX) : LibC::Int32
fun getDIBits(hdc : HDC, hbm : HBITMAP, start : LibC::UInt32, cLines : LibC::UInt32, lpvBits : LibC::Void*, lpbmi : BITMAPINFO*, usage : DIB_USAGE) : LibC::Int32
fun getFontData(hdc : HDC, dwTable : LibC::UInt32, dwOffset : LibC::UInt32, pvBuffer : LibC::Void*, cjBuffer : LibC::UInt32) : LibC::UInt32
fun getGlyphOutlineA(hdc : HDC, uChar : LibC::UInt32, fuFormat : GET_GLYPH_OUTLINE_FORMAT, lpgm : GLYPHMETRICS*, cjBuffer : LibC::UInt32, pvBuffer : LibC::Void*, lpmat2 : MAT2*) : LibC::UInt32
fun getGlyphOutlineW(hdc : HDC, uChar : LibC::UInt32, fuFormat : GET_GLYPH_OUTLINE_FORMAT, lpgm : GLYPHMETRICS*, cjBuffer : LibC::UInt32, pvBuffer : LibC::Void*, lpmat2 : MAT2*) : LibC::UInt32
fun getGraphicsMode(hdc : HDC) : LibC::Int32
fun getMapMode(hdc : HDC) : LibC::Int32
fun getMetaFileBitsEx(hMF : HMETAFILE, cbBuffer : LibC::UInt32, lpData : LibC::Void*) : LibC::UInt32
fun getMetaFileA(lpName : PSTR) : HMETAFILE
fun getMetaFileW(lpName : PWSTR) : HMETAFILE
fun getNearestColor(hdc : HDC, color : LibC::UInt32) : LibC::UInt32
fun getNearestPaletteIndex(h : HPALETTE, color : LibC::UInt32) : LibC::UInt32
fun getObjectType(h : HGDIOBJ) : LibC::UInt32
fun getOutlineTextMetricsA(hdc : HDC, cjCopy : LibC::UInt32, potm : OUTLINETEXTMETRICA*) : LibC::UInt32
fun getOutlineTextMetricsW(hdc : HDC, cjCopy : LibC::UInt32, potm : OUTLINETEXTMETRICW*) : LibC::UInt32
fun getPixel(hdc : HDC, x : LibC::Int32, y : LibC::Int32) : LibC::UInt32
fun getPolyFillMode(hdc : HDC) : LibC::Int32
fun getRasterizerCaps(lpraststat : RASTERIZER_STATUS*, cjBytes : LibC::UInt32) : BOOL
fun getRandomRgn(hdc : HDC, hrgn : HRGN, i : LibC::Int32) : LibC::Int32
fun getRegionData(hrgn : HRGN, nCount : LibC::UInt32, lpRgnData : RGNDATA*) : LibC::UInt32
fun getRgnBox(hrgn : HRGN, lprc : RECT*) : LibC::Int32
fun getStockObject(i : GET_STOCK_OBJECT_FLAGS) : HGDIOBJ
fun getStretchBltMode(hdc : HDC) : LibC::Int32
fun getSystemPaletteUse(hdc : HDC) : LibC::UInt32
fun getTextCharacterExtra(hdc : HDC) : LibC::Int32
fun getTextAlign(hdc : HDC) : LibC::UInt32
fun getTextColor(hdc : HDC) : LibC::UInt32
fun getFontLanguageInfo(hdc : HDC) : LibC::UInt32
fun getFontUnicodeRanges(hdc : HDC, lpgs : GLYPHSET*) : LibC::UInt32
fun addFontResourceExA(name : PSTR, fl : FONT_RESOURCE_CHARACTERISTICS, res : LibC::Void*) : LibC::Int32
fun addFontResourceExW(name : PWSTR, fl : FONT_RESOURCE_CHARACTERISTICS, res : LibC::Void*) : LibC::Int32
fun removeFontResourceExA(name : PSTR, fl : LibC::UInt32, pdv : LibC::Void*) : BOOL
fun removeFontResourceExW(name : PWSTR, fl : LibC::UInt32, pdv : LibC::Void*) : BOOL
fun addFontMemResourceEx(pFileView : LibC::Void*, cjSize : LibC::UInt32, pvResrved : LibC::Void*, pNumFonts : LibC::UInt32*) : HANDLE
fun removeFontMemResourceEx(h : HANDLE) : BOOL
fun createFontIndirectExA(param0 : ENUMLOGFONTEXDVA*) : HFONT
fun createFontIndirectExW(param0 : ENUMLOGFONTEXDVW*) : HFONT
fun getViewportExtEx(hdc : HDC, lpsize : SIZE*) : BOOL
fun getViewportOrgEx(hdc : HDC, lppoint : POINT*) : BOOL
fun getWindowExtEx(hdc : HDC, lpsize : SIZE*) : BOOL
fun getWindowOrgEx(hdc : HDC, lppoint : POINT*) : BOOL
fun intersectClipRect(hdc : HDC, left : LibC::Int32, top : LibC::Int32, right : LibC::Int32, bottom : LibC::Int32) : LibC::Int32
fun invertRgn(hdc : HDC, hrgn : HRGN) : BOOL
fun lineDDA(xStart : LibC::Int32, yStart : LibC::Int32, xEnd : LibC::Int32, yEnd : LibC::Int32, lpProc : LINEDDAPROC, data : LPARAM) : BOOL
fun lineTo(hdc : HDC, x : LibC::Int32, y : LibC::Int32) : BOOL
fun maskBlt(hdcDest : HDC, xDest : LibC::Int32, yDest : LibC::Int32, width : LibC::Int32, height : LibC::Int32, hdcSrc : HDC, xSrc : LibC::Int32, ySrc : LibC::Int32, hbmMask : HBITMAP, xMask : LibC::Int32, yMask : LibC::Int32, rop : LibC::UInt32) : BOOL
fun offsetClipRgn(hdc : HDC, x : LibC::Int32, y : LibC::Int32) : LibC::Int32
fun offsetRgn(hrgn : HRGN, x : LibC::Int32, y : LibC::Int32) : LibC::Int32
fun patBlt(hdc : HDC, x : LibC::Int32, y : LibC::Int32, w : LibC::Int32, h : LibC::Int32, rop : ROP_CODE) : BOOL
fun pie(hdc : HDC, left : LibC::Int32, top : LibC::Int32, right : LibC::Int32, bottom : LibC::Int32, xr1 : LibC::Int32, yr1 : LibC::Int32, xr2 : LibC::Int32, yr2 : LibC::Int32) : BOOL
fun playMetaFile(hdc : HDC, hmf : HMETAFILE) : BOOL
fun paintRgn(hdc : HDC, hrgn : HRGN) : BOOL
fun ptInRegion(hrgn : HRGN, x : LibC::Int32, y : LibC::Int32) : BOOL
fun ptVisible(hdc : HDC, x : LibC::Int32, y : LibC::Int32) : BOOL
fun rectInRegion(hrgn : HRGN, lprect : RECT*) : BOOL
fun rectVisible(hdc : HDC, lprect : RECT*) : BOOL
fun rectangle(hdc : HDC, left : LibC::Int32, top : LibC::Int32, right : LibC::Int32, bottom : LibC::Int32) : BOOL
fun restoreDC(hdc : HDC, nSavedDC : LibC::Int32) : BOOL
fun resetDCA(hdc : HDC, lpdm : DEVMODEA*) : HDC
fun resetDCW(hdc : HDC, lpdm : DEVMODEW*) : HDC
fun realizePalette(hdc : HDC) : LibC::UInt32
fun removeFontResourceA(lpFileName : PSTR) : BOOL
fun removeFontResourceW(lpFileName : PWSTR) : BOOL
fun roundRect(hdc : HDC, left : LibC::Int32, top : LibC::Int32, right : LibC::Int32, bottom : LibC::Int32, width : LibC::Int32, height : LibC::Int32) : BOOL
fun resizePalette(hpal : HPALETTE, n : LibC::UInt32) : BOOL
fun saveDC(hdc : HDC) : LibC::Int32
fun selectClipRgn(hdc : HDC, hrgn : HRGN) : LibC::Int32
fun extSelectClipRgn(hdc : HDC, hrgn : HRGN, mode : RGN_COMBINE_MODE) : LibC::Int32
fun setMetaRgn(hdc : HDC) : LibC::Int32
fun selectObject(hdc : HDC, h : HGDIOBJ) : HGDIOBJ
fun selectPalette(hdc : HDC, hPal : HPALETTE, bForceBkgd : BOOL) : HPALETTE
fun setBkColor(hdc : HDC, color : LibC::UInt32) : LibC::UInt32
fun setDCBrushColor(hdc : HDC, color : LibC::UInt32) : LibC::UInt32
fun setDCPenColor(hdc : HDC, color : LibC::UInt32) : LibC::UInt32
fun setBkMode(hdc : HDC, mode : BACKGROUND_MODE) : LibC::Int32
fun setBitmapBits(hbm : HBITMAP, cb : LibC::UInt32, pvBits : LibC::Void*) : LibC::Int32
fun setBoundsRect(hdc : HDC, lprect : RECT*, flags : SET_BOUNDS_RECT_FLAGS) : LibC::UInt32
fun setDIBits(hdc : HDC, hbm : HBITMAP, start : LibC::UInt32, cLines : LibC::UInt32, lpBits : LibC::Void*, lpbmi : BITMAPINFO*, colorUse : DIB_USAGE) : LibC::Int32
fun setDIBitsToDevice(hdc : HDC, xDest : LibC::Int32, yDest : LibC::Int32, w : LibC::UInt32, h : LibC::UInt32, xSrc : LibC::Int32, ySrc : LibC::Int32, startScan : LibC::UInt32, cLines : LibC::UInt32, lpvBits : LibC::Void*, lpbmi : BITMAPINFO*, colorUse : DIB_USAGE) : LibC::Int32
fun setMapperFlags(hdc : HDC, flags : LibC::UInt32) : LibC::UInt32
fun setGraphicsMode(hdc : HDC, iMode : GRAPHICS_MODE) : LibC::Int32
fun setMapMode(hdc : HDC, iMode : HDC_MAP_MODE) : LibC::Int32
fun setLayout(hdc : HDC, l : DC_LAYOUT) : LibC::UInt32
fun getLayout(hdc : HDC) : LibC::UInt32
fun setMetaFileBitsEx(cbBuffer : LibC::UInt32, lpData : LibC::Byte*) : HMETAFILE
fun setPixel(hdc : HDC, x : LibC::Int32, y : LibC::Int32, color : LibC::UInt32) : LibC::UInt32
fun setPixelV(hdc : HDC, x : LibC::Int32, y : LibC::Int32, color : LibC::UInt32) : BOOL
fun setPolyFillMode(hdc : HDC, mode : CREATE_POLYGON_RGN_MODE) : LibC::Int32
fun stretchBlt(hdcDest : HDC, xDest : LibC::Int32, yDest : LibC::Int32, wDest : LibC::Int32, hDest : LibC::Int32, hdcSrc : HDC, xSrc : LibC::Int32, ySrc : LibC::Int32, wSrc : LibC::Int32, hSrc : LibC::Int32, rop : ROP_CODE) : BOOL
fun setRectRgn(hrgn : HRGN, left : LibC::Int32, top : LibC::Int32, right : LibC::Int32, bottom : LibC::Int32) : BOOL
fun stretchDIBits(hdc : HDC, xDest : LibC::Int32, yDest : LibC::Int32, destWidth : LibC::Int32, destHeight : LibC::Int32, xSrc : LibC::Int32, ySrc : LibC::Int32, srcWidth : LibC::Int32, srcHeight : LibC::Int32, lpBits : LibC::Void*, lpbmi : BITMAPINFO*, iUsage : DIB_USAGE, rop : ROP_CODE) : LibC::Int32
fun setROP2(hdc : HDC, rop2 : R2_MODE) : LibC::Int32
fun setStretchBltMode(hdc : HDC, mode : STRETCH_BLT_MODE) : LibC::Int32
fun setSystemPaletteUse(hdc : HDC, use : SYSTEM_PALETTE_USE) : LibC::UInt32
fun setTextCharacterExtra(hdc : HDC, extra : LibC::Int32) : LibC::Int32
fun setTextColor(hdc : HDC, color : LibC::UInt32) : LibC::UInt32
fun setTextAlign(hdc : HDC, align : TEXT_ALIGN_OPTIONS) : LibC::UInt32
fun setTextJustification(hdc : HDC, extra : LibC::Int32, count : LibC::Int32) : BOOL
fun updateColors(hdc : HDC) : BOOL
fun alphaBlend(hdcDest : HDC, xoriginDest : LibC::Int32, yoriginDest : LibC::Int32, wDest : LibC::Int32, hDest : LibC::Int32, hdcSrc : HDC, xoriginSrc : LibC::Int32, yoriginSrc : LibC::Int32, wSrc : LibC::Int32, hSrc : LibC::Int32, ftn : BLENDFUNCTION) : BOOL
fun transparentBlt(hdcDest : HDC, xoriginDest : LibC::Int32, yoriginDest : LibC::Int32, wDest : LibC::Int32, hDest : LibC::Int32, hdcSrc : HDC, xoriginSrc : LibC::Int32, yoriginSrc : LibC::Int32, wSrc : LibC::Int32, hSrc : LibC::Int32, crTransparent : LibC::UInt32) : BOOL
fun gdiAlphaBlend(hdcDest : HDC, xoriginDest : LibC::Int32, yoriginDest : LibC::Int32, wDest : LibC::Int32, hDest : LibC::Int32, hdcSrc : HDC, xoriginSrc : LibC::Int32, yoriginSrc : LibC::Int32, wSrc : LibC::Int32, hSrc : LibC::Int32, ftn : BLENDFUNCTION) : BOOL
fun gdiTransparentBlt(hdcDest : HDC, xoriginDest : LibC::Int32, yoriginDest : LibC::Int32, wDest : LibC::Int32, hDest : LibC::Int32, hdcSrc : HDC, xoriginSrc : LibC::Int32, yoriginSrc : LibC::Int32, wSrc : LibC::Int32, hSrc : LibC::Int32, crTransparent : LibC::UInt32) : BOOL
fun closeEnhMetaFile(hdc : HDC) : HENHMETAFILE
fun copyEnhMetaFileA(hEnh : HENHMETAFILE, lpFileName : PSTR) : HENHMETAFILE
fun copyEnhMetaFileW(hEnh : HENHMETAFILE, lpFileName : PWSTR) : HENHMETAFILE
fun createEnhMetaFileA(hdc : HDC, lpFilename : PSTR, lprc : RECT*, lpDesc : PSTR) : HdcMetdataEnhFileHandle
fun createEnhMetaFileW(hdc : HDC, lpFilename : PWSTR, lprc : RECT*, lpDesc : PWSTR) : HdcMetdataEnhFileHandle
fun deleteEnhMetaFile(hmf : HENHMETAFILE) : BOOL
fun getEnhMetaFileA(lpName : PSTR) : HENHMETAFILE
fun getEnhMetaFileW(lpName : PWSTR) : HENHMETAFILE
fun getEnhMetaFileBits(hEMF : HENHMETAFILE, nSize : LibC::UInt32, lpData : LibC::Byte*) : LibC::UInt32
fun getEnhMetaFileHeader(hemf : HENHMETAFILE, nSize : LibC::UInt32, lpEnhMetaHeader : ENHMETAHEADER*) : LibC::UInt32
fun getWinMetaFileBits(hemf : HENHMETAFILE, cbData16 : LibC::UInt32, pData16 : LibC::Byte*, iMapMode : LibC::Int32, hdcRef : HDC) : LibC::UInt32
fun playEnhMetaFile(hdc : HDC, hmf : HENHMETAFILE, lprect : RECT*) : BOOL
fun setEnhMetaFileBits(nSize : LibC::UInt32, pb : LibC::Byte*) : HENHMETAFILE
fun gdiComment(hdc : HDC, nSize : LibC::UInt32, lpData : LibC::Byte*) : BOOL
fun getTextMetricsA(hdc : HDC, lptm : TEXTMETRICA*) : BOOL
fun getTextMetricsW(hdc : HDC, lptm : TEXTMETRICW*) : BOOL
fun angleArc(hdc : HDC, x : LibC::Int32, y : LibC::Int32, r : LibC::UInt32, startAngle : LibC::Single, sweepAngle : LibC::Single) : BOOL
fun getWorldTransform(hdc : HDC, lpxf : XFORM*) : BOOL
fun setWorldTransform(hdc : HDC, lpxf : XFORM*) : BOOL
fun modifyWorldTransform(hdc : HDC, lpxf : XFORM*, mode : MODIFY_WORLD_TRANSFORM_MODE) : BOOL
fun combineTransform(lpxfOut : XFORM*, lpxf1 : XFORM*, lpxf2 : XFORM*) : BOOL
fun createDIBSection(hdc : HDC, pbmi : BITMAPINFO*, usage : DIB_USAGE, ppvBits : LibC::Void**, hSection : HANDLE, offset : LibC::UInt32) : HBITMAP
fun setColorAdjustment(hdc : HDC, lpca : COLORADJUSTMENT*) : BOOL
fun getColorAdjustment(hdc : HDC, lpca : COLORADJUSTMENT*) : BOOL
fun createHalftonePalette(hdc : HDC) : HPALETTE
fun abortPath(hdc : HDC) : BOOL
fun arcTo(hdc : HDC, left : LibC::Int32, top : LibC::Int32, right : LibC::Int32, bottom : LibC::Int32, xr1 : LibC::Int32, yr1 : LibC::Int32, xr2 : LibC::Int32, yr2 : LibC::Int32) : BOOL
fun beginPath(hdc : HDC) : BOOL
fun closeFigure(hdc : HDC) : BOOL
fun endPath(hdc : HDC) : BOOL
fun fillPath(hdc : HDC) : BOOL
fun flattenPath(hdc : HDC) : BOOL
fun pathToRegion(hdc : HDC) : HRGN
fun selectClipPath(hdc : HDC, mode : RGN_COMBINE_MODE) : BOOL
fun setArcDirection(hdc : HDC, dir : ARC_DIRECTION) : LibC::Int32
fun setMiterLimit(hdc : HDC, limit : LibC::Single, old : LibC::Single*) : BOOL
fun strokeAndFillPath(hdc : HDC) : BOOL
fun strokePath(hdc : HDC) : BOOL
fun widenPath(hdc : HDC) : BOOL
fun getMiterLimit(hdc : HDC, plimit : LibC::Single*) : BOOL
fun getArcDirection(hdc : HDC) : LibC::Int32
fun getObjectW(h : HGDIOBJ, c : LibC::Int32, pv : LibC::Void*) : LibC::Int32
fun moveToEx(hdc : HDC, x : LibC::Int32, y : LibC::Int32, lppt : POINT*) : BOOL
fun setViewportExtEx(hdc : HDC, x : LibC::Int32, y : LibC::Int32, lpsz : SIZE*) : BOOL
fun setViewportOrgEx(hdc : HDC, x : LibC::Int32, y : LibC::Int32, lppt : POINT*) : BOOL
fun setWindowExtEx(hdc : HDC, x : LibC::Int32, y : LibC::Int32, lpsz : SIZE*) : BOOL
fun setWindowOrgEx(hdc : HDC, x : LibC::Int32, y : LibC::Int32, lppt : POINT*) : BOOL
fun offsetViewportOrgEx(hdc : HDC, x : LibC::Int32, y : LibC::Int32, lppt : POINT*) : BOOL
fun offsetWindowOrgEx(hdc : HDC, x : LibC::Int32, y : LibC::Int32, lppt : POINT*) : BOOL
fun scaleViewportExtEx(hdc : HDC, xn : LibC::Int32, dx : LibC::Int32, yn : LibC::Int32, yd : LibC::Int32, lpsz : SIZE*) : BOOL
fun scaleWindowExtEx(hdc : HDC, xn : LibC::Int32, xd : LibC::Int32, yn : LibC::Int32, yd : LibC::Int32, lpsz : SIZE*) : BOOL
fun setBitmapDimensionEx(hbm : HBITMAP, w : LibC::Int32, h : LibC::Int32, lpsz : SIZE*) : BOOL
fun setBrushOrgEx(hdc : HDC, x : LibC::Int32, y : LibC::Int32, lppt : POINT*) : BOOL
fun getDCOrgEx(hdc : HDC, lppt : POINT*) : BOOL
fun fixBrushOrgEx(hdc : HDC, x : LibC::Int32, y : LibC::Int32, ptl : POINT*) : BOOL
fun unrealizeObject(h : HGDIOBJ) : BOOL
fun gdiFlush() : BOOL
fun gdiSetBatchLimit(dw : LibC::UInt32) : LibC::UInt32
fun gdiGetBatchLimit() : LibC::UInt32
fun wglSwapMultipleBuffers(param0 : LibC::UInt32, param1 : WGLSWAP*) : LibC::UInt32
fun createFontPackage(puchSrcBuffer : LibC::Byte*, ulSrcBufferSize : LibC::UInt32, ppuchFontPackageBuffer : LibC::Byte**, pulFontPackageBufferSize : LibC::UInt32*, pulBytesWritten : LibC::UInt32*, usFlag : LibC::UInt16, usTTCIndex : LibC::UInt16, usSubsetFormat : LibC::UInt16, usSubsetLanguage : LibC::UInt16, usSubsetPlatform : CREATE_FONT_PACKAGE_SUBSET_PLATFORM, usSubsetEncoding : CREATE_FONT_PACKAGE_SUBSET_ENCODING, pusSubsetKeepList : LibC::UInt16*, usSubsetListCount : LibC::UInt16, lpfnAllocate : CFP_ALLOCPROC, lpfnReAllocate : CFP_REALLOCPROC, lpfnFree : CFP_FREEPROC, lpvReserved : LibC::Void*) : LibC::UInt32
fun mergeFontPackage(puchMergeFontBuffer : LibC::Byte*, ulMergeFontBufferSize : LibC::UInt32, puchFontPackageBuffer : LibC::Byte*, ulFontPackageBufferSize : LibC::UInt32, ppuchDestBuffer : LibC::Byte**, pulDestBufferSize : LibC::UInt32*, pulBytesWritten : LibC::UInt32*, usMode : LibC::UInt16, lpfnAllocate : CFP_ALLOCPROC, lpfnReAllocate : CFP_REALLOCPROC, lpfnFree : CFP_FREEPROC, lpvReserved : LibC::Void*) : LibC::UInt32
fun tTLoadEmbeddedFont(phFontReference : HANDLE*, ulFlags : LibC::UInt32, pulPrivStatus : EMBEDDED_FONT_PRIV_STATUS*, ulPrivs : FONT_LICENSE_PRIVS, pulStatus : TTLOAD_EMBEDDED_FONT_STATUS*, lpfnReadFromStream : READEMBEDPROC, lpvReadStream : LibC::Void*, szWinFamilyName : PWSTR, szMacFamilyName : PSTR, pTTLoadInfo : TTLOADINFO*) : LibC::Int32
fun tTGetEmbeddedFontInfo(ulFlags : TTEMBED_FLAGS, pulPrivStatus : LibC::UInt32*, ulPrivs : FONT_LICENSE_PRIVS, pulStatus : LibC::UInt32*, lpfnReadFromStream : READEMBEDPROC, lpvReadStream : LibC::Void*, pTTLoadInfo : TTLOADINFO*) : LibC::Int32
fun tTDeleteEmbeddedFont(hFontReference : HANDLE, ulFlags : LibC::UInt32, pulStatus : LibC::UInt32*) : LibC::Int32
fun tTGetEmbeddingType(hDC : HDC, pulEmbedType : EMBEDDED_FONT_PRIV_STATUS*) : LibC::Int32
fun tTRunValidationTests(hDC : HDC, pTestParam : TTVALIDATIONTESTSPARAMS*) : LibC::Int32
fun tTIsEmbeddingEnabled(hDC : HDC, pbEnabled : BOOL*) : LibC::Int32
fun tTIsEmbeddingEnabledForFacename(lpszFacename : PSTR, pbEnabled : BOOL*) : LibC::Int32
fun tTEnableEmbeddingForFacename(lpszFacename : PSTR, bEnable : BOOL) : LibC::Int32
fun tTRunValidationTestsEx(hDC : HDC, pTestParam : TTVALIDATIONTESTSPARAMSEX*) : LibC::Int32
fun drawEdge(hdc : HDC, qrc : RECT*, edge : DRAWEDGE_FLAGS, grfFlags : DRAW_EDGE_FLAGS) : BOOL
fun drawFrameControl(param0 : HDC, param1 : RECT*, param2 : DFC_TYPE, param3 : DFCS_STATE) : BOOL
fun drawCaption(hwnd : HWND, hdc : HDC, lprect : RECT*, flags : DRAW_CAPTION_FLAGS) : BOOL
fun drawAnimatedRects(hwnd : HWND, idAni : LibC::Int32, lprcFrom : RECT*, lprcTo : RECT*) : BOOL
fun grayStringA(hDC : HDC, hBrush : HBRUSH, lpOutputFunc : GRAYSTRINGPROC, lpData : LPARAM, nCount : LibC::Int32, x : LibC::Int32, y : LibC::Int32, nWidth : LibC::Int32, nHeight : LibC::Int32) : BOOL
fun grayStringW(hDC : HDC, hBrush : HBRUSH, lpOutputFunc : GRAYSTRINGPROC, lpData : LPARAM, nCount : LibC::Int32, x : LibC::Int32, y : LibC::Int32, nWidth : LibC::Int32, nHeight : LibC::Int32) : BOOL
fun drawStateA(hdc : HDC, hbrFore : HBRUSH, qfnCallBack : DRAWSTATEPROC, lData : LPARAM, wData : WPARAM, x : LibC::Int32, y : LibC::Int32, cx : LibC::Int32, cy : LibC::Int32, uFlags : DRAWSTATE_FLAGS) : BOOL
fun drawStateW(hdc : HDC, hbrFore : HBRUSH, qfnCallBack : DRAWSTATEPROC, lData : LPARAM, wData : WPARAM, x : LibC::Int32, y : LibC::Int32, cx : LibC::Int32, cy : LibC::Int32, uFlags : DRAWSTATE_FLAGS) : BOOL
fun updateWindow(hWnd : HWND) : BOOL
fun paintDesktop(hdc : HDC) : BOOL
fun windowFromDC(hDC : HDC) : HWND
fun getDC(hWnd : HWND) : HDC
fun getDCEx(hWnd : HWND, hrgnClip : HRGN, flags : GET_DCX_FLAGS) : HDC
fun getWindowDC(hWnd : HWND) : HDC
fun releaseDC(hWnd : HWND, hDC : HDC) : LibC::Int32
fun beginPaint(hWnd : HWND, lpPaint : PAINTSTRUCT*) : HDC
fun endPaint(hWnd : HWND, lpPaint : PAINTSTRUCT*) : BOOL
fun getUpdateRect(hWnd : HWND, lpRect : RECT*, bErase : BOOL) : BOOL
fun getUpdateRgn(hWnd : HWND, hRgn : HRGN, bErase : BOOL) : LibC::Int32
fun setWindowRgn(hWnd : HWND, hRgn : HRGN, bRedraw : BOOL) : LibC::Int32
fun getWindowRgn(hWnd : HWND, hRgn : HRGN) : LibC::Int32
fun getWindowRgnBox(hWnd : HWND, lprc : RECT*) : LibC::Int32
fun excludeUpdateRgn(hDC : HDC, hWnd : HWND) : LibC::Int32
fun invalidateRect(hWnd : HWND, lpRect : RECT*, bErase : BOOL) : BOOL
fun validateRect(hWnd : HWND, lpRect : RECT*) : BOOL
fun invalidateRgn(hWnd : HWND, hRgn : HRGN, bErase : BOOL) : BOOL
fun validateRgn(hWnd : HWND, hRgn : HRGN) : BOOL
fun redrawWindow(hWnd : HWND, lprcUpdate : RECT*, hrgnUpdate : HRGN, flags : REDRAW_WINDOW_FLAGS) : BOOL
fun lockWindowUpdate(hWndLock : HWND) : BOOL
fun clientToScreen(hWnd : HWND, lpPoint : POINT*) : BOOL
fun screenToClient(hWnd : HWND, lpPoint : POINT*) : BOOL
fun getSysColorBrush(nIndex : LibC::Int32) : HBRUSH
fun drawFocusRect(hDC : HDC, lprc : RECT*) : BOOL
fun fillRect(hDC : HDC, lprc : RECT*, hbr : HBRUSH) : LibC::Int32
fun frameRect(hDC : HDC, lprc : RECT*, hbr : HBRUSH) : LibC::Int32
fun invertRect(hDC : HDC, lprc : RECT*) : BOOL
fun setRect(lprc : RECT*, xLeft : LibC::Int32, yTop : LibC::Int32, xRight : LibC::Int32, yBottom : LibC::Int32) : BOOL
fun setRectEmpty(lprc : RECT*) : BOOL
fun copyRect(lprcDst : RECT*, lprcSrc : RECT*) : BOOL
fun inflateRect(lprc : RECT*, dx : LibC::Int32, dy : LibC::Int32) : BOOL
fun intersectRect(lprcDst : RECT*, lprcSrc1 : RECT*, lprcSrc2 : RECT*) : BOOL
fun unionRect(lprcDst : RECT*, lprcSrc1 : RECT*, lprcSrc2 : RECT*) : BOOL
fun subtractRect(lprcDst : RECT*, lprcSrc1 : RECT*, lprcSrc2 : RECT*) : BOOL
fun offsetRect(lprc : RECT*, dx : LibC::Int32, dy : LibC::Int32) : BOOL
fun isRectEmpty(lprc : RECT*) : BOOL
fun equalRect(lprc1 : RECT*, lprc2 : RECT*) : BOOL
fun ptInRect(lprc : RECT*, pt : POINT) : BOOL
fun loadBitmapA(hInstance : HINSTANCE, lpBitmapName : PSTR) : HBITMAP
fun loadBitmapW(hInstance : HINSTANCE, lpBitmapName : PWSTR) : HBITMAP
fun changeDisplaySettingsA(lpDevMode : DEVMODEA*, dwFlags : CDS_TYPE) : DISP_CHANGE
fun changeDisplaySettingsW(lpDevMode : DEVMODEW*, dwFlags : CDS_TYPE) : DISP_CHANGE
fun changeDisplaySettingsExA(lpszDeviceName : PSTR, lpDevMode : DEVMODEA*, hwnd : HWND, dwflags : CDS_TYPE, lParam : LibC::Void*) : DISP_CHANGE
fun changeDisplaySettingsExW(lpszDeviceName : PWSTR, lpDevMode : DEVMODEW*, hwnd : HWND, dwflags : CDS_TYPE, lParam : LibC::Void*) : DISP_CHANGE
fun enumDisplaySettingsA(lpszDeviceName : PSTR, iModeNum : ENUM_DISPLAY_SETTINGS_MODE, lpDevMode : DEVMODEA*) : BOOL
fun enumDisplaySettingsW(lpszDeviceName : PWSTR, iModeNum : ENUM_DISPLAY_SETTINGS_MODE, lpDevMode : DEVMODEW*) : BOOL
fun enumDisplaySettingsExA(lpszDeviceName : PSTR, iModeNum : ENUM_DISPLAY_SETTINGS_MODE, lpDevMode : DEVMODEA*, dwFlags : LibC::UInt32) : BOOL
fun enumDisplaySettingsExW(lpszDeviceName : PWSTR, iModeNum : ENUM_DISPLAY_SETTINGS_MODE, lpDevMode : DEVMODEW*, dwFlags : LibC::UInt32) : BOOL
fun enumDisplayDevicesA(lpDevice : PSTR, iDevNum : LibC::UInt32, lpDisplayDevice : DISPLAY_DEVICEA*, dwFlags : LibC::UInt32) : BOOL
fun enumDisplayDevicesW(lpDevice : PWSTR, iDevNum : LibC::UInt32, lpDisplayDevice : DISPLAY_DEVICEW*, dwFlags : LibC::UInt32) : BOOL
fun monitorFromPoint(pt : POINT, dwFlags : MONITOR_FROM_FLAGS) : HMONITOR
fun monitorFromRect(lprc : RECT*, dwFlags : MONITOR_FROM_FLAGS) : HMONITOR
fun monitorFromWindow(hwnd : HWND, dwFlags : MONITOR_FROM_FLAGS) : HMONITOR
fun getMonitorInfoA(hMonitor : HMONITOR, lpmi : MONITORINFO*) : BOOL
fun getMonitorInfoW(hMonitor : HMONITOR, lpmi : MONITORINFO*) : BOOL
fun enumDisplayMonitors(hdc : HDC, lprcClip : RECT*, lpfnEnum : MONITORENUMPROC, dwData : LPARAM) : BOOL

  end
