  @[Link("Media")]
  lib LibMedia
    TIMERR_NOERROR = 0
TIMERR_NOCANDO = 97
TIMERR_STRUCT = 129
MAXPNAMELEN = 32
MAXERRORLENGTH = 256
MM_MICROSOFT = 1
MM_MIDI_MAPPER = 1
MM_WAVE_MAPPER = 2
MM_SNDBLST_MIDIOUT = 3
MM_SNDBLST_MIDIIN = 4
MM_SNDBLST_SYNTH = 5
MM_SNDBLST_WAVEOUT = 6
MM_SNDBLST_WAVEIN = 7
MM_ADLIB = 9
MM_MPU401_MIDIOUT = 10
MM_MPU401_MIDIIN = 11
MM_PC_JOYSTICK = 12
TIME_MS = 1
TIME_SAMPLES = 2
TIME_BYTES = 4
TIME_SMPTE = 8
TIME_MIDI = 16
TIME_TICKS = 32
MM_JOY1MOVE = 928
MM_JOY2MOVE = 929
MM_JOY1ZMOVE = 930
MM_JOY2ZMOVE = 931
MM_JOY1BUTTONDOWN = 949
MM_JOY2BUTTONDOWN = 950
MM_JOY1BUTTONUP = 951
MM_JOY2BUTTONUP = 952
MM_MCINOTIFY = 953
MM_WOM_OPEN = 955
MM_WOM_CLOSE = 956
MM_WOM_DONE = 957
MM_WIM_OPEN = 958
MM_WIM_CLOSE = 959
MM_WIM_DATA = 960
MM_MIM_OPEN = 961
MM_MIM_CLOSE = 962
MM_MIM_DATA = 963
MM_MIM_LONGDATA = 964
MM_MIM_ERROR = 965
MM_MIM_LONGERROR = 966
MM_MOM_OPEN = 967
MM_MOM_CLOSE = 968
MM_MOM_DONE = 969
MM_DRVM_OPEN = 976
MM_DRVM_CLOSE = 977
MM_DRVM_DATA = 978
MM_DRVM_ERROR = 979
MM_STREAM_OPEN = 980
MM_STREAM_CLOSE = 981
MM_STREAM_DONE = 982
MM_STREAM_ERROR = 983
MM_MOM_POSITIONCB = 970
MM_MCISIGNAL = 971
MM_MIM_MOREDATA = 972
MM_MIXM_LINE_CHANGE = 976
MM_MIXM_CONTROL_CHANGE = 977
MMSYSERR_BASE = 0
WAVERR_BASE = 32
MIDIERR_BASE = 64
TIMERR_BASE = 96
JOYERR_BASE = 160
MCIERR_BASE = 256
MIXERR_BASE = 1024
MCI_STRING_OFFSET = 512
MCI_VD_OFFSET = 1024
MCI_CD_OFFSET = 1088
MCI_WAVE_OFFSET = 1152
MCI_SEQ_OFFSET = 1216
MMSYSERR_NOERROR = 0
MMSYSERR_ERROR = 1
MMSYSERR_BADDEVICEID = 2
MMSYSERR_NOTENABLED = 3
MMSYSERR_ALLOCATED = 4
MMSYSERR_INVALHANDLE = 5
MMSYSERR_NODRIVER = 6
MMSYSERR_NOMEM = 7
MMSYSERR_NOTSUPPORTED = 8
MMSYSERR_BADERRNUM = 9
MMSYSERR_INVALFLAG = 10
MMSYSERR_INVALPARAM = 11
MMSYSERR_HANDLEBUSY = 12
MMSYSERR_INVALIDALIAS = 13
MMSYSERR_BADDB = 14
MMSYSERR_KEYNOTFOUND = 15
MMSYSERR_READERROR = 16
MMSYSERR_WRITEERROR = 17
MMSYSERR_DELETEERROR = 18
MMSYSERR_VALNOTFOUND = 19
MMSYSERR_NODRIVERCB = 20
MMSYSERR_MOREDATA = 21
MMSYSERR_LASTERROR = 21
TIME_ONESHOT = 0
TIME_PERIODIC = 1
TIME_CALLBACK_FUNCTION = 0
TIME_CALLBACK_EVENT_SET = 16
TIME_CALLBACK_EVENT_PULSE = 32
TIME_KILL_SYNCHRONOUS = 256
enum TIMECODE_SAMPLE_FLAGS : UInt32
ED_DEVCAP_TIMECODE_READ = 4121

ED_DEVCAP_ATN_READ = 5047

ED_DEVCAP_RTC_READ = 5050

end
type HTASK = LibC::Int*
struct Pigb636ef4fd74f
  hour : LibC::Byte
  min : LibC::Byte
  sec : LibC::Byte
  frame : LibC::Byte
  fps : LibC::Byte
  dummy : LibC::Byte
  pad : Array(LibC::Byte)
end
struct Duckaef19e890068
  songptrpos : LibC::UInt32
end
type Otherfe138e5c3544 = LibC::UInt32 | LibC::UInt32 | LibC::UInt32 | LibC::UInt32 | Pigb636ef4fd74f | Duckaef19e890068
struct MMTIME
  wType : LibC::UInt32
  u : Otherfe138e5c3544
end
alias LPDRVCALLBACK = (HDRVR, LibC::UInt32, LibC::UIint*, LibC::UIint*, LibC::UIint* -> LibC::Void)
struct TIMECAPS
  wPeriodMin : LibC::UInt32
  wPeriodMax : LibC::UInt32
end
alias LPTIMECALLBACK = (LibC::UInt32, LibC::UInt32, LibC::UIint*, LibC::UIint*, LibC::UIint* -> LibC::Void)
struct Bird0e4a1ecdf761
  wFrameRate : LibC::UInt16
  wFrameFract : LibC::UInt16
  dwFrames : LibC::UInt32
end
type TIMECODE = Bird0e4a1ecdf761 | LibC::UInt64
struct TIMECODE_SAMPLE
  qwTick : LibC::Int64
  timecode : TIMECODE
  dwUser : LibC::UInt32
  dwFlags : TIMECODE_SAMPLE_FLAGS
end
fun timeGetSystemTime(pmmt : MMTIME*, cbmmt : LibC::UInt32) : LibC::UInt32
fun timeGetTime() : LibC::UInt32
fun timeGetDevCaps(ptc : TIMECAPS*, cbtc : LibC::UInt32) : LibC::UInt32
fun timeBeginPeriod(uPeriod : LibC::UInt32) : LibC::UInt32
fun timeEndPeriod(uPeriod : LibC::UInt32) : LibC::UInt32
fun timeSetEvent(uDelay : LibC::UInt32, uResolution : LibC::UInt32, fptc : LPTIMECALLBACK, dwUser : LibC::UIint*, fuEvent : LibC::UInt32) : LibC::UInt32
fun timeKillEvent(uTimerID : LibC::UInt32) : LibC::UInt32

  end
