  @[Link("System.Com.Urlmon")]
  lib LibSystemComUrlmon
    MKSYS_URLMONIKER = 6
URL_MK_LEGACY = 0
URL_MK_UNIFORM = 1
URL_MK_NO_CANONICALIZE = 2
FIEF_FLAG_FORCE_JITUI = 1
FIEF_FLAG_PEEK = 2
FIEF_FLAG_SKIP_INSTALLED_VERSION_CHECK = 4
FIEF_FLAG_RESERVED_0 = 8
FMFD_DEFAULT = 0
FMFD_URLASFILENAME = 1
FMFD_ENABLEMIMESNIFFING = 2
FMFD_IGNOREMIMETEXTPLAIN = 4
FMFD_SERVERMIME = 8
FMFD_RESPECTTEXTPLAIN = 16
FMFD_RETURNUPDATEDIMGMIMES = 32
FMFD_RESERVED_1 = 64
FMFD_RESERVED_2 = 128
UAS_EXACTLEGACY = 4096
URLMON_OPTION_USERAGENT = 268435457
URLMON_OPTION_USERAGENT_REFRESH = 268435458
URLMON_OPTION_URL_ENCODING = 268435460
URLMON_OPTION_USE_BINDSTRINGCREDS = 268435464
URLMON_OPTION_USE_BROWSERAPPSDOCUMENTS = 268435472
CF_NULL = 0
MK_S_ASYNCHRONOUS = 262632
S_ASYNCHRONOUS = 262632
E_PENDING = -2147483638
INET_E_INVALID_URL = -2146697214
INET_E_NO_SESSION = -2146697213
INET_E_CANNOT_CONNECT = -2146697212
INET_E_RESOURCE_NOT_FOUND = -2146697211
INET_E_OBJECT_NOT_FOUND = -2146697210
INET_E_DATA_NOT_AVAILABLE = -2146697209
INET_E_DOWNLOAD_FAILURE = -2146697208
INET_E_AUTHENTICATION_REQUIRED = -2146697207
INET_E_NO_VALID_MEDIA = -2146697206
INET_E_CONNECTION_TIMEOUT = -2146697205
INET_E_INVALID_REQUEST = -2146697204
INET_E_UNKNOWN_PROTOCOL = -2146697203
INET_E_SECURITY_PROBLEM = -2146697202
INET_E_CANNOT_LOAD_DATA = -2146697201
INET_E_CANNOT_INSTANTIATE_OBJECT = -2146697200
INET_E_INVALID_CERTIFICATE = -2146697191
INET_E_REDIRECT_FAILED = -2146697196
INET_E_REDIRECT_TO_DIR = -2146697195
INET_E_CANNOT_LOCK_REQUEST = -2146697194
INET_E_USE_EXTEND_BINDING = -2146697193
INET_E_TERMINATED_BIND = -2146697192
INET_E_RESERVED_1 = -2146697190
INET_E_BLOCKED_REDIRECT_XSECURITYID = -2146697189
INET_E_DOMINJECTIONVALIDATION = -2146697188
INET_E_VTAB_SWITCH_FORCE_ENGINE = -2146697187
INET_E_HSTS_CERTIFICATE_ERROR = -2146697186
INET_E_RESERVED_2 = -2146697185
INET_E_RESERVED_3 = -2146697184
INET_E_RESERVED_4 = -2146697183
INET_E_RESERVED_5 = -2146697182
INET_E_ERROR_FIRST = -2146697214
INET_E_CODE_DOWNLOAD_DECLINED = -2146696960
INET_E_RESULT_DISPATCHED = -2146696704
INET_E_CANNOT_REPLACE_SFP_FILE = -2146696448
INET_E_CODE_INSTALL_SUPPRESSED = -2146696192
INET_E_CODE_INSTALL_BLOCKED_BY_HASH_POLICY = -2146695936
INET_E_DOWNLOAD_BLOCKED_BY_INPRIVATE = -2146695935
INET_E_CODE_INSTALL_BLOCKED_IMMERSIVE = -2146695934
INET_E_FORBIDFRAMING = -2146695933
INET_E_CODE_INSTALL_BLOCKED_ARM = -2146695932
INET_E_BLOCKED_PLUGGABLE_PROTOCOL = -2146695931
INET_E_BLOCKED_ENHANCEDPROTECTEDMODE = -2146695930
INET_E_CODE_INSTALL_BLOCKED_BITNESS = -2146695929
INET_E_DOWNLOAD_BLOCKED_BY_CSP = -2146695928
INET_E_ERROR_LAST = -2146695928
Uri_DISPLAY_NO_FRAGMENT = 1
Uri_PUNYCODE_IDN_HOST = 2
Uri_DISPLAY_IDN_HOST = 4
Uri_DISPLAY_NO_PUNYCODE = 8
Uri_ENCODING_USER_INFO_AND_PATH_IS_PERCENT_ENCODED_UTF8 = 1
Uri_ENCODING_USER_INFO_AND_PATH_IS_CP = 2
Uri_ENCODING_HOST_IS_IDN = 4
Uri_ENCODING_HOST_IS_PERCENT_ENCODED_UTF8 = 8
Uri_ENCODING_HOST_IS_PERCENT_ENCODED_CP = 16
Uri_ENCODING_QUERY_AND_FRAGMENT_IS_PERCENT_ENCODED_UTF8 = 32
Uri_ENCODING_QUERY_AND_FRAGMENT_IS_CP = 64
UriBuilder_USE_ORIGINAL_FLAGS = 1
WININETINFO_OPTION_LOCK_HANDLE = 65534
URLOSTRM_USECACHEDCOPY_ONLY = 1
URLOSTRM_USECACHEDCOPY = 2
URLOSTRM_GETNEWESTVERSION = 3
SET_FEATURE_ON_THREAD = 1
SET_FEATURE_ON_PROCESS = 2
SET_FEATURE_IN_REGISTRY = 4
SET_FEATURE_ON_THREAD_LOCALMACHINE = 8
SET_FEATURE_ON_THREAD_INTRANET = 16
SET_FEATURE_ON_THREAD_TRUSTED = 32
SET_FEATURE_ON_THREAD_INTERNET = 64
SET_FEATURE_ON_THREAD_RESTRICTED = 128
GET_FEATURE_FROM_THREAD = 1
GET_FEATURE_FROM_PROCESS = 2
GET_FEATURE_FROM_REGISTRY = 4
GET_FEATURE_FROM_THREAD_LOCALMACHINE = 8
GET_FEATURE_FROM_THREAD_INTRANET = 16
GET_FEATURE_FROM_THREAD_TRUSTED = 32
GET_FEATURE_FROM_THREAD_INTERNET = 64
GET_FEATURE_FROM_THREAD_RESTRICTED = 128
INET_E_USE_DEFAULT_PROTOCOLHANDLER = -2146697199
INET_E_USE_DEFAULT_SETTING = -2146697198
INET_E_DEFAULT_ACTION = -2146697199
INET_E_QUERYOPTION_UNKNOWN = -2146697197
INET_E_REDIRECTING = -2146697196
PROTOCOLFLAG_NO_PICS_CHECK = 1
MUTZ_NOSAVEDFILECHECK = 1
MUTZ_ISFILE = 2
MUTZ_ACCEPT_WILDCARD_SCHEME = 128
MUTZ_ENFORCERESTRICTED = 256
MUTZ_RESERVED = 512
MUTZ_REQUIRESAVEDFILECHECK = 1024
MUTZ_DONT_UNESCAPE = 2048
MUTZ_DONT_USE_CACHE = 4096
MUTZ_FORCE_INTRANET_FLAGS = 8192
MUTZ_IGNORE_ZONE_MAPPINGS = 16384
MAX_SIZE_SECURITY_ID = 512
URLACTION_MIN = 4096
URLACTION_DOWNLOAD_MIN = 4096
URLACTION_DOWNLOAD_SIGNED_ACTIVEX = 4097
URLACTION_DOWNLOAD_UNSIGNED_ACTIVEX = 4100
URLACTION_DOWNLOAD_CURR_MAX = 4100
URLACTION_DOWNLOAD_MAX = 4607
URLACTION_ACTIVEX_MIN = 4608
URLACTION_ACTIVEX_RUN = 4608
URLPOLICY_ACTIVEX_CHECK_LIST = 65536
URLACTION_ACTIVEX_OVERRIDE_OBJECT_SAFETY = 4609
URLACTION_ACTIVEX_OVERRIDE_DATA_SAFETY = 4610
URLACTION_ACTIVEX_OVERRIDE_SCRIPT_SAFETY = 4611
URLACTION_SCRIPT_OVERRIDE_SAFETY = 5121
URLACTION_ACTIVEX_CONFIRM_NOOBJECTSAFETY = 4612
URLACTION_ACTIVEX_TREATASUNTRUSTED = 4613
URLACTION_ACTIVEX_NO_WEBOC_SCRIPT = 4614
URLACTION_ACTIVEX_OVERRIDE_REPURPOSEDETECTION = 4615
URLACTION_ACTIVEX_OVERRIDE_OPTIN = 4616
URLACTION_ACTIVEX_SCRIPTLET_RUN = 4617
URLACTION_ACTIVEX_DYNSRC_VIDEO_AND_ANIMATION = 4618
URLACTION_ACTIVEX_OVERRIDE_DOMAINLIST = 4619
URLACTION_ACTIVEX_ALLOW_TDC = 4620
URLACTION_ACTIVEX_CURR_MAX = 4620
URLACTION_ACTIVEX_MAX = 5119
URLACTION_SCRIPT_MIN = 5120
URLACTION_SCRIPT_RUN = 5120
URLACTION_SCRIPT_JAVA_USE = 5122
URLACTION_SCRIPT_SAFE_ACTIVEX = 5125
URLACTION_CROSS_DOMAIN_DATA = 5126
URLACTION_SCRIPT_PASTE = 5127
URLACTION_ALLOW_XDOMAIN_SUBFRAME_RESIZE = 5128
URLACTION_SCRIPT_XSSFILTER = 5129
URLACTION_SCRIPT_NAVIGATE = 5130
URLACTION_PLUGGABLE_PROTOCOL_XHR = 5131
URLACTION_ALLOW_VBSCRIPT_IE = 5132
URLACTION_ALLOW_JSCRIPT_IE = 5133
URLACTION_SCRIPT_CURR_MAX = 5133
URLACTION_SCRIPT_MAX = 5631
URLACTION_HTML_MIN = 5632
URLACTION_HTML_SUBMIT_FORMS = 5633
URLACTION_HTML_SUBMIT_FORMS_FROM = 5634
URLACTION_HTML_SUBMIT_FORMS_TO = 5635
URLACTION_HTML_FONT_DOWNLOAD = 5636
URLACTION_HTML_JAVA_RUN = 5637
URLACTION_HTML_USERDATA_SAVE = 5638
URLACTION_HTML_SUBFRAME_NAVIGATE = 5639
URLACTION_HTML_META_REFRESH = 5640
URLACTION_HTML_MIXED_CONTENT = 5641
URLACTION_HTML_INCLUDE_FILE_PATH = 5642
URLACTION_HTML_ALLOW_INJECTED_DYNAMIC_HTML = 5643
URLACTION_HTML_REQUIRE_UTF8_DOCUMENT_CODEPAGE = 5644
URLACTION_HTML_ALLOW_CROSS_DOMAIN_CANVAS = 5645
URLACTION_HTML_ALLOW_WINDOW_CLOSE = 5646
URLACTION_HTML_ALLOW_CROSS_DOMAIN_WEBWORKER = 5647
URLACTION_HTML_ALLOW_CROSS_DOMAIN_TEXTTRACK = 5648
URLACTION_HTML_ALLOW_INDEXEDDB = 5649
URLACTION_HTML_MAX = 6143
URLACTION_SHELL_MIN = 6144
URLACTION_SHELL_INSTALL_DTITEMS = 6144
URLACTION_SHELL_MOVE_OR_COPY = 6146
URLACTION_SHELL_FILE_DOWNLOAD = 6147
URLACTION_SHELL_VERB = 6148
URLACTION_SHELL_WEBVIEW_VERB = 6149
URLACTION_SHELL_SHELLEXECUTE = 6150
URLACTION_SHELL_EXECUTE_HIGHRISK = 6150
URLACTION_SHELL_EXECUTE_MODRISK = 6151
URLACTION_SHELL_EXECUTE_LOWRISK = 6152
URLACTION_SHELL_POPUPMGR = 6153
URLACTION_SHELL_RTF_OBJECTS_LOAD = 6154
URLACTION_SHELL_ENHANCED_DRAGDROP_SECURITY = 6155
URLACTION_SHELL_EXTENSIONSECURITY = 6156
URLACTION_SHELL_SECURE_DRAGSOURCE = 6157
URLACTION_SHELL_REMOTEQUERY = 6158
URLACTION_SHELL_PREVIEW = 6159
URLACTION_SHELL_SHARE = 6160
URLACTION_SHELL_ALLOW_CROSS_SITE_SHARE = 6161
URLACTION_SHELL_TOCTOU_RISK = 6162
URLACTION_SHELL_CURR_MAX = 6162
URLACTION_SHELL_MAX = 6655
URLACTION_NETWORK_MIN = 6656
URLACTION_CREDENTIALS_USE = 6656
URLPOLICY_CREDENTIALS_SILENT_LOGON_OK = 0
URLPOLICY_CREDENTIALS_MUST_PROMPT_USER = 65536
URLPOLICY_CREDENTIALS_CONDITIONAL_PROMPT = 131072
URLPOLICY_CREDENTIALS_ANONYMOUS_ONLY = 196608
URLACTION_AUTHENTICATE_CLIENT = 6657
URLPOLICY_AUTHENTICATE_CLEARTEXT_OK = 0
URLPOLICY_AUTHENTICATE_CHALLENGE_RESPONSE = 65536
URLPOLICY_AUTHENTICATE_MUTUAL_ONLY = 196608
URLACTION_COOKIES = 6658
URLACTION_COOKIES_SESSION = 6659
URLACTION_CLIENT_CERT_PROMPT = 6660
URLACTION_COOKIES_THIRD_PARTY = 6661
URLACTION_COOKIES_SESSION_THIRD_PARTY = 6662
URLACTION_COOKIES_ENABLED = 6672
URLACTION_NETWORK_CURR_MAX = 6672
URLACTION_NETWORK_MAX = 7167
URLACTION_JAVA_MIN = 7168
URLACTION_JAVA_PERMISSIONS = 7168
URLPOLICY_JAVA_PROHIBIT = 0
URLPOLICY_JAVA_HIGH = 65536
URLPOLICY_JAVA_MEDIUM = 131072
URLPOLICY_JAVA_LOW = 196608
URLPOLICY_JAVA_CUSTOM = 8388608
URLACTION_JAVA_CURR_MAX = 7168
URLACTION_JAVA_MAX = 7423
URLACTION_INFODELIVERY_MIN = 7424
URLACTION_INFODELIVERY_NO_ADDING_CHANNELS = 7424
URLACTION_INFODELIVERY_NO_EDITING_CHANNELS = 7425
URLACTION_INFODELIVERY_NO_REMOVING_CHANNELS = 7426
URLACTION_INFODELIVERY_NO_ADDING_SUBSCRIPTIONS = 7427
URLACTION_INFODELIVERY_NO_EDITING_SUBSCRIPTIONS = 7428
URLACTION_INFODELIVERY_NO_REMOVING_SUBSCRIPTIONS = 7429
URLACTION_INFODELIVERY_NO_CHANNEL_LOGGING = 7430
URLACTION_INFODELIVERY_CURR_MAX = 7430
URLACTION_INFODELIVERY_MAX = 7679
URLACTION_CHANNEL_SOFTDIST_MIN = 7680
URLACTION_CHANNEL_SOFTDIST_PERMISSIONS = 7685
URLPOLICY_CHANNEL_SOFTDIST_PROHIBIT = 65536
URLPOLICY_CHANNEL_SOFTDIST_PRECACHE = 131072
URLPOLICY_CHANNEL_SOFTDIST_AUTOINSTALL = 196608
URLACTION_CHANNEL_SOFTDIST_MAX = 7935
URLACTION_DOTNET_USERCONTROLS = 8197
URLACTION_BEHAVIOR_MIN = 8192
URLACTION_BEHAVIOR_RUN = 8192
URLPOLICY_BEHAVIOR_CHECK_LIST = 65536
URLACTION_FEATURE_MIN = 8448
URLACTION_FEATURE_MIME_SNIFFING = 8448
URLACTION_FEATURE_ZONE_ELEVATION = 8449
URLACTION_FEATURE_WINDOW_RESTRICTIONS = 8450
URLACTION_FEATURE_SCRIPT_STATUS_BAR = 8451
URLACTION_FEATURE_FORCE_ADDR_AND_STATUS = 8452
URLACTION_FEATURE_BLOCK_INPUT_PROMPTS = 8453
URLACTION_FEATURE_DATA_BINDING = 8454
URLACTION_FEATURE_CROSSDOMAIN_FOCUS_CHANGE = 8455
URLACTION_AUTOMATIC_DOWNLOAD_UI_MIN = 8704
URLACTION_AUTOMATIC_DOWNLOAD_UI = 8704
URLACTION_AUTOMATIC_ACTIVEX_UI = 8705
URLACTION_ALLOW_RESTRICTEDPROTOCOLS = 8960
URLACTION_ALLOW_APEVALUATION = 8961
URLACTION_ALLOW_XHR_EVALUATION = 8962
URLACTION_WINDOWS_BROWSER_APPLICATIONS = 9216
URLACTION_XPS_DOCUMENTS = 9217
URLACTION_LOOSE_XAML = 9218
URLACTION_LOWRIGHTS = 9472
URLACTION_WINFX_SETUP = 9728
URLACTION_INPRIVATE_BLOCKING = 9984
URLACTION_ALLOW_AUDIO_VIDEO = 9985
URLACTION_ALLOW_ACTIVEX_FILTERING = 9986
URLACTION_ALLOW_STRUCTURED_STORAGE_SNIFFING = 9987
URLACTION_ALLOW_AUDIO_VIDEO_PLUGINS = 9988
URLACTION_ALLOW_ZONE_ELEVATION_VIA_OPT_OUT = 9989
URLACTION_ALLOW_ZONE_ELEVATION_OPT_OUT_ADDITION = 9990
URLACTION_ALLOW_CROSSDOMAIN_DROP_WITHIN_WINDOW = 9992
URLACTION_ALLOW_CROSSDOMAIN_DROP_ACROSS_WINDOWS = 9993
URLACTION_ALLOW_CROSSDOMAIN_APPCACHE_MANIFEST = 9994
URLACTION_ALLOW_RENDER_LEGACY_DXTFILTERS = 9995
URLACTION_ALLOW_ANTIMALWARE_SCANNING_OF_ACTIVEX = 9996
URLACTION_ALLOW_CSS_EXPRESSIONS = 9997
URLPOLICY_ALLOW = 0
URLPOLICY_QUERY = 1
URLPOLICY_DISALLOW = 3
URLPOLICY_NOTIFY_ON_ALLOW = 16
URLPOLICY_NOTIFY_ON_DISALLOW = 32
URLPOLICY_LOG_ON_ALLOW = 64
URLPOLICY_LOG_ON_DISALLOW = 128
URLPOLICY_MASK_PERMISSIONS = 15
URLPOLICY_DONTCHECKDLGBOX = 256
URLZONE_ESC_FLAG = 256
SECURITY_IE_STATE_GREEN = 0
SECURITY_IE_STATE_RED = 1
SOFTDIST_FLAG_USAGE_EMAIL = 1
SOFTDIST_FLAG_USAGE_PRECACHE = 2
SOFTDIST_FLAG_USAGE_AUTOINSTALL = 4
SOFTDIST_FLAG_DELETE_SUBSCRIPTION = 8
SOFTDIST_ADSTATE_NONE = 0
SOFTDIST_ADSTATE_AVAILABLE = 1
SOFTDIST_ADSTATE_DOWNLOADED = 2
SOFTDIST_ADSTATE_INSTALLED = 3
CONFIRMSAFETYACTION_LOADOBJECT = 1
enum IEObjectType : Int32
IE_EPM_OBJECT_EVENT = 0

IE_EPM_OBJECT_MUTEX = 1

IE_EPM_OBJECT_SEMAPHORE = 2

IE_EPM_OBJECT_SHARED_MEMORY = 3

IE_EPM_OBJECT_WAITABLE_TIMER = 4

IE_EPM_OBJECT_FILE = 5

IE_EPM_OBJECT_NAMED_PIPE = 6

IE_EPM_OBJECT_REGISTRY = 7

end
enum MONIKERPROPERTY : Int32
MIMETYPEPROP = 0

USE_SRC_URL = 1

CLASSIDPROP = 2

TRUSTEDDOWNLOADPROP = 3

POPUPLEVELPROP = 4

end
enum BINDVERB : Int32
BINDVERB_GET = 0

BINDVERB_POST = 1

BINDVERB_PUT = 2

BINDVERB_CUSTOM = 3

BINDVERB_RESERVED1 = 4

end
enum BINDF : Int32
BINDF_ASYNCHRONOUS = 1

BINDF_ASYNCSTORAGE = 2

BINDF_NOPROGRESSIVERENDERING = 4

BINDF_OFFLINEOPERATION = 8

BINDF_GETNEWESTVERSION = 16

BINDF_NOWRITECACHE = 32

BINDF_NEEDFILE = 64

BINDF_PULLDATA = 128

BINDF_IGNORESECURITYPROBLEM = 256

BINDF_RESYNCHRONIZE = 512

BINDF_HYPERLINK = 1024

BINDF_NO_UI = 2048

BINDF_SILENTOPERATION = 4096

BINDF_PRAGMA_NO_CACHE = 8192

BINDF_GETCLASSOBJECT = 16384

BINDF_RESERVED_1 = 32768

BINDF_FREE_THREADED = 65536

BINDF_DIRECT_READ = 131072

BINDF_FORMS_SUBMIT = 262144

BINDF_GETFROMCACHE_IF_NET_FAIL = 524288

BINDF_FROMURLMON = 1048576

BINDF_FWD_BACK = 2097152

BINDF_PREFERDEFAULTHANDLER = 4194304

BINDF_ENFORCERESTRICTED = 8388608

BINDF_RESERVED_2 = -2147483648

BINDF_RESERVED_3 = 16777216

BINDF_RESERVED_4 = 33554432

BINDF_RESERVED_5 = 67108864

BINDF_RESERVED_6 = 134217728

BINDF_RESERVED_7 = 1073741824

BINDF_RESERVED_8 = 536870912

end
enum URL_ENCODING : Int32
URL_ENCODING_NONE = 0

URL_ENCODING_ENABLE_UTF8 = 268435456

URL_ENCODING_DISABLE_UTF8 = 536870912

end
struct REMSECURITY_ATTRIBUTES
  nLength : LibC::UInt32
  lpSecurityDescriptor : LibC::UInt32
  bInheritHandle : BOOL
end
struct RemBINDINFO
  cbSize : LibC::UInt32
  szExtraInfo : PWSTR
  grfBindInfoF : LibC::UInt32
  dwBindVerb : LibC::UInt32
  szCustomVerb : PWSTR
  cbstgmedData : LibC::UInt32
  dwOptions : LibC::UInt32
  dwOptionsFlags : LibC::UInt32
  dwCodePage : LibC::UInt32
  securityAttributes : REMSECURITY_ATTRIBUTES
  iid : LibC::Guid
  pUnk : IUnknown
  dwReserved : LibC::UInt32
end
struct RemFORMATETC
  cfFormat : LibC::UInt32
  ptd : LibC::UInt32
  dwAspect : LibC::UInt32
  lindex : LibC::Int32
  tymed : LibC::UInt32
end
enum BINDINFO_OPTIONS : Int32
BINDINFO_OPTIONS_WININETFLAG = 65536

BINDINFO_OPTIONS_ENABLE_UTF8 = 131072

BINDINFO_OPTIONS_DISABLE_UTF8 = 262144

BINDINFO_OPTIONS_USE_IE_ENCODING = 524288

BINDINFO_OPTIONS_BINDTOOBJECT = 1048576

BINDINFO_OPTIONS_SECURITYOPTOUT = 2097152

BINDINFO_OPTIONS_IGNOREMIMETEXTPLAIN = 4194304

BINDINFO_OPTIONS_USEBINDSTRINGCREDS = 8388608

BINDINFO_OPTIONS_IGNOREHTTPHTTPSREDIRECTS = 16777216

BINDINFO_OPTIONS_IGNORE_SSLERRORS_ONCE = 33554432

BINDINFO_WPC_DOWNLOADBLOCKED = 134217728

BINDINFO_WPC_LOGGING_ENABLED = 268435456

BINDINFO_OPTIONS_ALLOWCONNECTDATA = 536870912

BINDINFO_OPTIONS_DISABLEAUTOREDIRECTS = 1073741824

BINDINFO_OPTIONS_SHDOCVW_NAVIGATE = -2147483648

end
enum BSCF : Int32
BSCF_FIRSTDATANOTIFICATION = 1

BSCF_INTERMEDIATEDATANOTIFICATION = 2

BSCF_LASTDATANOTIFICATION = 4

BSCF_DATAFULLYAVAILABLE = 8

BSCF_AVAILABLEDATASIZEUNKNOWN = 16

BSCF_SKIPDRAINDATAFORFILEURLS = 32

BSCF_64BITLENGTHDOWNLOAD = 64

end
enum BINDSTATUS : Int32
BINDSTATUS_FINDINGRESOURCE = 1

BINDSTATUS_CONNECTING = 2

BINDSTATUS_REDIRECTING = 3

BINDSTATUS_BEGINDOWNLOADDATA = 4

BINDSTATUS_DOWNLOADINGDATA = 5

BINDSTATUS_ENDDOWNLOADDATA = 6

BINDSTATUS_BEGINDOWNLOADCOMPONENTS = 7

BINDSTATUS_INSTALLINGCOMPONENTS = 8

BINDSTATUS_ENDDOWNLOADCOMPONENTS = 9

BINDSTATUS_USINGCACHEDCOPY = 10

BINDSTATUS_SENDINGREQUEST = 11

BINDSTATUS_CLASSIDAVAILABLE = 12

BINDSTATUS_MIMETYPEAVAILABLE = 13

BINDSTATUS_CACHEFILENAMEAVAILABLE = 14

BINDSTATUS_BEGINSYNCOPERATION = 15

BINDSTATUS_ENDSYNCOPERATION = 16

BINDSTATUS_BEGINUPLOADDATA = 17

BINDSTATUS_UPLOADINGDATA = 18

BINDSTATUS_ENDUPLOADDATA = 19

BINDSTATUS_PROTOCOLCLASSID = 20

BINDSTATUS_ENCODING = 21

BINDSTATUS_VERIFIEDMIMETYPEAVAILABLE = 22

BINDSTATUS_CLASSINSTALLLOCATION = 23

BINDSTATUS_DECODING = 24

BINDSTATUS_LOADINGMIMEHANDLER = 25

BINDSTATUS_CONTENTDISPOSITIONATTACH = 26

BINDSTATUS_FILTERREPORTMIMETYPE = 27

BINDSTATUS_CLSIDCANINSTANTIATE = 28

BINDSTATUS_IUNKNOWNAVAILABLE = 29

BINDSTATUS_DIRECTBIND = 30

BINDSTATUS_RAWMIMETYPE = 31

BINDSTATUS_PROXYDETECTING = 32

BINDSTATUS_ACCEPTRANGES = 33

BINDSTATUS_COOKIE_SENT = 34

BINDSTATUS_COMPACT_POLICY_RECEIVED = 35

BINDSTATUS_COOKIE_SUPPRESSED = 36

BINDSTATUS_COOKIE_STATE_UNKNOWN = 37

BINDSTATUS_COOKIE_STATE_ACCEPT = 38

BINDSTATUS_COOKIE_STATE_REJECT = 39

BINDSTATUS_COOKIE_STATE_PROMPT = 40

BINDSTATUS_COOKIE_STATE_LEASH = 41

BINDSTATUS_COOKIE_STATE_DOWNGRADE = 42

BINDSTATUS_POLICY_HREF = 43

BINDSTATUS_P3P_HEADER = 44

BINDSTATUS_SESSION_COOKIE_RECEIVED = 45

BINDSTATUS_PERSISTENT_COOKIE_RECEIVED = 46

BINDSTATUS_SESSION_COOKIES_ALLOWED = 47

BINDSTATUS_CACHECONTROL = 48

BINDSTATUS_CONTENTDISPOSITIONFILENAME = 49

BINDSTATUS_MIMETEXTPLAINMISMATCH = 50

BINDSTATUS_PUBLISHERAVAILABLE = 51

BINDSTATUS_DISPLAYNAMEAVAILABLE = 52

BINDSTATUS_SSLUX_NAVBLOCKED = 53

BINDSTATUS_SERVER_MIMETYPEAVAILABLE = 54

BINDSTATUS_SNIFFED_CLASSIDAVAILABLE = 55

BINDSTATUS_64BIT_PROGRESS = 56

BINDSTATUS_LAST = 56

BINDSTATUS_RESERVED_0 = 57

BINDSTATUS_RESERVED_1 = 58

BINDSTATUS_RESERVED_2 = 59

BINDSTATUS_RESERVED_3 = 60

BINDSTATUS_RESERVED_4 = 61

BINDSTATUS_RESERVED_5 = 62

BINDSTATUS_RESERVED_6 = 63

BINDSTATUS_RESERVED_7 = 64

BINDSTATUS_RESERVED_8 = 65

BINDSTATUS_RESERVED_9 = 66

BINDSTATUS_RESERVED_A = 67

BINDSTATUS_RESERVED_B = 68

BINDSTATUS_RESERVED_C = 69

BINDSTATUS_RESERVED_D = 70

BINDSTATUS_RESERVED_E = 71

BINDSTATUS_RESERVED_F = 72

BINDSTATUS_RESERVED_10 = 73

BINDSTATUS_RESERVED_11 = 74

BINDSTATUS_RESERVED_12 = 75

BINDSTATUS_RESERVED_13 = 76

BINDSTATUS_RESERVED_14 = 77

BINDSTATUS_LAST_PRIVATE = 77

end
enum BINDF2 : Int32
BINDF2_DISABLEBASICOVERHTTP = 1

BINDF2_DISABLEAUTOCOOKIEHANDLING = 2

BINDF2_READ_DATA_GREATER_THAN_4GB = 4

BINDF2_DISABLE_HTTP_REDIRECT_XSECURITYID = 8

BINDF2_SETDOWNLOADMODE = 32

BINDF2_DISABLE_HTTP_REDIRECT_CACHING = 64

BINDF2_KEEP_CALLBACK_MODULE_LOADED = 128

BINDF2_ALLOW_PROXY_CRED_PROMPT = 256

BINDF2_RESERVED_17 = 512

BINDF2_RESERVED_16 = 1024

BINDF2_RESERVED_15 = 2048

BINDF2_RESERVED_14 = 4096

BINDF2_RESERVED_13 = 8192

BINDF2_RESERVED_12 = 16384

BINDF2_RESERVED_11 = 32768

BINDF2_RESERVED_10 = 65536

BINDF2_RESERVED_F = 131072

BINDF2_RESERVED_E = 262144

BINDF2_RESERVED_D = 524288

BINDF2_RESERVED_C = 1048576

BINDF2_RESERVED_B = 2097152

BINDF2_RESERVED_A = 4194304

BINDF2_RESERVED_9 = 8388608

BINDF2_RESERVED_8 = 16777216

BINDF2_RESERVED_7 = 33554432

BINDF2_RESERVED_6 = 67108864

BINDF2_RESERVED_5 = 134217728

BINDF2_RESERVED_4 = 268435456

BINDF2_RESERVED_3 = 536870912

BINDF2_RESERVED_2 = 1073741824

BINDF2_RESERVED_1 = -2147483648

end
enum AUTHENTICATEF : Int32
AUTHENTICATEF_PROXY = 1

AUTHENTICATEF_BASIC = 2

AUTHENTICATEF_HTTP = 4

end
enum CIP_STATUS : Int32
CIP_DISK_FULL = 0

CIP_ACCESS_DENIED = 1

CIP_NEWER_VERSION_EXISTS = 2

CIP_OLDER_VERSION_EXISTS = 3

CIP_NAME_CONFLICT = 4

CIP_TRUST_VERIFICATION_COMPONENT_MISSING = 5

CIP_EXE_SELF_REGISTERATION_TIMEOUT = 6

CIP_UNSAFE_TO_ABORT = 7

CIP_NEED_REBOOT = 8

CIP_NEED_REBOOT_UI_PERMISSION = 9

end
enum Uri_HOST_TYPE : Int32
Uri_HOST_UNKNOWN = 0

Uri_HOST_DNS = 1

Uri_HOST_IPV4 = 2

Uri_HOST_IPV6 = 3

Uri_HOST_IDN = 4

end
enum BINDSTRING : Int32
BINDSTRING_HEADERS = 1

BINDSTRING_ACCEPT_MIMES = 2

BINDSTRING_EXTRA_URL = 3

BINDSTRING_LANGUAGE = 4

BINDSTRING_USERNAME = 5

BINDSTRING_PASSWORD = 6

BINDSTRING_UA_PIXELS = 7

BINDSTRING_UA_COLOR = 8

BINDSTRING_OS = 9

BINDSTRING_USER_AGENT = 10

BINDSTRING_ACCEPT_ENCODINGS = 11

BINDSTRING_POST_COOKIE = 12

BINDSTRING_POST_DATA_MIME = 13

BINDSTRING_URL = 14

BINDSTRING_IID = 15

BINDSTRING_FLAG_BIND_TO_OBJECT = 16

BINDSTRING_PTR_BIND_CONTEXT = 17

BINDSTRING_XDR_ORIGIN = 18

BINDSTRING_DOWNLOADPATH = 19

BINDSTRING_ROOTDOC_URL = 20

BINDSTRING_INITIAL_FILENAME = 21

BINDSTRING_PROXY_USERNAME = 22

BINDSTRING_PROXY_PASSWORD = 23

BINDSTRING_ENTERPRISE_ID = 24

BINDSTRING_DOC_URL = 25

BINDSTRING_SAMESITE_COOKIE_LEVEL = 26

end
enum PI_FLAGS : Int32
PI_PARSE_URL = 1

PI_FILTER_MODE = 2

PI_FORCE_ASYNC = 4

PI_USE_WORKERTHREAD = 8

PI_MIMEVERIFICATION = 16

PI_CLSIDLOOKUP = 32

PI_DATAPROGRESS = 64

PI_SYNCHRONOUS = 128

PI_APARTMENTTHREADED = 256

PI_CLASSINSTALL = 512

PI_PASSONBINDCTX = 8192

PI_NOMIMEHANDLER = 32768

PI_LOADAPPDIRECT = 16384

PD_FORCE_SWITCH = 65536

PI_PREFERDEFAULTHANDLER = 131072

end
struct PROTOCOLDATA
  grfFlags : LibC::UInt32
  dwState : LibC::UInt32
  pData : LibC::Void*
  cbData : LibC::UInt32
end
struct StartParam
  iid : LibC::Guid
  pIBindCtx : IBindCtx
  pItf : IUnknown
end
enum OIBDG_FLAGS : Int32
OIBDG_APARTMENTTHREADED = 256

OIBDG_DATAONLY = 4096

end
enum PARSEACTION : Int32
PARSE_CANONICALIZE = 1

PARSE_FRIENDLY = 2

PARSE_SECURITY_URL = 3

PARSE_ROOTDOCUMENT = 4

PARSE_DOCUMENT = 5

PARSE_ANCHOR = 6

PARSE_ENCODE_IS_UNESCAPE = 7

PARSE_DECODE_IS_ESCAPE = 8

PARSE_PATH_FROM_URL = 9

PARSE_URL_FROM_PATH = 10

PARSE_MIME = 11

PARSE_SERVER = 12

PARSE_SCHEMA = 13

PARSE_SITE = 14

PARSE_DOMAIN = 15

PARSE_LOCATION = 16

PARSE_SECURITY_DOMAIN = 17

PARSE_ESCAPE = 18

PARSE_UNESCAPE = 19

end
enum PSUACTION : Int32
PSU_DEFAULT = 1

PSU_SECURITY_URL_ONLY = 2

end
enum QUERYOPTION : Int32
QUERY_EXPIRATION_DATE = 1

QUERY_TIME_OF_LAST_CHANGE = 2

QUERY_CONTENT_ENCODING = 3

QUERY_CONTENT_TYPE = 4

QUERY_REFRESH = 5

QUERY_RECOMBINE = 6

QUERY_CAN_NAVIGATE = 7

QUERY_USES_NETWORK = 8

QUERY_IS_CACHED = 9

QUERY_IS_INSTALLEDENTRY = 10

QUERY_IS_CACHED_OR_MAPPED = 11

QUERY_USES_CACHE = 12

QUERY_IS_SECURE = 13

QUERY_IS_SAFE = 14

QUERY_USES_HISTORYFOLDER = 15

QUERY_IS_CACHED_AND_USABLE_OFFLINE = 16

end
enum INTERNETFEATURELIST : Int32
FEATURE_OBJECT_CACHING = 0

FEATURE_ZONE_ELEVATION = 1

FEATURE_MIME_HANDLING = 2

FEATURE_MIME_SNIFFING = 3

FEATURE_WINDOW_RESTRICTIONS = 4

FEATURE_WEBOC_POPUPMANAGEMENT = 5

FEATURE_BEHAVIORS = 6

FEATURE_DISABLE_MK_PROTOCOL = 7

FEATURE_LOCALMACHINE_LOCKDOWN = 8

FEATURE_SECURITYBAND = 9

FEATURE_RESTRICT_ACTIVEXINSTALL = 10

FEATURE_VALIDATE_NAVIGATE_URL = 11

FEATURE_RESTRICT_FILEDOWNLOAD = 12

FEATURE_ADDON_MANAGEMENT = 13

FEATURE_PROTOCOL_LOCKDOWN = 14

FEATURE_HTTP_USERNAME_PASSWORD_DISABLE = 15

FEATURE_SAFE_BINDTOOBJECT = 16

FEATURE_UNC_SAVEDFILECHECK = 17

FEATURE_GET_URL_DOM_FILEPATH_UNENCODED = 18

FEATURE_TABBED_BROWSING = 19

FEATURE_SSLUX = 20

FEATURE_DISABLE_NAVIGATION_SOUNDS = 21

FEATURE_DISABLE_LEGACY_COMPRESSION = 22

FEATURE_FORCE_ADDR_AND_STATUS = 23

FEATURE_XMLHTTP = 24

FEATURE_DISABLE_TELNET_PROTOCOL = 25

FEATURE_FEEDS = 26

FEATURE_BLOCK_INPUT_PROMPTS = 27

FEATURE_ENTRY_COUNT = 28

end
enum PUAF : Int32
PUAF_DEFAULT = 0

PUAF_NOUI = 1

PUAF_ISFILE = 2

PUAF_WARN_IF_DENIED = 4

PUAF_FORCEUI_FOREGROUND = 8

PUAF_CHECK_TIFS = 16

PUAF_DONTCHECKBOXINDIALOG = 32

PUAF_TRUSTED = 64

PUAF_ACCEPT_WILDCARD_SCHEME = 128

PUAF_ENFORCERESTRICTED = 256

PUAF_NOSAVEDFILECHECK = 512

PUAF_REQUIRESAVEDFILECHECK = 1024

PUAF_DONT_USE_CACHE = 4096

PUAF_RESERVED1 = 8192

PUAF_RESERVED2 = 16384

PUAF_LMZ_UNLOCKED = 65536

PUAF_LMZ_LOCKED = 131072

PUAF_DEFAULTZONEPOL = 262144

PUAF_NPL_USE_LOCKED_IF_RESTRICTED = 524288

PUAF_NOUIIFLOCKED = 1048576

PUAF_DRAGPROTOCOLCHECK = 2097152

end
enum PUAFOUT : Int32
PUAFOUT_DEFAULT = 0

PUAFOUT_ISLOCKZONEPOLICY = 1

end
enum SZM_FLAGS : Int32
SZM_CREATE = 0

SZM_DELETE = 1

end
enum URLZONE : Int32
URLZONE_INVALID = -1

URLZONE_PREDEFINED_MIN = 0

URLZONE_LOCAL_MACHINE = 0

URLZONE_INTRANET = 1

URLZONE_TRUSTED = 2

URLZONE_INTERNET = 3

URLZONE_UNTRUSTED = 4

URLZONE_PREDEFINED_MAX = 999

URLZONE_USER_MIN = 1000

URLZONE_USER_MAX = 10000

end
enum URLTEMPLATE : Int32
URLTEMPLATE_CUSTOM = 0

URLTEMPLATE_PREDEFINED_MIN = 65536

URLTEMPLATE_LOW = 65536

URLTEMPLATE_MEDLOW = 66816

URLTEMPLATE_MEDIUM = 69632

URLTEMPLATE_MEDHIGH = 70912

URLTEMPLATE_HIGH = 73728

URLTEMPLATE_PREDEFINED_MAX = 131072

end
enum INET_ZONE_MANAGER_CONSTANTS : Int32
MAX_ZONE_PATH = 260

MAX_ZONE_DESCRIPTION = 200

end
enum ZAFLAGS : Int32
ZAFLAGS_CUSTOM_EDIT = 1

ZAFLAGS_ADD_SITES = 2

ZAFLAGS_REQUIRE_VERIFICATION = 4

ZAFLAGS_INCLUDE_PROXY_OVERRIDE = 8

ZAFLAGS_INCLUDE_INTRANET_SITES = 16

ZAFLAGS_NO_UI = 32

ZAFLAGS_SUPPORTS_VERIFICATION = 64

ZAFLAGS_UNC_AS_INTRANET = 128

ZAFLAGS_DETECT_INTRANET = 256

ZAFLAGS_USE_LOCKED_ZONES = 65536

ZAFLAGS_VERIFY_TEMPLATE_SETTINGS = 131072

ZAFLAGS_NO_CACHE = 262144

end
struct ZONEATTRIBUTES
  cbSize : LibC::UInt32
  szDisplayName : Array(LibC::Char)
  szDescription : Array(LibC::Char)
  szIconPath : Array(LibC::Char)
  dwTemplateMinLevel : LibC::UInt32
  dwTemplateRecommended : LibC::UInt32
  dwTemplateCurrentLevel : LibC::UInt32
  dwFlags : LibC::UInt32
end
enum URLZONEREG : Int32
URLZONEREG_DEFAULT = 0

URLZONEREG_HKLM = 1

URLZONEREG_HKCU = 2

end
struct CODEBASEHOLD
  cbSize : LibC::UInt32
  szDistUnit : PWSTR
  szCodeBase : PWSTR
  dwVersionMS : LibC::UInt32
  dwVersionLS : LibC::UInt32
  dwStyle : LibC::UInt32
end
struct SOFTDISTINFO
  cbSize : LibC::UInt32
  dwFlags : LibC::UInt32
  dwAdState : LibC::UInt32
  szTitle : PWSTR
  szAbstract : PWSTR
  szHREF : PWSTR
  dwInstalledVersionMS : LibC::UInt32
  dwInstalledVersionLS : LibC::UInt32
  dwUpdateVersionMS : LibC::UInt32
  dwUpdateVersionLS : LibC::UInt32
  dwAdvertisedVersionMS : LibC::UInt32
  dwAdvertisedVersionLS : LibC::UInt32
  dwReserved : LibC::UInt32
end
struct PROTOCOLFILTERDATA
  cbSize : LibC::UInt32
  pProtocolSink : IInternetProtocolSink
  pProtocol : IInternetProtocol
  pUnk : IUnknown
  dwFilterFlags : LibC::UInt32
end
struct DATAINFO
  ulTotalSize : LibC::UInt32
  ulavrPacketSize : LibC::UInt32
  ulConnectSpeed : LibC::UInt32
  ulProcessorSpeed : LibC::UInt32
end
struct HIT_LOGGING_INFO
  dwStructSize : LibC::UInt32
  lpszLoggedUrlName : PSTR
  startTime : SYSTEMTIME
  endTime : SYSTEMTIME
  lpszExtendedInfo : PSTR
end
struct CONFIRMSAFETY
  clsid : LibC::Guid
  pUnk : IUnknown
  dwFlags : LibC::UInt32
end
enum BINDHANDLETYPES : Int32
BINDHANDLETYPES_APPCACHE = 0

BINDHANDLETYPES_DEPENDENCY = 1

BINDHANDLETYPES_COUNT = 2

end
struct PROTOCOL_ARGUMENT
  szMethod : PWSTR
  szTargetUrl : PWSTR
end
fun createURLMoniker(pMkCtx : IMoniker, szURL : PWSTR, ppmk : IMoniker*) : HRESULT
fun createURLMonikerEx(pMkCtx : IMoniker, szURL : PWSTR, ppmk : IMoniker*, dwFlags : LibC::UInt32) : HRESULT
fun getClassURL(szURL : PWSTR, pClsID : LibC::Guid*) : HRESULT
fun createAsyncBindCtx(reserved : LibC::UInt32, pBSCb : IBindStatusCallback, pEFetc : IEnumFORMATETC, ppBC : IBindCtx*) : HRESULT
fun createURLMonikerEx2(pMkCtx : IMoniker, pUri : IUri, ppmk : IMoniker*, dwFlags : LibC::UInt32) : HRESULT
fun createAsyncBindCtxEx(pbc : IBindCtx, dwOptions : LibC::UInt32, pBSCb : IBindStatusCallback, pEnum : IEnumFORMATETC, ppBC : IBindCtx*, reserved : LibC::UInt32) : HRESULT
fun mkParseDisplayNameEx(pbc : IBindCtx, szDisplayName : PWSTR, pchEaten : LibC::UInt32*, ppmk : IMoniker*) : HRESULT
fun registerBindStatusCallback(pBC : IBindCtx, pBSCb : IBindStatusCallback, ppBSCBPrev : IBindStatusCallback*, dwReserved : LibC::UInt32) : HRESULT
fun revokeBindStatusCallback(pBC : IBindCtx, pBSCb : IBindStatusCallback) : HRESULT
fun getClassFileOrMime(pBC : IBindCtx, szFilename : PWSTR, pBuffer : LibC::Void*, cbSize : LibC::UInt32, szMime : PWSTR, dwReserved : LibC::UInt32, pclsid : LibC::Guid*) : HRESULT
fun isValidURL(pBC : IBindCtx, szURL : PWSTR, dwReserved : LibC::UInt32) : HRESULT
fun coGetClassObjectFromURL(rCLASSID : LibC::Guid*, szCODE : PWSTR, dwFileVersionMS : LibC::UInt32, dwFileVersionLS : LibC::UInt32, szTYPE : PWSTR, pBindCtx : IBindCtx, dwClsContext : CLSCTX, pvReserved : LibC::Void*, riid : LibC::Guid*, ppv : LibC::Void**) : HRESULT
fun iEInstallScope(pdwScope : LibC::UInt32*) : HRESULT
fun faultInIEFeature(hWnd : HWND, pClassSpec : UCLSSPEC*, pQuery : QUERYCONTEXT*, dwFlags : LibC::UInt32) : HRESULT
fun getComponentIDFromCLSSPEC(pClassspec : UCLSSPEC*, ppszComponentID : PSTR*) : HRESULT
fun isAsyncMoniker(pmk : IMoniker) : HRESULT
fun registerMediaTypes(ctypes : LibC::UInt32, rgszTypes : , rgcfTypes : ) : HRESULT
fun findMediaType(rgszTypes : PSTR, rgcfTypes : LibC::UInt16*) : HRESULT
fun createFormatEnumerator(cfmtetc : LibC::UInt32, rgfmtetc : , ppenumfmtetc : IEnumFORMATETC*) : HRESULT
fun registerFormatEnumerator(pBC : IBindCtx, pEFetc : IEnumFORMATETC, reserved : LibC::UInt32) : HRESULT
fun revokeFormatEnumerator(pBC : IBindCtx, pEFetc : IEnumFORMATETC) : HRESULT
fun registerMediaTypeClass(pBC : IBindCtx, ctypes : LibC::UInt32, rgszTypes : , rgclsID : , reserved : LibC::UInt32) : HRESULT
fun findMediaTypeClass(pBC : IBindCtx, szType : PSTR, pclsID : LibC::Guid*, reserved : LibC::UInt32) : HRESULT
fun urlMkSetSessionOption(dwOption : LibC::UInt32, pBuffer : LibC::Void*, dwBufferLength : LibC::UInt32, dwReserved : LibC::UInt32) : HRESULT
fun urlMkGetSessionOption(dwOption : LibC::UInt32, pBuffer : LibC::Void*, dwBufferLength : LibC::UInt32, pdwBufferLengthOut : LibC::UInt32*, dwReserved : LibC::UInt32) : HRESULT
fun findMimeFromData(pBC : IBindCtx, pwzUrl : PWSTR, pBuffer : LibC::Void*, cbSize : LibC::UInt32, pwzMimeProposed : PWSTR, dwMimeFlags : LibC::UInt32, ppwzMimeOut : PWSTR*, dwReserved : LibC::UInt32) : HRESULT
fun obtainUserAgentString(dwOption : LibC::UInt32, pszUAOut : , cbSize : LibC::UInt32*) : HRESULT
fun compareSecurityIds(pbSecurityId1 : , dwLen1 : LibC::UInt32, pbSecurityId2 : , dwLen2 : LibC::UInt32, dwReserved : LibC::UInt32) : HRESULT
fun compatFlagsFromClsid(pclsid : LibC::Guid*, pdwCompatFlags : LibC::UInt32*, pdwMiscStatusFlags : LibC::UInt32*) : HRESULT
fun setAccessForIEAppContainer(hObject : HANDLE, ieObjectType : IEObjectType, dwAccessMask : LibC::UInt32) : HRESULT
fun hlinkSimpleNavigateToString(szTarget : PWSTR, szLocation : PWSTR, szTargetFrameName : PWSTR, pUnk : IUnknown, pbc : IBindCtx, param5 : IBindStatusCallback, grfHLNF : LibC::UInt32, dwReserved : LibC::UInt32) : HRESULT
fun hlinkSimpleNavigateToMoniker(pmkTarget : IMoniker, szLocation : PWSTR, szTargetFrameName : PWSTR, pUnk : IUnknown, pbc : IBindCtx, param5 : IBindStatusCallback, grfHLNF : LibC::UInt32, dwReserved : LibC::UInt32) : HRESULT
fun uRLOpenStreamA(param0 : IUnknown, param1 : PSTR, param2 : LibC::UInt32, param3 : IBindStatusCallback) : HRESULT
fun uRLOpenStreamW(param0 : IUnknown, param1 : PWSTR, param2 : LibC::UInt32, param3 : IBindStatusCallback) : HRESULT
fun uRLOpenPullStreamA(param0 : IUnknown, param1 : PSTR, param2 : LibC::UInt32, param3 : IBindStatusCallback) : HRESULT
fun uRLOpenPullStreamW(param0 : IUnknown, param1 : PWSTR, param2 : LibC::UInt32, param3 : IBindStatusCallback) : HRESULT
fun uRLDownloadToFileA(param0 : IUnknown, param1 : PSTR, param2 : PSTR, param3 : LibC::UInt32, param4 : IBindStatusCallback) : HRESULT
fun uRLDownloadToFileW(param0 : IUnknown, param1 : PWSTR, param2 : PWSTR, param3 : LibC::UInt32, param4 : IBindStatusCallback) : HRESULT
fun uRLDownloadToCacheFileA(param0 : IUnknown, param1 : PSTR, param2 : , cchFileName : LibC::UInt32, param4 : LibC::UInt32, param5 : IBindStatusCallback) : HRESULT
fun uRLDownloadToCacheFileW(param0 : IUnknown, param1 : PWSTR, param2 : , cchFileName : LibC::UInt32, param4 : LibC::UInt32, param5 : IBindStatusCallback) : HRESULT
fun uRLOpenBlockingStreamA(param0 : IUnknown, param1 : PSTR, param2 : IStream*, param3 : LibC::UInt32, param4 : IBindStatusCallback) : HRESULT
fun uRLOpenBlockingStreamW(param0 : IUnknown, param1 : PWSTR, param2 : IStream*, param3 : LibC::UInt32, param4 : IBindStatusCallback) : HRESULT
fun hlinkGoBack(pUnk : IUnknown) : HRESULT
fun hlinkGoForward(pUnk : IUnknown) : HRESULT
fun hlinkNavigateString(pUnk : IUnknown, szTarget : PWSTR) : HRESULT
fun hlinkNavigateMoniker(pUnk : IUnknown, pmkTarget : IMoniker) : HRESULT
fun coInternetParseUrl(pwzUrl : PWSTR, parseAction : PARSEACTION, dwFlags : LibC::UInt32, pszResult : , cchResult : LibC::UInt32, pcchResult : LibC::UInt32*, dwReserved : LibC::UInt32) : HRESULT
fun coInternetParseIUri(pIUri : IUri, parseAction : PARSEACTION, dwFlags : LibC::UInt32, pwzResult : , cchResult : LibC::UInt32, pcchResult : LibC::UInt32*, dwReserved : LibC::UIint*) : HRESULT
fun coInternetCombineUrl(pwzBaseUrl : PWSTR, pwzRelativeUrl : PWSTR, dwCombineFlags : LibC::UInt32, pszResult : , cchResult : LibC::UInt32, pcchResult : LibC::UInt32*, dwReserved : LibC::UInt32) : HRESULT
fun coInternetCombineUrlEx(pBaseUri : IUri, pwzRelativeUrl : PWSTR, dwCombineFlags : LibC::UInt32, ppCombinedUri : IUri*, dwReserved : LibC::UIint*) : HRESULT
fun coInternetCombineIUri(pBaseUri : IUri, pRelativeUri : IUri, dwCombineFlags : LibC::UInt32, ppCombinedUri : IUri*, dwReserved : LibC::UIint*) : HRESULT
fun coInternetCompareUrl(pwzUrl1 : PWSTR, pwzUrl2 : PWSTR, dwFlags : LibC::UInt32) : HRESULT
fun coInternetGetProtocolFlags(pwzUrl : PWSTR, pdwFlags : LibC::UInt32*, dwReserved : LibC::UInt32) : HRESULT
fun coInternetQueryInfo(pwzUrl : PWSTR, queryOptions : QUERYOPTION, dwQueryFlags : LibC::UInt32, pvBuffer : LibC::Void*, cbBuffer : LibC::UInt32, pcbBuffer : LibC::UInt32*, dwReserved : LibC::UInt32) : HRESULT
fun coInternetGetSession(dwSessionMode : LibC::UInt32, ppIInternetSession : IInternetSession*, dwReserved : LibC::UInt32) : HRESULT
fun coInternetGetSecurityUrl(pwszUrl : PWSTR, ppwszSecUrl : PWSTR*, psuAction : PSUACTION, dwReserved : LibC::UInt32) : HRESULT
fun coInternetGetSecurityUrlEx(pUri : IUri, ppSecUri : IUri*, psuAction : PSUACTION, dwReserved : LibC::UIint*) : HRESULT
fun coInternetSetFeatureEnabled(featureEntry : INTERNETFEATURELIST, dwFlags : LibC::UInt32, fEnable : BOOL) : HRESULT
fun coInternetIsFeatureEnabled(featureEntry : INTERNETFEATURELIST, dwFlags : LibC::UInt32) : HRESULT
fun coInternetIsFeatureEnabledForUrl(featureEntry : INTERNETFEATURELIST, dwFlags : LibC::UInt32, szURL : PWSTR, pSecMgr : IInternetSecurityManager) : HRESULT
fun coInternetIsFeatureEnabledForIUri(featureEntry : INTERNETFEATURELIST, dwFlags : LibC::UInt32, pIUri : IUri, pSecMgr : IInternetSecurityManagerEx2) : HRESULT
fun coInternetIsFeatureZoneElevationEnabled(szFromURL : PWSTR, szToURL : PWSTR, pSecMgr : IInternetSecurityManager, dwFlags : LibC::UInt32) : HRESULT
fun copyStgMedium(pcstgmedSrc : STGMEDIUM*, pstgmedDest : STGMEDIUM*) : HRESULT
fun copyBindInfo(pcbiSrc : BINDINFO*, pbiDest : BINDINFO*) : HRESULT
fun releaseBindInfo(pbindinfo : BINDINFO*) : LibC::Void
fun iEGetUserPrivateNamespaceName() : PWSTR
fun coInternetCreateSecurityManager(pSP : IServiceProvider, ppSM : IInternetSecurityManager*, dwReserved : LibC::UInt32) : HRESULT
fun coInternetCreateZoneManager(pSP : IServiceProvider, ppZM : IInternetZoneManager*, dwReserved : LibC::UInt32) : HRESULT
fun getSoftwareUpdateInfo(szDistUnit : PWSTR, psdi : SOFTDISTINFO*) : HRESULT
fun setSoftwareUpdateAdvertisementState(szDistUnit : PWSTR, dwAdState : LibC::UInt32, dwAdvertisedVersionMS : LibC::UInt32, dwAdvertisedVersionLS : LibC::UInt32) : HRESULT
fun isLoggingEnabledA(pszUrl : PSTR) : BOOL
fun isLoggingEnabledW(pwszUrl : PWSTR) : BOOL
fun writeHitLogging(lpLogginginfo : HIT_LOGGING_INFO*) : BOOL

  end
