  @[Link("System.Ole")]
  lib LibSystemOle
    CTL_E_ILLEGALFUNCTIONCALL = -2146828283
CONNECT_E_FIRST = -2147220992
SELFREG_E_FIRST = -2147220992
PERPROP_E_FIRST = -2147220992
OLECMDERR_E_FIRST = -2147221248
OLECMDERR_E_DISABLED = -2147221247
OLECMDERR_E_NOHELP = -2147221246
OLECMDERR_E_CANCELED = -2147221245
OLECMDERR_E_UNKNOWNGROUP = -2147221244
CONNECT_E_NOCONNECTION = -2147220992
CONNECT_E_ADVISELIMIT = -2147220991
CONNECT_E_CANNOTCONNECT = -2147220990
CONNECT_E_OVERRIDDEN = -2147220989
SELFREG_E_TYPELIB = -2147220992
SELFREG_E_CLASS = -2147220991
PERPROP_E_NOPAGEAVAILABLE = -2147220992
CLSID_CFontPropPage = "0be35200-8f91-11ce-9de3-00aa004bb851"
CLSID_CColorPropPage = "0be35201-8f91-11ce-9de3-00aa004bb851"
CLSID_CPicturePropPage = "0be35202-8f91-11ce-9de3-00aa004bb851"
CLSID_PersistPropset = "fb8f0821-0164-101b-84ed-08002b2ec713"
CLSID_ConvertVBX = "fb8f0822-0164-101b-84ed-08002b2ec713"
CLSID_StdFont = "0be35203-8f91-11ce-9de3-00aa004bb851"
CLSID_StdPicture = "0be35204-8f91-11ce-9de3-00aa004bb851"
GUID_HIMETRIC = "66504300-be0f-101a-8bbb-00aa00300cab"
GUID_COLOR = "66504301-be0f-101a-8bbb-00aa00300cab"
GUID_XPOSPIXEL = "66504302-be0f-101a-8bbb-00aa00300cab"
GUID_YPOSPIXEL = "66504303-be0f-101a-8bbb-00aa00300cab"
GUID_XSIZEPIXEL = "66504304-be0f-101a-8bbb-00aa00300cab"
GUID_YSIZEPIXEL = "66504305-be0f-101a-8bbb-00aa00300cab"
GUID_XPOS = "66504306-be0f-101a-8bbb-00aa00300cab"
GUID_YPOS = "66504307-be0f-101a-8bbb-00aa00300cab"
GUID_XSIZE = "66504308-be0f-101a-8bbb-00aa00300cab"
GUID_YSIZE = "66504309-be0f-101a-8bbb-00aa00300cab"
GUID_TRISTATE = "6650430a-be0f-101a-8bbb-00aa00300cab"
GUID_OPTIONVALUEEXCLUSIVE = "6650430b-be0f-101a-8bbb-00aa00300cab"
GUID_CHECKVALUEEXCLUSIVE = "6650430c-be0f-101a-8bbb-00aa00300cab"
GUID_FONTNAME = "6650430d-be0f-101a-8bbb-00aa00300cab"
GUID_FONTSIZE = "6650430e-be0f-101a-8bbb-00aa00300cab"
GUID_FONTBOLD = "6650430f-be0f-101a-8bbb-00aa00300cab"
GUID_FONTITALIC = "66504310-be0f-101a-8bbb-00aa00300cab"
GUID_FONTUNDERSCORE = "66504311-be0f-101a-8bbb-00aa00300cab"
GUID_FONTSTRIKETHROUGH = "66504312-be0f-101a-8bbb-00aa00300cab"
GUID_HANDLE = "66504313-be0f-101a-8bbb-00aa00300cab"
PICTYPE_UNINITIALIZED = -1
PICTYPE_NONE = 0
PICTYPE_BITMAP = 1
PICTYPE_METAFILE = 2
PICTYPE_ICON = 3
PICTYPE_ENHMETAFILE = 4
CONNECT_E_LAST = -2147220977
CONNECT_S_FIRST = 262656
CONNECT_S_LAST = 262671
SELFREG_E_LAST = -2147220977
SELFREG_S_FIRST = 262656
SELFREG_S_LAST = 262671
PERPROP_E_LAST = -2147220977
PERPROP_S_FIRST = 262656
PERPROP_S_LAST = 262671
OLEIVERB_PROPERTIES = -7
VT_STREAMED_PROPSET = 73
VT_STORED_PROPSET = 74
VT_BLOB_PROPSET = 75
VT_VERBOSE_ENUM = 76
OCM__BASE = 8192
LP_DEFAULT = 0
LP_MONOCHROME = 1
LP_VGACOLOR = 2
LP_COLOR = 4
DISPID_AUTOSIZE = -500
DISPID_BACKCOLOR = -501
DISPID_BACKSTYLE = -502
DISPID_BORDERCOLOR = -503
DISPID_BORDERSTYLE = -504
DISPID_BORDERWIDTH = -505
DISPID_DRAWMODE = -507
DISPID_DRAWSTYLE = -508
DISPID_DRAWWIDTH = -509
DISPID_FILLCOLOR = -510
DISPID_FILLSTYLE = -511
DISPID_FONT = -512
DISPID_FORECOLOR = -513
DISPID_ENABLED = -514
DISPID_HWND = -515
DISPID_TABSTOP = -516
DISPID_TEXT = -517
DISPID_CAPTION = -518
DISPID_BORDERVISIBLE = -519
DISPID_APPEARANCE = -520
DISPID_MOUSEPOINTER = -521
DISPID_MOUSEICON = -522
DISPID_PICTURE = -523
DISPID_VALID = -524
DISPID_READYSTATE = -525
DISPID_LISTINDEX = -526
DISPID_SELECTED = -527
DISPID_LIST = -528
DISPID_COLUMN = -529
DISPID_LISTCOUNT = -531
DISPID_MULTISELECT = -532
DISPID_MAXLENGTH = -533
DISPID_PASSWORDCHAR = -534
DISPID_SCROLLBARS = -535
DISPID_WORDWRAP = -536
DISPID_MULTILINE = -537
DISPID_NUMBEROFROWS = -538
DISPID_NUMBEROFCOLUMNS = -539
DISPID_DISPLAYSTYLE = -540
DISPID_GROUPNAME = -541
DISPID_IMEMODE = -542
DISPID_ACCELERATOR = -543
DISPID_ENTERKEYBEHAVIOR = -544
DISPID_TABKEYBEHAVIOR = -545
DISPID_SELTEXT = -546
DISPID_SELSTART = -547
DISPID_SELLENGTH = -548
DISPID_REFRESH = -550
DISPID_DOCLICK = -551
DISPID_ABOUTBOX = -552
DISPID_ADDITEM = -553
DISPID_CLEAR = -554
DISPID_REMOVEITEM = -555
DISPID_CLICK = -600
DISPID_DBLCLICK = -601
DISPID_KEYDOWN = -602
DISPID_KEYPRESS = -603
DISPID_KEYUP = -604
DISPID_MOUSEDOWN = -605
DISPID_MOUSEMOVE = -606
DISPID_MOUSEUP = -607
DISPID_ERROREVENT = -608
DISPID_READYSTATECHANGE = -609
DISPID_CLICK_VALUE = -610
DISPID_RIGHTTOLEFT = -611
DISPID_TOPTOBOTTOM = -612
DISPID_THIS = -613
DISPID_AMBIENT_BACKCOLOR = -701
DISPID_AMBIENT_DISPLAYNAME = -702
DISPID_AMBIENT_FONT = -703
DISPID_AMBIENT_FORECOLOR = -704
DISPID_AMBIENT_LOCALEID = -705
DISPID_AMBIENT_MESSAGEREFLECT = -706
DISPID_AMBIENT_SCALEUNITS = -707
DISPID_AMBIENT_TEXTALIGN = -708
DISPID_AMBIENT_USERMODE = -709
DISPID_AMBIENT_UIDEAD = -710
DISPID_AMBIENT_SHOWGRABHANDLES = -711
DISPID_AMBIENT_SHOWHATCHING = -712
DISPID_AMBIENT_DISPLAYASDEFAULT = -713
DISPID_AMBIENT_SUPPORTSMNEMONICS = -714
DISPID_AMBIENT_AUTOCLIP = -715
DISPID_AMBIENT_APPEARANCE = -716
DISPID_AMBIENT_CODEPAGE = -725
DISPID_AMBIENT_PALETTE = -726
DISPID_AMBIENT_CHARSET = -727
DISPID_AMBIENT_TRANSFERPRIORITY = -728
DISPID_AMBIENT_RIGHTTOLEFT = -732
DISPID_AMBIENT_TOPTOBOTTOM = -733
DISPID_Name = -800
DISPID_Delete = -801
DISPID_Object = -802
DISPID_Parent = -803
DISPID_FONT_NAME = 0
DISPID_FONT_SIZE = 2
DISPID_FONT_BOLD = 3
DISPID_FONT_ITALIC = 4
DISPID_FONT_UNDER = 5
DISPID_FONT_STRIKE = 6
DISPID_FONT_WEIGHT = 7
DISPID_FONT_CHARSET = 8
DISPID_FONT_CHANGED = 9
DISPID_PICT_HANDLE = 0
DISPID_PICT_HPAL = 2
DISPID_PICT_TYPE = 3
DISPID_PICT_WIDTH = 4
DISPID_PICT_HEIGHT = 5
DISPID_PICT_RENDER = 6
GC_WCH_SIBLING = 1
TIFLAGS_EXTENDDISPATCHONLY = 1
OLECMDERR_E_NOTSUPPORTED = -2147221248
MSOCMDERR_E_FIRST = -2147221248
MSOCMDERR_E_NOTSUPPORTED = -2147221248
MSOCMDERR_E_DISABLED = -2147221247
MSOCMDERR_E_NOHELP = -2147221246
MSOCMDERR_E_CANCELED = -2147221245
MSOCMDERR_E_UNKNOWNGROUP = -2147221244
OLECMD_TASKDLGID_ONBEFOREUNLOAD = 1
OLECMDARGINDEX_SHOWPAGEACTIONMENU_HWND = 0
OLECMDARGINDEX_SHOWPAGEACTIONMENU_X = 1
OLECMDARGINDEX_SHOWPAGEACTIONMENU_Y = 2
OLECMDARGINDEX_ACTIVEXINSTALL_PUBLISHER = 0
OLECMDARGINDEX_ACTIVEXINSTALL_DISPLAYNAME = 1
OLECMDARGINDEX_ACTIVEXINSTALL_CLSID = 2
OLECMDARGINDEX_ACTIVEXINSTALL_INSTALLSCOPE = 3
OLECMDARGINDEX_ACTIVEXINSTALL_SOURCEURL = 4
INSTALL_SCOPE_INVALID = 0
INSTALL_SCOPE_MACHINE = 1
INSTALL_SCOPE_USER = 2
MK_ALT = 32
DROPEFFECT_NONE = 0
DROPEFFECT_COPY = 1
DROPEFFECT_MOVE = 2
DROPEFFECT_LINK = 4
DROPEFFECT_SCROLL = 2147483648
DD_DEFSCROLLINSET = 11
DD_DEFSCROLLDELAY = 50
DD_DEFSCROLLINTERVAL = 50
DD_DEFDRAGDELAY = 200
DD_DEFDRAGMINDIST = 2
OT_LINK = 1
OT_EMBEDDED = 2
OT_STATIC = 3
OLEVERB_PRIMARY = 0
OF_SET = 1
OF_GET = 2
OF_HANDLER = 4
WIN32 = 100
OLEIVERB_PRIMARY = 0
OLEIVERB_SHOW = -1
OLEIVERB_OPEN = -2
OLEIVERB_HIDE = -3
OLEIVERB_UIACTIVATE = -4
OLEIVERB_INPLACEACTIVATE = -5
OLEIVERB_DISCARDUNDOSTATE = -6
EMBDHLP_INPROC_HANDLER = 0
EMBDHLP_INPROC_SERVER = 1
EMBDHLP_CREATENOW = 0
EMBDHLP_DELAYCREATE = 65536
OLECREATE_LEAVERUNNING = 1
IDC_OLEUIHELP = 99
IDC_IO_CREATENEW = 2100
IDC_IO_CREATEFROMFILE = 2101
IDC_IO_LINKFILE = 2102
IDC_IO_OBJECTTYPELIST = 2103
IDC_IO_DISPLAYASICON = 2104
IDC_IO_CHANGEICON = 2105
IDC_IO_FILE = 2106
IDC_IO_FILEDISPLAY = 2107
IDC_IO_RESULTIMAGE = 2108
IDC_IO_RESULTTEXT = 2109
IDC_IO_ICONDISPLAY = 2110
IDC_IO_OBJECTTYPETEXT = 2111
IDC_IO_FILETEXT = 2112
IDC_IO_FILETYPE = 2113
IDC_IO_INSERTCONTROL = 2114
IDC_IO_ADDCONTROL = 2115
IDC_IO_CONTROLTYPELIST = 2116
IDC_PS_PASTE = 500
IDC_PS_PASTELINK = 501
IDC_PS_SOURCETEXT = 502
IDC_PS_PASTELIST = 503
IDC_PS_PASTELINKLIST = 504
IDC_PS_DISPLAYLIST = 505
IDC_PS_DISPLAYASICON = 506
IDC_PS_ICONDISPLAY = 507
IDC_PS_CHANGEICON = 508
IDC_PS_RESULTIMAGE = 509
IDC_PS_RESULTTEXT = 510
IDC_CI_GROUP = 120
IDC_CI_CURRENT = 121
IDC_CI_CURRENTICON = 122
IDC_CI_DEFAULT = 123
IDC_CI_DEFAULTICON = 124
IDC_CI_FROMFILE = 125
IDC_CI_FROMFILEEDIT = 126
IDC_CI_ICONLIST = 127
IDC_CI_LABEL = 128
IDC_CI_LABELEDIT = 129
IDC_CI_BROWSE = 130
IDC_CI_ICONDISPLAY = 131
IDC_CV_OBJECTTYPE = 150
IDC_CV_DISPLAYASICON = 152
IDC_CV_CHANGEICON = 153
IDC_CV_ACTIVATELIST = 154
IDC_CV_CONVERTTO = 155
IDC_CV_ACTIVATEAS = 156
IDC_CV_RESULTTEXT = 157
IDC_CV_CONVERTLIST = 158
IDC_CV_ICONDISPLAY = 165
IDC_EL_CHANGESOURCE = 201
IDC_EL_AUTOMATIC = 202
IDC_EL_CANCELLINK = 209
IDC_EL_UPDATENOW = 210
IDC_EL_OPENSOURCE = 211
IDC_EL_MANUAL = 212
IDC_EL_LINKSOURCE = 216
IDC_EL_LINKTYPE = 217
IDC_EL_LINKSLISTBOX = 206
IDC_EL_COL1 = 220
IDC_EL_COL2 = 221
IDC_EL_COL3 = 222
IDC_BZ_RETRY = 600
IDC_BZ_ICON = 601
IDC_BZ_MESSAGE1 = 602
IDC_BZ_SWITCHTO = 604
IDC_UL_METER = 1029
IDC_UL_STOP = 1030
IDC_UL_PERCENT = 1031
IDC_UL_PROGRESS = 1032
IDC_PU_LINKS = 900
IDC_PU_TEXT = 901
IDC_PU_CONVERT = 902
IDC_PU_ICON = 908
IDC_GP_OBJECTNAME = 1009
IDC_GP_OBJECTTYPE = 1010
IDC_GP_OBJECTSIZE = 1011
IDC_GP_CONVERT = 1013
IDC_GP_OBJECTICON = 1014
IDC_GP_OBJECTLOCATION = 1022
IDC_VP_PERCENT = 1000
IDC_VP_CHANGEICON = 1001
IDC_VP_EDITABLE = 1002
IDC_VP_ASICON = 1003
IDC_VP_RELATIVE = 1005
IDC_VP_SPIN = 1006
IDC_VP_SCALETXT = 1034
IDC_VP_ICONDISPLAY = 1021
IDC_VP_RESULTIMAGE = 1033
IDC_LP_OPENSOURCE = 1006
IDC_LP_UPDATENOW = 1007
IDC_LP_BREAKLINK = 1008
IDC_LP_LINKSOURCE = 1012
IDC_LP_CHANGESOURCE = 1015
IDC_LP_AUTOMATIC = 1016
IDC_LP_MANUAL = 1017
IDC_LP_DATE = 1018
IDC_LP_TIME = 1019
IDD_INSERTOBJECT = 1000
IDD_CHANGEICON = 1001
IDD_CONVERT = 1002
IDD_PASTESPECIAL = 1003
IDD_EDITLINKS = 1004
IDD_BUSY = 1006
IDD_UPDATELINKS = 1007
IDD_CHANGESOURCE = 1009
IDD_INSERTFILEBROWSE = 1010
IDD_CHANGEICONBROWSE = 1011
IDD_CONVERTONLY = 1012
IDD_CHANGESOURCE4 = 1013
IDD_GNRLPROPS = 1100
IDD_VIEWPROPS = 1101
IDD_LINKPROPS = 1102
IDD_CONVERT4 = 1103
IDD_CONVERTONLY4 = 1104
IDD_EDITLINKS4 = 1105
IDD_GNRLPROPS4 = 1106
IDD_LINKPROPS4 = 1107
IDD_PASTESPECIAL4 = 1108
IDD_CANNOTUPDATELINK = 1008
IDD_LINKSOURCEUNAVAILABLE = 1020
IDD_SERVERNOTFOUND = 1023
IDD_OUTOFMEMORY = 1024
IDD_SERVERNOTREGW = 1021
IDD_LINKTYPECHANGEDW = 1022
IDD_SERVERNOTREGA = 1025
IDD_LINKTYPECHANGEDA = 1026
IDD_SERVERNOTREG = 1021
IDD_LINKTYPECHANGED = 1022
ID_BROWSE_CHANGEICON = 1
ID_BROWSE_INSERTFILE = 2
ID_BROWSE_ADDCONTROL = 3
ID_BROWSE_CHANGESOURCE = 4
OLEUI_FALSE = 0
OLEUI_SUCCESS = 1
OLEUI_OK = 1
OLEUI_CANCEL = 2
OLEUI_ERR_STANDARDMIN = 100
OLEUI_ERR_OLEMEMALLOC = 100
OLEUI_ERR_STRUCTURENULL = 101
OLEUI_ERR_STRUCTUREINVALID = 102
OLEUI_ERR_CBSTRUCTINCORRECT = 103
OLEUI_ERR_HWNDOWNERINVALID = 104
OLEUI_ERR_LPSZCAPTIONINVALID = 105
OLEUI_ERR_LPFNHOOKINVALID = 106
OLEUI_ERR_HINSTANCEINVALID = 107
OLEUI_ERR_LPSZTEMPLATEINVALID = 108
OLEUI_ERR_HRESOURCEINVALID = 109
OLEUI_ERR_FINDTEMPLATEFAILURE = 110
OLEUI_ERR_LOADTEMPLATEFAILURE = 111
OLEUI_ERR_DIALOGFAILURE = 112
OLEUI_ERR_LOCALMEMALLOC = 113
OLEUI_ERR_GLOBALMEMALLOC = 114
OLEUI_ERR_LOADSTRING = 115
OLEUI_ERR_STANDARDMAX = 116
IOF_SHOWHELP = 1
IOF_SELECTCREATENEW = 2
IOF_SELECTCREATEFROMFILE = 4
IOF_CHECKLINK = 8
IOF_CHECKDISPLAYASICON = 16
IOF_CREATENEWOBJECT = 32
IOF_CREATEFILEOBJECT = 64
IOF_CREATELINKOBJECT = 128
IOF_DISABLELINK = 256
IOF_VERIFYSERVERSEXIST = 512
IOF_DISABLEDISPLAYASICON = 1024
IOF_HIDECHANGEICON = 2048
IOF_SHOWINSERTCONTROL = 4096
IOF_SELECTCREATECONTROL = 8192
OLEUI_IOERR_LPSZFILEINVALID = 116
OLEUI_IOERR_LPSZLABELINVALID = 117
OLEUI_IOERR_HICONINVALID = 118
OLEUI_IOERR_LPFORMATETCINVALID = 119
OLEUI_IOERR_PPVOBJINVALID = 120
OLEUI_IOERR_LPIOLECLIENTSITEINVALID = 121
OLEUI_IOERR_LPISTORAGEINVALID = 122
OLEUI_IOERR_SCODEHASERROR = 123
OLEUI_IOERR_LPCLSIDEXCLUDEINVALID = 124
OLEUI_IOERR_CCHFILEINVALID = 125
PS_MAXLINKTYPES = 8
PSF_SHOWHELP = 1
PSF_SELECTPASTE = 2
PSF_SELECTPASTELINK = 4
PSF_CHECKDISPLAYASICON = 8
PSF_DISABLEDISPLAYASICON = 16
PSF_HIDECHANGEICON = 32
PSF_STAYONCLIPBOARDCHANGE = 64
PSF_NOREFRESHDATAOBJECT = 128
OLEUI_IOERR_SRCDATAOBJECTINVALID = 116
OLEUI_IOERR_ARRPASTEENTRIESINVALID = 117
OLEUI_IOERR_ARRLINKTYPESINVALID = 118
OLEUI_PSERR_CLIPBOARDCHANGED = 119
OLEUI_PSERR_GETCLIPBOARDFAILED = 120
OLEUI_ELERR_LINKCNTRNULL = 116
OLEUI_ELERR_LINKCNTRINVALID = 117
ELF_SHOWHELP = 1
ELF_DISABLEUPDATENOW = 2
ELF_DISABLEOPENSOURCE = 4
ELF_DISABLECHANGESOURCE = 8
ELF_DISABLECANCELLINK = 16
CIF_SHOWHELP = 1
CIF_SELECTCURRENT = 2
CIF_SELECTDEFAULT = 4
CIF_SELECTFROMFILE = 8
CIF_USEICONEXE = 16
OLEUI_CIERR_MUSTHAVECLSID = 116
OLEUI_CIERR_MUSTHAVECURRENTMETAFILE = 117
OLEUI_CIERR_SZICONEXEINVALID = 118
CF_SHOWHELPBUTTON = 1
CF_SETCONVERTDEFAULT = 2
CF_SETACTIVATEDEFAULT = 4
CF_SELECTCONVERTTO = 8
CF_SELECTACTIVATEAS = 16
CF_DISABLEDISPLAYASICON = 32
CF_DISABLEACTIVATEAS = 64
CF_HIDECHANGEICON = 128
CF_CONVERTONLY = 256
OLEUI_CTERR_CLASSIDINVALID = 117
OLEUI_CTERR_DVASPECTINVALID = 118
OLEUI_CTERR_CBFORMATINVALID = 119
OLEUI_CTERR_HMETAPICTINVALID = 120
OLEUI_CTERR_STRINGINVALID = 121
BZ_DISABLECANCELBUTTON = 1
BZ_DISABLESWITCHTOBUTTON = 2
BZ_DISABLERETRYBUTTON = 4
BZ_NOTRESPONDINGDIALOG = 8
OLEUI_BZERR_HTASKINVALID = 116
OLEUI_BZ_SWITCHTOSELECTED = 117
OLEUI_BZ_RETRYSELECTED = 118
OLEUI_BZ_CALLUNBLOCKED = 119
CSF_SHOWHELP = 1
CSF_VALIDSOURCE = 2
CSF_ONLYGETSOURCE = 4
CSF_EXPLORER = 8
OLEUI_CSERR_LINKCNTRNULL = 116
OLEUI_CSERR_LINKCNTRINVALID = 117
OLEUI_CSERR_FROMNOTNULL = 118
OLEUI_CSERR_TONOTNULL = 119
OLEUI_CSERR_SOURCENULL = 120
OLEUI_CSERR_SOURCEINVALID = 121
OLEUI_CSERR_SOURCEPARSERROR = 122
OLEUI_CSERR_SOURCEPARSEERROR = 122
VPF_SELECTRELATIVE = 1
VPF_DISABLERELATIVE = 2
VPF_DISABLESCALE = 4
OPF_OBJECTISLINK = 1
OPF_NOFILLDEFAULT = 2
OPF_SHOWHELP = 4
OPF_DISABLECONVERT = 8
OLEUI_OPERR_SUBPROPNULL = 116
OLEUI_OPERR_SUBPROPINVALID = 117
OLEUI_OPERR_PROPSHEETNULL = 118
OLEUI_OPERR_PROPSHEETINVALID = 119
OLEUI_OPERR_SUPPROP = 120
OLEUI_OPERR_PROPSINVALID = 121
OLEUI_OPERR_PAGESINCORRECT = 122
OLEUI_OPERR_INVALIDPAGES = 123
OLEUI_OPERR_NOTSUPPORTED = 124
OLEUI_OPERR_DLGPROCNOTNULL = 125
OLEUI_OPERR_LPARAMNOTZERO = 126
OLEUI_GPERR_STRINGINVALID = 127
OLEUI_GPERR_CLASSIDINVALID = 128
OLEUI_GPERR_LPCLSIDEXCLUDEINVALID = 129
OLEUI_GPERR_CBFORMATINVALID = 130
OLEUI_VPERR_METAPICTINVALID = 131
OLEUI_VPERR_DVASPECTINVALID = 132
OLEUI_LPERR_LINKCNTRNULL = 133
OLEUI_LPERR_LINKCNTRINVALID = 134
OLEUI_OPERR_PROPERTYSHEET = 135
OLEUI_OPERR_OBJINFOINVALID = 136
OLEUI_OPERR_LINKINFOINVALID = 137
OLEUI_QUERY_GETCLASSID = 65280
OLEUI_QUERY_LINKBROKEN = 65281
FADF_AUTO = 1
FADF_STATIC = 2
FADF_EMBEDDED = 4
FADF_FIXEDSIZE = 16
FADF_RECORD = 32
FADF_HAVEIID = 64
FADF_HAVEVARTYPE = 128
FADF_BSTR = 256
FADF_UNKNOWN = 512
FADF_DISPATCH = 1024
FADF_VARIANT = 2048
FADF_RESERVED = 61448
PARAMFLAG_NONE = 0
PARAMFLAG_FIN = 1
PARAMFLAG_FOUT = 2
PARAMFLAG_FLCID = 4
PARAMFLAG_FRETVAL = 8
PARAMFLAG_FOPT = 16
PARAMFLAG_FHASDEFAULT = 32
PARAMFLAG_FHASCUSTDATA = 64
IDLFLAG_NONE = 0
IDLFLAG_FIN = 1
IDLFLAG_FOUT = 2
IDLFLAG_FLCID = 4
IDLFLAG_FRETVAL = 8
IMPLTYPEFLAG_FDEFAULT = 1
IMPLTYPEFLAG_FSOURCE = 2
IMPLTYPEFLAG_FRESTRICTED = 4
IMPLTYPEFLAG_FDEFAULTVTABLE = 8
DISPID_UNKNOWN = -1
DISPID_VALUE = 0
DISPID_PROPERTYPUT = -3
DISPID_NEWENUM = -4
DISPID_EVALUATE = -5
DISPID_CONSTRUCTOR = -6
DISPID_DESTRUCTOR = -7
DISPID_COLLECT = -8
STDOLE_MAJORVERNUM = 1
STDOLE_MINORVERNUM = 0
STDOLE_LCID = 0
STDOLE2_MAJORVERNUM = 2
STDOLE2_MINORVERNUM = 0
STDOLE2_LCID = 0
VARIANT_NOVALUEPROP = 1
VARIANT_ALPHABOOL = 2
VARIANT_NOUSEROVERRIDE = 4
VARIANT_CALENDAR_HIJRI = 8
VARIANT_LOCALBOOL = 16
VARIANT_CALENDAR_THAI = 32
VARIANT_CALENDAR_GREGORIAN = 64
VARIANT_USE_NLS = 128
LOCALE_USE_NLS = 268435456
VTDATEGRE_MAX = 2958465
VTDATEGRE_MIN = -657434
NUMPRS_LEADING_WHITE = 1
NUMPRS_TRAILING_WHITE = 2
NUMPRS_LEADING_PLUS = 4
NUMPRS_TRAILING_PLUS = 8
NUMPRS_LEADING_MINUS = 16
NUMPRS_TRAILING_MINUS = 32
NUMPRS_HEX_OCT = 64
NUMPRS_PARENS = 128
NUMPRS_DECIMAL = 256
NUMPRS_THOUSANDS = 512
NUMPRS_CURRENCY = 1024
NUMPRS_EXPONENT = 2048
NUMPRS_USE_ALL = 4096
NUMPRS_STD = 8191
NUMPRS_NEG = 65536
NUMPRS_INEXACT = 131072
VARCMP_LT = 0
VARCMP_EQ = 1
VARCMP_GT = 2
VARCMP_NULL = 3
MEMBERID_NIL = -1
ID_DEFAULTINST = -2
DISPATCH_METHOD = 1
DISPATCH_PROPERTYGET = 2
DISPATCH_PROPERTYPUT = 4
DISPATCH_PROPERTYPUTREF = 8
LOAD_TLB_AS_32BIT = 32
LOAD_TLB_AS_64BIT = 64
ACTIVEOBJECT_STRONG = 0
ACTIVEOBJECT_WEAK = 1
DISPATCH_CONSTRUCT = 16384
DISPID_STARTENUM = -1
SID_VariantConversion = "1f101481-bccd-11d0-9336-00a0c90dcaa9"
SID_GetCaller = "4717cc40-bcb9-11d0-9336-00a0c90dcaa9"
SID_ProvideRuntimeContext = "74a5040c-dd0c-48f0-ac85-194c3259180a"
enum UPDFCACHE_FLAGS : UInt32
UPDFCACHE_ALL = 2147483647

UPDFCACHE_ALLBUTNODATACACHE = 2147483646

UPDFCACHE_NORMALCACHE = 8

UPDFCACHE_IFBLANK = 16

UPDFCACHE_ONLYIFBLANK = 2147483648

UPDFCACHE_NODATACACHE = 1

UPDFCACHE_ONSAVECACHE = 2

UPDFCACHE_ONSTOPCACHE = 4

UPDFCACHE_IFBLANKORONSAVECACHE = 18

end
enum ENUM_CONTROLS_WHICH_FLAGS : UInt32
GCW_WCH_SIBLING = 1

GC_WCH_CONTAINER = 2

GC_WCH_CONTAINED = 3

GC_WCH_ALL = 4

GC_WCH_FREVERSEDIR = 134217728

GC_WCH_FONLYAFTER = 268435456

GC_WCH_FONLYBEFORE = 536870912

GC_WCH_FSELECTED = 1073741824

end
enum MULTICLASSINFO_FLAGS : UInt32
MULTICLASSINFO_GETTYPEINFO = 1

MULTICLASSINFO_GETNUMRESERVEDDISPIDS = 2

MULTICLASSINFO_GETIIDPRIMARY = 4

MULTICLASSINFO_GETIIDSOURCE = 8

end
enum VARENUM : Int32
VT_EMPTY = 0

VT_NULL = 1

VT_I2 = 2

VT_I4 = 3

VT_R4 = 4

VT_R8 = 5

VT_CY = 6

VT_DATE = 7

VT_BSTR = 8

VT_DISPATCH = 9

VT_ERROR = 10

VT_BOOL = 11

VT_VARIANT = 12

VT_UNKNOWN = 13

VT_DECIMAL = 14

VT_I1 = 16

VT_UI1 = 17

VT_UI2 = 18

VT_UI4 = 19

VT_I8 = 20

VT_UI8 = 21

VT_INT = 22

VT_UINT = 23

VT_VOID = 24

VT_HRESULT = 25

VT_PTR = 26

VT_SAFEARRAY = 27

VT_CARRAY = 28

VT_USERDEFINED = 29

VT_LPSTR = 30

VT_LPWSTR = 31

VT_RECORD = 36

VT_INT_PTR = 37

VT_UINT_PTR = 38

VT_FILETIME = 64

VT_BLOB = 65

VT_STREAM = 66

VT_STORAGE = 67

VT_STREAMED_OBJECT = 68

VT_STORED_OBJECT = 69

VT_BLOB_OBJECT = 70

VT_CF = 71

VT_CLSID = 72

VT_VERSIONED_STREAM = 73

VT_BSTR_BLOB = 4095

VT_VECTOR = 4096

VT_ARRAY = 8192

VT_BYREF = 16384

VT_RESERVED = 32768

VT_ILLEGAL = 65535

VT_ILLEGALMASKED = 4095

VT_TYPEMASK = 4095

end
struct WireSAFEARR_BSTR
  size : LibC::UInt32
  aBstr : FLAGGED_WORD_BLOB**
end
struct WireSAFEARR_UNKNOWN
  size : LibC::UInt32
  apUnknown : IUnknown*
end
struct WireSAFEARR_DISPATCH
  size : LibC::UInt32
  apDispatch : IDispatch*
end
struct WireSAFEARR_VARIANT
  size : LibC::UInt32
  aVariant : WireVARIANT**
end
struct WireSAFEARR_BRECORD
  size : LibC::UInt32
  aRecord : WireBRECORD**
end
struct WireSAFEARR_HAVEIID
  size : LibC::UInt32
  apUnknown : IUnknown*
  iid : LibC::Guid
end
enum SF_TYPE : Int32
SF_ERROR = 10

SF_I1 = 16

SF_I2 = 2

SF_I4 = 3

SF_I8 = 20

SF_BSTR = 8

SF_UNKNOWN = 13

SF_DISPATCH = 9

SF_VARIANT = 12

SF_RECORD = 36

SF_HAVEIID = 32781

end
type Pig8dcaba7bd26d = WireSAFEARR_BSTR | WireSAFEARR_UNKNOWN | WireSAFEARR_DISPATCH | WireSAFEARR_VARIANT | WireSAFEARR_BRECORD | WireSAFEARR_HAVEIID | BYTE_SIZEDARR | SHORT_SIZEDARR | LONG_SIZEDARR | HYPER_SIZEDARR
struct WireSAFEARRAY_UNION
  sfType : LibC::UInt32
  u : Pig8dcaba7bd26d
end
struct WireSAFEARRAY
  cDims : LibC::UInt16
  fFeatures : LibC::UInt16
  cbElements : LibC::UInt32
  cLocks : LibC::UInt32
  uArrayStructs : WireSAFEARRAY_UNION
  rgsabound : Array(SAFEARRAYBOUND)
end
struct WireBRECORD
  fFlags : LibC::UInt32
  clSize : LibC::UInt32
  pRecInfo : IRecordInfo
  pRecord : LibC::Byte*
end
type Owldc12fe5a4358 = LibC::Int64 | LibC::Int32 | LibC::Byte | LibC::Int16 | LibC::Single | LibC::Double | LibC::Int16 | LibC::Int32 | CY | LibC::Double | FLAGGED_WORD_BLOB* | IUnknown | IDispatch | WireSAFEARRAY** | WireBRECORD* | LibC::Byte* | LibC::Int16* | LibC::Int32* | LibC::Int64* | LibC::Single* | LibC::Double* | LibC::Int16* | LibC::Int32* | CY* | LibC::Double* | FLAGGED_WORD_BLOB** | IUnknown* | IDispatch* | WireSAFEARRAY*** | WireVARIANT** | CHAR | LibC::UInt16 | LibC::UInt32 | LibC::UInt64 | LibC::Int32 | LibC::UInt32 | DECIMAL | DECIMAL* | PSTR | LibC::UInt16* | LibC::UInt32* | LibC::UInt64* | LibC::Int32* | LibC::UInt32*
struct WireVARIANT
  clSize : LibC::UInt32
  rpcReserved : LibC::UInt32
  vt : LibC::UInt16
  wReserved1 : LibC::UInt16
  wReserved2 : LibC::UInt16
  wReserved3 : LibC::UInt16
end
struct ARRAYDESC
  tdescElem : TYPEDESC
  cDims : LibC::UInt16
  rgbounds : Array(SAFEARRAYBOUND)
end
struct PARAMDESCEX
  cBytes : LibC::UInt32
  varDefaultValue : VARIANT
end
struct PARAMDESC
  pparamdescex : PARAMDESCEX*
  wParamFlags : LibC::UInt16
end
enum TYPEFLAGS : Int32
TYPEFLAG_FAPPOBJECT = 1

TYPEFLAG_FCANCREATE = 2

TYPEFLAG_FLICENSED = 4

TYPEFLAG_FPREDECLID = 8

TYPEFLAG_FHIDDEN = 16

TYPEFLAG_FCONTROL = 32

TYPEFLAG_FDUAL = 64

TYPEFLAG_FNONEXTENSIBLE = 128

TYPEFLAG_FOLEAUTOMATION = 256

TYPEFLAG_FRESTRICTED = 512

TYPEFLAG_FAGGREGATABLE = 1024

TYPEFLAG_FREPLACEABLE = 2048

TYPEFLAG_FDISPATCHABLE = 4096

TYPEFLAG_FREVERSEBIND = 8192

TYPEFLAG_FPROXY = 16384

end
enum FUNCFLAGS : Int32
FUNCFLAG_FRESTRICTED = 1

FUNCFLAG_FSOURCE = 2

FUNCFLAG_FBINDABLE = 4

FUNCFLAG_FREQUESTEDIT = 8

FUNCFLAG_FDISPLAYBIND = 16

FUNCFLAG_FDEFAULTBIND = 32

FUNCFLAG_FHIDDEN = 64

FUNCFLAG_FUSESGETLASTERROR = 128

FUNCFLAG_FDEFAULTCOLLELEM = 256

FUNCFLAG_FUIDEFAULT = 512

FUNCFLAG_FNONBROWSABLE = 1024

FUNCFLAG_FREPLACEABLE = 2048

FUNCFLAG_FIMMEDIATEBIND = 4096

end
enum VARFLAGS : Int32
VARFLAG_FREADONLY = 1

VARFLAG_FSOURCE = 2

VARFLAG_FBINDABLE = 4

VARFLAG_FREQUESTEDIT = 8

VARFLAG_FDISPLAYBIND = 16

VARFLAG_FDEFAULTBIND = 32

VARFLAG_FHIDDEN = 64

VARFLAG_FRESTRICTED = 128

VARFLAG_FDEFAULTCOLLELEM = 256

VARFLAG_FUIDEFAULT = 512

VARFLAG_FNONBROWSABLE = 1024

VARFLAG_FREPLACEABLE = 2048

VARFLAG_FIMMEDIATEBIND = 4096

end
struct CLEANLOCALSTORAGE
  pInterface : IUnknown
  pStorage : LibC::Void*
  flags : LibC::UInt32
end
enum LIBFLAGS : Int32
LIBFLAG_FRESTRICTED = 1

LIBFLAG_FCONTROL = 2

LIBFLAG_FHIDDEN = 4

LIBFLAG_FHASDISKIMAGE = 8

end
enum CHANGEKIND : Int32
CHANGEKIND_ADDMEMBER = 0

CHANGEKIND_DELETEMEMBER = 1

CHANGEKIND_SETNAMES = 2

CHANGEKIND_SETDOCUMENTATION = 3

CHANGEKIND_GENERAL = 4

CHANGEKIND_INVALIDATE = 5

CHANGEKIND_CHANGEFAILED = 6

CHANGEKIND_MAX = 7

end
enum DISCARDCACHE : Int32
DISCARDCACHE_SAVEIFDIRTY = 0

DISCARDCACHE_NOSAVE = 1

end
enum OLEGETMONIKER : Int32
OLEGETMONIKER_ONLYIFTHERE = 1

OLEGETMONIKER_FORCEASSIGN = 2

OLEGETMONIKER_UNASSIGN = 3

OLEGETMONIKER_TEMPFORUSER = 4

end
enum OLEWHICHMK : Int32
OLEWHICHMK_CONTAINER = 1

OLEWHICHMK_OBJREL = 2

OLEWHICHMK_OBJFULL = 3

end
enum USERCLASSTYPE : Int32
USERCLASSTYPE_FULL = 1

USERCLASSTYPE_SHORT = 2

USERCLASSTYPE_APPNAME = 3

end
enum OLEMISC : Int32
OLEMISC_RECOMPOSEONRESIZE = 1

OLEMISC_ONLYICONIC = 2

OLEMISC_INSERTNOTREPLACE = 4

OLEMISC_STATIC = 8

OLEMISC_CANTLINKINSIDE = 16

OLEMISC_CANLINKBYOLE1 = 32

OLEMISC_ISLINKOBJECT = 64

OLEMISC_INSIDEOUT = 128

OLEMISC_ACTIVATEWHENVISIBLE = 256

OLEMISC_RENDERINGISDEVICEINDEPENDENT = 512

OLEMISC_INVISIBLEATRUNTIME = 1024

OLEMISC_ALWAYSRUN = 2048

OLEMISC_ACTSLIKEBUTTON = 4096

OLEMISC_ACTSLIKELABEL = 8192

OLEMISC_NOUIACTIVATE = 16384

OLEMISC_ALIGNABLE = 32768

OLEMISC_SIMPLEFRAME = 65536

OLEMISC_SETCLIENTSITEFIRST = 131072

OLEMISC_IMEMODE = 262144

OLEMISC_IGNOREACTIVATEWHENVISIBLE = 524288

OLEMISC_WANTSTOMENUMERGE = 1048576

OLEMISC_SUPPORTSMULTILEVELUNDO = 2097152

end
enum OLECLOSE : Int32
OLECLOSE_SAVEIFDIRTY = 0

OLECLOSE_NOSAVE = 1

OLECLOSE_PROMPTSAVE = 2

end
enum OLERENDER : Int32
OLERENDER_NONE = 0

OLERENDER_DRAW = 1

OLERENDER_FORMAT = 2

OLERENDER_ASIS = 3

end
struct OBJECTDESCRIPTOR
  cbSize : LibC::UInt32
  clsid : LibC::Guid
  dwDrawAspect : LibC::UInt32
  sizel : SIZE
  pointl : POINTL
  dwStatus : LibC::UInt32
  dwFullUserTypeName : LibC::UInt32
  dwSrcOfCopy : LibC::UInt32
end
enum OLEUPDATE : Int32
OLEUPDATE_ALWAYS = 1

OLEUPDATE_ONCALL = 3

end
enum OLELINKBIND : Int32
OLELINKBIND_EVENIFCLASSDIFF = 1

end
enum BINDSPEED : Int32
BINDSPEED_INDEFINITE = 1

BINDSPEED_MODERATE = 2

BINDSPEED_IMMEDIATE = 3

end
enum OLECONTF : Int32
OLECONTF_EMBEDDINGS = 1

OLECONTF_LINKS = 2

OLECONTF_OTHERS = 4

OLECONTF_ONLYUSER = 8

OLECONTF_ONLYIFRUNNING = 16

end
struct OIFI
  cb : LibC::UInt32
  fMDIApp : BOOL
  hwndFrame : HWND
  haccel : HACCEL
  cAccelEntries : LibC::UInt32
end
struct OleMenuGroupWidths
  width : Array(LibC::Int32)
end
struct OLEVERB
  lVerb : LibC::Int32
  lpszVerbName : PWSTR
  fuFlags : LibC::UInt32
  grfAttribs : LibC::UInt32
end
enum OLEVERBATTRIB : Int32
OLEVERBATTRIB_NEVERDIRTIES = 1

OLEVERBATTRIB_ONCONTAINERMENU = 2

end
struct NUMPARSE
  cDig : LibC::Int32
  dwInFlags : LibC::UInt32
  dwOutFlags : LibC::UInt32
  cchUsed : LibC::Int32
  nBaseShift : LibC::Int32
  nPwr10 : LibC::Int32
end
struct UDATE
  st : SYSTEMTIME
  wDayOfYear : LibC::UInt16
end
enum REGKIND : Int32
REGKIND_DEFAULT = 0

REGKIND_REGISTER = 1

REGKIND_NONE = 2

end
struct PARAMDATA
  szName : PWSTR
  vt : LibC::UInt16
end
struct METHODDATA
  szName : PWSTR
  ppdata : PARAMDATA*
  dispid : LibC::Int32
  iMeth : LibC::UInt32
  cc : CALLCONV
  cArgs : LibC::UInt32
  wFlags : LibC::UInt16
  vtReturn : LibC::UInt16
end
struct INTERFACEDATA
  pmethdata : METHODDATA*
  cMembers : LibC::UInt32
end
enum UASFLAGS : Int32
UAS_NORMAL = 0

UAS_BLOCKED = 1

UAS_NOPARENTENABLE = 2

UAS_MASK = 3

end
enum READYSTATE : Int32
READYSTATE_UNINITIALIZED = 0

READYSTATE_LOADING = 1

READYSTATE_LOADED = 2

READYSTATE_INTERACTIVE = 3

READYSTATE_COMPLETE = 4

end
struct LICINFO
  cbLicInfo : LibC::Int32
  fRuntimeKeyAvail : BOOL
  fLicVerified : BOOL
end
enum GUIDKIND : Int32
GUIDKIND_DEFAULT_SOURCE_DISP_IID = 1

end
struct CONTROLINFO
  cb : LibC::UInt32
  hAccel : HACCEL
  cAccel : LibC::UInt16
  dwFlags : LibC::UInt32
end
enum CTRLINFO : Int32
CTRLINFO_EATS_RETURN = 1

CTRLINFO_EATS_ESCAPE = 2

end
struct POINTF
  x : LibC::Single
  y : LibC::Single
end
enum XFORMCOORDS : Int32
XFORMCOORDS_POSITION = 1

XFORMCOORDS_SIZE = 2

XFORMCOORDS_HIMETRICTOCONTAINER = 4

XFORMCOORDS_CONTAINERTOHIMETRIC = 8

XFORMCOORDS_EVENTCOMPAT = 16

end
struct PROPPAGEINFO
  cb : LibC::UInt32
  pszTitle : PWSTR
  size : SIZE
  pszDocString : PWSTR
  pszHelpFile : PWSTR
  dwHelpContext : LibC::UInt32
end
enum PROPPAGESTATUS : Int32
PROPPAGESTATUS_DIRTY = 1

PROPPAGESTATUS_VALIDATE = 2

PROPPAGESTATUS_CLEAN = 4

end
struct CAUUID
  cElems : LibC::UInt32
  pElems : LibC::Guid*
end
enum PictureAttributes : Int32
PICTURE_SCALABLE = 1

PICTURE_TRANSPARENT = 2

end
enum ACTIVATEFLAGS : Int32
ACTIVATE_WINDOWLESS = 1

end
enum OLEDCFLAGS : Int32
OLEDC_NODRAW = 1

OLEDC_PAINTBKGND = 2

OLEDC_OFFSCREEN = 4

end
enum VIEWSTATUS : Int32
VIEWSTATUS_OPAQUE = 1

VIEWSTATUS_SOLIDBKGND = 2

VIEWSTATUS_DVASPECTOPAQUE = 4

VIEWSTATUS_DVASPECTTRANSPARENT = 8

VIEWSTATUS_SURFACE = 16

VIEWSTATUS_3DSURFACE = 32

end
enum HITRESULT : Int32
HITRESULT_OUTSIDE = 0

HITRESULT_TRANSPARENT = 1

HITRESULT_CLOSE = 2

HITRESULT_HIT = 3

end
enum DVASPECT2 : Int32
DVASPECT_OPAQUE = 16

DVASPECT_TRANSPARENT = 32

end
struct ExtentInfo
  cb : LibC::UInt32
  dwExtentMode : LibC::UInt32
  sizelProposed : SIZE
end
enum ExtentMode : Int32
DVEXTENT_CONTENT = 0

DVEXTENT_INTEGRAL = 1

end
enum AspectInfoFlag : Int32
DVASPECTINFOFLAG_CANOPTIMIZE = 1

end
struct AspectInfo
  cb : LibC::UInt32
  dwFlags : LibC::UInt32
end
enum POINTERINACTIVE : Int32
POINTERINACTIVE_ACTIVATEONENTRY = 1

POINTERINACTIVE_DEACTIVATEONLEAVE = 2

POINTERINACTIVE_ACTIVATEONDRAG = 4

end
struct CALPOLESTR
  cElems : LibC::UInt32
  pElems : PWSTR*
end
struct CADWORD
  cElems : LibC::UInt32
  pElems : LibC::UInt32*
end
enum PROPBAG2_TYPE : Int32
PROPBAG2_TYPE_UNDEFINED = 0

PROPBAG2_TYPE_DATA = 1

PROPBAG2_TYPE_URL = 2

PROPBAG2_TYPE_OBJECT = 3

PROPBAG2_TYPE_STREAM = 4

PROPBAG2_TYPE_STORAGE = 5

PROPBAG2_TYPE_MONIKER = 6

end
enum QACONTAINERFLAGS : Int32
QACONTAINER_SHOWHATCHING = 1

QACONTAINER_SHOWGRABHANDLES = 2

QACONTAINER_USERMODE = 4

QACONTAINER_DISPLAYASDEFAULT = 8

QACONTAINER_UIDEAD = 16

QACONTAINER_AUTOCLIP = 32

QACONTAINER_MESSAGEREFLECT = 64

QACONTAINER_SUPPORTSMNEMONICS = 128

end
struct QACONTAINER
  cbSize : LibC::UInt32
  pClientSite : IOleClientSite
  pAdviseSink : IAdviseSinkEx
  pPropertyNotifySink : IPropertyNotifySink
  pUnkEventSink : IUnknown
  dwAmbientFlags : LibC::UInt32
  colorFore : LibC::UInt32
  colorBack : LibC::UInt32
  pFont : IFont
  pUndoMgr : IOleUndoManager
  dwAppearance : LibC::UInt32
  lcid : LibC::Int32
  hpal : HPALETTE
  pBindHost : IBindHost
  pOleControlSite : IOleControlSite
  pServiceProvider : IServiceProvider
end
struct QACONTROL
  cbSize : LibC::UInt32
  dwMiscStatus : LibC::UInt32
  dwViewStatus : LibC::UInt32
  dwEventCookie : LibC::UInt32
  dwPropNotifyCookie : LibC::UInt32
  dwPointerActivationPolicy : LibC::UInt32
end
struct OCPFIPARAMS
  cbStructSize : LibC::UInt32
  hWndOwner : HWND
  x : LibC::Int32
  y : LibC::Int32
  lpszCaption : PWSTR
  cObjects : LibC::UInt32
  lplpUnk : IUnknown*
  cPages : LibC::UInt32
  lpPages : LibC::Guid*
  lcid : LibC::UInt32
  dispidInitialProperty : LibC::Int32
end
struct FONTDESC
  cbSizeofstruct : LibC::UInt32
  lpstrName : PWSTR
  cySize : CY
  sWeight : LibC::Int16
  sCharset : LibC::Int16
  fItalic : BOOL
  fUnderline : BOOL
  fStrikethrough : BOOL
end
struct Rabbit1987584fbcc2
  hicon : HICON
end
struct Pig5aa3ca3e1eab
  hbitmap : HBITMAP
  hpal : HPALETTE
end
struct Owl19b9b53386ef
  hmeta : HMETAFILE
  xExt : LibC::Int32
  yExt : LibC::Int32
end
struct Duckbb8f025f7d42
  hemf : HENHMETAFILE
end
type Owla0017e9f935f = Pig5aa3ca3e1eab | Owl19b9b53386ef | Rabbit1987584fbcc2 | Duckbb8f025f7d42
struct PICTDESC
  cbSizeofstruct : LibC::UInt32
  picType : LibC::UInt32
end
enum OLE_TRISTATE : Int32
TriUnchecked = 0

TriChecked = 1

TriGray = 2

end
enum DOCMISC : Int32
DOCMISC_CANCREATEMULTIPLEVIEWS = 1

DOCMISC_SUPPORTCOMPLEXRECTANGLES = 2

DOCMISC_CANTOPENEDIT = 4

DOCMISC_NOFILESUPPORT = 8

end
enum PRINTFLAG : UInt32
PRINTFLAG_MAYBOTHERUSER = 1

PRINTFLAG_PROMPTUSER = 2

PRINTFLAG_USERMAYCHANGEPRINTER = 4

PRINTFLAG_RECOMPOSETODEVICE = 8

PRINTFLAG_DONTACTUALLYPRINT = 16

PRINTFLAG_FORCEPROPERTIES = 32

PRINTFLAG_PRINTTOFILE = 64

end
struct PAGERANGE
  nFromPage : LibC::Int32
  nToPage : LibC::Int32
end
struct PAGESET
  cbStruct : LibC::UInt32
  fOddPages : BOOL
  fEvenPages : BOOL
  cPageRange : LibC::UInt32
  rgPages : Array(PAGERANGE)
end
enum OLECMDF : Int32
OLECMDF_SUPPORTED = 1

OLECMDF_ENABLED = 2

OLECMDF_LATCHED = 4

OLECMDF_NINCHED = 8

OLECMDF_INVISIBLE = 16

OLECMDF_DEFHIDEONCTXTMENU = 32

end
struct OLECMD
  cmdID : LibC::UInt32
  cmdf : LibC::UInt32
end
struct OLECMDTEXT
  cmdtextf : LibC::UInt32
  cwActual : LibC::UInt32
  cwBuf : LibC::UInt32
  rgwz : Array(LibC::Char)
end
enum OLECMDTEXTF : Int32
OLECMDTEXTF_NONE = 0

OLECMDTEXTF_NAME = 1

OLECMDTEXTF_STATUS = 2

end
enum OLECMDEXECOPT : Int32
OLECMDEXECOPT_DODEFAULT = 0

OLECMDEXECOPT_PROMPTUSER = 1

OLECMDEXECOPT_DONTPROMPTUSER = 2

OLECMDEXECOPT_SHOWHELP = 3

end
enum OLECMDID : Int32
OLECMDID_OPEN = 1

OLECMDID_NEW = 2

OLECMDID_SAVE = 3

OLECMDID_SAVEAS = 4

OLECMDID_SAVECOPYAS = 5

OLECMDID_PRINT = 6

OLECMDID_PRINTPREVIEW = 7

OLECMDID_PAGESETUP = 8

OLECMDID_SPELL = 9

OLECMDID_PROPERTIES = 10

OLECMDID_CUT = 11

OLECMDID_COPY = 12

OLECMDID_PASTE = 13

OLECMDID_PASTESPECIAL = 14

OLECMDID_UNDO = 15

OLECMDID_REDO = 16

OLECMDID_SELECTALL = 17

OLECMDID_CLEARSELECTION = 18

OLECMDID_ZOOM = 19

OLECMDID_GETZOOMRANGE = 20

OLECMDID_UPDATECOMMANDS = 21

OLECMDID_REFRESH = 22

OLECMDID_STOP = 23

OLECMDID_HIDETOOLBARS = 24

OLECMDID_SETPROGRESSMAX = 25

OLECMDID_SETPROGRESSPOS = 26

OLECMDID_SETPROGRESSTEXT = 27

OLECMDID_SETTITLE = 28

OLECMDID_SETDOWNLOADSTATE = 29

OLECMDID_STOPDOWNLOAD = 30

OLECMDID_ONTOOLBARACTIVATED = 31

OLECMDID_FIND = 32

OLECMDID_DELETE = 33

OLECMDID_HTTPEQUIV = 34

OLECMDID_HTTPEQUIV_DONE = 35

OLECMDID_ENABLE_INTERACTION = 36

OLECMDID_ONUNLOAD = 37

OLECMDID_PROPERTYBAG2 = 38

OLECMDID_PREREFRESH = 39

OLECMDID_SHOWSCRIPTERROR = 40

OLECMDID_SHOWMESSAGE = 41

OLECMDID_SHOWFIND = 42

OLECMDID_SHOWPAGESETUP = 43

OLECMDID_SHOWPRINT = 44

OLECMDID_CLOSE = 45

OLECMDID_ALLOWUILESSSAVEAS = 46

OLECMDID_DONTDOWNLOADCSS = 47

OLECMDID_UPDATEPAGESTATUS = 48

OLECMDID_PRINT2 = 49

OLECMDID_PRINTPREVIEW2 = 50

OLECMDID_SETPRINTTEMPLATE = 51

OLECMDID_GETPRINTTEMPLATE = 52

OLECMDID_PAGEACTIONBLOCKED = 55

OLECMDID_PAGEACTIONUIQUERY = 56

OLECMDID_FOCUSVIEWCONTROLS = 57

OLECMDID_FOCUSVIEWCONTROLSQUERY = 58

OLECMDID_SHOWPAGEACTIONMENU = 59

OLECMDID_ADDTRAVELENTRY = 60

OLECMDID_UPDATETRAVELENTRY = 61

OLECMDID_UPDATEBACKFORWARDSTATE = 62

OLECMDID_OPTICAL_ZOOM = 63

OLECMDID_OPTICAL_GETZOOMRANGE = 64

OLECMDID_WINDOWSTATECHANGED = 65

OLECMDID_ACTIVEXINSTALLSCOPE = 66

OLECMDID_UPDATETRAVELENTRY_DATARECOVERY = 67

OLECMDID_SHOWTASKDLG = 68

OLECMDID_POPSTATEEVENT = 69

OLECMDID_VIEWPORT_MODE = 70

OLECMDID_LAYOUT_VIEWPORT_WIDTH = 71

OLECMDID_VISUAL_VIEWPORT_EXCLUDE_BOTTOM = 72

OLECMDID_USER_OPTICAL_ZOOM = 73

OLECMDID_PAGEAVAILABLE = 74

OLECMDID_GETUSERSCALABLE = 75

OLECMDID_UPDATE_CARET = 76

OLECMDID_ENABLE_VISIBILITY = 77

OLECMDID_MEDIA_PLAYBACK = 78

OLECMDID_SETFAVICON = 79

OLECMDID_SET_HOST_FULLSCREENMODE = 80

OLECMDID_EXITFULLSCREEN = 81

OLECMDID_SCROLLCOMPLETE = 82

OLECMDID_ONBEFOREUNLOAD = 83

OLECMDID_SHOWMESSAGE_BLOCKABLE = 84

OLECMDID_SHOWTASKDLG_BLOCKABLE = 85

end
enum MEDIAPLAYBACK_STATE : Int32
MEDIAPLAYBACK_RESUME = 0

MEDIAPLAYBACK_PAUSE = 1

MEDIAPLAYBACK_PAUSE_AND_SUSPEND = 2

MEDIAPLAYBACK_RESUME_FROM_SUSPEND = 3

end
enum IGNOREMIME : Int32
IGNOREMIME_PROMPT = 1

IGNOREMIME_TEXT = 2

end
enum WPCSETTING : Int32
WPCSETTING_LOGGING_ENABLED = 1

WPCSETTING_FILEDOWNLOAD_BLOCKED = 2

end
enum OLECMDID_REFRESHFLAG : Int32
OLECMDIDF_REFRESH_NORMAL = 0

OLECMDIDF_REFRESH_IFEXPIRED = 1

OLECMDIDF_REFRESH_CONTINUE = 2

OLECMDIDF_REFRESH_COMPLETELY = 3

OLECMDIDF_REFRESH_NO_CACHE = 4

OLECMDIDF_REFRESH_RELOAD = 5

OLECMDIDF_REFRESH_LEVELMASK = 255

OLECMDIDF_REFRESH_CLEARUSERINPUT = 4096

OLECMDIDF_REFRESH_PROMPTIFOFFLINE = 8192

OLECMDIDF_REFRESH_THROUGHSCRIPT = 16384

OLECMDIDF_REFRESH_SKIPBEFOREUNLOADEVENT = 32768

OLECMDIDF_REFRESH_PAGEACTION_ACTIVEXINSTALL = 65536

OLECMDIDF_REFRESH_PAGEACTION_FILEDOWNLOAD = 131072

OLECMDIDF_REFRESH_PAGEACTION_LOCALMACHINE = 262144

OLECMDIDF_REFRESH_PAGEACTION_POPUPWINDOW = 524288

OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNLOCALMACHINE = 1048576

OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNTRUSTED = 2097152

OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNINTRANET = 4194304

OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNINTERNET = 8388608

OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNRESTRICTED = 16777216

OLECMDIDF_REFRESH_PAGEACTION_MIXEDCONTENT = 33554432

OLECMDIDF_REFRESH_PAGEACTION_INVALID_CERT = 67108864

OLECMDIDF_REFRESH_PAGEACTION_ALLOW_VERSION = 134217728

end
enum OLECMDID_PAGEACTIONFLAG : Int32
OLECMDIDF_PAGEACTION_FILEDOWNLOAD = 1

OLECMDIDF_PAGEACTION_ACTIVEXINSTALL = 2

OLECMDIDF_PAGEACTION_ACTIVEXTRUSTFAIL = 4

OLECMDIDF_PAGEACTION_ACTIVEXUSERDISABLE = 8

OLECMDIDF_PAGEACTION_ACTIVEXDISALLOW = 16

OLECMDIDF_PAGEACTION_ACTIVEXUNSAFE = 32

OLECMDIDF_PAGEACTION_POPUPWINDOW = 64

OLECMDIDF_PAGEACTION_LOCALMACHINE = 128

OLECMDIDF_PAGEACTION_MIMETEXTPLAIN = 256

OLECMDIDF_PAGEACTION_SCRIPTNAVIGATE = 512

OLECMDIDF_PAGEACTION_SCRIPTNAVIGATE_ACTIVEXINSTALL = 512

OLECMDIDF_PAGEACTION_PROTLOCKDOWNLOCALMACHINE = 1024

OLECMDIDF_PAGEACTION_PROTLOCKDOWNTRUSTED = 2048

OLECMDIDF_PAGEACTION_PROTLOCKDOWNINTRANET = 4096

OLECMDIDF_PAGEACTION_PROTLOCKDOWNINTERNET = 8192

OLECMDIDF_PAGEACTION_PROTLOCKDOWNRESTRICTED = 16384

OLECMDIDF_PAGEACTION_PROTLOCKDOWNDENY = 32768

OLECMDIDF_PAGEACTION_POPUPALLOWED = 65536

OLECMDIDF_PAGEACTION_SCRIPTPROMPT = 131072

OLECMDIDF_PAGEACTION_ACTIVEXUSERAPPROVAL = 262144

OLECMDIDF_PAGEACTION_MIXEDCONTENT = 524288

OLECMDIDF_PAGEACTION_INVALID_CERT = 1048576

OLECMDIDF_PAGEACTION_INTRANETZONEREQUEST = 2097152

OLECMDIDF_PAGEACTION_XSSFILTERED = 4194304

OLECMDIDF_PAGEACTION_SPOOFABLEIDNHOST = 8388608

OLECMDIDF_PAGEACTION_ACTIVEX_EPM_INCOMPATIBLE = 16777216

OLECMDIDF_PAGEACTION_SCRIPTNAVIGATE_ACTIVEXUSERAPPROVAL = 33554432

OLECMDIDF_PAGEACTION_WPCBLOCKED = 67108864

OLECMDIDF_PAGEACTION_WPCBLOCKED_ACTIVEX = 134217728

OLECMDIDF_PAGEACTION_EXTENSION_COMPAT_BLOCKED = 268435456

OLECMDIDF_PAGEACTION_NORESETACTIVEX = 536870912

OLECMDIDF_PAGEACTION_GENERIC_STATE = 1073741824

OLECMDIDF_PAGEACTION_RESET = -2147483648

end
enum OLECMDID_BROWSERSTATEFLAG : Int32
OLECMDIDF_BROWSERSTATE_EXTENSIONSOFF = 1

OLECMDIDF_BROWSERSTATE_IESECURITY = 2

OLECMDIDF_BROWSERSTATE_PROTECTEDMODE_OFF = 4

OLECMDIDF_BROWSERSTATE_RESET = 8

OLECMDIDF_BROWSERSTATE_REQUIRESACTIVEX = 16

OLECMDIDF_BROWSERSTATE_DESKTOPHTMLDIALOG = 32

OLECMDIDF_BROWSERSTATE_BLOCKEDVERSION = 64

end
enum OLECMDID_OPTICAL_ZOOMFLAG : Int32
OLECMDIDF_OPTICAL_ZOOM_NOPERSIST = 1

OLECMDIDF_OPTICAL_ZOOM_NOLAYOUT = 16

OLECMDIDF_OPTICAL_ZOOM_NOTRANSIENT = 32

OLECMDIDF_OPTICAL_ZOOM_RELOADFORNEWTAB = 64

end
enum PAGEACTION_UI : Int32
PAGEACTION_UI_DEFAULT = 0

PAGEACTION_UI_MODAL = 1

PAGEACTION_UI_MODELESS = 2

PAGEACTION_UI_SILENT = 3

end
enum OLECMDID_WINDOWSTATE_FLAG : Int32
OLECMDIDF_WINDOWSTATE_USERVISIBLE = 1

OLECMDIDF_WINDOWSTATE_ENABLED = 2

OLECMDIDF_WINDOWSTATE_USERVISIBLE_VALID = 65536

OLECMDIDF_WINDOWSTATE_ENABLED_VALID = 131072

end
enum OLECMDID_VIEWPORT_MODE_FLAG : Int32
OLECMDIDF_VIEWPORTMODE_FIXED_LAYOUT_WIDTH = 1

OLECMDIDF_VIEWPORTMODE_EXCLUDE_VISUAL_BOTTOM = 2

OLECMDIDF_VIEWPORTMODE_FIXED_LAYOUT_WIDTH_VALID = 65536

OLECMDIDF_VIEWPORTMODE_EXCLUDE_VISUAL_BOTTOM_VALID = 131072

end
alias LPFNOLEUIHOOK = (HWND, LibC::UInt32, WPARAM, LPARAM -> LibC::UInt32)
struct OLEUIINSERTOBJECTW
  cbStruct : LibC::UInt32
  dwFlags : LibC::UInt32
  hWndOwner : HWND
  lpszCaption : PWSTR
  lpfnHook : LPFNOLEUIHOOK
  lCustData : LPARAM
  hInstance : HINSTANCE
  lpszTemplate : PWSTR
  hResource : HRSRC
  clsid : LibC::Guid
  lpszFile : PWSTR
  cchFile : LibC::UInt32
  cClsidExclude : LibC::UInt32
  lpClsidExclude : LibC::Guid*
  iid : LibC::Guid
  oleRender : LibC::UInt32
  lpFormatEtc : FORMATETC*
  lpIOleClientSite : IOleClientSite
  lpIStorage : IStorage
  ppvObj : LibC::Void**
  sc : LibC::Int32
  hMetaPict : LibC::Int*
end
struct OLEUIINSERTOBJECTA
  cbStruct : LibC::UInt32
  dwFlags : LibC::UInt32
  hWndOwner : HWND
  lpszCaption : PSTR
  lpfnHook : LPFNOLEUIHOOK
  lCustData : LPARAM
  hInstance : HINSTANCE
  lpszTemplate : PSTR
  hResource : HRSRC
  clsid : LibC::Guid
  lpszFile : PSTR
  cchFile : LibC::UInt32
  cClsidExclude : LibC::UInt32
  lpClsidExclude : LibC::Guid*
  iid : LibC::Guid
  oleRender : LibC::UInt32
  lpFormatEtc : FORMATETC*
  lpIOleClientSite : IOleClientSite
  lpIStorage : IStorage
  ppvObj : LibC::Void**
  sc : LibC::Int32
  hMetaPict : LibC::Int*
end
enum OLEUIPASTEFLAG : Int32
OLEUIPASTE_ENABLEICON = 2048

OLEUIPASTE_PASTEONLY = 0

OLEUIPASTE_PASTE = 512

OLEUIPASTE_LINKANYTYPE = 1024

OLEUIPASTE_LINKTYPE1 = 1

OLEUIPASTE_LINKTYPE2 = 2

OLEUIPASTE_LINKTYPE3 = 4

OLEUIPASTE_LINKTYPE4 = 8

OLEUIPASTE_LINKTYPE5 = 16

OLEUIPASTE_LINKTYPE6 = 32

OLEUIPASTE_LINKTYPE7 = 64

OLEUIPASTE_LINKTYPE8 = 128

end
struct OLEUIPASTEENTRYW
  fmtetc : FORMATETC
  lpstrFormatName : PWSTR
  lpstrResultText : PWSTR
  dwFlags : LibC::UInt32
  dwScratchSpace : LibC::UInt32
end
struct OLEUIPASTEENTRYA
  fmtetc : FORMATETC
  lpstrFormatName : PSTR
  lpstrResultText : PSTR
  dwFlags : LibC::UInt32
  dwScratchSpace : LibC::UInt32
end
struct OLEUIPASTESPECIALW
  cbStruct : LibC::UInt32
  dwFlags : LibC::UInt32
  hWndOwner : HWND
  lpszCaption : PWSTR
  lpfnHook : LPFNOLEUIHOOK
  lCustData : LPARAM
  hInstance : HINSTANCE
  lpszTemplate : PWSTR
  hResource : HRSRC
  lpSrcDataObj : IDataObject
  arrPasteEntries : OLEUIPASTEENTRYW*
  cPasteEntries : LibC::Int32
  arrLinkTypes : LibC::UInt32*
  cLinkTypes : LibC::Int32
  cClsidExclude : LibC::UInt32
  lpClsidExclude : LibC::Guid*
  nSelectedIndex : LibC::Int32
  fLink : BOOL
  hMetaPict : LibC::Int*
  sizel : SIZE
end
struct OLEUIPASTESPECIALA
  cbStruct : LibC::UInt32
  dwFlags : LibC::UInt32
  hWndOwner : HWND
  lpszCaption : PSTR
  lpfnHook : LPFNOLEUIHOOK
  lCustData : LPARAM
  hInstance : HINSTANCE
  lpszTemplate : PSTR
  hResource : HRSRC
  lpSrcDataObj : IDataObject
  arrPasteEntries : OLEUIPASTEENTRYA*
  cPasteEntries : LibC::Int32
  arrLinkTypes : LibC::UInt32*
  cLinkTypes : LibC::Int32
  cClsidExclude : LibC::UInt32
  lpClsidExclude : LibC::Guid*
  nSelectedIndex : LibC::Int32
  fLink : BOOL
  hMetaPict : LibC::Int*
  sizel : SIZE
end
struct OLEUIEDITLINKSW
  cbStruct : LibC::UInt32
  dwFlags : LibC::UInt32
  hWndOwner : HWND
  lpszCaption : PWSTR
  lpfnHook : LPFNOLEUIHOOK
  lCustData : LPARAM
  hInstance : HINSTANCE
  lpszTemplate : PWSTR
  hResource : HRSRC
  lpOleUILinkContainer : IOleUILinkContainerW
end
struct OLEUIEDITLINKSA
  cbStruct : LibC::UInt32
  dwFlags : LibC::UInt32
  hWndOwner : HWND
  lpszCaption : PSTR
  lpfnHook : LPFNOLEUIHOOK
  lCustData : LPARAM
  hInstance : HINSTANCE
  lpszTemplate : PSTR
  hResource : HRSRC
  lpOleUILinkContainer : IOleUILinkContainerA
end
struct OLEUICHANGEICONW
  cbStruct : LibC::UInt32
  dwFlags : LibC::UInt32
  hWndOwner : HWND
  lpszCaption : PWSTR
  lpfnHook : LPFNOLEUIHOOK
  lCustData : LPARAM
  hInstance : HINSTANCE
  lpszTemplate : PWSTR
  hResource : HRSRC
  hMetaPict : LibC::Int*
  clsid : LibC::Guid
  szIconExe : Array(LibC::Char)
  cchIconExe : LibC::Int32
end
struct OLEUICHANGEICONA
  cbStruct : LibC::UInt32
  dwFlags : LibC::UInt32
  hWndOwner : HWND
  lpszCaption : PSTR
  lpfnHook : LPFNOLEUIHOOK
  lCustData : LPARAM
  hInstance : HINSTANCE
  lpszTemplate : PSTR
  hResource : HRSRC
  hMetaPict : LibC::Int*
  clsid : LibC::Guid
  szIconExe : Array(CHAR)
  cchIconExe : LibC::Int32
end
struct OLEUICONVERTW
  cbStruct : LibC::UInt32
  dwFlags : LibC::UInt32
  hWndOwner : HWND
  lpszCaption : PWSTR
  lpfnHook : LPFNOLEUIHOOK
  lCustData : LPARAM
  hInstance : HINSTANCE
  lpszTemplate : PWSTR
  hResource : HRSRC
  clsid : LibC::Guid
  clsidConvertDefault : LibC::Guid
  clsidActivateDefault : LibC::Guid
  clsidNew : LibC::Guid
  dvAspect : LibC::UInt32
  wFormat : LibC::UInt16
  fIsLinkedObject : BOOL
  hMetaPict : LibC::Int*
  lpszUserType : PWSTR
  fObjectsIconChanged : BOOL
  lpszDefLabel : PWSTR
  cClsidExclude : LibC::UInt32
  lpClsidExclude : LibC::Guid*
end
struct OLEUICONVERTA
  cbStruct : LibC::UInt32
  dwFlags : LibC::UInt32
  hWndOwner : HWND
  lpszCaption : PSTR
  lpfnHook : LPFNOLEUIHOOK
  lCustData : LPARAM
  hInstance : HINSTANCE
  lpszTemplate : PSTR
  hResource : HRSRC
  clsid : LibC::Guid
  clsidConvertDefault : LibC::Guid
  clsidActivateDefault : LibC::Guid
  clsidNew : LibC::Guid
  dvAspect : LibC::UInt32
  wFormat : LibC::UInt16
  fIsLinkedObject : BOOL
  hMetaPict : LibC::Int*
  lpszUserType : PSTR
  fObjectsIconChanged : BOOL
  lpszDefLabel : PSTR
  cClsidExclude : LibC::UInt32
  lpClsidExclude : LibC::Guid*
end
struct OLEUIBUSYW
  cbStruct : LibC::UInt32
  dwFlags : LibC::UInt32
  hWndOwner : HWND
  lpszCaption : PWSTR
  lpfnHook : LPFNOLEUIHOOK
  lCustData : LPARAM
  hInstance : HINSTANCE
  lpszTemplate : PWSTR
  hResource : HRSRC
  hTask : HTASK
  lphWndDialog : HWND*
end
struct OLEUIBUSYA
  cbStruct : LibC::UInt32
  dwFlags : LibC::UInt32
  hWndOwner : HWND
  lpszCaption : PSTR
  lpfnHook : LPFNOLEUIHOOK
  lCustData : LPARAM
  hInstance : HINSTANCE
  lpszTemplate : PSTR
  hResource : HRSRC
  hTask : HTASK
  lphWndDialog : HWND*
end
struct OLEUICHANGESOURCEW
  cbStruct : LibC::UInt32
  dwFlags : LibC::UInt32
  hWndOwner : HWND
  lpszCaption : PWSTR
  lpfnHook : LPFNOLEUIHOOK
  lCustData : LPARAM
  hInstance : HINSTANCE
  lpszTemplate : PWSTR
  hResource : HRSRC
  lpOFN : OPENFILENAMEW*
  dwReserved1 : Array(LibC::UInt32)
  lpOleUILinkContainer : IOleUILinkContainerW
  dwLink : LibC::UInt32
  lpszDisplayName : PWSTR
  nFileLength : LibC::UInt32
  lpszFrom : PWSTR
  lpszTo : PWSTR
end
struct OLEUICHANGESOURCEA
  cbStruct : LibC::UInt32
  dwFlags : LibC::UInt32
  hWndOwner : HWND
  lpszCaption : PSTR
  lpfnHook : LPFNOLEUIHOOK
  lCustData : LPARAM
  hInstance : HINSTANCE
  lpszTemplate : PSTR
  hResource : HRSRC
  lpOFN : OPENFILENAMEA*
  dwReserved1 : Array(LibC::UInt32)
  lpOleUILinkContainer : IOleUILinkContainerA
  dwLink : LibC::UInt32
  lpszDisplayName : PSTR
  nFileLength : LibC::UInt32
  lpszFrom : PSTR
  lpszTo : PSTR
end
struct OLEUIGNRLPROPSW
  cbStruct : LibC::UInt32
  dwFlags : LibC::UInt32
  dwReserved1 : Array(LibC::UInt32)
  lpfnHook : LPFNOLEUIHOOK
  lCustData : LPARAM
  dwReserved2 : Array(LibC::UInt32)
  lpOP : OLEUIOBJECTPROPSW*
end
struct OLEUIGNRLPROPSA
  cbStruct : LibC::UInt32
  dwFlags : LibC::UInt32
  dwReserved1 : Array(LibC::UInt32)
  lpfnHook : LPFNOLEUIHOOK
  lCustData : LPARAM
  dwReserved2 : Array(LibC::UInt32)
  lpOP : OLEUIOBJECTPROPSA*
end
struct OLEUIVIEWPROPSW
  cbStruct : LibC::UInt32
  dwFlags : LibC::UInt32
  dwReserved1 : Array(LibC::UInt32)
  lpfnHook : LPFNOLEUIHOOK
  lCustData : LPARAM
  dwReserved2 : Array(LibC::UInt32)
  lpOP : OLEUIOBJECTPROPSW*
  nScaleMin : LibC::Int32
  nScaleMax : LibC::Int32
end
struct OLEUIVIEWPROPSA
  cbStruct : LibC::UInt32
  dwFlags : LibC::UInt32
  dwReserved1 : Array(LibC::UInt32)
  lpfnHook : LPFNOLEUIHOOK
  lCustData : LPARAM
  dwReserved2 : Array(LibC::UInt32)
  lpOP : OLEUIOBJECTPROPSA*
  nScaleMin : LibC::Int32
  nScaleMax : LibC::Int32
end
struct OLEUILINKPROPSW
  cbStruct : LibC::UInt32
  dwFlags : LibC::UInt32
  dwReserved1 : Array(LibC::UInt32)
  lpfnHook : LPFNOLEUIHOOK
  lCustData : LPARAM
  dwReserved2 : Array(LibC::UInt32)
  lpOP : OLEUIOBJECTPROPSW*
end
struct OLEUILINKPROPSA
  cbStruct : LibC::UInt32
  dwFlags : LibC::UInt32
  dwReserved1 : Array(LibC::UInt32)
  lpfnHook : LPFNOLEUIHOOK
  lCustData : LPARAM
  dwReserved2 : Array(LibC::UInt32)
  lpOP : OLEUIOBJECTPROPSA*
end
struct OLEUIOBJECTPROPSW
  cbStruct : LibC::UInt32
  dwFlags : LibC::UInt32
  lpPS : PROPSHEETHEADERW_V2*
  dwObject : LibC::UInt32
  lpObjInfo : IOleUIObjInfoW
  dwLink : LibC::UInt32
  lpLinkInfo : IOleUILinkInfoW
  lpGP : OLEUIGNRLPROPSW*
  lpVP : OLEUIVIEWPROPSW*
  lpLP : OLEUILINKPROPSW*
end
struct OLEUIOBJECTPROPSA
  cbStruct : LibC::UInt32
  dwFlags : LibC::UInt32
  lpPS : PROPSHEETHEADERA_V2*
  dwObject : LibC::UInt32
  lpObjInfo : IOleUIObjInfoA
  dwLink : LibC::UInt32
  lpLinkInfo : IOleUILinkInfoA
  lpGP : OLEUIGNRLPROPSA*
  lpVP : OLEUIVIEWPROPSA*
  lpLP : OLEUILINKPROPSA*
end
fun dosDateTimeToVariantTime(wDosDate : LibC::UInt16, wDosTime : LibC::UInt16, pvtime : LibC::Double*) : LibC::Int32
fun variantTimeToDosDateTime(vtime : LibC::Double, pwDosDate : LibC::UInt16*, pwDosTime : LibC::UInt16*) : LibC::Int32
fun systemTimeToVariantTime(lpSystemTime : SYSTEMTIME*, pvtime : LibC::Double*) : LibC::Int32
fun variantTimeToSystemTime(vtime : LibC::Double, lpSystemTime : SYSTEMTIME*) : LibC::Int32
fun safeArrayAllocDescriptor(cDims : LibC::UInt32, ppsaOut : SAFEARRAY**) : HRESULT
fun safeArrayAllocDescriptorEx(vt : LibC::UInt16, cDims : LibC::UInt32, ppsaOut : SAFEARRAY**) : HRESULT
fun safeArrayAllocData(psa : SAFEARRAY*) : HRESULT
fun safeArrayCreate(vt : LibC::UInt16, cDims : LibC::UInt32, rgsabound : SAFEARRAYBOUND*) : SAFEARRAY*
fun safeArrayCreateEx(vt : LibC::UInt16, cDims : LibC::UInt32, rgsabound : SAFEARRAYBOUND*, pvExtra : LibC::Void*) : SAFEARRAY*
fun safeArrayCopyData(psaSource : SAFEARRAY*, psaTarget : SAFEARRAY*) : HRESULT
fun safeArrayReleaseDescriptor(psa : SAFEARRAY*) : LibC::Void
fun safeArrayDestroyDescriptor(psa : SAFEARRAY*) : HRESULT
fun safeArrayReleaseData(pData : LibC::Void*) : LibC::Void
fun safeArrayDestroyData(psa : SAFEARRAY*) : HRESULT
fun safeArrayAddRef(psa : SAFEARRAY*, ppDataToRelease : LibC::Void**) : HRESULT
fun safeArrayDestroy(psa : SAFEARRAY*) : HRESULT
fun safeArrayRedim(psa : SAFEARRAY*, psaboundNew : SAFEARRAYBOUND*) : HRESULT
fun safeArrayGetDim(psa : SAFEARRAY*) : LibC::UInt32
fun safeArrayGetElemsize(psa : SAFEARRAY*) : LibC::UInt32
fun safeArrayGetUBound(psa : SAFEARRAY*, nDim : LibC::UInt32, plUbound : LibC::Int32*) : HRESULT
fun safeArrayGetLBound(psa : SAFEARRAY*, nDim : LibC::UInt32, plLbound : LibC::Int32*) : HRESULT
fun safeArrayLock(psa : SAFEARRAY*) : HRESULT
fun safeArrayUnlock(psa : SAFEARRAY*) : HRESULT
fun safeArrayAccessData(psa : SAFEARRAY*, ppvData : LibC::Void**) : HRESULT
fun safeArrayUnaccessData(psa : SAFEARRAY*) : HRESULT
fun safeArrayGetElement(psa : SAFEARRAY*, rgIndices : LibC::Int32*, pv : LibC::Void*) : HRESULT
fun safeArrayPutElement(psa : SAFEARRAY*, rgIndices : LibC::Int32*, pv : LibC::Void*) : HRESULT
fun safeArrayCopy(psa : SAFEARRAY*, ppsaOut : SAFEARRAY**) : HRESULT
fun safeArrayPtrOfIndex(psa : SAFEARRAY*, rgIndices : LibC::Int32*, ppvData : LibC::Void**) : HRESULT
fun safeArraySetRecordInfo(psa : SAFEARRAY*, prinfo : IRecordInfo) : HRESULT
fun safeArrayGetRecordInfo(psa : SAFEARRAY*, prinfo : IRecordInfo*) : HRESULT
fun safeArraySetIID(psa : SAFEARRAY*, guid : LibC::Guid*) : HRESULT
fun safeArrayGetIID(psa : SAFEARRAY*, pguid : LibC::Guid*) : HRESULT
fun safeArrayGetVartype(psa : SAFEARRAY*, pvt : LibC::UInt16*) : HRESULT
fun safeArrayCreateVector(vt : LibC::UInt16, lLbound : LibC::Int32, cElements : LibC::UInt32) : SAFEARRAY*
fun safeArrayCreateVectorEx(vt : LibC::UInt16, lLbound : LibC::Int32, cElements : LibC::UInt32, pvExtra : LibC::Void*) : SAFEARRAY*
fun variantInit(pvarg : VARIANT*) : LibC::Void
fun variantClear(pvarg : VARIANT*) : HRESULT
fun variantCopy(pvargDest : VARIANT*, pvargSrc : VARIANT*) : HRESULT
fun variantCopyInd(pvarDest : VARIANT*, pvargSrc : VARIANT*) : HRESULT
fun variantChangeType(pvargDest : VARIANT*, pvarSrc : VARIANT*, wFlags : LibC::UInt16, vt : LibC::UInt16) : HRESULT
fun variantChangeTypeEx(pvargDest : VARIANT*, pvarSrc : VARIANT*, lcid : LibC::UInt32, wFlags : LibC::UInt16, vt : LibC::UInt16) : HRESULT
fun vectorFromBstr(bstr : BSTR, ppsa : SAFEARRAY**) : HRESULT
fun bstrFromVector(psa : SAFEARRAY*, pbstr : BSTR*) : HRESULT
fun varUI1FromI2(sIn : LibC::Int16, pbOut : LibC::Byte*) : HRESULT
fun varUI1FromI4(lIn : LibC::Int32, pbOut : LibC::Byte*) : HRESULT
fun varUI1FromI8(i64In : LibC::Int64, pbOut : LibC::Byte*) : HRESULT
fun varUI1FromR4(fltIn : LibC::Single, pbOut : LibC::Byte*) : HRESULT
fun varUI1FromR8(dblIn : LibC::Double, pbOut : LibC::Byte*) : HRESULT
fun varUI1FromCy(cyIn : CY, pbOut : LibC::Byte*) : HRESULT
fun varUI1FromDate(dateIn : LibC::Double, pbOut : LibC::Byte*) : HRESULT
fun varUI1FromStr(strIn : PWSTR, lcid : LibC::UInt32, dwFlags : LibC::UInt32, pbOut : LibC::Byte*) : HRESULT
fun varUI1FromDisp(pdispIn : IDispatch, lcid : LibC::UInt32, pbOut : LibC::Byte*) : HRESULT
fun varUI1FromBool(boolIn : LibC::Int16, pbOut : LibC::Byte*) : HRESULT
fun varUI1FromI1(cIn : CHAR, pbOut : LibC::Byte*) : HRESULT
fun varUI1FromUI2(uiIn : LibC::UInt16, pbOut : LibC::Byte*) : HRESULT
fun varUI1FromUI4(ulIn : LibC::UInt32, pbOut : LibC::Byte*) : HRESULT
fun varUI1FromUI8(ui64In : LibC::UInt64, pbOut : LibC::Byte*) : HRESULT
fun varUI1FromDec(pdecIn : DECIMAL*, pbOut : LibC::Byte*) : HRESULT
fun varI2FromUI1(bIn : LibC::Byte, psOut : LibC::Int16*) : HRESULT
fun varI2FromI4(lIn : LibC::Int32, psOut : LibC::Int16*) : HRESULT
fun varI2FromI8(i64In : LibC::Int64, psOut : LibC::Int16*) : HRESULT
fun varI2FromR4(fltIn : LibC::Single, psOut : LibC::Int16*) : HRESULT
fun varI2FromR8(dblIn : LibC::Double, psOut : LibC::Int16*) : HRESULT
fun varI2FromCy(cyIn : CY, psOut : LibC::Int16*) : HRESULT
fun varI2FromDate(dateIn : LibC::Double, psOut : LibC::Int16*) : HRESULT
fun varI2FromStr(strIn : PWSTR, lcid : LibC::UInt32, dwFlags : LibC::UInt32, psOut : LibC::Int16*) : HRESULT
fun varI2FromDisp(pdispIn : IDispatch, lcid : LibC::UInt32, psOut : LibC::Int16*) : HRESULT
fun varI2FromBool(boolIn : LibC::Int16, psOut : LibC::Int16*) : HRESULT
fun varI2FromI1(cIn : CHAR, psOut : LibC::Int16*) : HRESULT
fun varI2FromUI2(uiIn : LibC::UInt16, psOut : LibC::Int16*) : HRESULT
fun varI2FromUI4(ulIn : LibC::UInt32, psOut : LibC::Int16*) : HRESULT
fun varI2FromUI8(ui64In : LibC::UInt64, psOut : LibC::Int16*) : HRESULT
fun varI2FromDec(pdecIn : DECIMAL*, psOut : LibC::Int16*) : HRESULT
fun varI4FromUI1(bIn : LibC::Byte, plOut : LibC::Int32*) : HRESULT
fun varI4FromI2(sIn : LibC::Int16, plOut : LibC::Int32*) : HRESULT
fun varI4FromI8(i64In : LibC::Int64, plOut : LibC::Int32*) : HRESULT
fun varI4FromR4(fltIn : LibC::Single, plOut : LibC::Int32*) : HRESULT
fun varI4FromR8(dblIn : LibC::Double, plOut : LibC::Int32*) : HRESULT
fun varI4FromCy(cyIn : CY, plOut : LibC::Int32*) : HRESULT
fun varI4FromDate(dateIn : LibC::Double, plOut : LibC::Int32*) : HRESULT
fun varI4FromStr(strIn : PWSTR, lcid : LibC::UInt32, dwFlags : LibC::UInt32, plOut : LibC::Int32*) : HRESULT
fun varI4FromDisp(pdispIn : IDispatch, lcid : LibC::UInt32, plOut : LibC::Int32*) : HRESULT
fun varI4FromBool(boolIn : LibC::Int16, plOut : LibC::Int32*) : HRESULT
fun varI4FromI1(cIn : CHAR, plOut : LibC::Int32*) : HRESULT
fun varI4FromUI2(uiIn : LibC::UInt16, plOut : LibC::Int32*) : HRESULT
fun varI4FromUI4(ulIn : LibC::UInt32, plOut : LibC::Int32*) : HRESULT
fun varI4FromUI8(ui64In : LibC::UInt64, plOut : LibC::Int32*) : HRESULT
fun varI4FromDec(pdecIn : DECIMAL*, plOut : LibC::Int32*) : HRESULT
fun varI8FromUI1(bIn : LibC::Byte, pi64Out : LibC::Int64*) : HRESULT
fun varI8FromI2(sIn : LibC::Int16, pi64Out : LibC::Int64*) : HRESULT
fun varI8FromR4(fltIn : LibC::Single, pi64Out : LibC::Int64*) : HRESULT
fun varI8FromR8(dblIn : LibC::Double, pi64Out : LibC::Int64*) : HRESULT
fun varI8FromCy(cyIn : CY, pi64Out : LibC::Int64*) : HRESULT
fun varI8FromDate(dateIn : LibC::Double, pi64Out : LibC::Int64*) : HRESULT
fun varI8FromStr(strIn : PWSTR, lcid : LibC::UInt32, dwFlags : LibC::UInt32, pi64Out : LibC::Int64*) : HRESULT
fun varI8FromDisp(pdispIn : IDispatch, lcid : LibC::UInt32, pi64Out : LibC::Int64*) : HRESULT
fun varI8FromBool(boolIn : LibC::Int16, pi64Out : LibC::Int64*) : HRESULT
fun varI8FromI1(cIn : CHAR, pi64Out : LibC::Int64*) : HRESULT
fun varI8FromUI2(uiIn : LibC::UInt16, pi64Out : LibC::Int64*) : HRESULT
fun varI8FromUI4(ulIn : LibC::UInt32, pi64Out : LibC::Int64*) : HRESULT
fun varI8FromUI8(ui64In : LibC::UInt64, pi64Out : LibC::Int64*) : HRESULT
fun varI8FromDec(pdecIn : DECIMAL*, pi64Out : LibC::Int64*) : HRESULT
fun varR4FromUI1(bIn : LibC::Byte, pfltOut : LibC::Single*) : HRESULT
fun varR4FromI2(sIn : LibC::Int16, pfltOut : LibC::Single*) : HRESULT
fun varR4FromI4(lIn : LibC::Int32, pfltOut : LibC::Single*) : HRESULT
fun varR4FromI8(i64In : LibC::Int64, pfltOut : LibC::Single*) : HRESULT
fun varR4FromR8(dblIn : LibC::Double, pfltOut : LibC::Single*) : HRESULT
fun varR4FromCy(cyIn : CY, pfltOut : LibC::Single*) : HRESULT
fun varR4FromDate(dateIn : LibC::Double, pfltOut : LibC::Single*) : HRESULT
fun varR4FromStr(strIn : PWSTR, lcid : LibC::UInt32, dwFlags : LibC::UInt32, pfltOut : LibC::Single*) : HRESULT
fun varR4FromDisp(pdispIn : IDispatch, lcid : LibC::UInt32, pfltOut : LibC::Single*) : HRESULT
fun varR4FromBool(boolIn : LibC::Int16, pfltOut : LibC::Single*) : HRESULT
fun varR4FromI1(cIn : CHAR, pfltOut : LibC::Single*) : HRESULT
fun varR4FromUI2(uiIn : LibC::UInt16, pfltOut : LibC::Single*) : HRESULT
fun varR4FromUI4(ulIn : LibC::UInt32, pfltOut : LibC::Single*) : HRESULT
fun varR4FromUI8(ui64In : LibC::UInt64, pfltOut : LibC::Single*) : HRESULT
fun varR4FromDec(pdecIn : DECIMAL*, pfltOut : LibC::Single*) : HRESULT
fun varR8FromUI1(bIn : LibC::Byte, pdblOut : LibC::Double*) : HRESULT
fun varR8FromI2(sIn : LibC::Int16, pdblOut : LibC::Double*) : HRESULT
fun varR8FromI4(lIn : LibC::Int32, pdblOut : LibC::Double*) : HRESULT
fun varR8FromI8(i64In : LibC::Int64, pdblOut : LibC::Double*) : HRESULT
fun varR8FromR4(fltIn : LibC::Single, pdblOut : LibC::Double*) : HRESULT
fun varR8FromCy(cyIn : CY, pdblOut : LibC::Double*) : HRESULT
fun varR8FromDate(dateIn : LibC::Double, pdblOut : LibC::Double*) : HRESULT
fun varR8FromStr(strIn : PWSTR, lcid : LibC::UInt32, dwFlags : LibC::UInt32, pdblOut : LibC::Double*) : HRESULT
fun varR8FromDisp(pdispIn : IDispatch, lcid : LibC::UInt32, pdblOut : LibC::Double*) : HRESULT
fun varR8FromBool(boolIn : LibC::Int16, pdblOut : LibC::Double*) : HRESULT
fun varR8FromI1(cIn : CHAR, pdblOut : LibC::Double*) : HRESULT
fun varR8FromUI2(uiIn : LibC::UInt16, pdblOut : LibC::Double*) : HRESULT
fun varR8FromUI4(ulIn : LibC::UInt32, pdblOut : LibC::Double*) : HRESULT
fun varR8FromUI8(ui64In : LibC::UInt64, pdblOut : LibC::Double*) : HRESULT
fun varR8FromDec(pdecIn : DECIMAL*, pdblOut : LibC::Double*) : HRESULT
fun varDateFromUI1(bIn : LibC::Byte, pdateOut : LibC::Double*) : HRESULT
fun varDateFromI2(sIn : LibC::Int16, pdateOut : LibC::Double*) : HRESULT
fun varDateFromI4(lIn : LibC::Int32, pdateOut : LibC::Double*) : HRESULT
fun varDateFromI8(i64In : LibC::Int64, pdateOut : LibC::Double*) : HRESULT
fun varDateFromR4(fltIn : LibC::Single, pdateOut : LibC::Double*) : HRESULT
fun varDateFromR8(dblIn : LibC::Double, pdateOut : LibC::Double*) : HRESULT
fun varDateFromCy(cyIn : CY, pdateOut : LibC::Double*) : HRESULT
fun varDateFromStr(strIn : PWSTR, lcid : LibC::UInt32, dwFlags : LibC::UInt32, pdateOut : LibC::Double*) : HRESULT
fun varDateFromDisp(pdispIn : IDispatch, lcid : LibC::UInt32, pdateOut : LibC::Double*) : HRESULT
fun varDateFromBool(boolIn : LibC::Int16, pdateOut : LibC::Double*) : HRESULT
fun varDateFromI1(cIn : CHAR, pdateOut : LibC::Double*) : HRESULT
fun varDateFromUI2(uiIn : LibC::UInt16, pdateOut : LibC::Double*) : HRESULT
fun varDateFromUI4(ulIn : LibC::UInt32, pdateOut : LibC::Double*) : HRESULT
fun varDateFromUI8(ui64In : LibC::UInt64, pdateOut : LibC::Double*) : HRESULT
fun varDateFromDec(pdecIn : DECIMAL*, pdateOut : LibC::Double*) : HRESULT
fun varCyFromUI1(bIn : LibC::Byte, pcyOut : CY*) : HRESULT
fun varCyFromI2(sIn : LibC::Int16, pcyOut : CY*) : HRESULT
fun varCyFromI4(lIn : LibC::Int32, pcyOut : CY*) : HRESULT
fun varCyFromI8(i64In : LibC::Int64, pcyOut : CY*) : HRESULT
fun varCyFromR4(fltIn : LibC::Single, pcyOut : CY*) : HRESULT
fun varCyFromR8(dblIn : LibC::Double, pcyOut : CY*) : HRESULT
fun varCyFromDate(dateIn : LibC::Double, pcyOut : CY*) : HRESULT
fun varCyFromStr(strIn : PWSTR, lcid : LibC::UInt32, dwFlags : LibC::UInt32, pcyOut : CY*) : HRESULT
fun varCyFromDisp(pdispIn : IDispatch, lcid : LibC::UInt32, pcyOut : CY*) : HRESULT
fun varCyFromBool(boolIn : LibC::Int16, pcyOut : CY*) : HRESULT
fun varCyFromI1(cIn : CHAR, pcyOut : CY*) : HRESULT
fun varCyFromUI2(uiIn : LibC::UInt16, pcyOut : CY*) : HRESULT
fun varCyFromUI4(ulIn : LibC::UInt32, pcyOut : CY*) : HRESULT
fun varCyFromUI8(ui64In : LibC::UInt64, pcyOut : CY*) : HRESULT
fun varCyFromDec(pdecIn : DECIMAL*, pcyOut : CY*) : HRESULT
fun varBstrFromUI1(bVal : LibC::Byte, lcid : LibC::UInt32, dwFlags : LibC::UInt32, pbstrOut : BSTR*) : HRESULT
fun varBstrFromI2(iVal : LibC::Int16, lcid : LibC::UInt32, dwFlags : LibC::UInt32, pbstrOut : BSTR*) : HRESULT
fun varBstrFromI4(lIn : LibC::Int32, lcid : LibC::UInt32, dwFlags : LibC::UInt32, pbstrOut : BSTR*) : HRESULT
fun varBstrFromI8(i64In : LibC::Int64, lcid : LibC::UInt32, dwFlags : LibC::UInt32, pbstrOut : BSTR*) : HRESULT
fun varBstrFromR4(fltIn : LibC::Single, lcid : LibC::UInt32, dwFlags : LibC::UInt32, pbstrOut : BSTR*) : HRESULT
fun varBstrFromR8(dblIn : LibC::Double, lcid : LibC::UInt32, dwFlags : LibC::UInt32, pbstrOut : BSTR*) : HRESULT
fun varBstrFromCy(cyIn : CY, lcid : LibC::UInt32, dwFlags : LibC::UInt32, pbstrOut : BSTR*) : HRESULT
fun varBstrFromDate(dateIn : LibC::Double, lcid : LibC::UInt32, dwFlags : LibC::UInt32, pbstrOut : BSTR*) : HRESULT
fun varBstrFromDisp(pdispIn : IDispatch, lcid : LibC::UInt32, dwFlags : LibC::UInt32, pbstrOut : BSTR*) : HRESULT
fun varBstrFromBool(boolIn : LibC::Int16, lcid : LibC::UInt32, dwFlags : LibC::UInt32, pbstrOut : BSTR*) : HRESULT
fun varBstrFromI1(cIn : CHAR, lcid : LibC::UInt32, dwFlags : LibC::UInt32, pbstrOut : BSTR*) : HRESULT
fun varBstrFromUI2(uiIn : LibC::UInt16, lcid : LibC::UInt32, dwFlags : LibC::UInt32, pbstrOut : BSTR*) : HRESULT
fun varBstrFromUI4(ulIn : LibC::UInt32, lcid : LibC::UInt32, dwFlags : LibC::UInt32, pbstrOut : BSTR*) : HRESULT
fun varBstrFromUI8(ui64In : LibC::UInt64, lcid : LibC::UInt32, dwFlags : LibC::UInt32, pbstrOut : BSTR*) : HRESULT
fun varBstrFromDec(pdecIn : DECIMAL*, lcid : LibC::UInt32, dwFlags : LibC::UInt32, pbstrOut : BSTR*) : HRESULT
fun varBoolFromUI1(bIn : LibC::Byte, pboolOut : LibC::Int16*) : HRESULT
fun varBoolFromI2(sIn : LibC::Int16, pboolOut : LibC::Int16*) : HRESULT
fun varBoolFromI4(lIn : LibC::Int32, pboolOut : LibC::Int16*) : HRESULT
fun varBoolFromI8(i64In : LibC::Int64, pboolOut : LibC::Int16*) : HRESULT
fun varBoolFromR4(fltIn : LibC::Single, pboolOut : LibC::Int16*) : HRESULT
fun varBoolFromR8(dblIn : LibC::Double, pboolOut : LibC::Int16*) : HRESULT
fun varBoolFromDate(dateIn : LibC::Double, pboolOut : LibC::Int16*) : HRESULT
fun varBoolFromCy(cyIn : CY, pboolOut : LibC::Int16*) : HRESULT
fun varBoolFromStr(strIn : PWSTR, lcid : LibC::UInt32, dwFlags : LibC::UInt32, pboolOut : LibC::Int16*) : HRESULT
fun varBoolFromDisp(pdispIn : IDispatch, lcid : LibC::UInt32, pboolOut : LibC::Int16*) : HRESULT
fun varBoolFromI1(cIn : CHAR, pboolOut : LibC::Int16*) : HRESULT
fun varBoolFromUI2(uiIn : LibC::UInt16, pboolOut : LibC::Int16*) : HRESULT
fun varBoolFromUI4(ulIn : LibC::UInt32, pboolOut : LibC::Int16*) : HRESULT
fun varBoolFromUI8(i64In : LibC::UInt64, pboolOut : LibC::Int16*) : HRESULT
fun varBoolFromDec(pdecIn : DECIMAL*, pboolOut : LibC::Int16*) : HRESULT
fun varI1FromUI1(bIn : LibC::Byte, pcOut : PSTR) : HRESULT
fun varI1FromI2(uiIn : LibC::Int16, pcOut : PSTR) : HRESULT
fun varI1FromI4(lIn : LibC::Int32, pcOut : PSTR) : HRESULT
fun varI1FromI8(i64In : LibC::Int64, pcOut : PSTR) : HRESULT
fun varI1FromR4(fltIn : LibC::Single, pcOut : PSTR) : HRESULT
fun varI1FromR8(dblIn : LibC::Double, pcOut : PSTR) : HRESULT
fun varI1FromDate(dateIn : LibC::Double, pcOut : PSTR) : HRESULT
fun varI1FromCy(cyIn : CY, pcOut : PSTR) : HRESULT
fun varI1FromStr(strIn : PWSTR, lcid : LibC::UInt32, dwFlags : LibC::UInt32, pcOut : PSTR) : HRESULT
fun varI1FromDisp(pdispIn : IDispatch, lcid : LibC::UInt32, pcOut : PSTR) : HRESULT
fun varI1FromBool(boolIn : LibC::Int16, pcOut : PSTR) : HRESULT
fun varI1FromUI2(uiIn : LibC::UInt16, pcOut : PSTR) : HRESULT
fun varI1FromUI4(ulIn : LibC::UInt32, pcOut : PSTR) : HRESULT
fun varI1FromUI8(i64In : LibC::UInt64, pcOut : PSTR) : HRESULT
fun varI1FromDec(pdecIn : DECIMAL*, pcOut : PSTR) : HRESULT
fun varUI2FromUI1(bIn : LibC::Byte, puiOut : LibC::UInt16*) : HRESULT
fun varUI2FromI2(uiIn : LibC::Int16, puiOut : LibC::UInt16*) : HRESULT
fun varUI2FromI4(lIn : LibC::Int32, puiOut : LibC::UInt16*) : HRESULT
fun varUI2FromI8(i64In : LibC::Int64, puiOut : LibC::UInt16*) : HRESULT
fun varUI2FromR4(fltIn : LibC::Single, puiOut : LibC::UInt16*) : HRESULT
fun varUI2FromR8(dblIn : LibC::Double, puiOut : LibC::UInt16*) : HRESULT
fun varUI2FromDate(dateIn : LibC::Double, puiOut : LibC::UInt16*) : HRESULT
fun varUI2FromCy(cyIn : CY, puiOut : LibC::UInt16*) : HRESULT
fun varUI2FromStr(strIn : PWSTR, lcid : LibC::UInt32, dwFlags : LibC::UInt32, puiOut : LibC::UInt16*) : HRESULT
fun varUI2FromDisp(pdispIn : IDispatch, lcid : LibC::UInt32, puiOut : LibC::UInt16*) : HRESULT
fun varUI2FromBool(boolIn : LibC::Int16, puiOut : LibC::UInt16*) : HRESULT
fun varUI2FromI1(cIn : CHAR, puiOut : LibC::UInt16*) : HRESULT
fun varUI2FromUI4(ulIn : LibC::UInt32, puiOut : LibC::UInt16*) : HRESULT
fun varUI2FromUI8(i64In : LibC::UInt64, puiOut : LibC::UInt16*) : HRESULT
fun varUI2FromDec(pdecIn : DECIMAL*, puiOut : LibC::UInt16*) : HRESULT
fun varUI4FromUI1(bIn : LibC::Byte, pulOut : LibC::UInt32*) : HRESULT
fun varUI4FromI2(uiIn : LibC::Int16, pulOut : LibC::UInt32*) : HRESULT
fun varUI4FromI4(lIn : LibC::Int32, pulOut : LibC::UInt32*) : HRESULT
fun varUI4FromI8(i64In : LibC::Int64, plOut : LibC::UInt32*) : HRESULT
fun varUI4FromR4(fltIn : LibC::Single, pulOut : LibC::UInt32*) : HRESULT
fun varUI4FromR8(dblIn : LibC::Double, pulOut : LibC::UInt32*) : HRESULT
fun varUI4FromDate(dateIn : LibC::Double, pulOut : LibC::UInt32*) : HRESULT
fun varUI4FromCy(cyIn : CY, pulOut : LibC::UInt32*) : HRESULT
fun varUI4FromStr(strIn : PWSTR, lcid : LibC::UInt32, dwFlags : LibC::UInt32, pulOut : LibC::UInt32*) : HRESULT
fun varUI4FromDisp(pdispIn : IDispatch, lcid : LibC::UInt32, pulOut : LibC::UInt32*) : HRESULT
fun varUI4FromBool(boolIn : LibC::Int16, pulOut : LibC::UInt32*) : HRESULT
fun varUI4FromI1(cIn : CHAR, pulOut : LibC::UInt32*) : HRESULT
fun varUI4FromUI2(uiIn : LibC::UInt16, pulOut : LibC::UInt32*) : HRESULT
fun varUI4FromUI8(ui64In : LibC::UInt64, plOut : LibC::UInt32*) : HRESULT
fun varUI4FromDec(pdecIn : DECIMAL*, pulOut : LibC::UInt32*) : HRESULT
fun varUI8FromUI1(bIn : LibC::Byte, pi64Out : LibC::UInt64*) : HRESULT
fun varUI8FromI2(sIn : LibC::Int16, pi64Out : LibC::UInt64*) : HRESULT
fun varUI8FromI8(ui64In : LibC::Int64, pi64Out : LibC::UInt64*) : HRESULT
fun varUI8FromR4(fltIn : LibC::Single, pi64Out : LibC::UInt64*) : HRESULT
fun varUI8FromR8(dblIn : LibC::Double, pi64Out : LibC::UInt64*) : HRESULT
fun varUI8FromCy(cyIn : CY, pi64Out : LibC::UInt64*) : HRESULT
fun varUI8FromDate(dateIn : LibC::Double, pi64Out : LibC::UInt64*) : HRESULT
fun varUI8FromStr(strIn : PWSTR, lcid : LibC::UInt32, dwFlags : LibC::UInt32, pi64Out : LibC::UInt64*) : HRESULT
fun varUI8FromDisp(pdispIn : IDispatch, lcid : LibC::UInt32, pi64Out : LibC::UInt64*) : HRESULT
fun varUI8FromBool(boolIn : LibC::Int16, pi64Out : LibC::UInt64*) : HRESULT
fun varUI8FromI1(cIn : CHAR, pi64Out : LibC::UInt64*) : HRESULT
fun varUI8FromUI2(uiIn : LibC::UInt16, pi64Out : LibC::UInt64*) : HRESULT
fun varUI8FromUI4(ulIn : LibC::UInt32, pi64Out : LibC::UInt64*) : HRESULT
fun varUI8FromDec(pdecIn : DECIMAL*, pi64Out : LibC::UInt64*) : HRESULT
fun varDecFromUI1(bIn : LibC::Byte, pdecOut : DECIMAL*) : HRESULT
fun varDecFromI2(uiIn : LibC::Int16, pdecOut : DECIMAL*) : HRESULT
fun varDecFromI4(lIn : LibC::Int32, pdecOut : DECIMAL*) : HRESULT
fun varDecFromI8(i64In : LibC::Int64, pdecOut : DECIMAL*) : HRESULT
fun varDecFromR4(fltIn : LibC::Single, pdecOut : DECIMAL*) : HRESULT
fun varDecFromR8(dblIn : LibC::Double, pdecOut : DECIMAL*) : HRESULT
fun varDecFromDate(dateIn : LibC::Double, pdecOut : DECIMAL*) : HRESULT
fun varDecFromCy(cyIn : CY, pdecOut : DECIMAL*) : HRESULT
fun varDecFromStr(strIn : PWSTR, lcid : LibC::UInt32, dwFlags : LibC::UInt32, pdecOut : DECIMAL*) : HRESULT
fun varDecFromDisp(pdispIn : IDispatch, lcid : LibC::UInt32, pdecOut : DECIMAL*) : HRESULT
fun varDecFromBool(boolIn : LibC::Int16, pdecOut : DECIMAL*) : HRESULT
fun varDecFromI1(cIn : CHAR, pdecOut : DECIMAL*) : HRESULT
fun varDecFromUI2(uiIn : LibC::UInt16, pdecOut : DECIMAL*) : HRESULT
fun varDecFromUI4(ulIn : LibC::UInt32, pdecOut : DECIMAL*) : HRESULT
fun varDecFromUI8(ui64In : LibC::UInt64, pdecOut : DECIMAL*) : HRESULT
fun varParseNumFromStr(strIn : PWSTR, lcid : LibC::UInt32, dwFlags : LibC::UInt32, pnumprs : NUMPARSE*, rgbDig : LibC::Byte*) : HRESULT
fun varNumFromParseNum(pnumprs : NUMPARSE*, rgbDig : LibC::Byte*, dwVtBits : LibC::UInt32, pvar : VARIANT*) : HRESULT
fun varAdd(pvarLeft : VARIANT*, pvarRight : VARIANT*, pvarResult : VARIANT*) : HRESULT
fun varAnd(pvarLeft : VARIANT*, pvarRight : VARIANT*, pvarResult : VARIANT*) : HRESULT
fun varCat(pvarLeft : VARIANT*, pvarRight : VARIANT*, pvarResult : VARIANT*) : HRESULT
fun varDiv(pvarLeft : VARIANT*, pvarRight : VARIANT*, pvarResult : VARIANT*) : HRESULT
fun varEqv(pvarLeft : VARIANT*, pvarRight : VARIANT*, pvarResult : VARIANT*) : HRESULT
fun varIdiv(pvarLeft : VARIANT*, pvarRight : VARIANT*, pvarResult : VARIANT*) : HRESULT
fun varImp(pvarLeft : VARIANT*, pvarRight : VARIANT*, pvarResult : VARIANT*) : HRESULT
fun varMod(pvarLeft : VARIANT*, pvarRight : VARIANT*, pvarResult : VARIANT*) : HRESULT
fun varMul(pvarLeft : VARIANT*, pvarRight : VARIANT*, pvarResult : VARIANT*) : HRESULT
fun varOr(pvarLeft : VARIANT*, pvarRight : VARIANT*, pvarResult : VARIANT*) : HRESULT
fun varPow(pvarLeft : VARIANT*, pvarRight : VARIANT*, pvarResult : VARIANT*) : HRESULT
fun varSub(pvarLeft : VARIANT*, pvarRight : VARIANT*, pvarResult : VARIANT*) : HRESULT
fun varXor(pvarLeft : VARIANT*, pvarRight : VARIANT*, pvarResult : VARIANT*) : HRESULT
fun varAbs(pvarIn : VARIANT*, pvarResult : VARIANT*) : HRESULT
fun varFix(pvarIn : VARIANT*, pvarResult : VARIANT*) : HRESULT
fun varInt(pvarIn : VARIANT*, pvarResult : VARIANT*) : HRESULT
fun varNeg(pvarIn : VARIANT*, pvarResult : VARIANT*) : HRESULT
fun varNot(pvarIn : VARIANT*, pvarResult : VARIANT*) : HRESULT
fun varRound(pvarIn : VARIANT*, cDecimals : LibC::Int32, pvarResult : VARIANT*) : HRESULT
fun varCmp(pvarLeft : VARIANT*, pvarRight : VARIANT*, lcid : LibC::UInt32, dwFlags : LibC::UInt32) : HRESULT
fun varDecAdd(pdecLeft : DECIMAL*, pdecRight : DECIMAL*, pdecResult : DECIMAL*) : HRESULT
fun varDecDiv(pdecLeft : DECIMAL*, pdecRight : DECIMAL*, pdecResult : DECIMAL*) : HRESULT
fun varDecMul(pdecLeft : DECIMAL*, pdecRight : DECIMAL*, pdecResult : DECIMAL*) : HRESULT
fun varDecSub(pdecLeft : DECIMAL*, pdecRight : DECIMAL*, pdecResult : DECIMAL*) : HRESULT
fun varDecAbs(pdecIn : DECIMAL*, pdecResult : DECIMAL*) : HRESULT
fun varDecFix(pdecIn : DECIMAL*, pdecResult : DECIMAL*) : HRESULT
fun varDecInt(pdecIn : DECIMAL*, pdecResult : DECIMAL*) : HRESULT
fun varDecNeg(pdecIn : DECIMAL*, pdecResult : DECIMAL*) : HRESULT
fun varDecRound(pdecIn : DECIMAL*, cDecimals : LibC::Int32, pdecResult : DECIMAL*) : HRESULT
fun varDecCmp(pdecLeft : DECIMAL*, pdecRight : DECIMAL*) : HRESULT
fun varDecCmpR8(pdecLeft : DECIMAL*, dblRight : LibC::Double) : HRESULT
fun varCyAdd(cyLeft : CY, cyRight : CY, pcyResult : CY*) : HRESULT
fun varCyMul(cyLeft : CY, cyRight : CY, pcyResult : CY*) : HRESULT
fun varCyMulI4(cyLeft : CY, lRight : LibC::Int32, pcyResult : CY*) : HRESULT
fun varCyMulI8(cyLeft : CY, lRight : LibC::Int64, pcyResult : CY*) : HRESULT
fun varCySub(cyLeft : CY, cyRight : CY, pcyResult : CY*) : HRESULT
fun varCyAbs(cyIn : CY, pcyResult : CY*) : HRESULT
fun varCyFix(cyIn : CY, pcyResult : CY*) : HRESULT
fun varCyInt(cyIn : CY, pcyResult : CY*) : HRESULT
fun varCyNeg(cyIn : CY, pcyResult : CY*) : HRESULT
fun varCyRound(cyIn : CY, cDecimals : LibC::Int32, pcyResult : CY*) : HRESULT
fun varCyCmp(cyLeft : CY, cyRight : CY) : HRESULT
fun varCyCmpR8(cyLeft : CY, dblRight : LibC::Double) : HRESULT
fun varBstrCat(bstrLeft : BSTR, bstrRight : BSTR, pbstrResult : LibC::UInt16**) : HRESULT
fun varBstrCmp(bstrLeft : BSTR, bstrRight : BSTR, lcid : LibC::UInt32, dwFlags : LibC::UInt32) : HRESULT
fun varR8Pow(dblLeft : LibC::Double, dblRight : LibC::Double, pdblResult : LibC::Double*) : HRESULT
fun varR4CmpR8(fltLeft : LibC::Single, dblRight : LibC::Double) : HRESULT
fun varR8Round(dblIn : LibC::Double, cDecimals : LibC::Int32, pdblResult : LibC::Double*) : HRESULT
fun varDateFromUdate(pudateIn : UDATE*, dwFlags : LibC::UInt32, pdateOut : LibC::Double*) : HRESULT
fun varDateFromUdateEx(pudateIn : UDATE*, lcid : LibC::UInt32, dwFlags : LibC::UInt32, pdateOut : LibC::Double*) : HRESULT
fun varUdateFromDate(dateIn : LibC::Double, dwFlags : LibC::UInt32, pudateOut : UDATE*) : HRESULT
fun getAltMonthNames(lcid : LibC::UInt32, prgp : PWSTR**) : HRESULT
fun varFormat(pvarIn : VARIANT*, pstrFormat : PWSTR, iFirstDay : LibC::Int32, iFirstWeek : LibC::Int32, dwFlags : LibC::UInt32, pbstrOut : BSTR*) : HRESULT
fun varFormatDateTime(pvarIn : VARIANT*, iNamedFormat : LibC::Int32, dwFlags : LibC::UInt32, pbstrOut : BSTR*) : HRESULT
fun varFormatNumber(pvarIn : VARIANT*, iNumDig : LibC::Int32, iIncLead : LibC::Int32, iUseParens : LibC::Int32, iGroup : LibC::Int32, dwFlags : LibC::UInt32, pbstrOut : BSTR*) : HRESULT
fun varFormatPercent(pvarIn : VARIANT*, iNumDig : LibC::Int32, iIncLead : LibC::Int32, iUseParens : LibC::Int32, iGroup : LibC::Int32, dwFlags : LibC::UInt32, pbstrOut : BSTR*) : HRESULT
fun varFormatCurrency(pvarIn : VARIANT*, iNumDig : LibC::Int32, iIncLead : LibC::Int32, iUseParens : LibC::Int32, iGroup : LibC::Int32, dwFlags : LibC::UInt32, pbstrOut : BSTR*) : HRESULT
fun varWeekdayName(iWeekday : LibC::Int32, fAbbrev : LibC::Int32, iFirstDay : LibC::Int32, dwFlags : LibC::UInt32, pbstrOut : BSTR*) : HRESULT
fun varMonthName(iMonth : LibC::Int32, fAbbrev : LibC::Int32, dwFlags : LibC::UInt32, pbstrOut : BSTR*) : HRESULT
fun varFormatFromTokens(pvarIn : VARIANT*, pstrFormat : PWSTR, pbTokCur : LibC::Byte*, dwFlags : LibC::UInt32, pbstrOut : BSTR*, lcid : LibC::UInt32) : HRESULT
fun lHashValOfNameSysA(syskind : SYSKIND, lcid : LibC::UInt32, szName : PSTR) : LibC::UInt32
fun lHashValOfNameSys(syskind : SYSKIND, lcid : LibC::UInt32, szName : PWSTR) : LibC::UInt32
fun loadTypeLib(szFile : PWSTR, pptlib : ITypeLib*) : HRESULT
fun loadTypeLibEx(szFile : PWSTR, regkind : REGKIND, pptlib : ITypeLib*) : HRESULT
fun loadRegTypeLib(rguid : LibC::Guid*, wVerMajor : LibC::UInt16, wVerMinor : LibC::UInt16, lcid : LibC::UInt32, pptlib : ITypeLib*) : HRESULT
fun queryPathOfRegTypeLib(guid : LibC::Guid*, wMaj : LibC::UInt16, wMin : LibC::UInt16, lcid : LibC::UInt32, lpbstrPathName : LibC::UInt16**) : HRESULT
fun registerTypeLib(ptlib : ITypeLib, szFullPath : PWSTR, szHelpDir : PWSTR) : HRESULT
fun unRegisterTypeLib(libID : LibC::Guid*, wVerMajor : LibC::UInt16, wVerMinor : LibC::UInt16, lcid : LibC::UInt32, syskind : SYSKIND) : HRESULT
fun registerTypeLibForUser(ptlib : ITypeLib, szFullPath : PWSTR, szHelpDir : PWSTR) : HRESULT
fun unRegisterTypeLibForUser(libID : LibC::Guid*, wMajorVerNum : LibC::UInt16, wMinorVerNum : LibC::UInt16, lcid : LibC::UInt32, syskind : SYSKIND) : HRESULT
fun createTypeLib(syskind : SYSKIND, szFile : PWSTR, ppctlib : ICreateTypeLib*) : HRESULT
fun createTypeLib2(syskind : SYSKIND, szFile : PWSTR, ppctlib : ICreateTypeLib2*) : HRESULT
fun dispGetParam(pdispparams : DISPPARAMS*, position : LibC::UInt32, vtTarg : LibC::UInt16, pvarResult : VARIANT*, puArgErr : LibC::UInt32*) : HRESULT
fun dispInvoke(this : LibC::Void*, ptinfo : ITypeInfo, dispidMember : LibC::Int32, wFlags : LibC::UInt16, pparams : DISPPARAMS*, pvarResult : VARIANT*, pexcepinfo : EXCEPINFO*, puArgErr : LibC::UInt32*) : HRESULT
fun createDispTypeInfo(pidata : INTERFACEDATA*, lcid : LibC::UInt32, pptinfo : ITypeInfo*) : HRESULT
fun createStdDispatch(punkOuter : IUnknown, pvThis : LibC::Void*, ptinfo : ITypeInfo, ppunkStdDisp : IUnknown*) : HRESULT
fun registerActiveObject(punk : IUnknown, rclsid : LibC::Guid*, dwFlags : LibC::UInt32, pdwRegister : LibC::UInt32*) : HRESULT
fun revokeActiveObject(dwRegister : LibC::UInt32, pvReserved : LibC::Void*) : HRESULT
fun getActiveObject(rclsid : LibC::Guid*, pvReserved : LibC::Void*, ppunk : IUnknown*) : HRESULT
fun createErrorInfo(pperrinfo : ICreateErrorInfo*) : HRESULT
fun getRecordInfoFromTypeInfo(pTypeInfo : ITypeInfo, ppRecInfo : IRecordInfo*) : HRESULT
fun getRecordInfoFromGuids(rGuidTypeLib : LibC::Guid*, uVerMajor : LibC::UInt32, uVerMinor : LibC::UInt32, lcid : LibC::UInt32, rGuidTypeInfo : LibC::Guid*, ppRecInfo : IRecordInfo*) : HRESULT
fun oaBuildVersion() : LibC::UInt32
fun clearCustData(pCustData : CUSTDATA*) : LibC::Void
fun oaEnablePerUserTLibRegistration() : LibC::Void
fun oleBuildVersion() : LibC::UInt32
fun oleInitialize(pvReserved : LibC::Void*) : HRESULT
fun oleUninitialize() : LibC::Void
fun oleQueryLinkFromData(pSrcDataObject : IDataObject) : HRESULT
fun oleQueryCreateFromData(pSrcDataObject : IDataObject) : HRESULT
fun oleCreate(rclsid : LibC::Guid*, riid : LibC::Guid*, renderopt : LibC::UInt32, pFormatEtc : FORMATETC*, pClientSite : IOleClientSite, pStg : IStorage, ppvObj : LibC::Void**) : HRESULT
fun oleCreateEx(rclsid : LibC::Guid*, riid : LibC::Guid*, dwFlags : LibC::UInt32, renderopt : LibC::UInt32, cFormats : LibC::UInt32, rgAdvf : LibC::UInt32*, rgFormatEtc : FORMATETC*, lpAdviseSink : IAdviseSink, rgdwConnection : LibC::UInt32*, pClientSite : IOleClientSite, pStg : IStorage, ppvObj : LibC::Void**) : HRESULT
fun oleCreateFromData(pSrcDataObj : IDataObject, riid : LibC::Guid*, renderopt : LibC::UInt32, pFormatEtc : FORMATETC*, pClientSite : IOleClientSite, pStg : IStorage, ppvObj : LibC::Void**) : HRESULT
fun oleCreateFromDataEx(pSrcDataObj : IDataObject, riid : LibC::Guid*, dwFlags : LibC::UInt32, renderopt : LibC::UInt32, cFormats : LibC::UInt32, rgAdvf : LibC::UInt32*, rgFormatEtc : FORMATETC*, lpAdviseSink : IAdviseSink, rgdwConnection : LibC::UInt32*, pClientSite : IOleClientSite, pStg : IStorage, ppvObj : LibC::Void**) : HRESULT
fun oleCreateLinkFromData(pSrcDataObj : IDataObject, riid : LibC::Guid*, renderopt : LibC::UInt32, pFormatEtc : FORMATETC*, pClientSite : IOleClientSite, pStg : IStorage, ppvObj : LibC::Void**) : HRESULT
fun oleCreateLinkFromDataEx(pSrcDataObj : IDataObject, riid : LibC::Guid*, dwFlags : LibC::UInt32, renderopt : LibC::UInt32, cFormats : LibC::UInt32, rgAdvf : LibC::UInt32*, rgFormatEtc : FORMATETC*, lpAdviseSink : IAdviseSink, rgdwConnection : LibC::UInt32*, pClientSite : IOleClientSite, pStg : IStorage, ppvObj : LibC::Void**) : HRESULT
fun oleCreateStaticFromData(pSrcDataObj : IDataObject, iid : LibC::Guid*, renderopt : LibC::UInt32, pFormatEtc : FORMATETC*, pClientSite : IOleClientSite, pStg : IStorage, ppvObj : LibC::Void**) : HRESULT
fun oleCreateLink(pmkLinkSrc : IMoniker, riid : LibC::Guid*, renderopt : LibC::UInt32, lpFormatEtc : FORMATETC*, pClientSite : IOleClientSite, pStg : IStorage, ppvObj : LibC::Void**) : HRESULT
fun oleCreateLinkEx(pmkLinkSrc : IMoniker, riid : LibC::Guid*, dwFlags : LibC::UInt32, renderopt : LibC::UInt32, cFormats : LibC::UInt32, rgAdvf : LibC::UInt32*, rgFormatEtc : FORMATETC*, lpAdviseSink : IAdviseSink, rgdwConnection : LibC::UInt32*, pClientSite : IOleClientSite, pStg : IStorage, ppvObj : LibC::Void**) : HRESULT
fun oleCreateLinkToFile(lpszFileName : PWSTR, riid : LibC::Guid*, renderopt : LibC::UInt32, lpFormatEtc : FORMATETC*, pClientSite : IOleClientSite, pStg : IStorage, ppvObj : LibC::Void**) : HRESULT
fun oleCreateLinkToFileEx(lpszFileName : PWSTR, riid : LibC::Guid*, dwFlags : LibC::UInt32, renderopt : LibC::UInt32, cFormats : LibC::UInt32, rgAdvf : LibC::UInt32*, rgFormatEtc : FORMATETC*, lpAdviseSink : IAdviseSink, rgdwConnection : LibC::UInt32*, pClientSite : IOleClientSite, pStg : IStorage, ppvObj : LibC::Void**) : HRESULT
fun oleCreateFromFile(rclsid : LibC::Guid*, lpszFileName : PWSTR, riid : LibC::Guid*, renderopt : LibC::UInt32, lpFormatEtc : FORMATETC*, pClientSite : IOleClientSite, pStg : IStorage, ppvObj : LibC::Void**) : HRESULT
fun oleCreateFromFileEx(rclsid : LibC::Guid*, lpszFileName : PWSTR, riid : LibC::Guid*, dwFlags : LibC::UInt32, renderopt : LibC::UInt32, cFormats : LibC::UInt32, rgAdvf : LibC::UInt32*, rgFormatEtc : FORMATETC*, lpAdviseSink : IAdviseSink, rgdwConnection : LibC::UInt32*, pClientSite : IOleClientSite, pStg : IStorage, ppvObj : LibC::Void**) : HRESULT
fun oleLoad(pStg : IStorage, riid : LibC::Guid*, pClientSite : IOleClientSite, ppvObj : LibC::Void**) : HRESULT
fun oleSave(pPS : IPersistStorage, pStg : IStorage, fSameAsLoad : BOOL) : HRESULT
fun oleLoadFromStream(pStm : IStream, iidInterface : LibC::Guid*, ppvObj : LibC::Void**) : HRESULT
fun oleSaveToStream(pPStm : IPersistStream, pStm : IStream) : HRESULT
fun oleSetContainedObject(pUnknown : IUnknown, fContained : BOOL) : HRESULT
fun oleNoteObjectVisible(pUnknown : IUnknown, fVisible : BOOL) : HRESULT
fun registerDragDrop(hwnd : HWND, pDropTarget : IDropTarget) : HRESULT
fun revokeDragDrop(hwnd : HWND) : HRESULT
fun doDragDrop(pDataObj : IDataObject, pDropSource : IDropSource, dwOKEffects : LibC::UInt32, pdwEffect : LibC::UInt32*) : HRESULT
fun oleSetClipboard(pDataObj : IDataObject) : HRESULT
fun oleGetClipboard(ppDataObj : IDataObject*) : HRESULT
fun oleGetClipboardWithEnterpriseInfo(dataObject : IDataObject*, dataEnterpriseId : PWSTR*, sourceDescription : PWSTR*, targetDescription : PWSTR*, dataDescription : PWSTR*) : HRESULT
fun oleFlushClipboard() : HRESULT
fun oleIsCurrentClipboard(pDataObj : IDataObject) : HRESULT
fun oleCreateMenuDescriptor(hmenuCombined : HMENU, lpMenuWidths : OleMenuGroupWidths*) : LibC::Int*
fun oleSetMenuDescriptor(holemenu : LibC::Int*, hwndFrame : HWND, hwndActiveObject : HWND, lpFrame : IOleInPlaceFrame, lpActiveObj : IOleInPlaceActiveObject) : HRESULT
fun oleDestroyMenuDescriptor(holemenu : LibC::Int*) : HRESULT
fun oleTranslateAccelerator(lpFrame : IOleInPlaceFrame, lpFrameInfo : OIFI*, lpmsg : MSG*) : HRESULT
fun oleDuplicateData(hSrc : HANDLE, cfFormat : LibC::UInt16, uiFlags : LibC::UInt32) : HANDLE
fun oleDraw(pUnknown : IUnknown, dwAspect : LibC::UInt32, hdcDraw : HDC, lprcBounds : RECT*) : HRESULT
fun oleRun(pUnknown : IUnknown) : HRESULT
fun oleIsRunning(pObject : IOleObject) : BOOL
fun oleLockRunning(pUnknown : IUnknown, fLock : BOOL, fLastUnlockCloses : BOOL) : HRESULT
fun releaseStgMedium(param0 : STGMEDIUM*) : LibC::Void
fun createOleAdviseHolder(ppOAHolder : IOleAdviseHolder*) : HRESULT
fun oleCreateDefaultHandler(clsid : LibC::Guid*, pUnkOuter : IUnknown, riid : LibC::Guid*, lplpObj : LibC::Void**) : HRESULT
fun oleCreateEmbeddingHelper(clsid : LibC::Guid*, pUnkOuter : IUnknown, flags : LibC::UInt32, pCF : IClassFactory, riid : LibC::Guid*, lplpObj : LibC::Void**) : HRESULT
fun isAccelerator(hAccel : HACCEL, cAccelEntries : LibC::Int32, lpMsg : MSG*, lpwCmd : LibC::UInt16*) : BOOL
fun oleGetIconOfFile(lpszPath : PWSTR, fUseFileAsLabel : BOOL) : LibC::Int*
fun oleGetIconOfClass(rclsid : LibC::Guid*, lpszLabel : PWSTR, fUseTypeAsLabel : BOOL) : LibC::Int*
fun oleMetafilePictFromIconAndLabel(hIcon : HICON, lpszLabel : PWSTR, lpszSourceFile : PWSTR, iIconIndex : LibC::UInt32) : LibC::Int*
fun oleRegGetUserType(clsid : LibC::Guid*, dwFormOfType : LibC::UInt32, pszUserType : PWSTR*) : HRESULT
fun oleRegGetMiscStatus(clsid : LibC::Guid*, dwAspect : LibC::UInt32, pdwStatus : LibC::UInt32*) : HRESULT
fun oleRegEnumFormatEtc(clsid : LibC::Guid*, dwDirection : LibC::UInt32, ppenum : IEnumFORMATETC*) : HRESULT
fun oleRegEnumVerbs(clsid : LibC::Guid*, ppenum : IEnumOLEVERB*) : HRESULT
fun oleDoAutoConvert(pStg : IStorage, pClsidNew : LibC::Guid*) : HRESULT
fun oleGetAutoConvert(clsidOld : LibC::Guid*, pClsidNew : LibC::Guid*) : HRESULT
fun oleSetAutoConvert(clsidOld : LibC::Guid*, clsidNew : LibC::Guid*) : HRESULT
fun hRGN_UserSize(param0 : LibC::UInt32*, param1 : LibC::UInt32, param2 : HRGN*) : LibC::UInt32
fun hRGN_UserMarshal(param0 : LibC::UInt32*, param1 : LibC::Byte*, param2 : HRGN*) : LibC::Byte*
fun hRGN_UserFree(param0 : LibC::UInt32*, param1 : HRGN*) : LibC::Void
fun hRGN_UserSize64(param0 : LibC::UInt32*, param1 : LibC::UInt32, param2 : HRGN*) : LibC::UInt32
fun hRGN_UserMarshal64(param0 : LibC::UInt32*, param1 : LibC::Byte*, param2 : HRGN*) : LibC::Byte*
fun hRGN_UserFree64(param0 : LibC::UInt32*, param1 : HRGN*) : LibC::Void
fun oleCreatePropertyFrame(hwndOwner : HWND, x : LibC::UInt32, y : LibC::UInt32, lpszCaption : PWSTR, cObjects : LibC::UInt32, ppUnk : IUnknown*, cPages : LibC::UInt32, pPageClsID : LibC::Guid*, lcid : LibC::UInt32, dwReserved : LibC::UInt32, pvReserved : LibC::Void*) : HRESULT
fun oleCreatePropertyFrameIndirect(lpParams : OCPFIPARAMS*) : HRESULT
fun oleTranslateColor(clr : LibC::UInt32, hpal : HPALETTE, lpcolorref : LibC::UInt32*) : HRESULT
fun oleCreateFontIndirect(lpFontDesc : FONTDESC*, riid : LibC::Guid*, lplpvObj : LibC::Void**) : HRESULT
fun oleCreatePictureIndirect(lpPictDesc : PICTDESC*, riid : LibC::Guid*, fOwn : BOOL, lplpvObj : LibC::Void**) : HRESULT
fun oleLoadPicture(lpstream : IStream, lSize : LibC::Int32, fRunmode : BOOL, riid : LibC::Guid*, lplpvObj : LibC::Void**) : HRESULT
fun oleLoadPictureEx(lpstream : IStream, lSize : LibC::Int32, fRunmode : BOOL, riid : LibC::Guid*, xSizeDesired : LibC::UInt32, ySizeDesired : LibC::UInt32, dwFlags : LibC::UInt32, lplpvObj : LibC::Void**) : HRESULT
fun oleLoadPicturePath(szURLorPath : PWSTR, punkCaller : IUnknown, dwReserved : LibC::UInt32, clrReserved : LibC::UInt32, riid : LibC::Guid*, ppvRet : LibC::Void**) : HRESULT
fun oleLoadPictureFile(varFileName : VARIANT, lplpdispPicture : IDispatch*) : HRESULT
fun oleLoadPictureFileEx(varFileName : VARIANT, xSizeDesired : LibC::UInt32, ySizeDesired : LibC::UInt32, dwFlags : LibC::UInt32, lplpdispPicture : IDispatch*) : HRESULT
fun oleSavePictureFile(lpdispPicture : IDispatch, bstrFileName : BSTR) : HRESULT
fun oleIconToCursor(hinstExe : HINSTANCE, hIcon : HICON) : HCURSOR
fun oleUIAddVerbMenuW(lpOleObj : IOleObject, lpszShortType : PWSTR, hMenu : HMENU, uPos : LibC::UInt32, uIDVerbMin : LibC::UInt32, uIDVerbMax : LibC::UInt32, bAddConvert : BOOL, idConvert : LibC::UInt32, lphMenu : HMENU*) : BOOL
fun oleUIAddVerbMenuA(lpOleObj : IOleObject, lpszShortType : PSTR, hMenu : HMENU, uPos : LibC::UInt32, uIDVerbMin : LibC::UInt32, uIDVerbMax : LibC::UInt32, bAddConvert : BOOL, idConvert : LibC::UInt32, lphMenu : HMENU*) : BOOL
fun oleUIInsertObjectW(param0 : OLEUIINSERTOBJECTW*) : LibC::UInt32
fun oleUIInsertObjectA(param0 : OLEUIINSERTOBJECTA*) : LibC::UInt32
fun oleUIPasteSpecialW(param0 : OLEUIPASTESPECIALW*) : LibC::UInt32
fun oleUIPasteSpecialA(param0 : OLEUIPASTESPECIALA*) : LibC::UInt32
fun oleUIEditLinksW(param0 : OLEUIEDITLINKSW*) : LibC::UInt32
fun oleUIEditLinksA(param0 : OLEUIEDITLINKSA*) : LibC::UInt32
fun oleUIChangeIconW(param0 : OLEUICHANGEICONW*) : LibC::UInt32
fun oleUIChangeIconA(param0 : OLEUICHANGEICONA*) : LibC::UInt32
fun oleUIConvertW(param0 : OLEUICONVERTW*) : LibC::UInt32
fun oleUIConvertA(param0 : OLEUICONVERTA*) : LibC::UInt32
fun oleUICanConvertOrActivateAs(rClsid : LibC::Guid*, fIsLinkedObject : BOOL, wFormat : LibC::UInt16) : BOOL
fun oleUIBusyW(param0 : OLEUIBUSYW*) : LibC::UInt32
fun oleUIBusyA(param0 : OLEUIBUSYA*) : LibC::UInt32
fun oleUIChangeSourceW(param0 : OLEUICHANGESOURCEW*) : LibC::UInt32
fun oleUIChangeSourceA(param0 : OLEUICHANGESOURCEA*) : LibC::UInt32
fun oleUIObjectPropertiesW(param0 : OLEUIOBJECTPROPSW*) : LibC::UInt32
fun oleUIObjectPropertiesA(param0 : OLEUIOBJECTPROPSA*) : LibC::UInt32
fun oleUIPromptUserW(nTemplate : LibC::Int32, hwndParent : HWND) : LibC::Int32
fun oleUIPromptUserA(nTemplate : LibC::Int32, hwndParent : HWND) : LibC::Int32
fun oleUIUpdateLinksW(lpOleUILinkCntr : IOleUILinkContainerW, hwndParent : HWND, lpszTitle : PWSTR, cLinks : LibC::Int32) : BOOL
fun oleUIUpdateLinksA(lpOleUILinkCntr : IOleUILinkContainerA, hwndParent : HWND, lpszTitle : PSTR, cLinks : LibC::Int32) : BOOL

  end
