  @[Link("UI.WindowsAndMessaging")]
  lib LibUIWindowsAndMessaging
    WM_DEVICECHANGE = 537
BSM_VXDS = 1
BSM_NETDRIVER = 2
BSM_INSTALLABLEDRIVERS = 4
RT_CURSOR = 1
RT_BITMAP = 2
RT_ICON = 3
RT_MENU = 4
RT_DIALOG = 5
RT_FONTDIR = 7
RT_FONT = 8
RT_ACCELERATOR = 9
RT_MESSAGETABLE = 11
DIFFERENCE = 11
RT_VERSION = 16
RT_DLGINCLUDE = 17
RT_PLUGPLAY = 19
RT_VXD = 20
RT_ANICURSOR = 21
RT_ANIICON = 22
RT_HTML = 23
RT_MANIFEST = 24
CREATEPROCESS_MANIFEST_RESOURCE_ID = 1
ISOLATIONAWARE_MANIFEST_RESOURCE_ID = 2
ISOLATIONAWARE_NOSTATICIMPORT_MANIFEST_RESOURCE_ID = 3
ISOLATIONPOLICY_MANIFEST_RESOURCE_ID = 4
ISOLATIONPOLICY_BROWSER_MANIFEST_RESOURCE_ID = 5
MINIMUM_RESERVED_MANIFEST_RESOURCE_ID = 1
MAXIMUM_RESERVED_MANIFEST_RESOURCE_ID = 16
SB_LINEUP = 0
SB_LINELEFT = 0
SB_LINEDOWN = 1
SB_LINERIGHT = 1
SB_PAGEUP = 2
SB_PAGELEFT = 2
SB_PAGEDOWN = 3
SB_PAGERIGHT = 3
SB_THUMBPOSITION = 4
SB_THUMBTRACK = 5
SB_TOP = 6
SB_LEFT = 6
SB_BOTTOM = 7
SB_RIGHT = 7
SB_ENDSCROLL = 8
HIDE_WINDOW = 0
SHOW_OPENWINDOW = 1
SHOW_ICONWINDOW = 2
SHOW_FULLSCREEN = 3
SHOW_OPENNOACTIVATE = 4
KF_EXTENDED = 256
KF_DLGMODE = 2048
KF_MENUMODE = 4096
KF_ALTDOWN = 8192
KF_REPEAT = 16384
KF_UP = 32768
WH_MIN = -1
WH_HARDWARE = 8
WH_MAX = 14
WH_MINHOOK = -1
WH_MAXHOOK = 14
HC_ACTION = 0
HC_GETNEXT = 1
HC_SKIP = 2
HC_NOREMOVE = 3
HC_NOREM = 3
HC_SYSMODALON = 4
HC_SYSMODALOFF = 5
HCBT_MOVESIZE = 0
HCBT_MINMAX = 1
HCBT_QS = 2
HCBT_CREATEWND = 3
HCBT_DESTROYWND = 4
HCBT_ACTIVATE = 5
HCBT_CLICKSKIPPED = 6
HCBT_KEYSKIPPED = 7
HCBT_SYSCOMMAND = 8
HCBT_SETFOCUS = 9
WTS_CONSOLE_CONNECT = 1
WTS_CONSOLE_DISCONNECT = 2
WTS_REMOTE_CONNECT = 3
WTS_REMOTE_DISCONNECT = 4
WTS_SESSION_LOGON = 5
WTS_SESSION_LOGOFF = 6
WTS_SESSION_LOCK = 7
WTS_SESSION_UNLOCK = 8
WTS_SESSION_REMOTE_CONTROL = 9
WTS_SESSION_CREATE = 10
WTS_SESSION_TERMINATE = 11
MSGF_DIALOGBOX = 0
MSGF_MESSAGEBOX = 1
MSGF_MENU = 2
MSGF_SCROLLBAR = 5
MSGF_NEXTWINDOW = 6
MSGF_MAX = 8
MSGF_USER = 4096
HSHELL_WINDOWCREATED = 1
HSHELL_WINDOWDESTROYED = 2
HSHELL_ACTIVATESHELLWINDOW = 3
HSHELL_WINDOWACTIVATED = 4
HSHELL_GETMINRECT = 5
HSHELL_REDRAW = 6
HSHELL_TASKMAN = 7
HSHELL_LANGUAGE = 8
HSHELL_SYSMENU = 9
HSHELL_ENDTASK = 10
HSHELL_ACCESSIBILITYSTATE = 11
HSHELL_APPCOMMAND = 12
HSHELL_WINDOWREPLACED = 13
HSHELL_WINDOWREPLACING = 14
HSHELL_MONITORCHANGED = 16
HSHELL_HIGHBIT = 32768
FAPPCOMMAND_MOUSE = 32768
FAPPCOMMAND_KEY = 0
FAPPCOMMAND_OEM = 4096
FAPPCOMMAND_MASK = 61440
LLMHF_INJECTED = 1
LLMHF_LOWER_IL_INJECTED = 2
HKL_PREV = 0
HKL_NEXT = 1
INPUTLANGCHANGE_SYSCHARSET = 1
INPUTLANGCHANGE_FORWARD = 2
INPUTLANGCHANGE_BACKWARD = 4
KL_NAMELENGTH = 9
DESKTOP_READOBJECTS = 1
DESKTOP_CREATEWINDOW = 2
DESKTOP_CREATEMENU = 4
DESKTOP_HOOKCONTROL = 8
DESKTOP_JOURNALRECORD = 16
DESKTOP_JOURNALPLAYBACK = 32
DESKTOP_ENUMERATE = 64
DESKTOP_WRITEOBJECTS = 128
DESKTOP_SWITCHDESKTOP = 256
DF_ALLOWOTHERACCOUNTHOOK = 1
WINSTA_ENUMDESKTOPS = 1
WINSTA_READATTRIBUTES = 2
WINSTA_ACCESSCLIPBOARD = 4
WINSTA_CREATEDESKTOP = 8
WINSTA_WRITEATTRIBUTES = 16
WINSTA_ACCESSGLOBALATOMS = 32
WINSTA_EXITWINDOWS = 64
WINSTA_ENUMERATE = 256
WINSTA_READSCREEN = 512
CWF_CREATE_ONLY = 1
WSF_VISIBLE = 1
UOI_TIMERPROC_EXCEPTION_SUPPRESSION = 7
WM_NULL = 0
WM_CREATE = 1
WM_DESTROY = 2
WM_MOVE = 3
WM_SIZE = 5
WM_ACTIVATE = 6
WA_INACTIVE = 0
WA_ACTIVE = 1
WA_CLICKACTIVE = 2
WM_SETFOCUS = 7
WM_KILLFOCUS = 8
WM_ENABLE = 10
WM_SETREDRAW = 11
WM_SETTEXT = 12
WM_GETTEXT = 13
WM_GETTEXTLENGTH = 14
WM_PAINT = 15
WM_CLOSE = 16
WM_QUERYENDSESSION = 17
WM_QUERYOPEN = 19
WM_ENDSESSION = 22
WM_QUIT = 18
WM_ERASEBKGND = 20
WM_SYSCOLORCHANGE = 21
WM_SHOWWINDOW = 24
WM_WININICHANGE = 26
WM_SETTINGCHANGE = 26
WM_DEVMODECHANGE = 27
WM_ACTIVATEAPP = 28
WM_FONTCHANGE = 29
WM_TIMECHANGE = 30
WM_CANCELMODE = 31
WM_SETCURSOR = 32
WM_MOUSEACTIVATE = 33
WM_CHILDACTIVATE = 34
WM_QUEUESYNC = 35
WM_GETMINMAXINFO = 36
WM_PAINTICON = 38
WM_ICONERASEBKGND = 39
WM_NEXTDLGCTL = 40
WM_SPOOLERSTATUS = 42
WM_DRAWITEM = 43
WM_MEASUREITEM = 44
WM_DELETEITEM = 45
WM_VKEYTOITEM = 46
WM_CHARTOITEM = 47
WM_SETFONT = 48
WM_GETFONT = 49
WM_SETHOTKEY = 50
WM_GETHOTKEY = 51
WM_QUERYDRAGICON = 55
WM_COMPAREITEM = 57
WM_GETOBJECT = 61
WM_COMPACTING = 65
WM_COMMNOTIFY = 68
WM_WINDOWPOSCHANGING = 70
WM_WINDOWPOSCHANGED = 71
WM_POWER = 72
PWR_OK = 1
PWR_FAIL = -1
PWR_SUSPENDREQUEST = 1
PWR_SUSPENDRESUME = 2
PWR_CRITICALRESUME = 3
WM_COPYDATA = 74
WM_CANCELJOURNAL = 75
WM_INPUTLANGCHANGEREQUEST = 80
WM_INPUTLANGCHANGE = 81
WM_TCARD = 82
WM_HELP = 83
WM_USERCHANGED = 84
WM_NOTIFYFORMAT = 85
NFR_ANSI = 1
NFR_UNICODE = 2
NF_QUERY = 3
NF_REQUERY = 4
WM_STYLECHANGING = 124
WM_STYLECHANGED = 125
WM_DISPLAYCHANGE = 126
WM_GETICON = 127
WM_SETICON = 128
WM_NCCREATE = 129
WM_NCDESTROY = 130
WM_NCCALCSIZE = 131
WM_NCHITTEST = 132
WM_NCPAINT = 133
WM_NCACTIVATE = 134
WM_GETDLGCODE = 135
WM_SYNCPAINT = 136
WM_NCMOUSEMOVE = 160
WM_NCLBUTTONDOWN = 161
WM_NCLBUTTONUP = 162
WM_NCLBUTTONDBLCLK = 163
WM_NCRBUTTONDOWN = 164
WM_NCRBUTTONUP = 165
WM_NCRBUTTONDBLCLK = 166
WM_NCMBUTTONDOWN = 167
WM_NCMBUTTONUP = 168
WM_NCMBUTTONDBLCLK = 169
WM_NCXBUTTONDOWN = 171
WM_NCXBUTTONUP = 172
WM_NCXBUTTONDBLCLK = 173
WM_INPUT_DEVICE_CHANGE = 254
WM_INPUT = 255
WM_KEYFIRST = 256
WM_KEYDOWN = 256
WM_KEYUP = 257
WM_CHAR = 258
WM_DEADCHAR = 259
WM_SYSKEYDOWN = 260
WM_SYSKEYUP = 261
WM_SYSCHAR = 262
WM_SYSDEADCHAR = 263
WM_KEYLAST = 265
UNICODE_NOCHAR = 65535
WM_IME_STARTCOMPOSITION = 269
WM_IME_ENDCOMPOSITION = 270
WM_IME_COMPOSITION = 271
WM_IME_KEYLAST = 271
WM_INITDIALOG = 272
WM_COMMAND = 273
WM_SYSCOMMAND = 274
WM_TIMER = 275
WM_HSCROLL = 276
WM_VSCROLL = 277
WM_INITMENU = 278
WM_INITMENUPOPUP = 279
WM_GESTURE = 281
WM_GESTURENOTIFY = 282
WM_MENUSELECT = 287
WM_MENUCHAR = 288
WM_ENTERIDLE = 289
WM_MENURBUTTONUP = 290
WM_MENUDRAG = 291
WM_MENUGETOBJECT = 292
WM_UNINITMENUPOPUP = 293
WM_MENUCOMMAND = 294
WM_CHANGEUISTATE = 295
WM_UPDATEUISTATE = 296
WM_QUERYUISTATE = 297
UIS_SET = 1
UIS_CLEAR = 2
UIS_INITIALIZE = 3
UISF_HIDEFOCUS = 1
UISF_HIDEACCEL = 2
UISF_ACTIVE = 4
WM_CTLCOLORMSGBOX = 306
WM_CTLCOLOREDIT = 307
WM_CTLCOLORLISTBOX = 308
WM_CTLCOLORBTN = 309
WM_CTLCOLORDLG = 310
WM_CTLCOLORSCROLLBAR = 311
WM_CTLCOLORSTATIC = 312
MN_GETHMENU = 481
WM_MOUSEFIRST = 512
WM_MOUSEMOVE = 512
WM_LBUTTONDOWN = 513
WM_LBUTTONUP = 514
WM_LBUTTONDBLCLK = 515
WM_RBUTTONDOWN = 516
WM_RBUTTONUP = 517
WM_RBUTTONDBLCLK = 518
WM_MBUTTONDOWN = 519
WM_MBUTTONUP = 520
WM_MBUTTONDBLCLK = 521
WM_MOUSEWHEEL = 522
WM_XBUTTONDOWN = 523
WM_XBUTTONUP = 524
WM_XBUTTONDBLCLK = 525
WM_MOUSEHWHEEL = 526
WM_MOUSELAST = 526
WHEEL_DELTA = 120
WM_PARENTNOTIFY = 528
WM_ENTERMENULOOP = 529
WM_EXITMENULOOP = 530
WM_NEXTMENU = 531
WM_SIZING = 532
WM_CAPTURECHANGED = 533
WM_MOVING = 534
WM_POWERBROADCAST = 536
PBT_APMQUERYSUSPEND = 0
PBT_APMQUERYSTANDBY = 1
PBT_APMQUERYSUSPENDFAILED = 2
PBT_APMQUERYSTANDBYFAILED = 3
PBT_APMSUSPEND = 4
PBT_APMSTANDBY = 5
PBT_APMRESUMECRITICAL = 6
PBT_APMRESUMESUSPEND = 7
PBT_APMRESUMESTANDBY = 8
PBTF_APMRESUMEFROMFAILURE = 1
PBT_APMBATTERYLOW = 9
PBT_APMPOWERSTATUSCHANGE = 10
PBT_APMOEMEVENT = 11
PBT_APMRESUMEAUTOMATIC = 18
PBT_POWERSETTINGCHANGE = 32787
WM_MDICREATE = 544
WM_MDIDESTROY = 545
WM_MDIACTIVATE = 546
WM_MDIRESTORE = 547
WM_MDINEXT = 548
WM_MDIMAXIMIZE = 549
WM_MDITILE = 550
WM_MDICASCADE = 551
WM_MDIICONARRANGE = 552
WM_MDIGETACTIVE = 553
WM_MDISETMENU = 560
WM_ENTERSIZEMOVE = 561
WM_EXITSIZEMOVE = 562
WM_DROPFILES = 563
WM_MDIREFRESHMENU = 564
WM_POINTERDEVICECHANGE = 568
WM_POINTERDEVICEINRANGE = 569
WM_POINTERDEVICEOUTOFRANGE = 570
WM_TOUCH = 576
WM_NCPOINTERUPDATE = 577
WM_NCPOINTERDOWN = 578
WM_NCPOINTERUP = 579
WM_POINTERUPDATE = 581
WM_POINTERDOWN = 582
WM_POINTERUP = 583
WM_POINTERENTER = 585
WM_POINTERLEAVE = 586
WM_POINTERACTIVATE = 587
WM_POINTERCAPTURECHANGED = 588
WM_TOUCHHITTESTING = 589
WM_POINTERWHEEL = 590
WM_POINTERHWHEEL = 591
DM_POINTERHITTEST = 592
WM_POINTERROUTEDTO = 593
WM_POINTERROUTEDAWAY = 594
WM_POINTERROUTEDRELEASED = 595
WM_IME_SETCONTEXT = 641
WM_IME_NOTIFY = 642
WM_IME_CONTROL = 643
WM_IME_COMPOSITIONFULL = 644
WM_IME_SELECT = 645
WM_IME_CHAR = 646
WM_IME_REQUEST = 648
WM_IME_KEYDOWN = 656
WM_IME_KEYUP = 657
WM_NCMOUSEHOVER = 672
WM_NCMOUSELEAVE = 674
WM_WTSSESSION_CHANGE = 689
WM_TABLET_FIRST = 704
WM_TABLET_LAST = 735
WM_DPICHANGED = 736
WM_DPICHANGED_BEFOREPARENT = 738
WM_DPICHANGED_AFTERPARENT = 739
WM_GETDPISCALEDSIZE = 740
WM_CUT = 768
WM_COPY = 769
WM_PASTE = 770
WM_CLEAR = 771
WM_UNDO = 772
WM_RENDERFORMAT = 773
WM_RENDERALLFORMATS = 774
WM_DESTROYCLIPBOARD = 775
WM_DRAWCLIPBOARD = 776
WM_PAINTCLIPBOARD = 777
WM_VSCROLLCLIPBOARD = 778
WM_SIZECLIPBOARD = 779
WM_ASKCBFORMATNAME = 780
WM_CHANGECBCHAIN = 781
WM_HSCROLLCLIPBOARD = 782
WM_QUERYNEWPALETTE = 783
WM_PALETTEISCHANGING = 784
WM_PALETTECHANGED = 785
WM_HOTKEY = 786
WM_PRINT = 791
WM_APPCOMMAND = 793
WM_THEMECHANGED = 794
WM_CLIPBOARDUPDATE = 797
WM_DWMCOMPOSITIONCHANGED = 798
WM_DWMNCRENDERINGCHANGED = 799
WM_DWMCOLORIZATIONCOLORCHANGED = 800
WM_DWMWINDOWMAXIMIZEDCHANGE = 801
WM_DWMSENDICONICTHUMBNAIL = 803
WM_DWMSENDICONICLIVEPREVIEWBITMAP = 806
WM_GETTITLEBARINFOEX = 831
WM_HANDHELDFIRST = 856
WM_HANDHELDLAST = 863
WM_AFXFIRST = 864
WM_AFXLAST = 895
WM_PENWINFIRST = 896
WM_PENWINLAST = 911
WM_APP = 32768
WM_USER = 1024
WMSZ_LEFT = 1
WMSZ_RIGHT = 2
WMSZ_TOP = 3
WMSZ_TOPLEFT = 4
WMSZ_TOPRIGHT = 5
WMSZ_BOTTOM = 6
WMSZ_BOTTOMLEFT = 7
WMSZ_BOTTOMRIGHT = 8
HTERROR = -2
HTTRANSPARENT = -1
HTNOWHERE = 0
HTCLIENT = 1
HTCAPTION = 2
HTSYSMENU = 3
HTGROWBOX = 4
HTSIZE = 4
HTMENU = 5
HTHSCROLL = 6
HTVSCROLL = 7
HTMINBUTTON = 8
HTMAXBUTTON = 9
HTLEFT = 10
HTRIGHT = 11
HTTOP = 12
HTTOPLEFT = 13
HTTOPRIGHT = 14
HTBOTTOM = 15
HTBOTTOMLEFT = 16
HTBOTTOMRIGHT = 17
HTBORDER = 18
HTREDUCE = 8
HTZOOM = 9
HTSIZEFIRST = 10
HTSIZELAST = 17
HTOBJECT = 19
HTCLOSE = 20
HTHELP = 21
MA_ACTIVATE = 1
MA_ACTIVATEANDEAT = 2
MA_NOACTIVATE = 3
MA_NOACTIVATEANDEAT = 4
ICON_SMALL = 0
ICON_BIG = 1
ICON_SMALL2 = 2
SIZE_RESTORED = 0
SIZE_MINIMIZED = 1
SIZE_MAXIMIZED = 2
SIZE_MAXSHOW = 3
SIZE_MAXHIDE = 4
SIZENORMAL = 0
SIZEICONIC = 1
SIZEFULLSCREEN = 2
SIZEZOOMSHOW = 3
SIZEZOOMHIDE = 4
WVR_ALIGNTOP = 16
WVR_ALIGNLEFT = 32
WVR_ALIGNBOTTOM = 64
WVR_ALIGNRIGHT = 128
WVR_HREDRAW = 256
WVR_VREDRAW = 512
WVR_VALIDRECTS = 1024
MK_LBUTTON = 1
MK_RBUTTON = 2
MK_SHIFT = 4
MK_CONTROL = 8
MK_MBUTTON = 16
MK_XBUTTON1 = 32
MK_XBUTTON2 = 64
PRF_CHECKVISIBLE = 1
PRF_NONCLIENT = 2
PRF_CLIENT = 4
PRF_ERASEBKGND = 8
PRF_CHILDREN = 16
PRF_OWNED = 32
IDANI_OPEN = 1
IDANI_CAPTION = 3
FVIRTKEY = 1
FNOINVERT = 2
FSHIFT = 4
FCONTROL = 8
FALT = 16
ODA_DRAWENTIRE = 1
ODA_SELECT = 2
ODA_FOCUS = 4
ODS_SELECTED = 1
ODS_GRAYED = 2
ODS_DISABLED = 4
ODS_CHECKED = 8
ODS_FOCUS = 16
ODS_DEFAULT = 32
ODS_COMBOBOXEDIT = 4096
ODS_HOTLIGHT = 64
ODS_INACTIVE = 128
ODS_NOACCEL = 256
ODS_NOFOCUSRECT = 512
IDHOT_SNAPWINDOW = -1
IDHOT_SNAPDESKTOP = -2
ENDSESSION_CLOSEAPP = 1
ENDSESSION_CRITICAL = 1073741824
ENDSESSION_LOGOFF = 2147483648
EWX_FORCE = 4
EWX_FORCEIFHUNG = 16
EWX_QUICKRESOLVE = 32
EWX_BOOTOPTIONS = 16777216
EWX_ARSO = 67108864
EWX_CHECK_SAFE_FOR_SERVER = 134217728
EWX_SYSTEM_INITIATED = 268435456
BROADCAST_QUERY_DENY = 1112363332
DEVICE_NOTIFY_ALL_INTERFACE_CLASSES = 4
HWND_MESSAGE = -3
ISMEX_NOSEND = 0
ISMEX_SEND = 1
ISMEX_NOTIFY = 2
ISMEX_CALLBACK = 4
ISMEX_REPLIED = 8
HWND_DESKTOP = 0
PW_RENDERFULLCONTENT = 2
HWND_TOP = 0
HWND_BOTTOM = 1
HWND_TOPMOST = -1
HWND_NOTOPMOST = -2
DLGWINDOWEXTRA = 30
POINTER_MOD_SHIFT = 4
POINTER_MOD_CTRL = 8
TOUCH_FLAG_NONE = 0
TOUCH_MASK_NONE = 0
TOUCH_MASK_CONTACTAREA = 1
TOUCH_MASK_ORIENTATION = 2
TOUCH_MASK_PRESSURE = 4
PEN_FLAG_NONE = 0
PEN_FLAG_BARREL = 1
PEN_FLAG_INVERTED = 2
PEN_FLAG_ERASER = 4
PEN_MASK_NONE = 0
PEN_MASK_PRESSURE = 1
PEN_MASK_ROTATION = 2
PEN_MASK_TILT_X = 4
PEN_MASK_TILT_Y = 8
POINTER_MESSAGE_FLAG_NEW = 1
POINTER_MESSAGE_FLAG_INRANGE = 2
POINTER_MESSAGE_FLAG_INCONTACT = 4
POINTER_MESSAGE_FLAG_FIRSTBUTTON = 16
POINTER_MESSAGE_FLAG_SECONDBUTTON = 32
POINTER_MESSAGE_FLAG_THIRDBUTTON = 64
POINTER_MESSAGE_FLAG_FOURTHBUTTON = 128
POINTER_MESSAGE_FLAG_FIFTHBUTTON = 256
POINTER_MESSAGE_FLAG_PRIMARY = 8192
POINTER_MESSAGE_FLAG_CONFIDENCE = 16384
POINTER_MESSAGE_FLAG_CANCELED = 32768
PA_ACTIVATE = 1
PA_NOACTIVATE = 3
MAX_TOUCH_COUNT = 256
TOUCH_HIT_TESTING_DEFAULT = 0
TOUCH_HIT_TESTING_CLIENT = 1
TOUCH_HIT_TESTING_NONE = 2
TOUCH_HIT_TESTING_PROXIMITY_CLOSEST = 0
TOUCH_HIT_TESTING_PROXIMITY_FARTHEST = 4095
GWFS_INCLUDE_ANCESTORS = 1
MAPVK_VK_TO_VSC = 0
MAPVK_VSC_TO_VK = 1
MAPVK_VK_TO_CHAR = 2
MAPVK_VSC_TO_VK_EX = 3
MAPVK_VK_TO_VSC_EX = 4
QS_TOUCH = 2048
QS_POINTER = 4096
USER_TIMER_MAXIMUM = 2147483647
USER_TIMER_MINIMUM = 10
TIMERV_DEFAULT_COALESCING = 0
TIMERV_NO_COALESCING = 4294967295
TIMERV_COALESCING_MIN = 1
TIMERV_COALESCING_MAX = 2147483637
SM_RESERVED1 = 24
SM_RESERVED2 = 25
SM_RESERVED3 = 26
SM_RESERVED4 = 27
SM_CMETRICS = 76
SM_CARETBLINKINGENABLED = 8194
SM_SYSTEMDOCKED = 8196
PMB_ACTIVE = 1
MNC_IGNORE = 0
MNC_CLOSE = 1
MNC_EXECUTE = 2
MNC_SELECT = 3
MND_CONTINUE = 0
MND_ENDMENU = 1
MNGO_NOINTERFACE = 0
MNGO_NOERROR = 1
DOF_EXECUTABLE = 32769
DOF_DOCUMENT = 32770
DOF_DIRECTORY = 32771
DOF_MULTIPLE = 32772
DOF_PROGMAN = 1
DOF_SHELLDATA = 2
DO_DROPFILE = 1162627398
DO_PRINTFILE = 1414419024
ASFW_ANY = 4294967295
DCX_EXCLUDEUPDATE = 256
HELPINFO_WINDOW = 1
HELPINFO_MENUITEM = 2
CTLCOLOR_MSGBOX = 0
CTLCOLOR_EDIT = 1
CTLCOLOR_LISTBOX = 2
CTLCOLOR_BTN = 3
CTLCOLOR_DLG = 4
CTLCOLOR_SCROLLBAR = 5
CTLCOLOR_STATIC = 6
CTLCOLOR_MAX = 7
COLOR_BTNHIGHLIGHT = 20
COLOR_BTNHILIGHT = 20
GW_MAX = 5
SC_SIZE = 61440
SC_MOVE = 61456
SC_MINIMIZE = 61472
SC_MAXIMIZE = 61488
SC_NEXTWINDOW = 61504
SC_PREVWINDOW = 61520
SC_CLOSE = 61536
SC_VSCROLL = 61552
SC_HSCROLL = 61568
SC_MOUSEMENU = 61584
SC_KEYMENU = 61696
SC_ARRANGE = 61712
SC_RESTORE = 61728
SC_TASKLIST = 61744
SC_HOTKEY = 61776
SC_DEFAULT = 61792
SC_MONITORPOWER = 61808
SC_CONTEXTHELP = 61824
SC_SEPARATOR = 61455
SCF_ISSECURE = 1
SC_ICON = 61472
SC_ZOOM = 61488
IDC_ARROW = 32512
IDC_IBEAM = 32513
IDC_WAIT = 32514
IDC_CROSS = 32515
IDC_UPARROW = 32516
IDC_SIZE = 32640
IDC_ICON = 32641
IDC_SIZENWSE = 32642
IDC_SIZENESW = 32643
IDC_SIZEWE = 32644
IDC_SIZENS = 32645
IDC_SIZEALL = 32646
IDC_NO = 32648
IDC_HAND = 32649
IDC_APPSTARTING = 32650
IDC_HELP = 32651
IDC_PIN = 32671
IDC_PERSON = 32672
CURSOR_CREATION_SCALING_NONE = 1
CURSOR_CREATION_SCALING_DEFAULT = 2
IMAGE_ENHMETAFILE = 3
LR_COLOR = 2
RES_ICON = 1
RES_CURSOR = 2
OBM_CLOSE = 32754
OBM_UPARROW = 32753
OBM_DNARROW = 32752
OBM_RGARROW = 32751
OBM_LFARROW = 32750
OBM_REDUCE = 32749
OBM_ZOOM = 32748
OBM_RESTORE = 32747
OBM_REDUCED = 32746
OBM_ZOOMD = 32745
OBM_RESTORED = 32744
OBM_UPARROWD = 32743
OBM_DNARROWD = 32742
OBM_RGARROWD = 32741
OBM_LFARROWD = 32740
OBM_MNARROW = 32739
OBM_COMBO = 32738
OBM_UPARROWI = 32737
OBM_DNARROWI = 32736
OBM_RGARROWI = 32735
OBM_LFARROWI = 32734
OBM_OLD_CLOSE = 32767
OBM_SIZE = 32766
OBM_OLD_UPARROW = 32765
OBM_OLD_DNARROW = 32764
OBM_OLD_RGARROW = 32763
OBM_OLD_LFARROW = 32762
OBM_BTSIZE = 32761
OBM_CHECK = 32760
OBM_CHECKBOXES = 32759
OBM_BTNCORNERS = 32758
OBM_OLD_REDUCE = 32757
OBM_OLD_ZOOM = 32756
OBM_OLD_RESTORE = 32755
OCR_SIZE = 32640
OCR_ICON = 32641
OCR_ICOCUR = 32647
OIC_SAMPLE = 32512
OIC_HAND = 32513
OIC_QUES = 32514
OIC_BANG = 32515
OIC_NOTE = 32516
OIC_WINLOGO = 32517
OIC_WARNING = 32515
OIC_ERROR = 32513
OIC_INFORMATION = 32516
OIC_SHIELD = 32518
ORD_LANGDRIVER = 1
IDI_APPLICATION = 32512
IDI_HAND = 32513
IDI_QUESTION = 32514
IDI_EXCLAMATION = 32515
IDI_ASTERISK = 32516
IDI_WINLOGO = 32517
IDI_SHIELD = 32518
IDI_WARNING = 32515
IDI_ERROR = 32513
IDI_INFORMATION = 32516
ES_LEFT = 0
ES_CENTER = 1
ES_RIGHT = 2
ES_MULTILINE = 4
ES_UPPERCASE = 8
ES_LOWERCASE = 16
ES_PASSWORD = 32
ES_AUTOVSCROLL = 64
ES_AUTOHSCROLL = 128
ES_NOHIDESEL = 256
ES_OEMCONVERT = 1024
ES_READONLY = 2048
ES_WANTRETURN = 4096
ES_NUMBER = 8192
EN_SETFOCUS = 256
EN_KILLFOCUS = 512
EN_CHANGE = 768
EN_UPDATE = 1024
EN_ERRSPACE = 1280
EN_MAXTEXT = 1281
EN_HSCROLL = 1537
EN_VSCROLL = 1538
EN_ALIGN_LTR_EC = 1792
EN_ALIGN_RTL_EC = 1793
EN_BEFORE_PASTE = 2048
EN_AFTER_PASTE = 2049
EC_LEFTMARGIN = 1
EC_RIGHTMARGIN = 2
EC_USEFONTINFO = 65535
EMSIS_COMPOSITIONSTRING = 1
EIMES_GETCOMPSTRATONCE = 1
EIMES_CANCELCOMPSTRINFOCUS = 2
EIMES_COMPLETECOMPSTRKILLFOCUS = 4
BS_PUSHBUTTON = 0
BS_DEFPUSHBUTTON = 1
BS_CHECKBOX = 2
BS_AUTOCHECKBOX = 3
BS_RADIOBUTTON = 4
BS_3STATE = 5
BS_AUTO3STATE = 6
BS_GROUPBOX = 7
BS_USERBUTTON = 8
BS_AUTORADIOBUTTON = 9
BS_PUSHBOX = 10
BS_OWNERDRAW = 11
BS_TYPEMASK = 15
BS_LEFTTEXT = 32
BS_TEXT = 0
BS_ICON = 64
BS_BITMAP = 128
BS_LEFT = 256
BS_RIGHT = 512
BS_CENTER = 768
BS_TOP = 1024
BS_BOTTOM = 2048
BS_VCENTER = 3072
BS_PUSHLIKE = 4096
BS_MULTILINE = 8192
BS_NOTIFY = 16384
BS_FLAT = 32768
BS_RIGHTBUTTON = 32
BN_CLICKED = 0
BN_PAINT = 1
BN_HILITE = 2
BN_UNHILITE = 3
BN_DISABLE = 4
BN_DOUBLECLICKED = 5
BN_PUSHED = 2
BN_UNPUSHED = 3
BN_DBLCLK = 5
BN_SETFOCUS = 6
BN_KILLFOCUS = 7
BM_GETCHECK = 240
BM_SETCHECK = 241
BM_GETSTATE = 242
BM_SETSTATE = 243
BM_SETSTYLE = 244
BM_CLICK = 245
BM_GETIMAGE = 246
BM_SETIMAGE = 247
BM_SETDONTCLICK = 248
BST_PUSHED = 4
BST_FOCUS = 8
SS_LEFT = 0
SS_CENTER = 1
SS_RIGHT = 2
SS_ICON = 3
SS_BLACKRECT = 4
SS_GRAYRECT = 5
SS_WHITERECT = 6
SS_BLACKFRAME = 7
SS_GRAYFRAME = 8
SS_WHITEFRAME = 9
SS_USERITEM = 10
SS_SIMPLE = 11
SS_LEFTNOWORDWRAP = 12
SS_OWNERDRAW = 13
SS_BITMAP = 14
SS_ENHMETAFILE = 15
SS_ETCHEDHORZ = 16
SS_ETCHEDVERT = 17
SS_ETCHEDFRAME = 18
SS_TYPEMASK = 31
SS_REALSIZECONTROL = 64
SS_NOPREFIX = 128
SS_NOTIFY = 256
SS_CENTERIMAGE = 512
SS_RIGHTJUST = 1024
SS_REALSIZEIMAGE = 2048
SS_SUNKEN = 4096
SS_EDITCONTROL = 8192
SS_ENDELLIPSIS = 16384
SS_PATHELLIPSIS = 32768
SS_WORDELLIPSIS = 49152
SS_ELLIPSISMASK = 49152
STM_SETICON = 368
STM_GETICON = 369
STM_SETIMAGE = 370
STM_GETIMAGE = 371
STN_CLICKED = 0
STN_DBLCLK = 1
STN_ENABLE = 2
STN_DISABLE = 3
STM_MSGMAX = 372
DWL_MSGRESULT = 0
DWL_DLGPROC = 4
DWL_USER = 8
DWLP_MSGRESULT = 0
DS_ABSALIGN = 1
DS_SYSMODAL = 2
DS_LOCALEDIT = 32
DS_SETFONT = 64
DS_MODALFRAME = 128
DS_NOIDLEMSG = 256
DS_SETFOREGROUND = 512
DS_3DLOOK = 4
DS_FIXEDSYS = 8
DS_NOFAILCREATE = 16
DS_CONTROL = 1024
DS_CENTER = 2048
DS_CENTERMOUSE = 4096
DS_CONTEXTHELP = 8192
DS_USEPIXELS = 32768
DM_GETDEFID = 1024
DM_SETDEFID = 1025
DM_REPOSITION = 1026
DC_HASDEFID = 21323
DLGC_WANTARROWS = 1
DLGC_WANTTAB = 2
DLGC_WANTALLKEYS = 4
DLGC_WANTMESSAGE = 4
DLGC_HASSETSEL = 8
DLGC_DEFPUSHBUTTON = 16
DLGC_UNDEFPUSHBUTTON = 32
DLGC_RADIOBUTTON = 64
DLGC_WANTCHARS = 128
DLGC_STATIC = 256
DLGC_BUTTON = 8192
LB_CTLCODE = 0
LB_OKAY = 0
LB_ERR = -1
LB_ERRSPACE = -2
LBN_ERRSPACE = -2
LBN_SELCHANGE = 1
LBN_DBLCLK = 2
LBN_SELCANCEL = 3
LBN_SETFOCUS = 4
LBN_KILLFOCUS = 5
LB_ADDSTRING = 384
LB_INSERTSTRING = 385
LB_DELETESTRING = 386
LB_SELITEMRANGEEX = 387
LB_RESETCONTENT = 388
LB_SETSEL = 389
LB_SETCURSEL = 390
LB_GETSEL = 391
LB_GETCURSEL = 392
LB_GETTEXT = 393
LB_GETTEXTLEN = 394
LB_GETCOUNT = 395
LB_SELECTSTRING = 396
LB_DIR = 397
LB_GETTOPINDEX = 398
LB_FINDSTRING = 399
LB_GETSELCOUNT = 400
LB_GETSELITEMS = 401
LB_SETTABSTOPS = 402
LB_GETHORIZONTALEXTENT = 403
LB_SETHORIZONTALEXTENT = 404
LB_SETCOLUMNWIDTH = 405
LB_ADDFILE = 406
LB_SETTOPINDEX = 407
LB_GETITEMRECT = 408
LB_GETITEMDATA = 409
LB_SETITEMDATA = 410
LB_SELITEMRANGE = 411
LB_SETANCHORINDEX = 412
LB_GETANCHORINDEX = 413
LB_SETCARETINDEX = 414
LB_GETCARETINDEX = 415
LB_SETITEMHEIGHT = 416
LB_GETITEMHEIGHT = 417
LB_FINDSTRINGEXACT = 418
LB_SETLOCALE = 421
LB_GETLOCALE = 422
LB_SETCOUNT = 423
LB_INITSTORAGE = 424
LB_ITEMFROMPOINT = 425
LB_MULTIPLEADDSTRING = 433
LB_GETLISTBOXINFO = 434
LB_MSGMAX = 435
LBS_NOTIFY = 1
LBS_SORT = 2
LBS_NOREDRAW = 4
LBS_MULTIPLESEL = 8
LBS_OWNERDRAWFIXED = 16
LBS_OWNERDRAWVARIABLE = 32
LBS_HASSTRINGS = 64
LBS_USETABSTOPS = 128
LBS_NOINTEGRALHEIGHT = 256
LBS_MULTICOLUMN = 512
LBS_WANTKEYBOARDINPUT = 1024
LBS_EXTENDEDSEL = 2048
LBS_DISABLENOSCROLL = 4096
LBS_NODATA = 8192
LBS_NOSEL = 16384
LBS_COMBOBOX = 32768
CB_OKAY = 0
CB_ERR = -1
CB_ERRSPACE = -2
CBN_ERRSPACE = -1
CBN_SELCHANGE = 1
CBN_DBLCLK = 2
CBN_SETFOCUS = 3
CBN_KILLFOCUS = 4
CBN_EDITCHANGE = 5
CBN_EDITUPDATE = 6
CBN_DROPDOWN = 7
CBN_CLOSEUP = 8
CBN_SELENDOK = 9
CBN_SELENDCANCEL = 10
CBS_SIMPLE = 1
CBS_DROPDOWN = 2
CBS_DROPDOWNLIST = 3
CBS_OWNERDRAWFIXED = 16
CBS_OWNERDRAWVARIABLE = 32
CBS_AUTOHSCROLL = 64
CBS_OEMCONVERT = 128
CBS_SORT = 256
CBS_HASSTRINGS = 512
CBS_NOINTEGRALHEIGHT = 1024
CBS_DISABLENOSCROLL = 2048
CBS_UPPERCASE = 8192
CBS_LOWERCASE = 16384
CB_GETEDITSEL = 320
CB_LIMITTEXT = 321
CB_SETEDITSEL = 322
CB_ADDSTRING = 323
CB_DELETESTRING = 324
CB_DIR = 325
CB_GETCOUNT = 326
CB_GETCURSEL = 327
CB_GETLBTEXT = 328
CB_GETLBTEXTLEN = 329
CB_INSERTSTRING = 330
CB_RESETCONTENT = 331
CB_FINDSTRING = 332
CB_SELECTSTRING = 333
CB_SETCURSEL = 334
CB_SHOWDROPDOWN = 335
CB_GETITEMDATA = 336
CB_SETITEMDATA = 337
CB_GETDROPPEDCONTROLRECT = 338
CB_SETITEMHEIGHT = 339
CB_GETITEMHEIGHT = 340
CB_SETEXTENDEDUI = 341
CB_GETEXTENDEDUI = 342
CB_GETDROPPEDSTATE = 343
CB_FINDSTRINGEXACT = 344
CB_SETLOCALE = 345
CB_GETLOCALE = 346
CB_GETTOPINDEX = 347
CB_SETTOPINDEX = 348
CB_GETHORIZONTALEXTENT = 349
CB_SETHORIZONTALEXTENT = 350
CB_GETDROPPEDWIDTH = 351
CB_SETDROPPEDWIDTH = 352
CB_INITSTORAGE = 353
CB_MULTIPLEADDSTRING = 355
CB_GETCOMBOBOXINFO = 356
CB_MSGMAX = 357
SBS_HORZ = 0
SBS_VERT = 1
SBS_TOPALIGN = 2
SBS_LEFTALIGN = 2
SBS_BOTTOMALIGN = 4
SBS_RIGHTALIGN = 4
SBS_SIZEBOXTOPLEFTALIGN = 2
SBS_SIZEBOXBOTTOMRIGHTALIGN = 4
SBS_SIZEBOX = 8
SBS_SIZEGRIP = 16
SBM_SETPOS = 224
SBM_GETPOS = 225
SBM_SETRANGE = 226
SBM_SETRANGEREDRAW = 230
SBM_GETRANGE = 227
SBM_ENABLE_ARROWS = 228
SBM_SETSCROLLINFO = 233
SBM_GETSCROLLINFO = 234
SBM_GETSCROLLBARINFO = 235
MDIS_ALLCHILDSTYLES = 1
HELP_CONTEXT = 1
HELP_QUIT = 2
HELP_INDEX = 3
HELP_CONTENTS = 3
HELP_HELPONHELP = 4
HELP_SETINDEX = 5
HELP_SETCONTENTS = 5
HELP_CONTEXTPOPUP = 8
HELP_FORCEFILE = 9
HELP_KEY = 257
HELP_COMMAND = 258
HELP_PARTIALKEY = 261
HELP_MULTIKEY = 513
HELP_SETWINPOS = 515
HELP_CONTEXTMENU = 10
HELP_FINDER = 11
HELP_WM_HELP = 12
HELP_SETPOPUP_POS = 13
HELP_TCARD = 32768
HELP_TCARD_DATA = 16
HELP_TCARD_OTHER_CALLER = 17
IDH_NO_HELP = 28440
IDH_MISSING_CONTEXT = 28441
IDH_GENERIC_HELP_BUTTON = 28442
IDH_OK = 28443
IDH_CANCEL = 28444
IDH_HELP = 28445
MAX_TOUCH_PREDICTION_FILTER_TAPS = 3
TOUCHPREDICTIONPARAMETERS_DEFAULT_LATENCY = 8
TOUCHPREDICTIONPARAMETERS_DEFAULT_SAMPLETIME = 8
TOUCHPREDICTIONPARAMETERS_DEFAULT_USE_HW_TIMESTAMP = 1
TOUCHPREDICTIONPARAMETERS_DEFAULT_RLS_DELTA = 0.001
TOUCHPREDICTIONPARAMETERS_DEFAULT_RLS_LAMBDA_MIN = 0.9
TOUCHPREDICTIONPARAMETERS_DEFAULT_RLS_LAMBDA_MAX = 0.999
TOUCHPREDICTIONPARAMETERS_DEFAULT_RLS_LAMBDA_LEARNING_RATE = 0.001
TOUCHPREDICTIONPARAMETERS_DEFAULT_RLS_EXPO_SMOOTH_ALPHA = 0.99
MAX_LOGICALDPIOVERRIDE = 2
MIN_LOGICALDPIOVERRIDE = -2
FE_FONTSMOOTHINGSTANDARD = 1
FE_FONTSMOOTHINGCLEARTYPE = 2
FE_FONTSMOOTHINGORIENTATIONBGR = 0
FE_FONTSMOOTHINGORIENTATIONRGB = 1
CONTACTVISUALIZATION_OFF = 0
CONTACTVISUALIZATION_ON = 1
CONTACTVISUALIZATION_PRESENTATIONMODE = 2
GESTUREVISUALIZATION_OFF = 0
GESTUREVISUALIZATION_ON = 31
GESTUREVISUALIZATION_TAP = 1
GESTUREVISUALIZATION_DOUBLETAP = 2
GESTUREVISUALIZATION_PRESSANDTAP = 4
GESTUREVISUALIZATION_PRESSANDHOLD = 8
GESTUREVISUALIZATION_RIGHTTAP = 16
MOUSEWHEEL_ROUTING_FOCUS = 0
MOUSEWHEEL_ROUTING_HYBRID = 1
MOUSEWHEEL_ROUTING_MOUSE_POS = 2
PENVISUALIZATION_ON = 35
PENVISUALIZATION_OFF = 0
PENVISUALIZATION_TAP = 1
PENVISUALIZATION_DOUBLETAP = 2
PENVISUALIZATION_CURSOR = 32
PENARBITRATIONTYPE_NONE = 0
PENARBITRATIONTYPE_WIN8 = 1
PENARBITRATIONTYPE_FIS = 2
PENARBITRATIONTYPE_SPT = 3
PENARBITRATIONTYPE_MAX = 4
METRICS_USEDEFAULT = -1
ARW_STARTMASK = 3
ARW_STARTRIGHT = 1
ARW_STARTTOP = 2
ARW_LEFT = 0
ARW_RIGHT = 0
ARW_UP = 4
ARW_DOWN = 4
ARW_HIDE = 8
HCF_LOGONDESKTOP = 256
HCF_DEFAULTDESKTOP = 512
EDS_RAWMODE = 2
EDS_ROTATEDMODE = 4
EDD_GET_DEVICE_INTERFACE_NAME = 1
FKF_FILTERKEYSON = 1
FKF_AVAILABLE = 2
FKF_HOTKEYACTIVE = 4
FKF_CONFIRMHOTKEY = 8
FKF_HOTKEYSOUND = 16
FKF_INDICATOR = 32
FKF_CLICKON = 64
MKF_MOUSEKEYSON = 1
MKF_AVAILABLE = 2
MKF_HOTKEYACTIVE = 4
MKF_CONFIRMHOTKEY = 8
MKF_HOTKEYSOUND = 16
MKF_INDICATOR = 32
MKF_MODIFIERS = 64
MKF_REPLACENUMBERS = 128
MKF_LEFTBUTTONSEL = 268435456
MKF_RIGHTBUTTONSEL = 536870912
MKF_LEFTBUTTONDOWN = 16777216
MKF_RIGHTBUTTONDOWN = 33554432
MKF_MOUSEMODE = 2147483648
TKF_TOGGLEKEYSON = 1
TKF_AVAILABLE = 2
TKF_HOTKEYACTIVE = 4
TKF_CONFIRMHOTKEY = 8
TKF_HOTKEYSOUND = 16
TKF_INDICATOR = 32
MONITORINFOF_PRIMARY = 1
WINEVENT_OUTOFCONTEXT = 0
WINEVENT_SKIPOWNTHREAD = 1
WINEVENT_SKIPOWNPROCESS = 2
WINEVENT_INCONTEXT = 4
CHILDID_SELF = 0
INDEXID_OBJECT = 0
INDEXID_CONTAINER = 0
EVENT_MIN = 1
EVENT_MAX = 2147483647
EVENT_SYSTEM_SOUND = 1
EVENT_SYSTEM_ALERT = 2
EVENT_SYSTEM_FOREGROUND = 3
EVENT_SYSTEM_MENUSTART = 4
EVENT_SYSTEM_MENUEND = 5
EVENT_SYSTEM_MENUPOPUPSTART = 6
EVENT_SYSTEM_MENUPOPUPEND = 7
EVENT_SYSTEM_CAPTURESTART = 8
EVENT_SYSTEM_CAPTUREEND = 9
EVENT_SYSTEM_MOVESIZESTART = 10
EVENT_SYSTEM_MOVESIZEEND = 11
EVENT_SYSTEM_CONTEXTHELPSTART = 12
EVENT_SYSTEM_CONTEXTHELPEND = 13
EVENT_SYSTEM_DRAGDROPSTART = 14
EVENT_SYSTEM_DRAGDROPEND = 15
EVENT_SYSTEM_DIALOGSTART = 16
EVENT_SYSTEM_DIALOGEND = 17
EVENT_SYSTEM_SCROLLINGSTART = 18
EVENT_SYSTEM_SCROLLINGEND = 19
EVENT_SYSTEM_SWITCHSTART = 20
EVENT_SYSTEM_SWITCHEND = 21
EVENT_SYSTEM_MINIMIZESTART = 22
EVENT_SYSTEM_MINIMIZEEND = 23
EVENT_SYSTEM_DESKTOPSWITCH = 32
EVENT_SYSTEM_SWITCHER_APPGRABBED = 36
EVENT_SYSTEM_SWITCHER_APPOVERTARGET = 37
EVENT_SYSTEM_SWITCHER_APPDROPPED = 38
EVENT_SYSTEM_SWITCHER_CANCELLED = 39
EVENT_SYSTEM_IME_KEY_NOTIFICATION = 41
EVENT_SYSTEM_END = 255
EVENT_OEM_DEFINED_START = 257
EVENT_OEM_DEFINED_END = 511
EVENT_UIA_EVENTID_START = 19968
EVENT_UIA_EVENTID_END = 20223
EVENT_UIA_PROPID_START = 29952
EVENT_UIA_PROPID_END = 30207
EVENT_CONSOLE_CARET = 16385
EVENT_CONSOLE_UPDATE_REGION = 16386
EVENT_CONSOLE_UPDATE_SIMPLE = 16387
EVENT_CONSOLE_UPDATE_SCROLL = 16388
EVENT_CONSOLE_LAYOUT = 16389
EVENT_CONSOLE_START_APPLICATION = 16390
EVENT_CONSOLE_END_APPLICATION = 16391
CONSOLE_APPLICATION_16BIT = 0
CONSOLE_CARET_SELECTION = 1
CONSOLE_CARET_VISIBLE = 2
EVENT_CONSOLE_END = 16639
EVENT_OBJECT_CREATE = 32768
EVENT_OBJECT_DESTROY = 32769
EVENT_OBJECT_SHOW = 32770
EVENT_OBJECT_HIDE = 32771
EVENT_OBJECT_REORDER = 32772
EVENT_OBJECT_FOCUS = 32773
EVENT_OBJECT_SELECTION = 32774
EVENT_OBJECT_SELECTIONADD = 32775
EVENT_OBJECT_SELECTIONREMOVE = 32776
EVENT_OBJECT_SELECTIONWITHIN = 32777
EVENT_OBJECT_STATECHANGE = 32778
EVENT_OBJECT_LOCATIONCHANGE = 32779
EVENT_OBJECT_NAMECHANGE = 32780
EVENT_OBJECT_DESCRIPTIONCHANGE = 32781
EVENT_OBJECT_VALUECHANGE = 32782
EVENT_OBJECT_PARENTCHANGE = 32783
EVENT_OBJECT_HELPCHANGE = 32784
EVENT_OBJECT_DEFACTIONCHANGE = 32785
EVENT_OBJECT_ACCELERATORCHANGE = 32786
EVENT_OBJECT_INVOKED = 32787
EVENT_OBJECT_TEXTSELECTIONCHANGED = 32788
EVENT_OBJECT_CONTENTSCROLLED = 32789
EVENT_SYSTEM_ARRANGMENTPREVIEW = 32790
EVENT_OBJECT_CLOAKED = 32791
EVENT_OBJECT_UNCLOAKED = 32792
EVENT_OBJECT_LIVEREGIONCHANGED = 32793
EVENT_OBJECT_HOSTEDOBJECTSINVALIDATED = 32800
EVENT_OBJECT_DRAGSTART = 32801
EVENT_OBJECT_DRAGCANCEL = 32802
EVENT_OBJECT_DRAGCOMPLETE = 32803
EVENT_OBJECT_DRAGENTER = 32804
EVENT_OBJECT_DRAGLEAVE = 32805
EVENT_OBJECT_DRAGDROPPED = 32806
EVENT_OBJECT_IME_SHOW = 32807
EVENT_OBJECT_IME_HIDE = 32808
EVENT_OBJECT_IME_CHANGE = 32809
EVENT_OBJECT_TEXTEDIT_CONVERSIONTARGETCHANGED = 32816
EVENT_OBJECT_END = 33023
EVENT_AIA_START = 40960
EVENT_AIA_END = 45055
SOUND_SYSTEM_STARTUP = 1
SOUND_SYSTEM_SHUTDOWN = 2
SOUND_SYSTEM_BEEP = 3
SOUND_SYSTEM_ERROR = 4
SOUND_SYSTEM_QUESTION = 5
SOUND_SYSTEM_WARNING = 6
SOUND_SYSTEM_INFORMATION = 7
SOUND_SYSTEM_MAXIMIZE = 8
SOUND_SYSTEM_MINIMIZE = 9
SOUND_SYSTEM_RESTOREUP = 10
SOUND_SYSTEM_RESTOREDOWN = 11
SOUND_SYSTEM_APPSTART = 12
SOUND_SYSTEM_FAULT = 13
SOUND_SYSTEM_APPEND = 14
SOUND_SYSTEM_MENUCOMMAND = 15
SOUND_SYSTEM_MENUPOPUP = 16
CSOUND_SYSTEM = 16
CALERT_SYSTEM = 6
GUI_16BITTASK = 0
USER_DEFAULT_SCREEN_DPI = 96
STATE_SYSTEM_SELECTED = 2
STATE_SYSTEM_FOCUSED = 4
STATE_SYSTEM_CHECKED = 16
STATE_SYSTEM_MIXED = 32
STATE_SYSTEM_INDETERMINATE = 32
STATE_SYSTEM_READONLY = 64
STATE_SYSTEM_HOTTRACKED = 128
STATE_SYSTEM_DEFAULT = 256
STATE_SYSTEM_EXPANDED = 512
STATE_SYSTEM_COLLAPSED = 1024
STATE_SYSTEM_BUSY = 2048
STATE_SYSTEM_FLOATING = 4096
STATE_SYSTEM_MARQUEED = 8192
STATE_SYSTEM_ANIMATED = 16384
STATE_SYSTEM_SIZEABLE = 131072
STATE_SYSTEM_MOVEABLE = 262144
STATE_SYSTEM_SELFVOICING = 524288
STATE_SYSTEM_SELECTABLE = 2097152
STATE_SYSTEM_LINKED = 4194304
STATE_SYSTEM_TRAVERSED = 8388608
STATE_SYSTEM_MULTISELECTABLE = 16777216
STATE_SYSTEM_EXTSELECTABLE = 33554432
STATE_SYSTEM_ALERT_LOW = 67108864
STATE_SYSTEM_ALERT_MEDIUM = 134217728
STATE_SYSTEM_ALERT_HIGH = 268435456
STATE_SYSTEM_PROTECTED = 536870912
STATE_SYSTEM_VALID = 1073741823
CCHILDREN_TITLEBAR = 5
CCHILDREN_SCROLLBAR = 5
RIM_INPUT = 0
RIM_INPUTSINK = 1
RIM_TYPEMAX = 2
RI_MOUSE_LEFT_BUTTON_DOWN = 1
RI_MOUSE_LEFT_BUTTON_UP = 2
RI_MOUSE_RIGHT_BUTTON_DOWN = 4
RI_MOUSE_RIGHT_BUTTON_UP = 8
RI_MOUSE_MIDDLE_BUTTON_DOWN = 16
RI_MOUSE_MIDDLE_BUTTON_UP = 32
RI_MOUSE_BUTTON_1_DOWN = 1
RI_MOUSE_BUTTON_1_UP = 2
RI_MOUSE_BUTTON_2_DOWN = 4
RI_MOUSE_BUTTON_2_UP = 8
RI_MOUSE_BUTTON_3_DOWN = 16
RI_MOUSE_BUTTON_3_UP = 32
RI_MOUSE_BUTTON_4_DOWN = 64
RI_MOUSE_BUTTON_4_UP = 128
RI_MOUSE_BUTTON_5_DOWN = 256
RI_MOUSE_BUTTON_5_UP = 512
RI_MOUSE_WHEEL = 1024
RI_MOUSE_HWHEEL = 2048
RI_KEY_MAKE = 0
RI_KEY_BREAK = 1
RI_KEY_E0 = 2
RI_KEY_E1 = 4
RI_KEY_TERMSRV_SET_LED = 8
RI_KEY_TERMSRV_SHADOW = 16
RIDEV_EXMODEMASK = 240
GIDC_ARRIVAL = 1
GIDC_REMOVAL = 2
POINTER_DEVICE_PRODUCT_STRING_MAX = 520
PDC_ARRIVAL = 1
PDC_REMOVAL = 2
PDC_ORIENTATION_0 = 4
PDC_ORIENTATION_90 = 8
PDC_ORIENTATION_180 = 16
PDC_ORIENTATION_270 = 32
PDC_MODE_DEFAULT = 64
PDC_MODE_CENTERED = 128
PDC_MAPPING_CHANGE = 256
PDC_RESOLUTION = 512
PDC_ORIGIN = 1024
PDC_MODE_ASPECTRATIOPRESERVED = 2048
GF_BEGIN = 1
GF_INERTIA = 2
GF_END = 4
GESTURECONFIGMAXCOUNT = 256
GCF_INCLUDE_ANCESTORS = 1
NID_INTEGRATED_TOUCH = 1
NID_EXTERNAL_TOUCH = 2
NID_INTEGRATED_PEN = 4
NID_EXTERNAL_PEN = 8
NID_MULTI_INPUT = 64
NID_READY = 128
MAX_STR_BLOCKREASON = 256
STRSAFE_USE_SECURE_CRT = 0
STRSAFE_MAX_CCH = 2147483647
STRSAFE_IGNORE_NULLS = 256
STRSAFE_FILL_BEHIND_NULL = 512
STRSAFE_FILL_ON_FAILURE = 1024
STRSAFE_NULL_ON_FAILURE = 2048
STRSAFE_NO_TRUNCATION = 4096
STRSAFE_E_INSUFFICIENT_BUFFER = -2147024774
STRSAFE_E_INVALID_PARAMETER = -2147024809
STRSAFE_E_END_OF_FILE = -2147024858
WARNING_CYCLOMATIC_COMPLEXITY = 28734
WARNING_USING_UNINIT_VAR = 6001
WARNING_RETURN_UNINIT_VAR = 6101
WARNING_DEREF_NULL_PTR = 6011
WARNING_MISSING_ZERO_TERMINATION2 = 6054
WARNING_INVALID_PARAM_VALUE_1 = 6387
WARNING_INCORRECT_ANNOTATION = 26007
WARNING_POTENTIAL_BUFFER_OVERFLOW_HIGH_PRIORITY = 26015
WARNING_PRECONDITION_NULLTERMINATION_VIOLATION = 26035
WARNING_POSTCONDITION_NULLTERMINATION_VIOLATION = 26036
WARNING_HIGH_PRIORITY_OVERFLOW_POSTCONDITION = 26045
WARNING_RANGE_POSTCONDITION_VIOLATION = 26061
WARNING_POTENTIAL_RANGE_POSTCONDITION_VIOLATION = 26071
WARNING_INVALID_PARAM_VALUE_3 = 28183
WARNING_RETURNING_BAD_RESULT = 28196
WARNING_BANNED_API_USAGE = 28719
WARNING_POST_EXPECTED = 28210
HBMMENU_CALLBACK = -1
HBMMENU_SYSTEM = 1
HBMMENU_MBAR_RESTORE = 2
HBMMENU_MBAR_MINIMIZE = 3
HBMMENU_MBAR_CLOSE = 5
HBMMENU_MBAR_CLOSE_D = 6
HBMMENU_MBAR_MINIMIZE_D = 7
HBMMENU_POPUP_CLOSE = 8
HBMMENU_POPUP_RESTORE = 9
HBMMENU_POPUP_MAXIMIZE = 10
HBMMENU_POPUP_MINIMIZE = 11
CW_USEDEFAULT = -2147483648
LBS_STANDARD = 10485763
enum WNDCLASS_STYLES : UInt32
CS_VREDRAW = 1

CS_HREDRAW = 2

CS_DBLCLKS = 8

CS_OWNDC = 32

CS_CLASSDC = 64

CS_PARENTDC = 128

CS_NOCLOSE = 512

CS_SAVEBITS = 2048

CS_BYTEALIGNCLIENT = 4096

CS_BYTEALIGNWINDOW = 8192

CS_GLOBALCLASS = 16384

CS_IME = 65536

CS_DROPSHADOW = 131072

end
enum CWP_FLAGS : UInt32
CWP_ALL = 0

CWP_SKIPINVISIBLE = 1

CWP_SKIPDISABLED = 2

CWP_SKIPTRANSPARENT = 4

end
enum MESSAGEBOX_STYLE : UInt32
MB_ABORTRETRYIGNORE = 2

MB_CANCELTRYCONTINUE = 6

MB_HELP = 16384

MB_OK = 0

MB_OKCANCEL = 1

MB_RETRYCANCEL = 5

MB_YESNO = 4

MB_YESNOCANCEL = 3

MB_ICONHAND = 16

MB_ICONQUESTION = 32

MB_ICONEXCLAMATION = 48

MB_ICONASTERISK = 64

MB_USERICON = 128

MB_ICONWARNING = 48

MB_ICONERROR = 16

MB_ICONINFORMATION = 64

MB_ICONSTOP = 16

MB_DEFBUTTON1 = 0

MB_DEFBUTTON2 = 256

MB_DEFBUTTON3 = 512

MB_DEFBUTTON4 = 768

MB_APPLMODAL = 0

MB_SYSTEMMODAL = 4096

MB_TASKMODAL = 8192

MB_NOFOCUS = 32768

MB_SETFOREGROUND = 65536

MB_DEFAULT_DESKTOP_ONLY = 131072

MB_TOPMOST = 262144

MB_RIGHT = 524288

MB_RTLREADING = 1048576

MB_SERVICE_NOTIFICATION = 2097152

MB_SERVICE_NOTIFICATION_NT3X = 262144

MB_TYPEMASK = 15

MB_ICONMASK = 240

MB_DEFMASK = 3840

MB_MODEMASK = 12288

MB_MISCMASK = 49152

end
enum MENU_ITEM_FLAGS : UInt32
MF_BYCOMMAND = 0

MF_BYPOSITION = 1024

MF_BITMAP = 4

MF_CHECKED = 8

MF_DISABLED = 2

MF_ENABLED = 0

MF_GRAYED = 1

MF_MENUBARBREAK = 32

MF_MENUBREAK = 64

MF_OWNERDRAW = 256

MF_POPUP = 16

MF_SEPARATOR = 2048

MF_STRING = 0

MF_UNCHECKED = 0

MF_INSERT = 0

MF_CHANGE = 128

MF_APPEND = 256

MF_DELETE = 512

MF_REMOVE = 4096

MF_USECHECKBITMAPS = 512

MF_UNHILITE = 0

MF_HILITE = 128

MF_DEFAULT = 4096

MF_SYSMENU = 8192

MF_HELP = 16384

MF_RIGHTJUSTIFY = 16384

MF_MOUSESELECT = 32768

MF_END = 128

end
enum SHOW_WINDOW_CMD : UInt32
SW_FORCEMINIMIZE = 11

SW_HIDE = 0

SW_MAXIMIZE = 3

SW_MINIMIZE = 6

SW_RESTORE = 9

SW_SHOW = 5

SW_SHOWDEFAULT = 10

SW_SHOWMAXIMIZED = 3

SW_SHOWMINIMIZED = 2

SW_SHOWMINNOACTIVE = 7

SW_SHOWNA = 8

SW_SHOWNOACTIVATE = 4

SW_SHOWNORMAL = 1

SW_NORMAL = 1

SW_MAX = 11

SW_PARENTCLOSING = 1

SW_OTHERZOOM = 2

SW_PARENTOPENING = 3

SW_OTHERUNZOOM = 4

SW_SCROLLCHILDREN = 1

SW_INVALIDATE = 2

SW_ERASE = 4

SW_SMOOTHSCROLL = 16

end
enum SYSTEM_PARAMETERS_INFO_ACTION : UInt32
SPI_GETBEEP = 1

SPI_SETBEEP = 2

SPI_GETMOUSE = 3

SPI_SETMOUSE = 4

SPI_GETBORDER = 5

SPI_SETBORDER = 6

SPI_GETKEYBOARDSPEED = 10

SPI_SETKEYBOARDSPEED = 11

SPI_LANGDRIVER = 12

SPI_ICONHORIZONTALSPACING = 13

SPI_GETSCREENSAVETIMEOUT = 14

SPI_SETSCREENSAVETIMEOUT = 15

SPI_GETSCREENSAVEACTIVE = 16

SPI_SETSCREENSAVEACTIVE = 17

SPI_GETGRIDGRANULARITY = 18

SPI_SETGRIDGRANULARITY = 19

SPI_SETDESKWALLPAPER = 20

SPI_SETDESKPATTERN = 21

SPI_GETKEYBOARDDELAY = 22

SPI_SETKEYBOARDDELAY = 23

SPI_ICONVERTICALSPACING = 24

SPI_GETICONTITLEWRAP = 25

SPI_SETICONTITLEWRAP = 26

SPI_GETMENUDROPALIGNMENT = 27

SPI_SETMENUDROPALIGNMENT = 28

SPI_SETDOUBLECLKWIDTH = 29

SPI_SETDOUBLECLKHEIGHT = 30

SPI_GETICONTITLELOGFONT = 31

SPI_SETDOUBLECLICKTIME = 32

SPI_SETMOUSEBUTTONSWAP = 33

SPI_SETICONTITLELOGFONT = 34

SPI_GETFASTTASKSWITCH = 35

SPI_SETFASTTASKSWITCH = 36

SPI_SETDRAGFULLWINDOWS = 37

SPI_GETDRAGFULLWINDOWS = 38

SPI_GETNONCLIENTMETRICS = 41

SPI_SETNONCLIENTMETRICS = 42

SPI_GETMINIMIZEDMETRICS = 43

SPI_SETMINIMIZEDMETRICS = 44

SPI_GETICONMETRICS = 45

SPI_SETICONMETRICS = 46

SPI_SETWORKAREA = 47

SPI_GETWORKAREA = 48

SPI_SETPENWINDOWS = 49

SPI_GETHIGHCONTRAST = 66

SPI_SETHIGHCONTRAST = 67

SPI_GETKEYBOARDPREF = 68

SPI_SETKEYBOARDPREF = 69

SPI_GETSCREENREADER = 70

SPI_SETSCREENREADER = 71

SPI_GETANIMATION = 72

SPI_SETANIMATION = 73

SPI_GETFONTSMOOTHING = 74

SPI_SETFONTSMOOTHING = 75

SPI_SETDRAGWIDTH = 76

SPI_SETDRAGHEIGHT = 77

SPI_SETHANDHELD = 78

SPI_GETLOWPOWERTIMEOUT = 79

SPI_GETPOWEROFFTIMEOUT = 80

SPI_SETLOWPOWERTIMEOUT = 81

SPI_SETPOWEROFFTIMEOUT = 82

SPI_GETLOWPOWERACTIVE = 83

SPI_GETPOWEROFFACTIVE = 84

SPI_SETLOWPOWERACTIVE = 85

SPI_SETPOWEROFFACTIVE = 86

SPI_SETCURSORS = 87

SPI_SETICONS = 88

SPI_GETDEFAULTINPUTLANG = 89

SPI_SETDEFAULTINPUTLANG = 90

SPI_SETLANGTOGGLE = 91

SPI_GETWINDOWSEXTENSION = 92

SPI_SETMOUSETRAILS = 93

SPI_GETMOUSETRAILS = 94

SPI_SETSCREENSAVERRUNNING = 97

SPI_SCREENSAVERRUNNING = 97

SPI_GETFILTERKEYS = 50

SPI_SETFILTERKEYS = 51

SPI_GETTOGGLEKEYS = 52

SPI_SETTOGGLEKEYS = 53

SPI_GETMOUSEKEYS = 54

SPI_SETMOUSEKEYS = 55

SPI_GETSHOWSOUNDS = 56

SPI_SETSHOWSOUNDS = 57

SPI_GETSTICKYKEYS = 58

SPI_SETSTICKYKEYS = 59

SPI_GETACCESSTIMEOUT = 60

SPI_SETACCESSTIMEOUT = 61

SPI_GETSERIALKEYS = 62

SPI_SETSERIALKEYS = 63

SPI_GETSOUNDSENTRY = 64

SPI_SETSOUNDSENTRY = 65

SPI_GETSNAPTODEFBUTTON = 95

SPI_SETSNAPTODEFBUTTON = 96

SPI_GETMOUSEHOVERWIDTH = 98

SPI_SETMOUSEHOVERWIDTH = 99

SPI_GETMOUSEHOVERHEIGHT = 100

SPI_SETMOUSEHOVERHEIGHT = 101

SPI_GETMOUSEHOVERTIME = 102

SPI_SETMOUSEHOVERTIME = 103

SPI_GETWHEELSCROLLLINES = 104

SPI_SETWHEELSCROLLLINES = 105

SPI_GETMENUSHOWDELAY = 106

SPI_SETMENUSHOWDELAY = 107

SPI_GETWHEELSCROLLCHARS = 108

SPI_SETWHEELSCROLLCHARS = 109

SPI_GETSHOWIMEUI = 110

SPI_SETSHOWIMEUI = 111

SPI_GETMOUSESPEED = 112

SPI_SETMOUSESPEED = 113

SPI_GETSCREENSAVERRUNNING = 114

SPI_GETDESKWALLPAPER = 115

SPI_GETAUDIODESCRIPTION = 116

SPI_SETAUDIODESCRIPTION = 117

SPI_GETSCREENSAVESECURE = 118

SPI_SETSCREENSAVESECURE = 119

SPI_GETHUNGAPPTIMEOUT = 120

SPI_SETHUNGAPPTIMEOUT = 121

SPI_GETWAITTOKILLTIMEOUT = 122

SPI_SETWAITTOKILLTIMEOUT = 123

SPI_GETWAITTOKILLSERVICETIMEOUT = 124

SPI_SETWAITTOKILLSERVICETIMEOUT = 125

SPI_GETMOUSEDOCKTHRESHOLD = 126

SPI_SETMOUSEDOCKTHRESHOLD = 127

SPI_GETPENDOCKTHRESHOLD = 128

SPI_SETPENDOCKTHRESHOLD = 129

SPI_GETWINARRANGING = 130

SPI_SETWINARRANGING = 131

SPI_GETMOUSEDRAGOUTTHRESHOLD = 132

SPI_SETMOUSEDRAGOUTTHRESHOLD = 133

SPI_GETPENDRAGOUTTHRESHOLD = 134

SPI_SETPENDRAGOUTTHRESHOLD = 135

SPI_GETMOUSESIDEMOVETHRESHOLD = 136

SPI_SETMOUSESIDEMOVETHRESHOLD = 137

SPI_GETPENSIDEMOVETHRESHOLD = 138

SPI_SETPENSIDEMOVETHRESHOLD = 139

SPI_GETDRAGFROMMAXIMIZE = 140

SPI_SETDRAGFROMMAXIMIZE = 141

SPI_GETSNAPSIZING = 142

SPI_SETSNAPSIZING = 143

SPI_GETDOCKMOVING = 144

SPI_SETDOCKMOVING = 145

SPI_GETTOUCHPREDICTIONPARAMETERS = 156

SPI_SETTOUCHPREDICTIONPARAMETERS = 157

SPI_GETLOGICALDPIOVERRIDE = 158

SPI_SETLOGICALDPIOVERRIDE = 159

SPI_GETMENURECT = 162

SPI_SETMENURECT = 163

SPI_GETACTIVEWINDOWTRACKING = 4096

SPI_SETACTIVEWINDOWTRACKING = 4097

SPI_GETMENUANIMATION = 4098

SPI_SETMENUANIMATION = 4099

SPI_GETCOMBOBOXANIMATION = 4100

SPI_SETCOMBOBOXANIMATION = 4101

SPI_GETLISTBOXSMOOTHSCROLLING = 4102

SPI_SETLISTBOXSMOOTHSCROLLING = 4103

SPI_GETGRADIENTCAPTIONS = 4104

SPI_SETGRADIENTCAPTIONS = 4105

SPI_GETKEYBOARDCUES = 4106

SPI_SETKEYBOARDCUES = 4107

SPI_GETMENUUNDERLINES = 4106

SPI_SETMENUUNDERLINES = 4107

SPI_GETACTIVEWNDTRKZORDER = 4108

SPI_SETACTIVEWNDTRKZORDER = 4109

SPI_GETHOTTRACKING = 4110

SPI_SETHOTTRACKING = 4111

SPI_GETMENUFADE = 4114

SPI_SETMENUFADE = 4115

SPI_GETSELECTIONFADE = 4116

SPI_SETSELECTIONFADE = 4117

SPI_GETTOOLTIPANIMATION = 4118

SPI_SETTOOLTIPANIMATION = 4119

SPI_GETTOOLTIPFADE = 4120

SPI_SETTOOLTIPFADE = 4121

SPI_GETCURSORSHADOW = 4122

SPI_SETCURSORSHADOW = 4123

SPI_GETMOUSESONAR = 4124

SPI_SETMOUSESONAR = 4125

SPI_GETMOUSECLICKLOCK = 4126

SPI_SETMOUSECLICKLOCK = 4127

SPI_GETMOUSEVANISH = 4128

SPI_SETMOUSEVANISH = 4129

SPI_GETFLATMENU = 4130

SPI_SETFLATMENU = 4131

SPI_GETDROPSHADOW = 4132

SPI_SETDROPSHADOW = 4133

SPI_GETBLOCKSENDINPUTRESETS = 4134

SPI_SETBLOCKSENDINPUTRESETS = 4135

SPI_GETUIEFFECTS = 4158

SPI_SETUIEFFECTS = 4159

SPI_GETDISABLEOVERLAPPEDCONTENT = 4160

SPI_SETDISABLEOVERLAPPEDCONTENT = 4161

SPI_GETCLIENTAREAANIMATION = 4162

SPI_SETCLIENTAREAANIMATION = 4163

SPI_GETCLEARTYPE = 4168

SPI_SETCLEARTYPE = 4169

SPI_GETSPEECHRECOGNITION = 4170

SPI_SETSPEECHRECOGNITION = 4171

SPI_GETCARETBROWSING = 4172

SPI_SETCARETBROWSING = 4173

SPI_GETTHREADLOCALINPUTSETTINGS = 4174

SPI_SETTHREADLOCALINPUTSETTINGS = 4175

SPI_GETSYSTEMLANGUAGEBAR = 4176

SPI_SETSYSTEMLANGUAGEBAR = 4177

SPI_GETFOREGROUNDLOCKTIMEOUT = 8192

SPI_SETFOREGROUNDLOCKTIMEOUT = 8193

SPI_GETACTIVEWNDTRKTIMEOUT = 8194

SPI_SETACTIVEWNDTRKTIMEOUT = 8195

SPI_GETFOREGROUNDFLASHCOUNT = 8196

SPI_SETFOREGROUNDFLASHCOUNT = 8197

SPI_GETCARETWIDTH = 8198

SPI_SETCARETWIDTH = 8199

SPI_GETMOUSECLICKLOCKTIME = 8200

SPI_SETMOUSECLICKLOCKTIME = 8201

SPI_GETFONTSMOOTHINGTYPE = 8202

SPI_SETFONTSMOOTHINGTYPE = 8203

SPI_GETFONTSMOOTHINGCONTRAST = 8204

SPI_SETFONTSMOOTHINGCONTRAST = 8205

SPI_GETFOCUSBORDERWIDTH = 8206

SPI_SETFOCUSBORDERWIDTH = 8207

SPI_GETFOCUSBORDERHEIGHT = 8208

SPI_SETFOCUSBORDERHEIGHT = 8209

SPI_GETFONTSMOOTHINGORIENTATION = 8210

SPI_SETFONTSMOOTHINGORIENTATION = 8211

SPI_GETMINIMUMHITRADIUS = 8212

SPI_SETMINIMUMHITRADIUS = 8213

SPI_GETMESSAGEDURATION = 8214

SPI_SETMESSAGEDURATION = 8215

SPI_GETCONTACTVISUALIZATION = 8216

SPI_SETCONTACTVISUALIZATION = 8217

SPI_GETGESTUREVISUALIZATION = 8218

SPI_SETGESTUREVISUALIZATION = 8219

SPI_GETMOUSEWHEELROUTING = 8220

SPI_SETMOUSEWHEELROUTING = 8221

SPI_GETPENVISUALIZATION = 8222

SPI_SETPENVISUALIZATION = 8223

SPI_GETPENARBITRATIONTYPE = 8224

SPI_SETPENARBITRATIONTYPE = 8225

SPI_GETCARETTIMEOUT = 8226

SPI_SETCARETTIMEOUT = 8227

SPI_GETHANDEDNESS = 8228

SPI_SETHANDEDNESS = 8229

end
enum TRACK_POPUP_MENU_FLAGS : UInt32
TPM_LEFTBUTTON = 0

TPM_RIGHTBUTTON = 2

TPM_LEFTALIGN = 0

TPM_CENTERALIGN = 4

TPM_RIGHTALIGN = 8

TPM_TOPALIGN = 0

TPM_VCENTERALIGN = 16

TPM_BOTTOMALIGN = 32

TPM_HORIZONTAL = 0

TPM_VERTICAL = 64

TPM_NONOTIFY = 128

TPM_RETURNCMD = 256

TPM_RECURSE = 1

TPM_HORPOSANIMATION = 1024

TPM_HORNEGANIMATION = 2048

TPM_VERPOSANIMATION = 4096

TPM_VERNEGANIMATION = 8192

TPM_NOANIMATION = 16384

TPM_LAYOUTRTL = 32768

TPM_WORKAREA = 65536

end
enum WINDOW_EX_STYLE : UInt32
WS_EX_DLGMODALFRAME = 1

WS_EX_NOPARENTNOTIFY = 4

WS_EX_TOPMOST = 8

WS_EX_ACCEPTFILES = 16

WS_EX_TRANSPARENT = 32

WS_EX_MDICHILD = 64

WS_EX_TOOLWINDOW = 128

WS_EX_WINDOWEDGE = 256

WS_EX_CLIENTEDGE = 512

WS_EX_CONTEXTHELP = 1024

WS_EX_RIGHT = 4096

WS_EX_LEFT = 0

WS_EX_RTLREADING = 8192

WS_EX_LTRREADING = 0

WS_EX_LEFTSCROLLBAR = 16384

WS_EX_RIGHTSCROLLBAR = 0

WS_EX_CONTROLPARENT = 65536

WS_EX_STATICEDGE = 131072

WS_EX_APPWINDOW = 262144

WS_EX_OVERLAPPEDWINDOW = 768

WS_EX_PALETTEWINDOW = 392

WS_EX_LAYERED = 524288

WS_EX_NOINHERITLAYOUT = 1048576

WS_EX_NOREDIRECTIONBITMAP = 2097152

WS_EX_LAYOUTRTL = 4194304

WS_EX_COMPOSITED = 33554432

WS_EX_NOACTIVATE = 134217728

end
enum WINDOW_STYLE : UInt32
WS_OVERLAPPED = 0

WS_POPUP = 2147483648

WS_CHILD = 1073741824

WS_MINIMIZE = 536870912

WS_VISIBLE = 268435456

WS_DISABLED = 134217728

WS_CLIPSIBLINGS = 67108864

WS_CLIPCHILDREN = 33554432

WS_MAXIMIZE = 16777216

WS_CAPTION = 12582912

WS_BORDER = 8388608

WS_DLGFRAME = 4194304

WS_VSCROLL = 2097152

WS_HSCROLL = 1048576

WS_SYSMENU = 524288

WS_THICKFRAME = 262144

WS_GROUP = 131072

WS_TABSTOP = 65536

WS_MINIMIZEBOX = 131072

WS_MAXIMIZEBOX = 65536

WS_TILED = 0

WS_ICONIC = 536870912

WS_SIZEBOX = 262144

WS_TILEDWINDOW = 13565952

WS_OVERLAPPEDWINDOW = 13565952

WS_POPUPWINDOW = 2156396544

WS_CHILDWINDOW = 1073741824

WS_ACTIVECAPTION = 1

end
enum OBJECT_IDENTIFIER : Int32
OBJID_WINDOW = 0

OBJID_SYSMENU = -1

OBJID_TITLEBAR = -2

OBJID_MENU = -3

OBJID_CLIENT = -4

OBJID_VSCROLL = -5

OBJID_HSCROLL = -6

OBJID_SIZEGRIP = -7

OBJID_CARET = -8

OBJID_CURSOR = -9

OBJID_ALERT = -10

OBJID_SOUND = -11

OBJID_QUERYCLASSNAMEIDX = -12

OBJID_NATIVEOM = -16

end
enum MENU_ITEM_TYPE : UInt32
MFT_BITMAP = 4

MFT_MENUBARBREAK = 32

MFT_MENUBREAK = 64

MFT_OWNERDRAW = 256

MFT_RADIOCHECK = 512

MFT_RIGHTJUSTIFY = 16384

MFT_RIGHTORDER = 8192

MFT_SEPARATOR = 2048

MFT_STRING = 0

end
enum MESSAGEBOX_RESULT : Int32
IDOK = 1

IDCANCEL = 2

IDABORT = 3

IDRETRY = 4

IDIGNORE = 5

IDYES = 6

IDNO = 7

IDCLOSE = 8

IDHELP = 9

IDTRYAGAIN = 10

IDCONTINUE = 11

IDASYNC = 32001

IDTIMEOUT = 32000

end
enum MENU_ITEM_STATE : UInt32
MFS_GRAYED = 3

MFS_DISABLED = 3

MFS_CHECKED = 8

MFS_HILITE = 128

MFS_ENABLED = 0

MFS_UNCHECKED = 0

MFS_UNHILITE = 0

MFS_DEFAULT = 4096

end
enum SCROLLBAR_CONSTANTS : UInt32
SB_CTL = 2

SB_HORZ = 0

SB_VERT = 1

SB_BOTH = 3

end
enum GET_CLASS_LONG_INDEX : Int32
GCW_ATOM = -32

GCL_CBCLSEXTRA = -20

GCL_CBWNDEXTRA = -18

GCL_HBRBACKGROUND = -10

GCL_HCURSOR = -12

GCL_HICON = -14

GCL_HICONSM = -34

GCL_HMODULE = -16

GCL_MENUNAME = -8

GCL_STYLE = -26

GCL_WNDPROC = -24

GCLP_HBRBACKGROUND = -10

GCLP_HCURSOR = -12

GCLP_HICON = -14

GCLP_HICONSM = -34

GCLP_HMODULE = -16

GCLP_MENUNAME = -8

GCLP_WNDPROC = -24

end
enum UPDATE_LAYERED_WINDOW_FLAGS : UInt32
ULW_ALPHA = 2

ULW_COLORKEY = 1

ULW_OPAQUE = 4

ULW_EX_NORESIZE = 8

end
enum WINDOW_LONG_PTR_INDEX : Int32
GWL_EXSTYLE = -20

GWLP_HINSTANCE = -6

GWLP_HWNDPARENT = -8

GWLP_ID = -12

GWL_STYLE = -16

GWLP_USERDATA = -21

GWLP_WNDPROC = -4

GWL_HINSTANCE = -6

GWL_ID = -12

GWL_USERDATA = -21

GWL_WNDPROC = -4

GWL_HWNDPARENT = -8

end
enum ANIMATE_WINDOW_FLAGS : UInt32
AW_ACTIVATE = 131072

AW_BLEND = 524288

AW_CENTER = 16

AW_HIDE = 65536

AW_HOR_POSITIVE = 1

AW_HOR_NEGATIVE = 2

AW_SLIDE = 262144

AW_VER_POSITIVE = 4

AW_VER_NEGATIVE = 8

end
enum CHANGE_WINDOW_MESSAGE_FILTER_FLAGS : UInt32
MSGFLT_ADD = 1

MSGFLT_REMOVE = 2

end
enum GDI_IMAGE_TYPE : UInt32
IMAGE_BITMAP = 0

IMAGE_CURSOR = 2

IMAGE_ICON = 1

end
enum WINDOWS_HOOK_ID : Int32
WH_CALLWNDPROC = 4

WH_CALLWNDPROCRET = 12

WH_CBT = 5

WH_DEBUG = 9

WH_FOREGROUNDIDLE = 11

WH_GETMESSAGE = 3

WH_JOURNALPLAYBACK = 1

WH_JOURNALRECORD = 0

WH_KEYBOARD = 2

WH_KEYBOARD_LL = 13

WH_MOUSE = 7

WH_MOUSE_LL = 14

WH_MSGFILTER = -1

WH_SHELL = 10

WH_SYSMSGFILTER = 6

end
enum IMAGE_FLAGS : UInt32
LR_CREATEDIBSECTION = 8192

LR_DEFAULTCOLOR = 0

LR_DEFAULTSIZE = 64

LR_LOADFROMFILE = 16

LR_LOADMAP3DCOLORS = 4096

LR_LOADTRANSPARENT = 32

LR_MONOCHROME = 1

LR_SHARED = 32768

LR_VGACOLOR = 128

LR_COPYDELETEORG = 8

LR_COPYFROMRESOURCE = 16384

LR_COPYRETURNORG = 4

end
enum SYSTEM_PARAMETERS_INFO_UPDATE_FLAGS : UInt32
SPIF_UPDATEINIFILE = 1

SPIF_SENDCHANGE = 2

SPIF_SENDWININICHANGE = 2

end
enum SET_WINDOW_POS_FLAGS : UInt32
SWP_ASYNCWINDOWPOS = 16384

SWP_DEFERERASE = 8192

SWP_DRAWFRAME = 32

SWP_FRAMECHANGED = 32

SWP_HIDEWINDOW = 128

SWP_NOACTIVATE = 16

SWP_NOCOPYBITS = 256

SWP_NOMOVE = 2

SWP_NOOWNERZORDER = 512

SWP_NOREDRAW = 8

SWP_NOREPOSITION = 512

SWP_NOSENDCHANGING = 1024

SWP_NOSIZE = 1

SWP_NOZORDER = 4

SWP_SHOWWINDOW = 64

SWP__NOOWNERZORDER = 512

end
enum MSG_WAIT_FOR_MULTIPLE_OBJECTS_EX_FLAGS : UInt32
MWMO_NONE = 0

MWMO_ALERTABLE = 2

MWMO_INPUTAVAILABLE = 4

MWMO_WAITALL = 1

end
enum QUEUE_STATUS_FLAGS : UInt32
QS_ALLEVENTS = 1215

QS_ALLINPUT = 1279

QS_ALLPOSTMESSAGE = 256

QS_HOTKEY = 128

QS_INPUT = 1031

QS_KEY = 1

QS_MOUSE = 6

QS_MOUSEBUTTON = 4

QS_MOUSEMOVE = 2

QS_PAINT = 32

QS_POSTMESSAGE = 8

QS_RAWINPUT = 1024

QS_SENDMESSAGE = 64

QS_TIMER = 16

end
enum SYSTEM_CURSOR_ID : UInt32
OCR_APPSTARTING = 32650

OCR_NORMAL = 32512

OCR_CROSS = 32515

OCR_HAND = 32649

OCR_HELP = 32651

OCR_IBEAM = 32513

OCR_NO = 32648

OCR_SIZEALL = 32646

OCR_SIZENESW = 32643

OCR_SIZENS = 32645

OCR_SIZENWSE = 32642

OCR_SIZEWE = 32644

OCR_UP = 32516

OCR_WAIT = 32514

end
enum LAYERED_WINDOW_ATTRIBUTES_FLAGS : UInt32
LWA_ALPHA = 2

LWA_COLORKEY = 1

end
enum SEND_MESSAGE_TIMEOUT_FLAGS : UInt32
SMTO_ABORTIFHUNG = 2

SMTO_BLOCK = 1

SMTO_NORMAL = 0

SMTO_NOTIMEOUTIFNOTHUNG = 8

SMTO_ERRORONEXIT = 32

end
enum PEEK_MESSAGE_REMOVE_TYPE : UInt32
PM_NOREMOVE = 0

PM_REMOVE = 1

PM_NOYIELD = 2

PM_QS_INPUT = 67567616

PM_QS_POSTMESSAGE = 9961472

PM_QS_PAINT = 2097152

PM_QS_SENDMESSAGE = 4194304

end
enum SYS_COLOR_INDEX : UInt32
COLOR_3DDKSHADOW = 21

COLOR_3DFACE = 15

COLOR_3DHIGHLIGHT = 20

COLOR_3DHILIGHT = 20

COLOR_3DLIGHT = 22

COLOR_3DSHADOW = 16

COLOR_ACTIVEBORDER = 10

COLOR_ACTIVECAPTION = 2

COLOR_APPWORKSPACE = 12

COLOR_BACKGROUND = 1

COLOR_BTNFACE = 15

COLOR_BTNHIGHLIGHT = 20

COLOR_BTNHILIGHT = 20

COLOR_BTNSHADOW = 16

COLOR_BTNTEXT = 18

COLOR_CAPTIONTEXT = 9

COLOR_DESKTOP = 1

COLOR_GRADIENTACTIVECAPTION = 27

COLOR_GRADIENTINACTIVECAPTION = 28

COLOR_GRAYTEXT = 17

COLOR_HIGHLIGHT = 13

COLOR_HIGHLIGHTTEXT = 14

COLOR_HOTLIGHT = 26

COLOR_INACTIVEBORDER = 11

COLOR_INACTIVECAPTION = 3

COLOR_INACTIVECAPTIONTEXT = 19

COLOR_INFOBK = 24

COLOR_INFOTEXT = 23

COLOR_MENU = 4

COLOR_MENUHILIGHT = 29

COLOR_MENUBAR = 30

COLOR_MENUTEXT = 7

COLOR_SCROLLBAR = 0

COLOR_WINDOW = 5

COLOR_WINDOWFRAME = 6

COLOR_WINDOWTEXT = 8

end
enum GET_WINDOW_CMD : UInt32
GW_CHILD = 5

GW_ENABLEDPOPUP = 6

GW_HWNDFIRST = 0

GW_HWNDLAST = 1

GW_HWNDNEXT = 2

GW_HWNDPREV = 3

GW_OWNER = 4

end
enum SYSTEM_METRICS_INDEX : UInt32
SM_ARRANGE = 56

SM_CLEANBOOT = 67

SM_CMONITORS = 80

SM_CMOUSEBUTTONS = 43

SM_CONVERTIBLESLATEMODE = 8195

SM_CXBORDER = 5

SM_CXCURSOR = 13

SM_CXDLGFRAME = 7

SM_CXDOUBLECLK = 36

SM_CXDRAG = 68

SM_CXEDGE = 45

SM_CXFIXEDFRAME = 7

SM_CXFOCUSBORDER = 83

SM_CXFRAME = 32

SM_CXFULLSCREEN = 16

SM_CXHSCROLL = 21

SM_CXHTHUMB = 10

SM_CXICON = 11

SM_CXICONSPACING = 38

SM_CXMAXIMIZED = 61

SM_CXMAXTRACK = 59

SM_CXMENUCHECK = 71

SM_CXMENUSIZE = 54

SM_CXMIN = 28

SM_CXMINIMIZED = 57

SM_CXMINSPACING = 47

SM_CXMINTRACK = 34

SM_CXPADDEDBORDER = 92

SM_CXSCREEN = 0

SM_CXSIZE = 30

SM_CXSIZEFRAME = 32

SM_CXSMICON = 49

SM_CXSMSIZE = 52

SM_CXVIRTUALSCREEN = 78

SM_CXVSCROLL = 2

SM_CYBORDER = 6

SM_CYCAPTION = 4

SM_CYCURSOR = 14

SM_CYDLGFRAME = 8

SM_CYDOUBLECLK = 37

SM_CYDRAG = 69

SM_CYEDGE = 46

SM_CYFIXEDFRAME = 8

SM_CYFOCUSBORDER = 84

SM_CYFRAME = 33

SM_CYFULLSCREEN = 17

SM_CYHSCROLL = 3

SM_CYICON = 12

SM_CYICONSPACING = 39

SM_CYKANJIWINDOW = 18

SM_CYMAXIMIZED = 62

SM_CYMAXTRACK = 60

SM_CYMENU = 15

SM_CYMENUCHECK = 72

SM_CYMENUSIZE = 55

SM_CYMIN = 29

SM_CYMINIMIZED = 58

SM_CYMINSPACING = 48

SM_CYMINTRACK = 35

SM_CYSCREEN = 1

SM_CYSIZE = 31

SM_CYSIZEFRAME = 33

SM_CYSMCAPTION = 51

SM_CYSMICON = 50

SM_CYSMSIZE = 53

SM_CYVIRTUALSCREEN = 79

SM_CYVSCROLL = 20

SM_CYVTHUMB = 9

SM_DBCSENABLED = 42

SM_DEBUG = 22

SM_DIGITIZER = 94

SM_IMMENABLED = 82

SM_MAXIMUMTOUCHES = 95

SM_MEDIACENTER = 87

SM_MENUDROPALIGNMENT = 40

SM_MIDEASTENABLED = 74

SM_MOUSEPRESENT = 19

SM_MOUSEHORIZONTALWHEELPRESENT = 91

SM_MOUSEWHEELPRESENT = 75

SM_NETWORK = 63

SM_PENWINDOWS = 41

SM_REMOTECONTROL = 8193

SM_REMOTESESSION = 4096

SM_SAMEDISPLAYFORMAT = 81

SM_SECURE = 44

SM_SERVERR2 = 89

SM_SHOWSOUNDS = 70

SM_SHUTTINGDOWN = 8192

SM_SLOWMACHINE = 73

SM_STARTER = 88

SM_SWAPBUTTON = 23

SM_SYSTEMDOCKED_ = 8196

SM_TABLETPC = 86

SM_XVIRTUALSCREEN = 76

SM_YVIRTUALSCREEN = 77

end
enum GET_ANCESTOR_FLAGS : UInt32
GA_PARENT = 1

GA_ROOT = 2

GA_ROOTOWNER = 3

end
enum TILE_WINDOWS_HOW : UInt32
MDITILE_HORIZONTAL = 1

MDITILE_VERTICAL = 0

end
enum WINDOW_DISPLAY_AFFINITY : UInt32
WDA_NONE = 0

WDA_MONITOR = 1

WDA_EXCLUDEFROMCAPTURE = 17

end
enum FOREGROUND_WINDOW_LOCK_CODE : UInt32
LSFW_LOCK = 1

LSFW_UNLOCK = 2

end
enum CASCADE_WINDOWS_HOW : UInt32
MDITILE_SKIPDISABLED = 2

MDITILE_ZORDER = 4

end
enum WINDOW_MESSAGE_FILTER_ACTION : UInt32
MSGFLT_ALLOW = 1

MSGFLT_DISALLOW = 2

MSGFLT_RESET = 0

end
enum GET_MENU_DEFAULT_ITEM_FLAGS : UInt32
GMDI_GOINTOPOPUPS = 2

GMDI_USEDISABLED = 1

end
enum MSGFLTINFO_STATUS : UInt32
MSGFLTINFO_NONE = 0

MSGFLTINFO_ALLOWED_HIGHER = 3

MSGFLTINFO_ALREADYALLOWED_FORWND = 1

MSGFLTINFO_ALREADYDISALLOWED_FORWND = 2

end
enum MOUSEHOOKSTRUCTEX_MOUSE_DATA : UInt32
XBUTTON1 = 1

XBUTTON2 = 2

end
enum MENU_ITEM_MASK : UInt32
MIIM_BITMAP = 128

MIIM_CHECKMARKS = 8

MIIM_DATA = 32

MIIM_FTYPE = 256

MIIM_ID = 2

MIIM_STATE = 1

MIIM_STRING = 64

MIIM_SUBMENU = 4

MIIM_TYPE = 16

end
enum FLASHWINFO_FLAGS : UInt32
FLASHW_ALL = 3

FLASHW_CAPTION = 1

FLASHW_STOP = 0

FLASHW_TIMER = 4

FLASHW_TIMERNOFG = 12

FLASHW_TRAY = 2

end
enum CURSORINFO_FLAGS : UInt32
CURSOR_SHOWING = 1

CURSOR_SUPPRESSED = 2

end
enum MENUINFO_STYLE : UInt32
MNS_AUTODISMISS = 268435456

MNS_CHECKORBMP = 67108864

MNS_DRAGDROP = 536870912

MNS_MODELESS = 1073741824

MNS_NOCHECK = 2147483648

MNS_NOTIFYBYPOS = 134217728

end
enum WINDOWPLACEMENT_FLAGS : UInt32
WPF_ASYNCWINDOWPLACEMENT = 4

WPF_RESTORETOMAXIMIZED = 2

WPF_SETMINPOSITION = 1

end
enum MENUINFO_MASK : UInt32
MIM_APPLYTOSUBMENUS = 2147483648

MIM_BACKGROUND = 2

MIM_HELPID = 4

MIM_MAXHEIGHT = 1

MIM_MENUDATA = 8

MIM_STYLE = 16

end
enum MINIMIZEDMETRICS_ARRANGE : Int32
ARW_BOTTOMLEFT = 0

ARW_BOTTOMRIGHT = 1

ARW_TOPLEFT = 2

ARW_TOPRIGHT = 3

end
enum SCROLLINFO_MASK : UInt32
SIF_ALL = 23

SIF_DISABLENOSCROLL = 8

SIF_PAGE = 2

SIF_POS = 4

SIF_RANGE = 1

SIF_TRACKPOS = 16

end
enum MENUGETOBJECTINFO_FLAGS : UInt32
MNGOF_BOTTOMGAP = 2

MNGOF_TOPGAP = 1

end
enum GUITHREADINFO_FLAGS : UInt32
GUI_CARETBLINKING = 1

GUI_INMENUMODE = 4

GUI_INMOVESIZE = 2

GUI_POPUPMENUMODE = 16

GUI_SYSTEMMENUMODE = 8

end
enum KBDLLHOOKSTRUCT_FLAGS : UInt32
LLKHF_EXTENDED = 1

LLKHF_ALTDOWN = 32

LLKHF_UP = 128

LLKHF_INJECTED = 16

LLKHF_LOWER_IL_INJECTED = 2

end
enum DI_FLAGS : UInt32
DI_MASK = 1

DI_IMAGE = 2

DI_NORMAL = 3

DI_COMPAT = 4

DI_DEFAULTSIZE = 8

DI_NOMIRROR = 16

end
type HHOOK = LibC::Int*
type HICON = LibC::Int*
type HMENU = LibC::Int*
type HCURSOR = LibC::Int*
type HACCEL = LibC::Int*
struct MESSAGE_RESOURCE_ENTRY
  length : LibC::UInt16
  flags : LibC::UInt16
  text : Array(LibC::Byte)
end
struct MESSAGE_RESOURCE_BLOCK
  lowId : LibC::UInt32
  highId : LibC::UInt32
  offsetToEntries : LibC::UInt32
end
struct MESSAGE_RESOURCE_DATA
  numberOfBlocks : LibC::UInt32
  blocks : Array(MESSAGE_RESOURCE_BLOCK)
end
alias WNDPROC = (HWND, LibC::UInt32, WPARAM, LPARAM -> LRESULT)
alias DLGPROC = (HWND, LibC::UInt32, WPARAM, LPARAM -> LibC::Int*)
alias TIMERPROC = (HWND, LibC::UInt32, LibC::UIint*, LibC::UInt32 -> LibC::Void)
alias WNDENUMPROC = (HWND, LPARAM -> BOOL)
alias HOOKPROC = (LibC::Int32, WPARAM, LPARAM -> LRESULT)
alias SENDASYNCPROC = (HWND, LibC::UInt32, LibC::UIint*, LRESULT -> LibC::Void)
alias PROPENUMPROCA = (HWND, PSTR, HANDLE -> BOOL)
alias PROPENUMPROCW = (HWND, PWSTR, HANDLE -> BOOL)
alias PROPENUMPROCEXA = (HWND, PSTR, HANDLE, LibC::UIint* -> BOOL)
alias PROPENUMPROCEXW = (HWND, PWSTR, HANDLE, LibC::UIint* -> BOOL)
alias NAMEENUMPROCA = (PSTR, LPARAM -> BOOL)
alias NAMEENUMPROCW = (PWSTR, LPARAM -> BOOL)
struct CBT_CREATEWNDA
  lpcs : CREATESTRUCTA*
  hwndInsertAfter : HWND
end
struct CBT_CREATEWNDW
  lpcs : CREATESTRUCTW*
  hwndInsertAfter : HWND
end
struct CBTACTIVATESTRUCT
  fMouse : BOOL
  hWndActive : HWND
end
struct SHELLHOOKINFO
  hwnd : HWND
  rc : RECT
end
struct EVENTMSG
  message : LibC::UInt32
  paramL : LibC::UInt32
  paramH : LibC::UInt32
  time : LibC::UInt32
  hwnd : HWND
end
struct CWPSTRUCT
  lParam : LPARAM
  wParam : WPARAM
  message : LibC::UInt32
  hwnd : HWND
end
struct CWPRETSTRUCT
  lResult : LRESULT
  lParam : LPARAM
  wParam : WPARAM
  message : LibC::UInt32
  hwnd : HWND
end
struct KBDLLHOOKSTRUCT
  vkCode : LibC::UInt32
  scanCode : LibC::UInt32
  flags : KBDLLHOOKSTRUCT_FLAGS
  time : LibC::UInt32
  dwExtraInfo : LibC::UIint*
end
struct MSLLHOOKSTRUCT
  pt : POINT
  mouseData : MOUSEHOOKSTRUCTEX_MOUSE_DATA
  flags : LibC::UInt32
  time : LibC::UInt32
  dwExtraInfo : LibC::UIint*
end
struct DEBUGHOOKINFO
  idThread : LibC::UInt32
  idThreadInstaller : LibC::UInt32
  lParam : LPARAM
  wParam : WPARAM
  code : LibC::Int32
end
struct MOUSEHOOKSTRUCT
  pt : POINT
  hwnd : HWND
  wHitTestCode : LibC::UInt32
  dwExtraInfo : LibC::UIint*
end
struct MOUSEHOOKSTRUCTEX
  anonymousBase_winuser_L1166_C46 : MOUSEHOOKSTRUCT
  mouseData : MOUSEHOOKSTRUCTEX_MOUSE_DATA
end
struct HARDWAREHOOKSTRUCT
  hwnd : HWND
  message : LibC::UInt32
  wParam : WPARAM
  lParam : LPARAM
end
struct WNDCLASSEXA
  cbSize : LibC::UInt32
  style : WNDCLASS_STYLES
  lpfnWndProc : WNDPROC
  cbClsExtra : LibC::Int32
  cbWndExtra : LibC::Int32
  hInstance : HINSTANCE
  hIcon : HICON
  hCursor : HCURSOR
  hbrBackground : HBRUSH
  lpszMenuName : PSTR
  lpszClassName : PSTR
  hIconSm : HICON
end
struct WNDCLASSEXW
  cbSize : LibC::UInt32
  style : WNDCLASS_STYLES
  lpfnWndProc : WNDPROC
  cbClsExtra : LibC::Int32
  cbWndExtra : LibC::Int32
  hInstance : HINSTANCE
  hIcon : HICON
  hCursor : HCURSOR
  hbrBackground : HBRUSH
  lpszMenuName : PWSTR
  lpszClassName : PWSTR
  hIconSm : HICON
end
struct WNDCLASSA
  style : WNDCLASS_STYLES
  lpfnWndProc : WNDPROC
  cbClsExtra : LibC::Int32
  cbWndExtra : LibC::Int32
  hInstance : HINSTANCE
  hIcon : HICON
  hCursor : HCURSOR
  hbrBackground : HBRUSH
  lpszMenuName : PSTR
  lpszClassName : PSTR
end
struct WNDCLASSW
  style : WNDCLASS_STYLES
  lpfnWndProc : WNDPROC
  cbClsExtra : LibC::Int32
  cbWndExtra : LibC::Int32
  hInstance : HINSTANCE
  hIcon : HICON
  hCursor : HCURSOR
  hbrBackground : HBRUSH
  lpszMenuName : PWSTR
  lpszClassName : PWSTR
end
struct MSG
  hwnd : HWND
  message : LibC::UInt32
  wParam : WPARAM
  lParam : LPARAM
  time : LibC::UInt32
  pt : POINT
end
struct MINMAXINFO
  ptReserved : POINT
  ptMaxSize : POINT
  ptMaxPosition : POINT
  ptMinTrackSize : POINT
  ptMaxTrackSize : POINT
end
struct MDINEXTMENU
  hmenuIn : HMENU
  hmenuNext : HMENU
  hwndNext : HWND
end
struct WINDOWPOS
  hwnd : HWND
  hwndInsertAfter : HWND
  x : LibC::Int32
  y : LibC::Int32
  cx : LibC::Int32
  cy : LibC::Int32
  flags : SET_WINDOW_POS_FLAGS
end
struct NCCALCSIZE_PARAMS
  rgrc : Array(RECT)
  lppos : WINDOWPOS*
end
struct ACCEL
  fVirt : LibC::Byte
  key : LibC::UInt16
  cmd : LibC::UInt16
end
struct CREATESTRUCTA
  lpCreateParams : LibC::Void*
  hInstance : HINSTANCE
  hMenu : HMENU
  hwndParent : HWND
  cy : LibC::Int32
  cx : LibC::Int32
  y : LibC::Int32
  x : LibC::Int32
  style : LibC::Int32
  lpszName : PSTR
  lpszClass : PSTR
  dwExStyle : LibC::UInt32
end
struct CREATESTRUCTW
  lpCreateParams : LibC::Void*
  hInstance : HINSTANCE
  hMenu : HMENU
  hwndParent : HWND
  cy : LibC::Int32
  cx : LibC::Int32
  y : LibC::Int32
  x : LibC::Int32
  style : LibC::Int32
  lpszName : PWSTR
  lpszClass : PWSTR
  dwExStyle : LibC::UInt32
end
struct WINDOWPLACEMENT
  length : LibC::UInt32
  flags : WINDOWPLACEMENT_FLAGS
  showCmd : SHOW_WINDOW_CMD
  ptMinPosition : POINT
  ptMaxPosition : POINT
  rcNormalPosition : RECT
end
struct STYLESTRUCT
  styleOld : LibC::UInt32
  styleNew : LibC::UInt32
end
alias PREGISTERCLASSNAMEW = (PWSTR -> BOOLEAN)
struct UPDATELAYEREDWINDOWINFO
  cbSize : LibC::UInt32
  hdcDst : HDC
  pptDst : POINT*
  psize : SIZE*
  hdcSrc : HDC
  pptSrc : POINT*
  crKey : LibC::UInt32
  pblend : BLENDFUNCTION*
  dwFlags : UPDATE_LAYERED_WINDOW_FLAGS
  prcDirty : RECT*
end
struct FLASHWINFO
  cbSize : LibC::UInt32
  hwnd : HWND
  dwFlags : FLASHWINFO_FLAGS
  uCount : LibC::UInt32
  dwTimeout : LibC::UInt32
end
struct DLGTEMPLATE
  style : LibC::UInt32
  dwExtendedStyle : LibC::UInt32
  cdit : LibC::UInt16
  x : LibC::Int16
  y : LibC::Int16
  cx : LibC::Int16
  cy : LibC::Int16
end
struct DLGITEMTEMPLATE
  style : LibC::UInt32
  dwExtendedStyle : LibC::UInt32
  x : LibC::Int16
  y : LibC::Int16
  cx : LibC::Int16
  cy : LibC::Int16
  id : LibC::UInt16
end
enum POINTER_INPUT_TYPE : Int32
PT_POINTER = 1

PT_TOUCH = 2

PT_PEN = 3

PT_MOUSE = 4

PT_TOUCHPAD = 5

end
struct TPMPARAMS
  cbSize : LibC::UInt32
  rcExclude : RECT
end
struct MENUINFO
  cbSize : LibC::UInt32
  fMask : MENUINFO_MASK
  dwStyle : MENUINFO_STYLE
  cyMax : LibC::UInt32
  hbrBack : HBRUSH
  dwContextHelpID : LibC::UInt32
  dwMenuData : LibC::UIint*
end
struct MENUGETOBJECTINFO
  dwFlags : MENUGETOBJECTINFO_FLAGS
  uPos : LibC::UInt32
  hmenu : HMENU
  riid : LibC::Void*
  pvObj : LibC::Void*
end
struct MENUITEMINFOA
  cbSize : LibC::UInt32
  fMask : MENU_ITEM_MASK
  fType : MENU_ITEM_TYPE
  fState : MENU_ITEM_STATE
  wID : LibC::UInt32
  hSubMenu : HMENU
  hbmpChecked : HBITMAP
  hbmpUnchecked : HBITMAP
  dwItemData : LibC::UIint*
  dwTypeData : PSTR
  cch : LibC::UInt32
  hbmpItem : HBITMAP
end
struct MENUITEMINFOW
  cbSize : LibC::UInt32
  fMask : MENU_ITEM_MASK
  fType : MENU_ITEM_TYPE
  fState : MENU_ITEM_STATE
  wID : LibC::UInt32
  hSubMenu : HMENU
  hbmpChecked : HBITMAP
  hbmpUnchecked : HBITMAP
  dwItemData : LibC::UIint*
  dwTypeData : PWSTR
  cch : LibC::UInt32
  hbmpItem : HBITMAP
end
struct DROPSTRUCT
  hwndSource : HWND
  hwndSink : HWND
  wFmt : LibC::UInt32
  dwData : LibC::UIint*
  ptDrop : POINT
  dwControlData : LibC::UInt32
end
alias MSGBOXCALLBACK = (HELPINFO* -> LibC::Void)
struct MSGBOXPARAMSA
  cbSize : LibC::UInt32
  hwndOwner : HWND
  hInstance : HINSTANCE
  lpszText : PSTR
  lpszCaption : PSTR
  dwStyle : MESSAGEBOX_STYLE
  lpszIcon : PSTR
  dwContextHelpId : LibC::UIint*
  lpfnMsgBoxCallback : MSGBOXCALLBACK
  dwLanguageId : LibC::UInt32
end
struct MSGBOXPARAMSW
  cbSize : LibC::UInt32
  hwndOwner : HWND
  hInstance : HINSTANCE
  lpszText : PWSTR
  lpszCaption : PWSTR
  dwStyle : MESSAGEBOX_STYLE
  lpszIcon : PWSTR
  dwContextHelpId : LibC::UIint*
  lpfnMsgBoxCallback : MSGBOXCALLBACK
  dwLanguageId : LibC::UInt32
end
struct MENUITEMTEMPLATEHEADER
  versionNumber : LibC::UInt16
  offset : LibC::UInt16
end
struct MENUITEMTEMPLATE
  mtOption : LibC::UInt16
  mtID : LibC::UInt16
  mtString : Array(LibC::Char)
end
struct ICONINFO
  fIcon : BOOL
  xHotspot : LibC::UInt32
  yHotspot : LibC::UInt32
  hbmMask : HBITMAP
  hbmColor : HBITMAP
end
struct CURSORSHAPE
  xHotSpot : LibC::Int32
  yHotSpot : LibC::Int32
  cx : LibC::Int32
  cy : LibC::Int32
  cbWidth : LibC::Int32
  planes : LibC::Byte
  bitsPixel : LibC::Byte
end
struct ICONINFOEXA
  cbSize : LibC::UInt32
  fIcon : BOOL
  xHotspot : LibC::UInt32
  yHotspot : LibC::UInt32
  hbmMask : HBITMAP
  hbmColor : HBITMAP
  wResID : LibC::UInt16
  szModName : Array(CHAR)
  szResName : Array(CHAR)
end
struct ICONINFOEXW
  cbSize : LibC::UInt32
  fIcon : BOOL
  xHotspot : LibC::UInt32
  yHotspot : LibC::UInt32
  hbmMask : HBITMAP
  hbmColor : HBITMAP
  wResID : LibC::UInt16
  szModName : Array(LibC::Char)
  szResName : Array(LibC::Char)
end
enum EDIT_CONTROL_FEATURE : Int32
EDIT_CONTROL_FEATURE_ENTERPRISE_DATA_PROTECTION_PASTE_SUPPORT = 0

EDIT_CONTROL_FEATURE_PASTE_NOTIFICATIONS = 1

end
struct SCROLLINFO
  cbSize : LibC::UInt32
  fMask : SCROLLINFO_MASK
  nMin : LibC::Int32
  nMax : LibC::Int32
  nPage : LibC::UInt32
  nPos : LibC::Int32
  nTrackPos : LibC::Int32
end
struct MDICREATESTRUCTA
  szClass : PSTR
  szTitle : PSTR
  hOwner : HANDLE
  x : LibC::Int32
  y : LibC::Int32
  cx : LibC::Int32
  cy : LibC::Int32
  style : WINDOW_STYLE
  lParam : LPARAM
end
struct MDICREATESTRUCTW
  szClass : PWSTR
  szTitle : PWSTR
  hOwner : HANDLE
  x : LibC::Int32
  y : LibC::Int32
  cx : LibC::Int32
  cy : LibC::Int32
  style : WINDOW_STYLE
  lParam : LPARAM
end
struct CLIENTCREATESTRUCT
  hWindowMenu : HANDLE
  idFirstChild : LibC::UInt32
end
struct TouchPredictionParameters
  cbSize : LibC::UInt32
  dwLatency : LibC::UInt32
  dwSampleTime : LibC::UInt32
  bUseHWTimeStamp : LibC::UInt32
end
enum HANDEDNESS : Int32
HANDEDNESS_LEFT = 0

HANDEDNESS_RIGHT = 1

end
struct NONCLIENTMETRICSA
  cbSize : LibC::UInt32
  iBorderWidth : LibC::Int32
  iScrollWidth : LibC::Int32
  iScrollHeight : LibC::Int32
  iCaptionWidth : LibC::Int32
  iCaptionHeight : LibC::Int32
  lfCaptionFont : LOGFONTA
  iSmCaptionWidth : LibC::Int32
  iSmCaptionHeight : LibC::Int32
  lfSmCaptionFont : LOGFONTA
  iMenuWidth : LibC::Int32
  iMenuHeight : LibC::Int32
  lfMenuFont : LOGFONTA
  lfStatusFont : LOGFONTA
  lfMessageFont : LOGFONTA
  iPaddedBorderWidth : LibC::Int32
end
struct NONCLIENTMETRICSW
  cbSize : LibC::UInt32
  iBorderWidth : LibC::Int32
  iScrollWidth : LibC::Int32
  iScrollHeight : LibC::Int32
  iCaptionWidth : LibC::Int32
  iCaptionHeight : LibC::Int32
  lfCaptionFont : LOGFONTW
  iSmCaptionWidth : LibC::Int32
  iSmCaptionHeight : LibC::Int32
  lfSmCaptionFont : LOGFONTW
  iMenuWidth : LibC::Int32
  iMenuHeight : LibC::Int32
  lfMenuFont : LOGFONTW
  lfStatusFont : LOGFONTW
  lfMessageFont : LOGFONTW
  iPaddedBorderWidth : LibC::Int32
end
struct MINIMIZEDMETRICS
  cbSize : LibC::UInt32
  iWidth : LibC::Int32
  iHorzGap : LibC::Int32
  iVertGap : LibC::Int32
  iArrange : MINIMIZEDMETRICS_ARRANGE
end
struct ICONMETRICSA
  cbSize : LibC::UInt32
  iHorzSpacing : LibC::Int32
  iVertSpacing : LibC::Int32
  iTitleWrap : LibC::Int32
  lfFont : LOGFONTA
end
struct ICONMETRICSW
  cbSize : LibC::UInt32
  iHorzSpacing : LibC::Int32
  iVertSpacing : LibC::Int32
  iTitleWrap : LibC::Int32
  lfFont : LOGFONTW
end
struct ANIMATIONINFO
  cbSize : LibC::UInt32
  iMinAnimate : LibC::Int32
end
struct AUDIODESCRIPTION
  cbSize : LibC::UInt32
  enabled : BOOL
  locale : LibC::UInt32
end
struct GUITHREADINFO
  cbSize : LibC::UInt32
  flags : GUITHREADINFO_FLAGS
  hwndActive : HWND
  hwndFocus : HWND
  hwndCapture : HWND
  hwndMenuOwner : HWND
  hwndMoveSize : HWND
  hwndCaret : HWND
  rcCaret : RECT
end
struct CURSORINFO
  cbSize : LibC::UInt32
  flags : CURSORINFO_FLAGS
  hCursor : HCURSOR
  ptScreenPos : POINT
end
struct WINDOWINFO
  cbSize : LibC::UInt32
  rcWindow : RECT
  rcClient : RECT
  dwStyle : LibC::UInt32
  dwExStyle : LibC::UInt32
  dwWindowStatus : LibC::UInt32
  cxWindowBorders : LibC::UInt32
  cyWindowBorders : LibC::UInt32
  atomWindowType : LibC::UInt16
  wCreatorVersion : LibC::UInt16
end
struct TITLEBARINFO
  cbSize : LibC::UInt32
  rcTitleBar : RECT
  rgstate : Array(LibC::UInt32)
end
struct TITLEBARINFOEX
  cbSize : LibC::UInt32
  rcTitleBar : RECT
  rgstate : Array(LibC::UInt32)
  rgrect : Array(RECT)
end
struct MENUBARINFO
  cbSize : LibC::UInt32
  rcBar : RECT
  hMenu : HMENU
  hwndMenu : HWND
  bitfield : LibC::Int32
end
struct SCROLLBARINFO
  cbSize : LibC::UInt32
  rcScrollBar : RECT
  dxyLineButton : LibC::Int32
  xyThumbTop : LibC::Int32
  xyThumbBottom : LibC::Int32
  reserved : LibC::Int32
  rgstate : Array(LibC::UInt32)
end
struct ALTTABINFO
  cbSize : LibC::UInt32
  cItems : LibC::Int32
  cColumns : LibC::Int32
  cRows : LibC::Int32
  iColFocus : LibC::Int32
  iRowFocus : LibC::Int32
  cxItem : LibC::Int32
  cyItem : LibC::Int32
  ptStart : POINT
end
struct CHANGEFILTERSTRUCT
  cbSize : LibC::UInt32
  extStatus : MSGFLTINFO_STATUS
end
struct IndexedResourceQualifier
  name : PWSTR
  value : PWSTR
end
enum MrmPlatformVersion : Int32
MrmPlatformVersion_Default = 0

MrmPlatformVersion_Windows10_0_0_0 = 17432576

MrmPlatformVersion_Windows10_0_0_5 = 17432581

end
struct MrmResourceIndexerHandle
  handle : LibC::Void*
end
enum MrmPackagingMode : Int32
MrmPackagingModeStandaloneFile = 0

MrmPackagingModeAutoSplit = 1

MrmPackagingModeResourcePack = 2

end
enum MrmPackagingOptions : Int32
MrmPackagingOptionsNone = 0

MrmPackagingOptionsOmitSchemaFromResourcePacks = 1

MrmPackagingOptionsSplitLanguageVariants = 2

end
enum MrmDumpType : Int32
MrmDumpType_Basic = 0

MrmDumpType_Detailed = 1

MrmDumpType_Schema = 2

end
enum MrmResourceIndexerMessageSeverity : Int32
MrmResourceIndexerMessageSeverityVerbose = 0

MrmResourceIndexerMessageSeverityInfo = 1

MrmResourceIndexerMessageSeverityWarning = 2

MrmResourceIndexerMessageSeverityError = 3

end
enum MrmIndexerFlags : Int32
MrmIndexerFlagsNone = 0

MrmIndexerFlagsAutoMerge = 1

MrmIndexerFlagsCreateContentChecksum = 2

end
struct MrmResourceIndexerMessage
  severity : MrmResourceIndexerMessageSeverity
  id : LibC::UInt32
  text : PWSTR
end
fun wvsprintfA(param0 : PSTR, param1 : PSTR, arglist : LibC::SByte*) : LibC::Int32
fun wvsprintfW(param0 : PWSTR, param1 : PWSTR, arglist : LibC::SByte*) : LibC::Int32
fun wsprintfA(param0 : PSTR, param1 : PSTR) : LibC::Int32
fun wsprintfW(param0 : PWSTR, param1 : PWSTR) : LibC::Int32
fun isHungAppWindow(hwnd : HWND) : BOOL
fun disableProcessWindowsGhosting() : LibC::Void
fun registerWindowMessageA(lpString : PSTR) : LibC::UInt32
fun registerWindowMessageW(lpString : PWSTR) : LibC::UInt32
fun getMessageA(lpMsg : MSG*, hWnd : HWND, wMsgFilterMin : LibC::UInt32, wMsgFilterMax : LibC::UInt32) : BOOL
fun getMessageW(lpMsg : MSG*, hWnd : HWND, wMsgFilterMin : LibC::UInt32, wMsgFilterMax : LibC::UInt32) : BOOL
fun translateMessage(lpMsg : MSG*) : BOOL
fun dispatchMessageA(lpMsg : MSG*) : LRESULT
fun dispatchMessageW(lpMsg : MSG*) : LRESULT
fun setMessageQueue(cMessagesMax : LibC::Int32) : BOOL
fun peekMessageA(lpMsg : MSG*, hWnd : HWND, wMsgFilterMin : LibC::UInt32, wMsgFilterMax : LibC::UInt32, wRemoveMsg : PEEK_MESSAGE_REMOVE_TYPE) : BOOL
fun peekMessageW(lpMsg : MSG*, hWnd : HWND, wMsgFilterMin : LibC::UInt32, wMsgFilterMax : LibC::UInt32, wRemoveMsg : PEEK_MESSAGE_REMOVE_TYPE) : BOOL
fun getMessagePos() : LibC::UInt32
fun getMessageTime() : LibC::Int32
fun getMessageExtraInfo() : LPARAM
fun isWow64Message() : BOOL
fun setMessageExtraInfo(lParam : LPARAM) : LPARAM
fun sendMessageA(hWnd : HWND, msg : LibC::UInt32, wParam : WPARAM, lParam : LPARAM) : LRESULT
fun sendMessageW(hWnd : HWND, msg : LibC::UInt32, wParam : WPARAM, lParam : LPARAM) : LRESULT
fun sendMessageTimeoutA(hWnd : HWND, msg : LibC::UInt32, wParam : WPARAM, lParam : LPARAM, fuFlags : SEND_MESSAGE_TIMEOUT_FLAGS, uTimeout : LibC::UInt32, lpdwResult : LibC::UIint**) : LRESULT
fun sendMessageTimeoutW(hWnd : HWND, msg : LibC::UInt32, wParam : WPARAM, lParam : LPARAM, fuFlags : SEND_MESSAGE_TIMEOUT_FLAGS, uTimeout : LibC::UInt32, lpdwResult : LibC::UIint**) : LRESULT
fun sendNotifyMessageA(hWnd : HWND, msg : LibC::UInt32, wParam : WPARAM, lParam : LPARAM) : BOOL
fun sendNotifyMessageW(hWnd : HWND, msg : LibC::UInt32, wParam : WPARAM, lParam : LPARAM) : BOOL
fun sendMessageCallbackA(hWnd : HWND, msg : LibC::UInt32, wParam : WPARAM, lParam : LPARAM, lpResultCallBack : SENDASYNCPROC, dwData : LibC::UIint*) : BOOL
fun sendMessageCallbackW(hWnd : HWND, msg : LibC::UInt32, wParam : WPARAM, lParam : LPARAM, lpResultCallBack : SENDASYNCPROC, dwData : LibC::UIint*) : BOOL
fun registerDeviceNotificationA(hRecipient : HANDLE, notificationFilter : LibC::Void*, flags : POWER_SETTING_REGISTER_NOTIFICATION_FLAGS) : LibC::Void*
fun registerDeviceNotificationW(hRecipient : HANDLE, notificationFilter : LibC::Void*, flags : POWER_SETTING_REGISTER_NOTIFICATION_FLAGS) : LibC::Void*
fun postMessageA(hWnd : HWND, msg : LibC::UInt32, wParam : WPARAM, lParam : LPARAM) : BOOL
fun postMessageW(hWnd : HWND, msg : LibC::UInt32, wParam : WPARAM, lParam : LPARAM) : BOOL
fun postThreadMessageA(idThread : LibC::UInt32, msg : LibC::UInt32, wParam : WPARAM, lParam : LPARAM) : BOOL
fun postThreadMessageW(idThread : LibC::UInt32, msg : LibC::UInt32, wParam : WPARAM, lParam : LPARAM) : BOOL
fun replyMessage(lResult : LRESULT) : BOOL
fun waitMessage() : BOOL
fun defWindowProcA(hWnd : HWND, msg : LibC::UInt32, wParam : WPARAM, lParam : LPARAM) : LRESULT
fun defWindowProcW(hWnd : HWND, msg : LibC::UInt32, wParam : WPARAM, lParam : LPARAM) : LRESULT
fun postQuitMessage(nExitCode : LibC::Int32) : LibC::Void
fun callWindowProcA(lpPrevWndFunc : WNDPROC, hWnd : HWND, msg : LibC::UInt32, wParam : WPARAM, lParam : LPARAM) : LRESULT
fun callWindowProcW(lpPrevWndFunc : WNDPROC, hWnd : HWND, msg : LibC::UInt32, wParam : WPARAM, lParam : LPARAM) : LRESULT
fun inSendMessage() : BOOL
fun inSendMessageEx(lpReserved : LibC::Void*) : LibC::UInt32
fun registerClassA(lpWndClass : WNDCLASSA*) : LibC::UInt16
fun registerClassW(lpWndClass : WNDCLASSW*) : LibC::UInt16
fun unregisterClassA(lpClassName : PSTR, hInstance : HINSTANCE) : BOOL
fun unregisterClassW(lpClassName : PWSTR, hInstance : HINSTANCE) : BOOL
fun getClassInfoA(hInstance : HINSTANCE, lpClassName : PSTR, lpWndClass : WNDCLASSA*) : BOOL
fun getClassInfoW(hInstance : HINSTANCE, lpClassName : PWSTR, lpWndClass : WNDCLASSW*) : BOOL
fun registerClassExA(param0 : WNDCLASSEXA*) : LibC::UInt16
fun registerClassExW(param0 : WNDCLASSEXW*) : LibC::UInt16
fun getClassInfoExA(hInstance : HINSTANCE, lpszClass : PSTR, lpwcx : WNDCLASSEXA*) : BOOL
fun getClassInfoExW(hInstance : HINSTANCE, lpszClass : PWSTR, lpwcx : WNDCLASSEXW*) : BOOL
fun createWindowExA(dwExStyle : WINDOW_EX_STYLE, lpClassName : PSTR, lpWindowName : PSTR, dwStyle : WINDOW_STYLE, x : LibC::Int32, y : LibC::Int32, nWidth : LibC::Int32, nHeight : LibC::Int32, hWndParent : HWND, hMenu : HMENU, hInstance : HINSTANCE, lpParam : LibC::Void*) : HWND
fun createWindowExW(dwExStyle : WINDOW_EX_STYLE, lpClassName : PWSTR, lpWindowName : PWSTR, dwStyle : WINDOW_STYLE, x : LibC::Int32, y : LibC::Int32, nWidth : LibC::Int32, nHeight : LibC::Int32, hWndParent : HWND, hMenu : HMENU, hInstance : HINSTANCE, lpParam : LibC::Void*) : HWND
fun isWindow(hWnd : HWND) : BOOL
fun isMenu(hMenu : HMENU) : BOOL
fun isChild(hWndParent : HWND, hWnd : HWND) : BOOL
fun destroyWindow(hWnd : HWND) : BOOL
fun showWindow(hWnd : HWND, nCmdShow : SHOW_WINDOW_CMD) : BOOL
fun animateWindow(hWnd : HWND, dwTime : LibC::UInt32, dwFlags : ANIMATE_WINDOW_FLAGS) : BOOL
fun updateLayeredWindow(hWnd : HWND, hdcDst : HDC, pptDst : POINT*, psize : SIZE*, hdcSrc : HDC, pptSrc : POINT*, crKey : LibC::UInt32, pblend : BLENDFUNCTION*, dwFlags : UPDATE_LAYERED_WINDOW_FLAGS) : BOOL
fun updateLayeredWindowIndirect(hWnd : HWND, pULWInfo : UPDATELAYEREDWINDOWINFO*) : BOOL
fun getLayeredWindowAttributes(hwnd : HWND, pcrKey : LibC::UInt32*, pbAlpha : LibC::Byte*, pdwFlags : LAYERED_WINDOW_ATTRIBUTES_FLAGS*) : BOOL
fun setLayeredWindowAttributes(hwnd : HWND, crKey : LibC::UInt32, bAlpha : LibC::Byte, dwFlags : LAYERED_WINDOW_ATTRIBUTES_FLAGS) : BOOL
fun showWindowAsync(hWnd : HWND, nCmdShow : SHOW_WINDOW_CMD) : BOOL
fun flashWindow(hWnd : HWND, bInvert : BOOL) : BOOL
fun flashWindowEx(pfwi : FLASHWINFO*) : BOOL
fun showOwnedPopups(hWnd : HWND, fShow : BOOL) : BOOL
fun openIcon(hWnd : HWND) : BOOL
fun closeWindow(hWnd : HWND) : BOOL
fun moveWindow(hWnd : HWND, x : LibC::Int32, y : LibC::Int32, nWidth : LibC::Int32, nHeight : LibC::Int32, bRepaint : BOOL) : BOOL
fun setWindowPos(hWnd : HWND, hWndInsertAfter : HWND, x : LibC::Int32, y : LibC::Int32, cx : LibC::Int32, cy : LibC::Int32, uFlags : SET_WINDOW_POS_FLAGS) : BOOL
fun getWindowPlacement(hWnd : HWND, lpwndpl : WINDOWPLACEMENT*) : BOOL
fun setWindowPlacement(hWnd : HWND, lpwndpl : WINDOWPLACEMENT*) : BOOL
fun getWindowDisplayAffinity(hWnd : HWND, pdwAffinity : LibC::UInt32*) : BOOL
fun setWindowDisplayAffinity(hWnd : HWND, dwAffinity : WINDOW_DISPLAY_AFFINITY) : BOOL
fun beginDeferWindowPos(nNumWindows : LibC::Int32) : LibC::Int*
fun deferWindowPos(hWinPosInfo : LibC::Int*, hWnd : HWND, hWndInsertAfter : HWND, x : LibC::Int32, y : LibC::Int32, cx : LibC::Int32, cy : LibC::Int32, uFlags : SET_WINDOW_POS_FLAGS) : LibC::Int*
fun endDeferWindowPos(hWinPosInfo : LibC::Int*) : BOOL
fun isWindowVisible(hWnd : HWND) : BOOL
fun isIconic(hWnd : HWND) : BOOL
fun anyPopup() : BOOL
fun bringWindowToTop(hWnd : HWND) : BOOL
fun isZoomed(hWnd : HWND) : BOOL
fun createDialogParamA(hInstance : HINSTANCE, lpTemplateName : PSTR, hWndParent : HWND, lpDialogFunc : DLGPROC, dwInitParam : LPARAM) : HWND
fun createDialogParamW(hInstance : HINSTANCE, lpTemplateName : PWSTR, hWndParent : HWND, lpDialogFunc : DLGPROC, dwInitParam : LPARAM) : HWND
fun createDialogIndirectParamA(hInstance : HINSTANCE, lpTemplate : DLGTEMPLATE*, hWndParent : HWND, lpDialogFunc : DLGPROC, dwInitParam : LPARAM) : HWND
fun createDialogIndirectParamW(hInstance : HINSTANCE, lpTemplate : DLGTEMPLATE*, hWndParent : HWND, lpDialogFunc : DLGPROC, dwInitParam : LPARAM) : HWND
fun dialogBoxParamA(hInstance : HINSTANCE, lpTemplateName : PSTR, hWndParent : HWND, lpDialogFunc : DLGPROC, dwInitParam : LPARAM) : LibC::Int*
fun dialogBoxParamW(hInstance : HINSTANCE, lpTemplateName : PWSTR, hWndParent : HWND, lpDialogFunc : DLGPROC, dwInitParam : LPARAM) : LibC::Int*
fun dialogBoxIndirectParamA(hInstance : HINSTANCE, hDialogTemplate : DLGTEMPLATE*, hWndParent : HWND, lpDialogFunc : DLGPROC, dwInitParam : LPARAM) : LibC::Int*
fun dialogBoxIndirectParamW(hInstance : HINSTANCE, hDialogTemplate : DLGTEMPLATE*, hWndParent : HWND, lpDialogFunc : DLGPROC, dwInitParam : LPARAM) : LibC::Int*
fun endDialog(hDlg : HWND, nResult : LibC::Int*) : BOOL
fun getDlgItem(hDlg : HWND, nIDDlgItem : LibC::Int32) : HWND
fun setDlgItemInt(hDlg : HWND, nIDDlgItem : LibC::Int32, uValue : LibC::UInt32, bSigned : BOOL) : BOOL
fun getDlgItemInt(hDlg : HWND, nIDDlgItem : LibC::Int32, lpTranslated : BOOL*, bSigned : BOOL) : LibC::UInt32
fun setDlgItemTextA(hDlg : HWND, nIDDlgItem : LibC::Int32, lpString : PSTR) : BOOL
fun setDlgItemTextW(hDlg : HWND, nIDDlgItem : LibC::Int32, lpString : PWSTR) : BOOL
fun sendDlgItemMessageA(hDlg : HWND, nIDDlgItem : LibC::Int32, msg : LibC::UInt32, wParam : WPARAM, lParam : LPARAM) : LRESULT
fun sendDlgItemMessageW(hDlg : HWND, nIDDlgItem : LibC::Int32, msg : LibC::UInt32, wParam : WPARAM, lParam : LPARAM) : LRESULT
fun getNextDlgGroupItem(hDlg : HWND, hCtl : HWND, bPrevious : BOOL) : HWND
fun getNextDlgTabItem(hDlg : HWND, hCtl : HWND, bPrevious : BOOL) : HWND
fun getDlgCtrlID(hWnd : HWND) : LibC::Int32
fun getDialogBaseUnits() : LibC::Int32
fun defDlgProcA(hDlg : HWND, msg : LibC::UInt32, wParam : WPARAM, lParam : LPARAM) : LRESULT
fun defDlgProcW(hDlg : HWND, msg : LibC::UInt32, wParam : WPARAM, lParam : LPARAM) : LRESULT
fun callMsgFilterA(lpMsg : MSG*, nCode : LibC::Int32) : BOOL
fun callMsgFilterW(lpMsg : MSG*, nCode : LibC::Int32) : BOOL
fun charToOemA(pSrc : PSTR, pDst : PSTR) : BOOL
fun charToOemW(pSrc : PWSTR, pDst : PSTR) : BOOL
fun oemToCharA(pSrc : PSTR, pDst : PSTR) : BOOL
fun oemToCharW(pSrc : PSTR, pDst : PWSTR) : BOOL
fun charUpperA(lpsz : PSTR) : PSTR
fun charUpperW(lpsz : PWSTR) : PWSTR
fun charLowerA(lpsz : PSTR) : PSTR
fun charLowerW(lpsz : PWSTR) : PWSTR
fun charNextA(lpsz : PSTR) : PSTR
fun charNextW(lpsz : PWSTR) : PWSTR
fun charPrevA(lpszStart : PSTR, lpszCurrent : PSTR) : PSTR
fun charPrevW(lpszStart : PWSTR, lpszCurrent : PWSTR) : PWSTR
fun charNextExA(codePage : LibC::UInt16, lpCurrentChar : PSTR, dwFlags : LibC::UInt32) : PSTR
fun charPrevExA(codePage : LibC::UInt16, lpStart : PSTR, lpCurrentChar : PSTR, dwFlags : LibC::UInt32) : PSTR
fun isCharAlphaA(ch : CHAR) : BOOL
fun isCharAlphaW(ch : LibC::Char) : BOOL
fun isCharAlphaNumericA(ch : CHAR) : BOOL
fun isCharAlphaNumericW(ch : LibC::Char) : BOOL
fun isCharUpperA(ch : CHAR) : BOOL
fun isCharUpperW(ch : LibC::Char) : BOOL
fun isCharLowerA(ch : CHAR) : BOOL
fun getInputState() : BOOL
fun getQueueStatus(flags : QUEUE_STATUS_FLAGS) : LibC::UInt32
fun setTimer(hWnd : HWND, nIDEvent : LibC::UIint*, uElapse : LibC::UInt32, lpTimerFunc : TIMERPROC) : LibC::UIint*
fun setCoalescableTimer(hWnd : HWND, nIDEvent : LibC::UIint*, uElapse : LibC::UInt32, lpTimerFunc : TIMERPROC, uToleranceDelay : LibC::UInt32) : LibC::UIint*
fun killTimer(hWnd : HWND, uIDEvent : LibC::UIint*) : BOOL
fun isWindowUnicode(hWnd : HWND) : BOOL
fun loadAcceleratorsA(hInstance : HINSTANCE, lpTableName : PSTR) : HACCEL
fun loadAcceleratorsW(hInstance : HINSTANCE, lpTableName : PWSTR) : HACCEL
fun destroyAcceleratorTable(hAccel : HACCEL) : BOOL
fun translateAcceleratorA(hWnd : HWND, hAccTable : HACCEL, lpMsg : MSG*) : LibC::Int32
fun translateAcceleratorW(hWnd : HWND, hAccTable : HACCEL, lpMsg : MSG*) : LibC::Int32
fun getSystemMetrics(nIndex : SYSTEM_METRICS_INDEX) : LibC::Int32
fun loadMenuA(hInstance : HINSTANCE, lpMenuName : PSTR) : HMENU
fun loadMenuW(hInstance : HINSTANCE, lpMenuName : PWSTR) : HMENU
fun loadMenuIndirectA(lpMenuTemplate : LibC::Void*) : HMENU
fun loadMenuIndirectW(lpMenuTemplate : LibC::Void*) : HMENU
fun getMenu(hWnd : HWND) : HMENU
fun setMenu(hWnd : HWND, hMenu : HMENU) : BOOL
fun changeMenuA(hMenu : HMENU, cmd : LibC::UInt32, lpszNewItem : PSTR, cmdInsert : LibC::UInt32, flags : LibC::UInt32) : BOOL
fun changeMenuW(hMenu : HMENU, cmd : LibC::UInt32, lpszNewItem : PWSTR, cmdInsert : LibC::UInt32, flags : LibC::UInt32) : BOOL
fun hiliteMenuItem(hWnd : HWND, hMenu : HMENU, uIDHiliteItem : LibC::UInt32, uHilite : LibC::UInt32) : BOOL
fun getMenuState(hMenu : HMENU, uId : LibC::UInt32, uFlags : MENU_ITEM_FLAGS) : LibC::UInt32
fun drawMenuBar(hWnd : HWND) : BOOL
fun getSystemMenu(hWnd : HWND, bRevert : BOOL) : HMENU
fun createMenu() : HMENU
fun createPopupMenu() : HMENU
fun destroyMenu(hMenu : HMENU) : BOOL
fun checkMenuItem(hMenu : HMENU, uIDCheckItem : LibC::UInt32, uCheck : LibC::UInt32) : LibC::UInt32
fun enableMenuItem(hMenu : HMENU, uIDEnableItem : LibC::UInt32, uEnable : MENU_ITEM_FLAGS) : BOOL
fun getSubMenu(hMenu : HMENU, nPos : LibC::Int32) : HMENU
fun getMenuItemID(hMenu : HMENU, nPos : LibC::Int32) : LibC::UInt32
fun getMenuItemCount(hMenu : HMENU) : LibC::Int32
fun insertMenuA(hMenu : HMENU, uPosition : LibC::UInt32, uFlags : MENU_ITEM_FLAGS, uIDNewItem : LibC::UIint*, lpNewItem : PSTR) : BOOL
fun insertMenuW(hMenu : HMENU, uPosition : LibC::UInt32, uFlags : MENU_ITEM_FLAGS, uIDNewItem : LibC::UIint*, lpNewItem : PWSTR) : BOOL
fun appendMenuA(hMenu : HMENU, uFlags : MENU_ITEM_FLAGS, uIDNewItem : LibC::UIint*, lpNewItem : PSTR) : BOOL
fun appendMenuW(hMenu : HMENU, uFlags : MENU_ITEM_FLAGS, uIDNewItem : LibC::UIint*, lpNewItem : PWSTR) : BOOL
fun modifyMenuA(hMnu : HMENU, uPosition : LibC::UInt32, uFlags : MENU_ITEM_FLAGS, uIDNewItem : LibC::UIint*, lpNewItem : PSTR) : BOOL
fun modifyMenuW(hMnu : HMENU, uPosition : LibC::UInt32, uFlags : MENU_ITEM_FLAGS, uIDNewItem : LibC::UIint*, lpNewItem : PWSTR) : BOOL
fun removeMenu(hMenu : HMENU, uPosition : LibC::UInt32, uFlags : MENU_ITEM_FLAGS) : BOOL
fun deleteMenu(hMenu : HMENU, uPosition : LibC::UInt32, uFlags : MENU_ITEM_FLAGS) : BOOL
fun setMenuItemBitmaps(hMenu : HMENU, uPosition : LibC::UInt32, uFlags : MENU_ITEM_FLAGS, hBitmapUnchecked : HBITMAP, hBitmapChecked : HBITMAP) : BOOL
fun getMenuCheckMarkDimensions() : LibC::Int32
fun trackPopupMenu(hMenu : HMENU, uFlags : TRACK_POPUP_MENU_FLAGS, x : LibC::Int32, y : LibC::Int32, nReserved : LibC::Int32, hWnd : HWND, prcRect : RECT*) : BOOL
fun trackPopupMenuEx(hMenu : HMENU, uFlags : LibC::UInt32, x : LibC::Int32, y : LibC::Int32, hwnd : HWND, lptpm : TPMPARAMS*) : BOOL
fun calculatePopupWindowPosition(anchorPoint : POINT*, windowSize : SIZE*, flags : LibC::UInt32, excludeRect : RECT*, popupWindowPosition : RECT*) : BOOL
fun getMenuInfo(param0 : HMENU, param1 : MENUINFO*) : BOOL
fun setMenuInfo(param0 : HMENU, param1 : MENUINFO*) : BOOL
fun endMenu() : BOOL
fun insertMenuItemA(hmenu : HMENU, item : LibC::UInt32, fByPosition : BOOL, lpmi : MENUITEMINFOA*) : BOOL
fun insertMenuItemW(hmenu : HMENU, item : LibC::UInt32, fByPosition : BOOL, lpmi : MENUITEMINFOW*) : BOOL
fun getMenuItemInfoA(hmenu : HMENU, item : LibC::UInt32, fByPosition : BOOL, lpmii : MENUITEMINFOA*) : BOOL
fun getMenuItemInfoW(hmenu : HMENU, item : LibC::UInt32, fByPosition : BOOL, lpmii : MENUITEMINFOW*) : BOOL
fun setMenuItemInfoA(hmenu : HMENU, item : LibC::UInt32, fByPositon : BOOL, lpmii : MENUITEMINFOA*) : BOOL
fun setMenuItemInfoW(hmenu : HMENU, item : LibC::UInt32, fByPositon : BOOL, lpmii : MENUITEMINFOW*) : BOOL
fun getMenuDefaultItem(hMenu : HMENU, fByPos : LibC::UInt32, gmdiFlags : GET_MENU_DEFAULT_ITEM_FLAGS) : LibC::UInt32
fun setMenuDefaultItem(hMenu : HMENU, uItem : LibC::UInt32, fByPos : LibC::UInt32) : BOOL
fun getMenuItemRect(hWnd : HWND, hMenu : HMENU, uItem : LibC::UInt32, lprcItem : RECT*) : BOOL
fun menuItemFromPoint(hWnd : HWND, hMenu : HMENU, ptScreen : POINT) : LibC::Int32
fun dragObject(hwndParent : HWND, hwndFrom : HWND, fmt : LibC::UInt32, data : LibC::UIint*, hcur : HCURSOR) : LibC::UInt32
fun drawIcon(hDC : HDC, x : LibC::Int32, y : LibC::Int32, hIcon : HICON) : BOOL
fun getForegroundWindow() : HWND
fun switchToThisWindow(hwnd : HWND, fUnknown : BOOL) : LibC::Void
fun setForegroundWindow(hWnd : HWND) : BOOL
fun allowSetForegroundWindow(dwProcessId : LibC::UInt32) : BOOL
fun lockSetForegroundWindow(uLockCode : FOREGROUND_WINDOW_LOCK_CODE) : BOOL
fun scrollWindow(hWnd : HWND, xAmount : LibC::Int32, yAmount : LibC::Int32, lpRect : RECT*, lpClipRect : RECT*) : BOOL
fun scrollDC(hDC : HDC, dx : LibC::Int32, dy : LibC::Int32, lprcScroll : RECT*, lprcClip : RECT*, hrgnUpdate : HRGN, lprcUpdate : RECT*) : BOOL
fun scrollWindowEx(hWnd : HWND, dx : LibC::Int32, dy : LibC::Int32, prcScroll : RECT*, prcClip : RECT*, hrgnUpdate : HRGN, prcUpdate : RECT*, flags : SHOW_WINDOW_CMD) : LibC::Int32
fun getScrollPos(hWnd : HWND, nBar : SCROLLBAR_CONSTANTS) : LibC::Int32
fun getScrollRange(hWnd : HWND, nBar : SCROLLBAR_CONSTANTS, lpMinPos : LibC::Int32*, lpMaxPos : LibC::Int32*) : BOOL
fun setPropA(hWnd : HWND, lpString : PSTR, hData : HANDLE) : BOOL
fun setPropW(hWnd : HWND, lpString : PWSTR, hData : HANDLE) : BOOL
fun getPropA(hWnd : HWND, lpString : PSTR) : HANDLE
fun getPropW(hWnd : HWND, lpString : PWSTR) : HANDLE
fun removePropA(hWnd : HWND, lpString : PSTR) : HANDLE
fun removePropW(hWnd : HWND, lpString : PWSTR) : HANDLE
fun enumPropsExA(hWnd : HWND, lpEnumFunc : PROPENUMPROCEXA, lParam : LPARAM) : LibC::Int32
fun enumPropsExW(hWnd : HWND, lpEnumFunc : PROPENUMPROCEXW, lParam : LPARAM) : LibC::Int32
fun enumPropsA(hWnd : HWND, lpEnumFunc : PROPENUMPROCA) : LibC::Int32
fun enumPropsW(hWnd : HWND, lpEnumFunc : PROPENUMPROCW) : LibC::Int32
fun setWindowTextA(hWnd : HWND, lpString : PSTR) : BOOL
fun setWindowTextW(hWnd : HWND, lpString : PWSTR) : BOOL
fun getWindowTextLengthA(hWnd : HWND) : LibC::Int32
fun getWindowTextLengthW(hWnd : HWND) : LibC::Int32
fun getClientRect(hWnd : HWND, lpRect : RECT*) : BOOL
fun getWindowRect(hWnd : HWND, lpRect : RECT*) : BOOL
fun adjustWindowRect(lpRect : RECT*, dwStyle : WINDOW_STYLE, bMenu : BOOL) : BOOL
fun adjustWindowRectEx(lpRect : RECT*, dwStyle : WINDOW_STYLE, bMenu : BOOL, dwExStyle : WINDOW_EX_STYLE) : BOOL
fun messageBoxA(hWnd : HWND, lpText : PSTR, lpCaption : PSTR, uType : MESSAGEBOX_STYLE) : MESSAGEBOX_RESULT
fun messageBoxW(hWnd : HWND, lpText : PWSTR, lpCaption : PWSTR, uType : MESSAGEBOX_STYLE) : MESSAGEBOX_RESULT
fun messageBoxExA(hWnd : HWND, lpText : PSTR, lpCaption : PSTR, uType : MESSAGEBOX_STYLE, wLanguageId : LibC::UInt16) : MESSAGEBOX_RESULT
fun messageBoxExW(hWnd : HWND, lpText : PWSTR, lpCaption : PWSTR, uType : MESSAGEBOX_STYLE, wLanguageId : LibC::UInt16) : MESSAGEBOX_RESULT
fun messageBoxIndirectA(lpmbp : MSGBOXPARAMSA*) : MESSAGEBOX_RESULT
fun messageBoxIndirectW(lpmbp : MSGBOXPARAMSW*) : MESSAGEBOX_RESULT
fun showCursor(bShow : BOOL) : LibC::Int32
fun setCursorPos(x : LibC::Int32, y : LibC::Int32) : BOOL
fun setPhysicalCursorPos(x : LibC::Int32, y : LibC::Int32) : BOOL
fun setCursor(hCursor : HCURSOR) : HCURSOR
fun getCursorPos(lpPoint : POINT*) : BOOL
fun getPhysicalCursorPos(lpPoint : POINT*) : BOOL
fun getClipCursor(lpRect : RECT*) : BOOL
fun getCursor() : HCURSOR
fun createCaret(hWnd : HWND, hBitmap : HBITMAP, nWidth : LibC::Int32, nHeight : LibC::Int32) : BOOL
fun getCaretBlinkTime() : LibC::UInt32
fun setCaretBlinkTime(uMSeconds : LibC::UInt32) : BOOL
fun destroyCaret() : BOOL
fun hideCaret(hWnd : HWND) : BOOL
fun showCaret(hWnd : HWND) : BOOL
fun setCaretPos(x : LibC::Int32, y : LibC::Int32) : BOOL
fun getCaretPos(lpPoint : POINT*) : BOOL
fun logicalToPhysicalPoint(hWnd : HWND, lpPoint : POINT*) : BOOL
fun physicalToLogicalPoint(hWnd : HWND, lpPoint : POINT*) : BOOL
fun windowFromPoint(point : POINT) : HWND
fun windowFromPhysicalPoint(point : POINT) : HWND
fun childWindowFromPoint(hWndParent : HWND, point : POINT) : HWND
fun clipCursor(lpRect : RECT*) : BOOL
fun childWindowFromPointEx(hwnd : HWND, pt : POINT, flags : CWP_FLAGS) : HWND
fun getSysColor(nIndex : SYS_COLOR_INDEX) : LibC::UInt32
fun getWindowWord(hWnd : HWND, nIndex : LibC::Int32) : LibC::UInt16
fun setWindowWord(hWnd : HWND, nIndex : LibC::Int32, wNewWord : LibC::UInt16) : LibC::UInt16
fun getWindowLongA(hWnd : HWND, nIndex : WINDOW_LONG_PTR_INDEX) : LibC::Int32
fun getWindowLongW(hWnd : HWND, nIndex : WINDOW_LONG_PTR_INDEX) : LibC::Int32
fun setWindowLongA(hWnd : HWND, nIndex : WINDOW_LONG_PTR_INDEX, dwNewLong : LibC::Int32) : LibC::Int32
fun setWindowLongW(hWnd : HWND, nIndex : WINDOW_LONG_PTR_INDEX, dwNewLong : LibC::Int32) : LibC::Int32
fun getWindowLongPtrA(hWnd : HWND, nIndex : WINDOW_LONG_PTR_INDEX) : LibC::Int*
fun getWindowLongPtrW(hWnd : HWND, nIndex : WINDOW_LONG_PTR_INDEX) : LibC::Int*
fun setWindowLongPtrA(hWnd : HWND, nIndex : WINDOW_LONG_PTR_INDEX, dwNewLong : LibC::Int*) : LibC::Int*
fun setWindowLongPtrW(hWnd : HWND, nIndex : WINDOW_LONG_PTR_INDEX, dwNewLong : LibC::Int*) : LibC::Int*
fun getClassWord(hWnd : HWND, nIndex : LibC::Int32) : LibC::UInt16
fun setClassWord(hWnd : HWND, nIndex : LibC::Int32, wNewWord : LibC::UInt16) : LibC::UInt16
fun getClassLongA(hWnd : HWND, nIndex : GET_CLASS_LONG_INDEX) : LibC::UInt32
fun getClassLongW(hWnd : HWND, nIndex : GET_CLASS_LONG_INDEX) : LibC::UInt32
fun setClassLongA(hWnd : HWND, nIndex : GET_CLASS_LONG_INDEX, dwNewLong : LibC::Int32) : LibC::UInt32
fun setClassLongW(hWnd : HWND, nIndex : GET_CLASS_LONG_INDEX, dwNewLong : LibC::Int32) : LibC::UInt32
fun getClassLongPtrA(hWnd : HWND, nIndex : GET_CLASS_LONG_INDEX) : LibC::UIint*
fun getClassLongPtrW(hWnd : HWND, nIndex : GET_CLASS_LONG_INDEX) : LibC::UIint*
fun setClassLongPtrA(hWnd : HWND, nIndex : GET_CLASS_LONG_INDEX, dwNewLong : LibC::Int*) : LibC::UIint*
fun setClassLongPtrW(hWnd : HWND, nIndex : GET_CLASS_LONG_INDEX, dwNewLong : LibC::Int*) : LibC::UIint*
fun getProcessDefaultLayout(pdwDefaultLayout : LibC::UInt32*) : BOOL
fun setProcessDefaultLayout(dwDefaultLayout : LibC::UInt32) : BOOL
fun getDesktopWindow() : HWND
fun getParent(hWnd : HWND) : HWND
fun setParent(hWndChild : HWND, hWndNewParent : HWND) : HWND
fun enumChildWindows(hWndParent : HWND, lpEnumFunc : WNDENUMPROC, lParam : LPARAM) : BOOL
fun findWindowA(lpClassName : PSTR, lpWindowName : PSTR) : HWND
fun findWindowW(lpClassName : PWSTR, lpWindowName : PWSTR) : HWND
fun findWindowExA(hWndParent : HWND, hWndChildAfter : HWND, lpszClass : PSTR, lpszWindow : PSTR) : HWND
fun findWindowExW(hWndParent : HWND, hWndChildAfter : HWND, lpszClass : PWSTR, lpszWindow : PWSTR) : HWND
fun getShellWindow() : HWND
fun registerShellHookWindow(hwnd : HWND) : BOOL
fun deregisterShellHookWindow(hwnd : HWND) : BOOL
fun enumWindows(lpEnumFunc : WNDENUMPROC, lParam : LPARAM) : BOOL
fun enumThreadWindows(dwThreadId : LibC::UInt32, lpfn : WNDENUMPROC, lParam : LPARAM) : BOOL
fun getTopWindow(hWnd : HWND) : HWND
fun getWindowThreadProcessId(hWnd : HWND, lpdwProcessId : LibC::UInt32*) : LibC::UInt32
fun isGUIThread(bConvert : BOOL) : BOOL
fun getLastActivePopup(hWnd : HWND) : HWND
fun getWindow(hWnd : HWND, uCmd : GET_WINDOW_CMD) : HWND
fun setWindowsHookA(nFilterType : LibC::Int32, pfnFilterProc : HOOKPROC) : HHOOK
fun setWindowsHookW(nFilterType : LibC::Int32, pfnFilterProc : HOOKPROC) : HHOOK
fun unhookWindowsHook(nCode : LibC::Int32, pfnFilterProc : HOOKPROC) : BOOL
fun setWindowsHookExA(idHook : WINDOWS_HOOK_ID, lpfn : HOOKPROC, hmod : HINSTANCE, dwThreadId : LibC::UInt32) : HHOOK
fun setWindowsHookExW(idHook : WINDOWS_HOOK_ID, lpfn : HOOKPROC, hmod : HINSTANCE, dwThreadId : LibC::UInt32) : HHOOK
fun unhookWindowsHookEx(hhk : HHOOK) : BOOL
fun callNextHookEx(hhk : HHOOK, nCode : LibC::Int32, wParam : WPARAM, lParam : LPARAM) : LRESULT
fun checkMenuRadioItem(hmenu : HMENU, first : LibC::UInt32, last : LibC::UInt32, check : LibC::UInt32, flags : LibC::UInt32) : BOOL
fun loadCursorA(hInstance : HINSTANCE, lpCursorName : PSTR) : HCURSOR
fun loadCursorW(hInstance : HINSTANCE, lpCursorName : PWSTR) : HCURSOR
fun loadCursorFromFileA(lpFileName : PSTR) : HCURSOR
fun loadCursorFromFileW(lpFileName : PWSTR) : HCURSOR
fun createCursor(hInst : HINSTANCE, xHotSpot : LibC::Int32, yHotSpot : LibC::Int32, nWidth : LibC::Int32, nHeight : LibC::Int32, pvANDPlane : LibC::Void*, pvXORPlane : LibC::Void*) : HCURSOR
fun destroyCursor(hCursor : HCURSOR) : BOOL
fun setSystemCursor(hcur : HCURSOR, id : SYSTEM_CURSOR_ID) : BOOL
fun loadIconA(hInstance : HINSTANCE, lpIconName : PSTR) : HICON
fun loadIconW(hInstance : HINSTANCE, lpIconName : PWSTR) : HICON
fun destroyIcon(hIcon : HICON) : BOOL
fun lookupIconIdFromDirectory(presbits : LibC::Byte*, fIcon : BOOL) : LibC::Int32
fun lookupIconIdFromDirectoryEx(presbits : LibC::Byte*, fIcon : BOOL, cxDesired : LibC::Int32, cyDesired : LibC::Int32, flags : IMAGE_FLAGS) : LibC::Int32
fun createIconFromResource(presbits : LibC::Byte*, dwResSize : LibC::UInt32, fIcon : BOOL, dwVer : LibC::UInt32) : HICON
fun createIconFromResourceEx(presbits : LibC::Byte*, dwResSize : LibC::UInt32, fIcon : BOOL, dwVer : LibC::UInt32, cxDesired : LibC::Int32, cyDesired : LibC::Int32, flags : IMAGE_FLAGS) : HICON
fun loadImageA(hInst : HINSTANCE, name : PSTR, type : GDI_IMAGE_TYPE, cx : LibC::Int32, cy : LibC::Int32, fuLoad : IMAGE_FLAGS) : HANDLE
fun loadImageW(hInst : HINSTANCE, name : PWSTR, type : GDI_IMAGE_TYPE, cx : LibC::Int32, cy : LibC::Int32, fuLoad : IMAGE_FLAGS) : HANDLE
fun copyImage(h : HANDLE, type : GDI_IMAGE_TYPE, cx : LibC::Int32, cy : LibC::Int32, flags : IMAGE_FLAGS) : HANDLE
fun drawIconEx(hdc : HDC, xLeft : LibC::Int32, yTop : LibC::Int32, hIcon : HICON, cxWidth : LibC::Int32, cyWidth : LibC::Int32, istepIfAniCur : LibC::UInt32, hbrFlickerFreeDraw : HBRUSH, diFlags : DI_FLAGS) : BOOL
fun createIconIndirect(piconinfo : ICONINFO*) : HICON
fun copyIcon(hIcon : HICON) : HICON
fun getIconInfo(hIcon : HICON, piconinfo : ICONINFO*) : BOOL
fun getIconInfoExA(hicon : HICON, piconinfo : ICONINFOEXA*) : BOOL
fun getIconInfoExW(hicon : HICON, piconinfo : ICONINFOEXW*) : BOOL
fun isDialogMessageA(hDlg : HWND, lpMsg : MSG*) : BOOL
fun isDialogMessageW(hDlg : HWND, lpMsg : MSG*) : BOOL
fun mapDialogRect(hDlg : HWND, lpRect : RECT*) : BOOL
fun getScrollInfo(hwnd : HWND, nBar : SCROLLBAR_CONSTANTS, lpsi : SCROLLINFO*) : BOOL
fun defFrameProcA(hWnd : HWND, hWndMDIClient : HWND, uMsg : LibC::UInt32, wParam : WPARAM, lParam : LPARAM) : LRESULT
fun defFrameProcW(hWnd : HWND, hWndMDIClient : HWND, uMsg : LibC::UInt32, wParam : WPARAM, lParam : LPARAM) : LRESULT
fun defMDIChildProcA(hWnd : HWND, uMsg : LibC::UInt32, wParam : WPARAM, lParam : LPARAM) : LRESULT
fun defMDIChildProcW(hWnd : HWND, uMsg : LibC::UInt32, wParam : WPARAM, lParam : LPARAM) : LRESULT
fun translateMDISysAccel(hWndClient : HWND, lpMsg : MSG*) : BOOL
fun arrangeIconicWindows(hWnd : HWND) : LibC::UInt32
fun createMDIWindowA(lpClassName : PSTR, lpWindowName : PSTR, dwStyle : WINDOW_STYLE, x : LibC::Int32, y : LibC::Int32, nWidth : LibC::Int32, nHeight : LibC::Int32, hWndParent : HWND, hInstance : HINSTANCE, lParam : LPARAM) : HWND
fun createMDIWindowW(lpClassName : PWSTR, lpWindowName : PWSTR, dwStyle : WINDOW_STYLE, x : LibC::Int32, y : LibC::Int32, nWidth : LibC::Int32, nHeight : LibC::Int32, hWndParent : HWND, hInstance : HINSTANCE, lParam : LPARAM) : HWND
fun systemParametersInfoA(uiAction : SYSTEM_PARAMETERS_INFO_ACTION, uiParam : LibC::UInt32, pvParam : LibC::Void*, fWinIni : SYSTEM_PARAMETERS_INFO_UPDATE_FLAGS) : BOOL
fun systemParametersInfoW(uiAction : SYSTEM_PARAMETERS_INFO_ACTION, uiParam : LibC::UInt32, pvParam : LibC::Void*, fWinIni : SYSTEM_PARAMETERS_INFO_UPDATE_FLAGS) : BOOL
fun soundSentry() : BOOL
fun setDebugErrorLevel(dwLevel : LibC::UInt32) : LibC::Void
fun cancelShutdown() : BOOL
fun getGUIThreadInfo(idThread : LibC::UInt32, pgui : GUITHREADINFO*) : BOOL
fun setProcessDPIAware() : BOOL
fun isProcessDPIAware() : BOOL
fun inheritWindowMonitor(hwnd : HWND, hwndInherit : HWND) : BOOL
fun getCursorInfo(pci : CURSORINFO*) : BOOL
fun getWindowInfo(hwnd : HWND, pwi : WINDOWINFO*) : BOOL
fun getTitleBarInfo(hwnd : HWND, pti : TITLEBARINFO*) : BOOL
fun getMenuBarInfo(hwnd : HWND, idObject : OBJECT_IDENTIFIER, idItem : LibC::Int32, pmbi : MENUBARINFO*) : BOOL
fun getScrollBarInfo(hwnd : HWND, idObject : OBJECT_IDENTIFIER, psbi : SCROLLBARINFO*) : BOOL
fun getAncestor(hwnd : HWND, gaFlags : GET_ANCESTOR_FLAGS) : HWND
fun realChildWindowFromPoint(hwndParent : HWND, ptParentClientCoords : POINT) : HWND
fun changeWindowMessageFilter(message : LibC::UInt32, dwFlag : CHANGE_WINDOW_MESSAGE_FILTER_FLAGS) : BOOL
fun changeWindowMessageFilterEx(hwnd : HWND, message : LibC::UInt32, action : WINDOW_MESSAGE_FILTER_ACTION, pChangeFilterStruct : CHANGEFILTERSTRUCT*) : BOOL
fun createResourceIndexer(projectRoot : PWSTR, extensionDllPath : PWSTR, ppResourceIndexer : LibC::Void**) : HRESULT
fun destroyResourceIndexer(resourceIndexer : LibC::Void*) : LibC::Void
fun mrmCreateResourceIndexer(packageFamilyName : PWSTR, projectRoot : PWSTR, platformVersion : MrmPlatformVersion, defaultQualifiers : PWSTR, indexer : MrmResourceIndexerHandle*) : HRESULT
fun mrmCreateResourceIndexerFromPreviousSchemaFile(projectRoot : PWSTR, platformVersion : MrmPlatformVersion, defaultQualifiers : PWSTR, schemaFile : PWSTR, indexer : MrmResourceIndexerHandle*) : HRESULT
fun mrmCreateResourceIndexerFromPreviousPriFile(projectRoot : PWSTR, platformVersion : MrmPlatformVersion, defaultQualifiers : PWSTR, priFile : PWSTR, indexer : MrmResourceIndexerHandle*) : HRESULT
fun mrmCreateResourceIndexerFromPreviousSchemaData(projectRoot : PWSTR, platformVersion : MrmPlatformVersion, defaultQualifiers : PWSTR, schemaXmlData : LibC::Byte*, schemaXmlSize : LibC::UInt32, indexer : MrmResourceIndexerHandle*) : HRESULT
fun mrmCreateResourceIndexerFromPreviousPriData(projectRoot : PWSTR, platformVersion : MrmPlatformVersion, defaultQualifiers : PWSTR, priData : LibC::Byte*, priSize : LibC::UInt32, indexer : MrmResourceIndexerHandle*) : HRESULT
fun mrmCreateResourceIndexerWithFlags(packageFamilyName : PWSTR, projectRoot : PWSTR, platformVersion : MrmPlatformVersion, defaultQualifiers : PWSTR, flags : MrmIndexerFlags, indexer : MrmResourceIndexerHandle*) : HRESULT
fun mrmIndexString(indexer : MrmResourceIndexerHandle, resourceUri : PWSTR, resourceString : PWSTR, qualifiers : PWSTR) : HRESULT
fun mrmIndexEmbeddedData(indexer : MrmResourceIndexerHandle, resourceUri : PWSTR, embeddedData : LibC::Byte*, embeddedDataSize : LibC::UInt32, qualifiers : PWSTR) : HRESULT
fun mrmIndexFile(indexer : MrmResourceIndexerHandle, resourceUri : PWSTR, filePath : PWSTR, qualifiers : PWSTR) : HRESULT
fun mrmIndexFileAutoQualifiers(indexer : MrmResourceIndexerHandle, filePath : PWSTR) : HRESULT
fun mrmIndexResourceContainerAutoQualifiers(indexer : MrmResourceIndexerHandle, containerPath : PWSTR) : HRESULT
fun mrmCreateResourceFile(indexer : MrmResourceIndexerHandle, packagingMode : MrmPackagingMode, packagingOptions : MrmPackagingOptions, outputDirectory : PWSTR) : HRESULT
fun mrmCreateResourceFileWithChecksum(indexer : MrmResourceIndexerHandle, packagingMode : MrmPackagingMode, packagingOptions : MrmPackagingOptions, checksum : LibC::UInt32, outputDirectory : PWSTR) : HRESULT
fun mrmCreateResourceFileInMemory(indexer : MrmResourceIndexerHandle, packagingMode : MrmPackagingMode, packagingOptions : MrmPackagingOptions, outputPriData : LibC::Byte**, outputPriSize : LibC::UInt32*) : HRESULT
fun mrmDestroyIndexerAndMessages(indexer : MrmResourceIndexerHandle) : HRESULT
fun mrmFreeMemory(data : LibC::Byte*) : HRESULT
fun mrmDumpPriFile(indexFileName : PWSTR, schemaPriFile : PWSTR, dumpType : MrmDumpType, outputXmlFile : PWSTR) : HRESULT
fun mrmDumpPriFileInMemory(indexFileName : PWSTR, schemaPriFile : PWSTR, dumpType : MrmDumpType, outputXmlData : LibC::Byte**, outputXmlSize : LibC::UInt32*) : HRESULT
fun mrmDumpPriDataInMemory(inputPriData : LibC::Byte*, inputPriSize : LibC::UInt32, schemaPriData : LibC::Byte*, schemaPriSize : LibC::UInt32, dumpType : MrmDumpType, outputXmlData : LibC::Byte**, outputXmlSize : LibC::UInt32*) : HRESULT
fun mrmCreateConfig(platformVersion : MrmPlatformVersion, defaultQualifiers : PWSTR, outputXmlFile : PWSTR) : HRESULT
fun mrmCreateConfigInMemory(platformVersion : MrmPlatformVersion, defaultQualifiers : PWSTR, outputXmlData : LibC::Byte**, outputXmlSize : LibC::UInt32*) : HRESULT
fun mrmGetPriFileContentChecksum(priFile : PWSTR, checksum : LibC::UInt32*) : HRESULT

  end
